/**
 * learner-model.ts — the read layer: raw persisted facts → what the
 * dashboard is allowed to say (LEARNER-MODEL-SPEC.md).
 *
 * Every function here is PURE: no fetch, no Supabase, no `fs`, no
 * `Date.now()` read internally (a `now: Date` is always a PARAMETER, never
 * read from the ambient clock) — so every rule in the spec is testable on a
 * plain fixture, exactly as §8 requires ("La classification A/C/U est du
 * code pur (lecture) → tests unitaires sur table de cas, pas dom-truth").
 * The three input shapes below mirror the draft schemas byte-for-byte
 * (`backend/supabase/migrations/048_user_events_and_notion_progress.sql`,
 * `draft-049_user_notion_misconception_states.sql`) — camelCased, nothing
 * renamed beyond that. Nothing here writes anything; the write path (RPCs,
 * edge functions) stays untouched and stays the only place clearing facts
 * get decided (ADR 0013: "le chemin d'écriture ne classifie pas" — and
 * symmetrically, the read layer never re-derives what the write path
 * already decided, e.g. `cleared_at`).
 *
 * NO %, no streak, no XP, no "maîtrisé" anywhere below — the honest-state
 * vocabulary ban (LEARNER-MODEL-SPEC §8) applies to this module's own
 * output as much as to any rendered string.
 */

// Type-only — erased at compile time, so this never creates a runtime
// dependency on student-state.ts (which is "use client" + Supabase-aware).
// This is the one place the DASHBOARD-SPEC §2 contract type is REUSED
// rather than redeclared, so the two files cannot silently drift apart.
import type { StudentState } from "./student-state";

// ── Input shapes (draft-048 / draft-049, camelCased) ──────────────────────

export type AnswerEventKind = "item" | "checkpoint" | "exercise_reveal";

/** One row of `user_answer_events` (draft-048 §1) — the append-only journal. */
export interface AnswerEvent {
  id: number;
  userId: string;
  notionId: string;
  itemId: string;
  kind: AnswerEventKind;
  choiceIndex: number | null;
  isCorrect: boolean | null;
  /** String key into items.yaml's misconceptions[] — NULL if the chosen
   *  choice wasn't tagged with a misconception. */
  misconceptionId: string | null;
  /** 0-based; NULL if the event happened outside a specific chapter. */
  chapterIndex: number | null;
  /** ISO timestamp. */
  createdAt: string;
}

/** One row of `user_notion_progress` (draft-048 §2) — the materialized fold. */
export interface NotionProgress {
  userId: string;
  notionId: string;
  /** 0-based, deduplicated chapter indices actually visited. */
  chaptersVisited: number[];
  /** N as of the LAST visit — a snapshot, not necessarily today's real
   *  content total (LEARNER-MODEL-SPEC §4, ledger 14.4). */
  chaptersTotal: number | null;
  lastChapterIndex: number | null;
  itemsAttempted: number;
  itemsCorrect: number;
  firstVisitAt: string;
  lastVisitAt: string;
}

/** One row of `user_notion_misconception_states` (draft-049) — the notion
 *  twin of migration 043. `exhibitedCount` is read here for completeness
 *  only; classification NEVER uses it (LEARNER-MODEL-SPEC §0.3: it is a
 *  binary flag under the floor, never a confidence count) — classification
 *  counts EVENTS from the journal instead (§3). */
export interface MisconceptionState {
  userId: string;
  notionId: string;
  misconceptionId: string;
  exhibitedCount: number;
  firstExhibitedAt: string | null;
  lastExhibitedAt: string | null;
  remediationAttempts: number;
  /** Set by the write path (record_notion_misconception_cleared) — the
   *  read layer TRUSTS this value, it never recomputes clearing itself
   *  (that 2-distinct-items-since-last-exhibition detection is edge-function
   *  territory, LEARNER-MODEL-SPEC §3 / draft-049's own comment). */
  clearedAt: string | null;
}

/** `{ notion_id: { misconception_id: item_count } }` — generated by
 *  `web/scripts/build-learner-inputs.mjs` from items.yaml's END-BANK only.
 *  `floor_met(m)` = `count >= 3` (LEARNER-MODEL-SPEC §0.2). A count below 3
 *  (or a missing entry entirely) both mean "not floor met" — the caller
 *  never needs to special-case "absent" vs "present-but-low". */
export type FloorMap = Record<string, Record<string, number>>;

// ── (a) A/C/U classification — LEARNER-MODEL-SPEC §3 ───────────────────────

export type MisconceptionClassification = "unassessed" | "active" | "cleared";

const COVERAGE_FLOOR = 3; // items.yaml items targeting m, §0.2
const EXHIBITION_FLOOR = 2; // distinct journal exhibition events, §0.2

function floorMet(notionId: string, misconceptionId: string, floorMap: FloorMap): boolean {
  const count = floorMap[notionId]?.[misconceptionId];
  return typeof count === "number" && count >= COVERAGE_FLOOR;
}

/** Count of journal events exhibiting `misconceptionId` on `notionId` —
 *  EVERY matching row counts (§3: "événements d'exhibition distincts (le
 *  journal)", never the state row's own binary `exhibitedCount`). */
function exhibitionCount(notionId: string, misconceptionId: string, events: AnswerEvent[]): number {
  let n = 0;
  for (const e of events) {
    if (e.notionId === notionId && e.misconceptionId === misconceptionId) n++;
  }
  return n;
}

/**
 * The exact ladder from LEARNER-MODEL-SPEC §3:
 *
 *   si NOT floor_met(m)                          → Unassessed
 *   sinon si exhibitions(m) ≥ 2 ET cleared_at IS NULL → Active
 *   sinon si cleared_at IS NOT NULL                → Cleared
 *   sinon (0 ou 1 exhibition, plancher couvert)    → Unassessed
 *
 * `state` may be `null` (no row yet — e.g. floor just became met but the
 * student hasn't been exhibited) — that degrades to Unassessed exactly like
 * an unmet floor, never to a fabricated "no misconception" (§0.1:
 * "non détecté" ne s'effondre jamais en "pas de misconception").
 */
export function classifyMisconception(
  notionId: string,
  misconceptionId: string,
  events: AnswerEvent[],
  state: MisconceptionState | null,
  floorMap: FloorMap
): MisconceptionClassification {
  if (!floorMet(notionId, misconceptionId, floorMap)) return "unassessed";

  const exhibitions = exhibitionCount(notionId, misconceptionId, events);
  const clearedAt = state?.clearedAt ?? null;

  if (exhibitions >= EXHIBITION_FLOOR && clearedAt === null) return "active";
  if (clearedAt !== null) return "cleared";
  return "unassessed";
}

export interface ClassifiedMisconception {
  notionId: string;
  misconceptionId: string;
  classification: MisconceptionClassification;
  /** From the state row — null when no row exists yet. Used by NextUp §5
   *  predicate 1 to pick the MATURE-est active misconception (oldest). */
  lastExhibitedAt: string | null;
}

// "::" cannot appear in a notion id ("<subject>/<slug>") or a misconception
// id (dot/underscore/hyphen-separated) — an unambiguous join/split key for
// the Map/Set below.
const PAIR_SEP = "::";
function pairKey(notionId: string, misconceptionId: string): string {
  return notionId + PAIR_SEP + misconceptionId;
}
function unpackPairKey(key: string): { notionId: string; misconceptionId: string } {
  const idx = key.indexOf(PAIR_SEP);
  return { notionId: key.slice(0, idx), misconceptionId: key.slice(idx + PAIR_SEP.length) };
}

/**
 * Classifies every (notion, misconception) pair worth classifying: every
 * pair `floorMap` declares (this is the only set that can EVER be anything
 * but Unassessed) plus every pair with a state row (defensive — keeps a
 * stray row visible as Unassessed rather than silently dropped).
 */
export function classifyMisconceptions(
  events: AnswerEvent[],
  states: MisconceptionState[],
  floorMap: FloorMap
): ClassifiedMisconception[] {
  const stateByKey = new Map<string, MisconceptionState>();
  for (const s of states) stateByKey.set(pairKey(s.notionId, s.misconceptionId), s);

  const pairs = new Set<string>();
  for (const notionId of Object.keys(floorMap)) {
    for (const misconceptionId of Object.keys(floorMap[notionId])) {
      pairs.add(pairKey(notionId, misconceptionId));
    }
  }
  for (const s of states) pairs.add(pairKey(s.notionId, s.misconceptionId));

  const out: ClassifiedMisconception[] = [];
  for (const key of pairs) {
    const { notionId, misconceptionId } = unpackPairKey(key);
    const state = stateByKey.get(key) ?? null;
    out.push({
      notionId,
      misconceptionId,
      classification: classifyMisconception(notionId, misconceptionId, events, state, floorMap),
      lastExhibitedAt: state?.lastExhibitedAt ?? null,
    });
  }
  return out;
}

// ── (b) Per-notion mastery state — LEARNER-MODEL-SPEC §4 ───────────────────

export type MasteryState = "non-ouvert" | "entamé" | "lu" | "exercé" | "à revoir";

export interface MasteryResult {
  state: MasteryState;
  /** 1-based "next chapter to open" (k in "chapitre k/N") — entamé only. */
  chapterK?: number;
  /** N — the total this result's coverage was judged against (entamé/lu/à
   *  revoir; the STORED snapshot unless `currentChaptersTotal` was passed). */
  chaptersTotal?: number;
  itemsAttempted?: number;
}

const REVOIR_THRESHOLD_DAYS = 21; // LEARNER-MODEL-SPEC §4, ledger 14.5 — a
// stated simple threshold, NOT a claimed forgetting curve.
const MS_PER_DAY = 1000 * 60 * 60 * 24;

function daysBetween(fromIso: string, now: Date): number {
  return (now.getTime() - new Date(fromIso).getTime()) / MS_PER_DAY;
}

/**
 * Derives ONE display state per DASHBOARD-SPEC §2 / LEARNER-MODEL-SPEC §4's
 * table. The five rows read as a priority ladder (each state is a MORE
 * SPECIFIC fact than the one below it), highest-signal first:
 *
 *   à revoir  > exercé > lu > entamé > non-ouvert
 *
 * `currentChaptersTotal` is OPTIONAL: when supplied, the "lu" regression
 * rule applies in full (content growing after the last visit demotes a
 * stale "lu" honestly back to "entamé", ledger 14.4). When omitted (the
 * caller has no live content read — e.g. a browser-only client that cannot
 * `fs`-read lesson.md), the function degrades to judging coverage against
 * the STORED `progress.chaptersTotal` snapshot alone — an honest "as of the
 * last visit" read, never a fabricated one.
 */
export function notionMasteryState(
  progress: NotionProgress | null,
  now: Date,
  currentChaptersTotal?: number
): MasteryResult {
  if (!progress) return { state: "non-ouvert" };

  const visited = progress.chaptersVisited ?? [];
  if (visited.length === 0) {
    return progress.itemsAttempted > 0
      ? { state: "exercé", itemsAttempted: progress.itemsAttempted }
      : { state: "non-ouvert" };
  }

  const storedTotal = progress.chaptersTotal ?? undefined;
  const distinctVisited = new Set(visited).size;
  const maxVisited = Math.max(...visited);

  const coversStored = storedTotal != null && distinctVisited >= storedTotal;
  const contentGrew =
    currentChaptersTotal != null && storedTotal != null && currentChaptersTotal > storedTotal;
  const isLu = coversStored && !contentGrew;

  if (isLu && daysBetween(progress.lastVisitAt, now) > REVOIR_THRESHOLD_DAYS) {
    return { state: "à revoir", chaptersTotal: storedTotal, itemsAttempted: progress.itemsAttempted };
  }
  if (progress.itemsAttempted > 0) {
    return { state: "exercé", itemsAttempted: progress.itemsAttempted };
  }
  if (isLu) {
    return { state: "lu", chaptersTotal: storedTotal };
  }
  return {
    state: "entamé",
    chapterK: maxVisited + 1,
    chaptersTotal: currentChaptersTotal ?? storedTotal,
  };
}

// ── (c) StudentState — DASHBOARD-SPEC §2 contract, filled honestly ─────────

/**
 * Builds the DASHBOARD-SPEC §2 `StudentState` shape from real
 * `user_notion_progress` rows ONLY — every field it fills (`opened`,
 * `chaptersVisited`, `chaptersTotal`, `itemsAttempted`, `itemsCorrect`,
 * `lastVisit`) is a direct, un-derived column read. `lastSession` is "la
 * ligne progress au last_visit_at max" (§4's own closing line) — ties break
 * on array order (first row wins), which is fine: a genuine tie means the
 * two visits are indistinguishable in time to the minute the client can see.
 *
 * An empty `progressRows` array is a VALID, REAL answer (an authenticated
 * student who has opened nothing yet) — it returns `{ lastSession: null,
 * perNotion: {} }`, not `null`. The caller (student-state.ts) is the one
 * that decides when NOT to call this at all (no session → stays `null`,
 * "we haven't asked" vs. this function's "we asked and this is real").
 */
export function computeStudentState(progressRows: NotionProgress[]): StudentState {
  const perNotion: StudentState["perNotion"] = {};
  let last: NotionProgress | null = null;

  for (const row of progressRows) {
    perNotion[row.notionId] = {
      opened: true,
      chaptersVisited: [...row.chaptersVisited].sort((a, b) => a - b),
      chaptersTotal: row.chaptersTotal ?? 0,
      itemsAttempted: row.itemsAttempted,
      itemsCorrect: row.itemsCorrect,
      lastVisit: row.lastVisitAt,
    };
    if (!last || new Date(row.lastVisitAt).getTime() > new Date(last.lastVisitAt).getTime()) {
      last = row;
    }
  }

  return {
    lastSession: last
      ? { notionId: last.notionId, chapterIndex: last.lastChapterIndex ?? 0, at: last.lastVisitAt }
      : null,
    perNotion,
  };
}

// ── (d) NextUp — LEARNER-MODEL-SPEC §5, predicates 1-3 only ────────────────
//
// Predicate 4 ("parcours" — the first non-opened notion in curriculum/
// filière order) needs the CONTENT TREE, not the event log — it stays
// NextUp.tsx's own existing logic (`firstOfParcours`). This function
// returns `null` when none of 1-3 fire, which IS "fall through to
// predicate 4" — the two layers compose by that single `null` check.

export type NextUpSource = "misconception-active" | "reprise" | "revision";

export interface NextUpPick {
  source: NextUpSource;
  notionId: string;
  /**
   * "reprise" only: the 1-based NEXT chapter to open (k in "chapitre
   * k/N") — NOT a raw 0-based DB index.
   */
  chapterIndex?: number;
  /** "reprise" only: N, the STORED chaptersTotal snapshot for that notion. */
  chaptersTotal?: number;
  /** "revision" only: whole days since last_visit_at (floored), for "Ça
   *  fait {j} jours". */
  daysSinceVisit?: number;
}

/** The exhibition event with the latest `createdAt` for this (notion,
 *  misconception) pair — "ancrée au chapitre de ses items" (§5 predicate 1):
 *  anchors the recommendation to wherever the student most recently met it. */
function mostRecentChapterIndex(
  events: AnswerEvent[],
  notionId: string,
  misconceptionId: string
): number | undefined {
  let best: AnswerEvent | null = null;
  for (const e of events) {
    if (e.notionId !== notionId || e.misconceptionId !== misconceptionId) continue;
    if (e.chapterIndex == null) continue;
    if (!best || new Date(e.createdAt).getTime() > new Date(best.createdAt).getTime()) best = e;
  }
  return best?.chapterIndex ?? undefined;
}

/**
 * Strict priority, first true predicate wins (§5, ledger 14.6):
 *
 *   1. misconception-active — an Active misconception exists anywhere →
 *      the one whose `lastExhibitedAt` is OLDEST (most mature for
 *      remediation).
 *   2. reprise — the lastSession notion (max `last_visit_at` across
 *      progress rows) is itself "entamé" (started, not yet fully read).
 *   3. revision — any notion is "à revoir" → the OLDEST `last_visit_at`
 *      among them.
 *
 * Returns `null` when none fire — the caller falls through to predicate 4.
 */
export function nextUpRecommendation(
  events: AnswerEvent[],
  progressRows: NotionProgress[],
  misconceptionStates: MisconceptionState[],
  floorMap: FloorMap,
  now: Date
): NextUpPick | null {
  // Predicate 1 — misconception-active.
  const active = classifyMisconceptions(events, misconceptionStates, floorMap).filter(
    (c) => c.classification === "active" && c.lastExhibitedAt != null
  );
  if (active.length > 0) {
    active.sort(
      (a, b) => new Date(a.lastExhibitedAt as string).getTime() - new Date(b.lastExhibitedAt as string).getTime()
    );
    const pick = active[0];
    return {
      source: "misconception-active",
      notionId: pick.notionId,
      chapterIndex: mostRecentChapterIndex(events, pick.notionId, pick.misconceptionId),
    };
  }

  // Predicate 2 — reprise (the lastSession itself is entamé/non-lu).
  if (progressRows.length > 0) {
    let last = progressRows[0];
    for (const row of progressRows) {
      if (new Date(row.lastVisitAt).getTime() > new Date(last.lastVisitAt).getTime()) last = row;
    }
    const mastery = notionMasteryState(last, now);
    if (mastery.state === "entamé") {
      return {
        source: "reprise",
        notionId: last.notionId,
        chapterIndex: mastery.chapterK,
        chaptersTotal: last.chaptersTotal ?? undefined,
      };
    }
  }

  // Predicate 3 — révision (à revoir; oldest last_visit_at among them).
  const revoir = progressRows
    .map((p) => ({ p, mastery: notionMasteryState(p, now) }))
    .filter((x) => x.mastery.state === "à revoir");
  if (revoir.length > 0) {
    revoir.sort((a, b) => new Date(a.p.lastVisitAt).getTime() - new Date(b.p.lastVisitAt).getTime());
    const top = revoir[0];
    return {
      source: "revision",
      notionId: top.p.notionId,
      daysSinceVisit: Math.floor(daysBetween(top.p.lastVisitAt, now)),
    };
  }

  return null;
}
