// Long-form lesson content for SMB chapters → migration 017.
//
// Run:
//   dart backend/seed/json_encode_long_lessons_smb.dart
//
// Authors 32 SMB chapters as v2 LessonV2-shaped JSON, emits an idempotent
// PostgreSQL migration that UPDATEs `skills.lesson` for every SMB skill
// (Math + Physique-Chimie). Pattern-authored from the SMA equivalents in
// json_encode_long_lessons.dart, with one notch lower depth (less proof,
// fewer abstract callouts, gentler checkpoint difficulty).
//
// SMB skill codes are non-prefixed (e.g. 'arithmetic_seq', 'kinematics')
// and live alongside the SMA `sma_*` codes in the `skills` table — the
// distinction comes from the topic→subject→stream join.

import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final out = StringBuffer();
  out.writeln('-- ============================================================');
  out.writeln('-- Migration 017: Seed long-form (v2) lessons for 32 SMB chapters.');
  out.writeln('-- Auto-generated by backend/seed/json_encode_long_lessons_smb.dart.');
  out.writeln('-- Idempotent: re-running rewrites the same JSON.');
  out.writeln('-- Targets:');
  out.writeln('--   Math (23): suites, limites, derivation, integration, probas, complexes, ED');
  out.writeln('--   PC   (9) : mecanique, ondes, electricite, chimie');
  out.writeln('-- Pattern-authored from SMA. Treat as v0 — review chapter-by-chapter.');
  out.writeln('-- ============================================================');
  out.writeln();
  out.writeln('BEGIN;');
  out.writeln();

  for (final entry in _chapters.entries) {
    final code = entry.key;
    final lesson = entry.value;
    final json = jsonEncode(lesson);
    final escaped = json.replaceAll("'", "''");
    out.writeln('-- ===== $code =====');
    out.writeln(
        "UPDATE public.skills SET lesson = '$escaped'::jsonb WHERE code = '$code';");
    out.writeln();
  }

  out.writeln('COMMIT;');

  final output = args.isNotEmpty
      ? args[0]
      : 'backend/supabase/migrations/017_long_lessons_smb.sql';
  File(output).writeAsStringSync(out.toString());
  stdout.writeln('Wrote $output (${_chapters.length} chapters).');
  for (final code in _chapters.keys) {
    final l = _chapters[code]!;
    final n = (l['sections'] as List).length;
    stdout.writeln('  $code → ${l['title_fr']} ($n sections)');
  }
}

// ============================================================================
// Builder helpers — mirror json_encode_long_lessons.dart
// ============================================================================

Map<String, dynamic> _lesson({
  required String titleFr,
  String? subtitleFr,
  required List<Map<String, dynamic>> sections,
}) =>
    {
      'version': 2,
      'title_fr': titleFr,
      if (subtitleFr != null) 'subtitle_fr': subtitleFr,
      'sections': sections,
    };

Map<String, dynamic> _section({
  required String kind,
  required String titleFr,
  String? eyebrowFr,
  required String estimatedMinutes,
  required List<Map<String, dynamic>> blocks,
}) =>
    {
      'kind': kind,
      'title_fr': titleFr,
      if (eyebrowFr != null) 'eyebrow_fr': eyebrowFr,
      'estimated_minutes': estimatedMinutes,
      'blocks': blocks,
    };

Map<String, dynamic> _p(String md) => {'kind': 'paragraph', 'md': md};
Map<String, dynamic> _h(String text, [int level = 2]) =>
    {'kind': 'heading', 'text': text, 'level': level};
Map<String, dynamic> _f(String latex, [String? caption]) =>
    {'kind': 'formula', 'latex': latex, if (caption != null) 'caption_fr': caption};
Map<String, dynamic> _callout(String tone, String title, String body) =>
    {'kind': 'callout', 'tone': tone, 'title_fr': title, 'body_fr': body};
Map<String, dynamic> _example({
  required String title,
  required String problem,
  required List<String> steps,
  String? answer,
}) =>
    {
      'kind': 'example',
      'title_fr': title,
      'problem_fr': problem,
      'steps_fr': steps,
      if (answer != null) 'answer_fr': answer,
    };
Map<String, dynamic> _interactive(String widgetType,
        {Map<String, dynamic>? config, String? caption}) =>
    {
      'kind': 'interactive',
      'widget_type': widgetType,
      if (config != null) 'config': config,
      if (caption != null) 'caption_fr': caption,
    };
Map<String, dynamic> _checkpoint(String title, List<Map<String, dynamic>> qs) =>
    {'kind': 'checkpoint', 'title_fr': title, 'questions': qs};
Map<String, dynamic> _q(
        {required String stem,
        required List<String> choices,
        required int correct,
        required String explanation}) =>
    {
      'stem_fr': stem,
      'choices_fr': choices,
      'correct_index': correct,
      'explanation_fr': explanation,
    };
Map<String, dynamic> _tryIt({
  required String title,
  required String problem,
  required String hint,
  required String solution,
}) =>
    {
      'kind': 'try_it',
      'title_fr': title,
      'problem_fr': problem,
      'hint_fr': hint,
      'solution_fr': solution,
    };

// ============================================================================
// THE CONTENT — 32 SMB chapters
// ============================================================================

final Map<String, Map<String, dynamic>> _chapters = {
  // --- Math (23 chapters) ---
  'arithmetic_seq': _arithmeticSeq(),
  'geometric_seq': _geometricSeq(),
  'seq_convergence': _seqConvergence(),
  'seq_recursive': _seqRecursive(),
  'seq_adjacent': _seqAdjacent(),
  'limit_def': _limitDef(),
  'limit_calc': _limitCalc(),
  'continuity': _continuity(),
  'tvi': _tvi(),
  'deriv_basic': _derivBasic(),
  'deriv_rules': _derivRules(),
  'deriv_apps': _derivApps(),
  'primitives': _primitives(),
  'definite_integral': _definiteIntegral(),
  'integral_apps': _integralApps(),
  'prob_basic': _probBasic(),
  'conditional_prob': _conditionalProb(),
  'random_variables': _randomVariables(),
  'complex_basics': _complexBasics(),
  'complex_trig': _complexTrig(),
  'complex_geometry': _complexGeometry(),
  'ode_first_order': _odeFirstOrder(),
  'ode_second_order': _odeSecondOrder(),
  // --- Physique-Chimie (9 chapters) ---
  'kinematics': _kinematics(),
  'newtons_laws': _newtonsLaws(),
  'energy': _energy(),
  'wave_properties': _waveProperties(),
  'sound_light': _soundLight(),
  'rc_rl_circuits': _rcRlCircuits(),
  'rlc_oscillations': _rlcOscillations(),
  'acid_base': _acidBase(),
  'redox': _redox(),
};

// ============================================================================
// MATH — Suites
// ============================================================================

Map<String, dynamic> _arithmeticSeq() => _lesson(
      titleFr: 'Suites arithmétiques',
      subtitleFr: 'Raison constante, terme général, somme.',
      sections: [
        _section(kind: 'prerequisite', titleFr: 'Prérequis', eyebrowFr: 'PRÉREQUIS', estimatedMinutes: '2', blocks: [
          _p("Une **suite numérique** \$(u_n)\$ est une famille de nombres indexée par \$n \\in \\mathbb{N}\$. On note \$u_0, u_1, u_2, \\dots\$ ou \$u_n\$ le terme de rang \$n\$."),
          _checkpoint("Bases", [
            _q(stem: "Si \$u_n = 2n+1\$, que vaut \$u_3\$ ?", choices: ['5', '6', '7', '8'], correct: 2, explanation: "\$u_3 = 2 \\times 3 + 1 = 7\$."),
          ]),
        ]),
        _section(kind: 'concept', titleFr: 'Définition et raison', eyebrowFr: 'CONCEPT', estimatedMinutes: '4', blocks: [
          _p("Une suite est **arithmétique** si l'on passe d'un terme au suivant en **ajoutant toujours le même nombre**, appelé la **raison** \$r\$."),
          _f("u_{n+1} = u_n + r", "Définition par récurrence."),
          _f("u_n = u_0 + n \\cdot r \\qquad \\text{ou} \\qquad u_n = u_p + (n-p)\\cdot r", "Terme général : à partir de \$u_0\$ ou d'un terme \$u_p\$ quelconque."),
          _example(
            title: "Identifier la raison",
            problem: "La suite \$3, 7, 11, 15, \\dots\$ est-elle arithmétique ? Si oui, donne sa raison.",
            steps: [
              "\$u_1 - u_0 = 7 - 3 = 4\$.",
              "\$u_2 - u_1 = 11 - 7 = 4\$, \$u_3 - u_2 = 15 - 11 = 4\$.",
              "L'écart est constant : la suite est arithmétique de raison \$r = 4\$.",
            ],
            answer: "Arithmétique, \$r = 4\$.",
          ),
        ]),
        _section(kind: 'concept', titleFr: 'Somme des termes', eyebrowFr: 'SOMME', estimatedMinutes: '4', blocks: [
          _f("S_n = u_0 + u_1 + \\dots + u_n = (n+1)\\cdot \\frac{u_0 + u_n}{2}", "**Astuce de Gauss** : (nombre de termes) × (premier + dernier) / 2."),
          _example(
            title: "Calculer une somme",
            problem: "Calcule \$1 + 2 + 3 + \\dots + 100\$.",
            steps: [
              "C'est la suite arithmétique de raison 1, allant de \$u_1 = 1\$ à \$u_{100} = 100\$.",
              "Nombre de termes : 100. Premier + dernier : \$1+100 = 101\$.",
              "\$S = 100 \\times \\frac{101}{2} = 5050\$.",
            ],
            answer: "\$1 + 2 + \\dots + 100 = 5050\$.",
          ),
          _tryIt(
            title: "À toi de jouer",
            problem: "Calcule \$2 + 5 + 8 + \\dots + 50\$ (raison 3, partant de 2).",
            hint: "Trouve le nombre de termes \$n+1\$ avec \$u_n = 50\$, puis applique la formule.",
            solution: "\$50 = 2 + 3n \\Rightarrow n = 16\$, donc 17 termes. \$S = 17 \\times (2+50)/2 = 17 \\times 26 = 442\$.",
          ),
          _checkpoint("Suites arithmétiques", [
            _q(stem: "Quelle est la raison de la suite \$5, 9, 13, 17\$ ?", choices: ['3', '4', '5', '9'], correct: 1, explanation: "Différence entre deux termes consécutifs : \$9-5 = 4\$."),
            _q(stem: "Si \$u_0 = 2\$ et \$r = 3\$, que vaut \$u_{10}\$ ?", choices: ['30', '31', '32', '33'], correct: 2, explanation: "\$u_{10} = 2 + 10 \\times 3 = 32\$."),
            _q(stem: "Somme de \$1 + 2 + \\dots + 10\$ ?", choices: ['45', '50', '55', '60'], correct: 2, explanation: "\$10 \\times 11 / 2 = 55\$."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _geometricSeq() => _lesson(
      titleFr: 'Suites géométriques',
      subtitleFr: 'Raison multiplicative, terme général, somme géométrique.',
      sections: [
        _section(kind: 'prerequisite', titleFr: 'Prérequis : suites arithmétiques', eyebrowFr: 'PRÉREQUIS', estimatedMinutes: '2', blocks: [
          _p("Tu sais reconnaître une suite arithmétique (raison **additive** \$r\$). Une suite **géométrique** fonctionne de la même manière, mais avec une raison **multiplicative** \$q\$."),
          _checkpoint("Vocabulaire", [
            _q(stem: "Dans \$2, 6, 18, 54\$, on multiplie chaque terme par :", choices: ['2', '3', '4', '6'], correct: 1, explanation: "\$6/2 = 3\$, \$18/6 = 3\$ — raison \$q = 3\$."),
          ]),
        ]),
        _section(kind: 'concept', titleFr: 'Définition et terme général', eyebrowFr: 'CONCEPT', estimatedMinutes: '4', blocks: [
          _f("u_{n+1} = u_n \\cdot q", "Définition par récurrence — chaque terme = précédent × \$q\$."),
          _f("u_n = u_0 \\cdot q^n", "Terme général."),
          _callout('warning', 'Attention si \$q = 0\$ ou \$q = 1\$',
              "Si \$q = 0\$, tous les termes sauf \$u_0\$ sont nuls. Si \$q = 1\$, la suite est constante. Les formules de somme ci-dessous **excluent** \$q = 1\$."),
          _example(
            title: "Calcul direct",
            problem: "Soit \$(u_n)\$ géométrique avec \$u_0 = 3\$ et \$q = 2\$. Calcule \$u_5\$.",
            steps: [
              "\$u_n = u_0 \\cdot q^n\$.",
              "\$u_5 = 3 \\cdot 2^5 = 3 \\cdot 32 = 96\$.",
            ],
            answer: "\$u_5 = 96\$.",
          ),
        ]),
        _section(kind: 'concept', titleFr: 'Somme géométrique', eyebrowFr: 'SOMME', estimatedMinutes: '4', blocks: [
          _f("S_n = u_0 + u_0 q + u_0 q^2 + \\dots + u_0 q^n = u_0 \\cdot \\frac{1 - q^{n+1}}{1 - q} \\quad (q \\ne 1)", "Formule de la somme géométrique."),
          _example(
            title: "Somme jusqu'à \$u_4\$",
            problem: "Calcule \$1 + 2 + 4 + 8 + 16\$.",
            steps: [
              "Suite géométrique de premier terme 1 et raison 2, 5 termes.",
              "\$S = 1 \\cdot \\frac{1 - 2^5}{1 - 2} = \\frac{1 - 32}{-1} = 31\$.",
            ],
            answer: "31.",
          ),
          _checkpoint("Suites géométriques", [
            _q(stem: "Quelle est la raison de \$8, 4, 2, 1, 0{,}5\$ ?", choices: ['1/2', '2', '−2', '4'], correct: 0, explanation: "\$4/8 = 1/2\$ : on divise par 2 = on multiplie par 1/2."),
            _q(stem: "\$u_0 = 1\$, \$q = 3\$. Que vaut \$u_4\$ ?", choices: ['64', '81', '243', '729'], correct: 1, explanation: "\$u_4 = 1 \\cdot 3^4 = 81\$."),
            _q(stem: "Que vaut \$1 + 1/2 + 1/4 + \\dots\$ (somme infinie, \$|q|<1\$) ?", choices: ['1', '3/2', '2', '∞'], correct: 2, explanation: "Somme infinie : \$u_0/(1-q) = 1/(1-1/2) = 2\$."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _seqConvergence() => _lesson(
      titleFr: 'Convergence des suites',
      subtitleFr: 'Limite finie, divergence, théorèmes de comparaison.',
      sections: [
        _section(kind: 'prerequisite', titleFr: 'Prérequis', eyebrowFr: 'PRÉREQUIS', estimatedMinutes: '2', blocks: [
          _p("Tu connais le terme général d'une suite arithmétique (\$u_n = u_0 + nr\$) et géométrique (\$u_n = u_0 q^n\$). On va maintenant étudier leur **comportement quand \$n \\to +\\infty\$**."),
        ]),
        _section(kind: 'concept', titleFr: 'Définition de la limite', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _p("Une suite \$(u_n)\$ **converge vers** \$\\ell\$ si \$u_n\$ se rapproche autant qu'on veut de \$\\ell\$ pour \$n\$ assez grand. On note \$\\lim_{n\\to+\\infty} u_n = \\ell\$."),
          _p("Si la limite n'existe pas (ou est \$\\pm\\infty\$), la suite **diverge**."),
          _f("\\lim_{n\\to+\\infty} \\frac{1}{n} = 0", "Suite de référence : 1, 1/2, 1/3, ... tend vers 0."),
          _callout('insight', 'Suites géométriques',
              "\$\\lim q^n\$ dépend de \$q\$ : si \$|q|<1\$, ça tend vers 0 ; si \$q>1\$, ça tend vers \$+\\infty\$ ; si \$q \\le -1\$, ça oscille (pas de limite)."),
          _interactive('sequence_calculator', caption: "Saisis une formule pour \$u_n\$ et observe son comportement à l'infini."),
        ]),
        _section(kind: 'concept', titleFr: 'Théorèmes de comparaison', eyebrowFr: 'THÉORÈMES', estimatedMinutes: '5', blocks: [
          _p("**Théorème des gendarmes** : si \$a_n \\le u_n \\le b_n\$ et \$a_n, b_n \\to \\ell\$, alors \$u_n \\to \\ell\$."),
          _p("**Théorème de comparaison à l'infini** : si \$u_n \\ge v_n\$ et \$v_n \\to +\\infty\$, alors \$u_n \\to +\\infty\$."),
          _example(
            title: "Théorème des gendarmes",
            problem: "Calcule \$\\lim_{n\\to+\\infty} \\dfrac{\\sin n}{n}\$.",
            steps: [
              "Pour tout \$n\$ : \$-1 \\le \\sin n \\le 1\$.",
              "Donc \$-\\dfrac{1}{n} \\le \\dfrac{\\sin n}{n} \\le \\dfrac{1}{n}\$.",
              "\$-1/n \\to 0\$ et \$1/n \\to 0\$, donc par les gendarmes la limite cherchée vaut \$0\$.",
            ],
            answer: "\$\\lim \\frac{\\sin n}{n} = 0\$.",
          ),
          _checkpoint("Limites de suites", [
            _q(stem: "\$\\lim 1/n^2\$ vaut :", choices: ['0', '1', '∞', "n'existe pas"], correct: 0, explanation: "Plus \$n\$ grandit, plus \$1/n^2\$ devient petit."),
            _q(stem: "\$\\lim (0{,}5)^n\$ vaut :", choices: ['0', '0,5', '1', '∞'], correct: 0, explanation: "\$|q|=0{,}5 < 1\$ donc \$q^n \\to 0\$."),
            _q(stem: "\$\\lim 2^n\$ vaut :", choices: ['0', '2', '∞', "n'existe pas"], correct: 2, explanation: "\$q=2>1\$ donc la suite diverge vers \$+\\infty\$."),
            _q(stem: "Le théorème des gendarmes sert à :", choices: ['démontrer une convergence par encadrement', 'calculer une dérivée', 'résoudre une équation', 'rien de spécial'], correct: 0, explanation: "On encadre la suite entre deux suites de même limite."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _seqRecursive() => _lesson(
      titleFr: 'Suites récurrentes',
      subtitleFr: 'Étudier \$u_{n+1} = f(u_n)\$ — variations, convergence vers un point fixe.',
      sections: [
        _section(kind: 'prerequisite', titleFr: 'Prérequis', eyebrowFr: 'PRÉREQUIS', estimatedMinutes: '2', blocks: [
          _p("On suppose \$f\$ continue, et on étudie une suite définie par \$u_0 \\in I\$ et \$u_{n+1} = f(u_n)\$. L'objectif : décrire le comportement de \$(u_n)\$."),
        ]),
        _section(kind: 'concept', titleFr: 'Méthode standard en 4 étapes', eyebrowFr: 'MÉTHODE', estimatedMinutes: '6', blocks: [
          _p("**Étape 1** — Vérifier que \$(u_n)\$ reste dans un intervalle stable \$I\$ (récurrence : si \$u_n \\in I\$ alors \$f(u_n) \\in I\$)."),
          _p("**Étape 2** — Étudier la **monotonie** : signe de \$u_{n+1} - u_n\$ ou comparaison de \$f(x)\$ et \$x\$."),
          _p("**Étape 3** — Si \$(u_n)\$ est monotone et bornée, elle **converge** (théorème de la limite monotone)."),
          _p("**Étape 4** — La limite \$\\ell\$ est un **point fixe** de \$f\$ : \$\\ell = f(\\ell)\$. Résoudre cette équation."),
          _interactive('recurrence_solver', caption: "Saisis \$f(x)\$ et \$u_0\$ — visualise la convergence en escalier."),
        ]),
        _section(kind: 'exampleWalkthrough', titleFr: 'Exemple complet', eyebrowFr: 'EXEMPLE', estimatedMinutes: '5', blocks: [
          _example(
            title: "Étude de \$u_{n+1} = \\sqrt{u_n + 2}\$, \$u_0 = 0\$",
            problem: "Étudier la suite \$u_{n+1} = \\sqrt{u_n + 2}\$ avec \$u_0 = 0\$.",
            steps: [
              "On vérifie que \$(u_n)\$ reste dans \$[0, 2]\$ par récurrence.",
              "Étude de la monotonie : \$u_1 = \\sqrt{2} \\approx 1{,}41 > u_0 = 0\$ — la suite semble croissante. On le démontre par récurrence : si \$u_n \\le u_{n+1}\$ alors \$u_n + 2 \\le u_{n+1} + 2\$, et \$\\sqrt{}\$ étant croissante, \$u_{n+1} \\le u_{n+2}\$.",
              "La suite est croissante et majorée par 2 → elle converge vers \$\\ell\$ avec \$0 \\le \\ell \\le 2\$.",
              "Point fixe : \$\\ell = \\sqrt{\\ell + 2} \\Leftrightarrow \\ell^2 = \\ell + 2 \\Leftrightarrow \\ell^2 - \\ell - 2 = 0\\Leftrightarrow (\\ell-2)(\\ell+1) = 0\$.",
              "Comme \$\\ell \\ge 0\$, on retient \$\\ell = 2\$.",
            ],
            answer: "\$(u_n)\$ converge vers 2.",
          ),
          _checkpoint("Récurrentes", [
            _q(stem: "Si \$f\$ est continue et \$u_n \\to \\ell\$, alors :", choices: ['\$\\ell = 0\$', '\$\\ell = u_0\$', "\$\\ell = f(\\ell)\$", "\$\\ell = +\\infty\$"], correct: 2, explanation: "Par continuité, on passe à la limite dans \$u_{n+1} = f(u_n)\$ : \$\\ell = f(\\ell)\$."),
            _q(stem: "Pour conclure à la convergence d'une suite récurrente, on cherche typiquement à montrer qu'elle est :", choices: ['arithmétique', 'majorée seulement', 'monotone et bornée', 'oscillante'], correct: 2, explanation: "Théorème de la limite monotone."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _seqAdjacent() => _lesson(
      titleFr: 'Suites adjacentes',
      subtitleFr: 'Définition, théorème et applications.',
      sections: [
        _section(kind: 'concept', titleFr: 'Définition', eyebrowFr: 'CONCEPT', estimatedMinutes: '4', blocks: [
          _p("Deux suites \$(u_n)\$ et \$(v_n)\$ sont **adjacentes** si :"),
          _p("• \$(u_n)\$ est croissante,"),
          _p("• \$(v_n)\$ est décroissante,"),
          _p("• \$\\lim (v_n - u_n) = 0\$."),
          _callout('insight', 'Théorème des suites adjacentes',
              "Si \$(u_n)\$ et \$(v_n)\$ sont adjacentes, alors elles **convergent vers la même limite** \$\\ell\$, et de plus \$u_n \\le \\ell \\le v_n\$ pour tout \$n\$."),
        ]),
        _section(kind: 'exampleWalkthrough', titleFr: 'Exemple type', eyebrowFr: 'EXEMPLE', estimatedMinutes: '4', blocks: [
          _example(
            title: "Approximation de \$\\sqrt{2}\$",
            problem: "Soit \$u_n\$ et \$v_n\$ deux suites construites par dichotomie autour de \$\\sqrt{2}\$. Montre qu'elles sont adjacentes et déduis-en \$\\sqrt{2}\$.",
            steps: [
              "Par construction, \$u_n\$ est croissante et \$v_n\$ décroissante.",
              "À chaque étape on divise l'écart par 2 : \$v_n - u_n = (v_0 - u_0)/2^n \\to 0\$.",
              "Donc \$(u_n)\$ et \$(v_n)\$ sont adjacentes : elles convergent vers une même limite \$\\ell\$.",
              "\$\\ell\$ est l'unique solution dans \$[u_0, v_0]\$ de \$x^2 = 2\$ : \$\\ell = \\sqrt{2}\$.",
            ],
            answer: "\$(u_n)\$ et \$(v_n)\$ convergent vers \$\\sqrt{2}\$.",
          ),
          _checkpoint("Adjacentes", [
            _q(stem: "Si \$(u_n)\$ croissante, \$(v_n)\$ décroissante et \$v_n - u_n \\to 0\$, alors :", choices: ['elles divergent', 'elles ont la même limite', 'elles sont égales', 'elles tendent vers 0'], correct: 1, explanation: "C'est le théorème des suites adjacentes."),
          ]),
        ]),
      ],
    );

// ============================================================================
// MATH — Limites
// ============================================================================

Map<String, dynamic> _limitDef() => _lesson(
      titleFr: 'Notion de limite',
      subtitleFr: "L'idée de « tendre vers » et la limite finie.",
      sections: [
        _section(kind: 'concept', titleFr: 'Idée intuitive', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _p("Pour la fonction \$f(x) = \\frac{x^2 - 4}{x - 2}\$, on peut calculer \$f\$ pour \$x\$ proche de 2 (mais \$\\ne 2\$, car le dénominateur s'annule en 2)."),
          _p("Pour \$x = 1{,}9\$ : \$f(x) = 3{,}9\$. Pour \$x = 1{,}99\$ : \$f(x) = 3{,}99\$. Plus \$x\$ s'approche de 2, plus \$f(x)\$ s'approche de 4."),
          _f("\\lim_{x\\to a} f(x) = L", "« \$f(x)\$ tend vers \$L\$ quand \$x\$ tend vers \$a\$ »."),
          _interactive('function_graph', config: {'function': '(x*x - 4) / (x - 2)'}, caption: "Observe que \$f(x)\$ approche 4 sans que \$x = 2\$."),
        ]),
        _section(kind: 'concept', titleFr: 'Trois cas possibles', eyebrowFr: 'CAS', estimatedMinutes: '4', blocks: [
          _p("**1. Limite finie** : \$f(x) \\to L\$ avec \$L\$ un nombre."),
          _p("**2. Limite infinie** : \$f(x) \\to +\\infty\$ ou \$-\\infty\$."),
          _p("**3. Pas de limite** : \$f(x)\$ n'approche aucune valeur (oscille, etc.)."),
          _example(
            title: "Substitution directe",
            problem: "\$\\lim_{x \\to 3}(x^2 + 1) = ?\$",
            steps: [
              "La fonction \$x^2 + 1\$ est un polynôme, continue partout.",
              "On substitue : \$3^2 + 1 = 10\$.",
            ],
            answer: "10.",
          ),
          _checkpoint("Limites — bases", [
            _q(stem: "\$\\lim_{x\\to 0} x^2 = ?\$", choices: ['0', '1', '∞', "n'existe pas"], correct: 0, explanation: "Substitution directe : \$0^2 = 0\$."),
            _q(stem: "\$\\lim_{x\\to +\\infty} \\frac{1}{x} = ?\$", choices: ['0', '1', '∞', "−∞"], correct: 0, explanation: "\$1/x\$ devient infiniment petit quand \$x \\to +\\infty\$."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _limitCalc() => _lesson(
      titleFr: 'Calcul de limites',
      subtitleFr: 'Substitution, formes indéterminées, factorisation et conjugué.',
      sections: [
        _section(kind: 'concept', titleFr: 'Les 4 outils essentiels', eyebrowFr: 'OUTILS', estimatedMinutes: '6', blocks: [
          _p("**1. Substitution directe** — si \$f\$ est continue, \$\\lim_{x\\to a} f(x) = f(a)\$. Toujours essayer en premier."),
          _p("**2. Forme \$0/0\$** — factorise et simplifie."),
          _p("**3. Forme \$\\infty/\\infty\$** — divise haut et bas par la plus haute puissance."),
          _p("**4. Multiplication par le conjugué** — quand il y a une racine carrée."),
          _f("\\lim(f \\pm g) = \\lim f \\pm \\lim g, \\quad \\lim(fg) = \\lim f \\cdot \\lim g, \\quad \\lim(f/g) = \\lim f / \\lim g", "Opérations sur les limites (sous condition que les limites existent)."),
          _interactive('limit_calculator', caption: "Saisis une expression et observe sa limite."),
        ]),
        _section(kind: 'exampleWalkthrough', titleFr: 'Trois exemples-clés', eyebrowFr: 'EXEMPLES', estimatedMinutes: '6', blocks: [
          _example(
            title: "Forme 0/0",
            problem: "\$\\lim_{x\\to 2} \\dfrac{x^2 - 4}{x - 2}\$",
            steps: [
              "Substitution : \$0/0\$, indéterminé.",
              "Factorise : \$x^2 - 4 = (x-2)(x+2)\$.",
              "Simplifie : \$\\frac{(x-2)(x+2)}{x-2} = x + 2\$.",
              "Limite : \$\\lim_{x\\to 2}(x+2) = 4\$.",
            ],
            answer: "4.",
          ),
          _example(
            title: "Forme ∞/∞",
            problem: "\$\\lim_{x\\to +\\infty} \\dfrac{2x^2 + 3}{x^2 - 1}\$",
            steps: [
              "Forme \$\\infty/\\infty\$.",
              "Divise haut/bas par \$x^2\$ : \$\\frac{2 + 3/x^2}{1 - 1/x^2}\$.",
              "À l'infini : \$\\frac{2 + 0}{1 - 0} = 2\$.",
            ],
            answer: "2.",
          ),
          _tryIt(
            title: "À toi",
            problem: "Calcule \$\\lim_{x\\to 1} \\dfrac{x^2 - 1}{x - 1}\$.",
            hint: "C'est une forme \$0/0\$ — factorise.",
            solution: "\$x^2 - 1 = (x-1)(x+1)\$, donc la limite vaut \$1+1 = 2\$.",
          ),
          _checkpoint("Calcul de limites", [
            _q(stem: "\$\\lim_{x\\to 4} \\frac{x^2-16}{x-4} = ?\$", choices: ['0', '4', '8', '16'], correct: 2, explanation: "Factorise \$x^2-16 = (x-4)(x+4)\$ → \$x+4 \\to 8\$."),
            _q(stem: "\$\\lim_{x\\to +\\infty} \\frac{3x+1}{x+5} = ?\$", choices: ['0', '1', '3', '∞'], correct: 2, explanation: "Même degré, rapport des coefficients dominants = 3."),
            _q(stem: "\$\\lim_{x\\to 0^+} \\frac{1}{x} = ?\$", choices: ['0', '+∞', '−∞', "n'existe pas"], correct: 1, explanation: "À droite de 0, \$1/x\$ tend vers \$+\\infty\$."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _continuity() => _lesson(
      titleFr: 'Continuité',
      subtitleFr: 'Définition et fonctions usuelles.',
      sections: [
        _section(kind: 'concept', titleFr: 'Définition formelle', eyebrowFr: 'CONCEPT', estimatedMinutes: '4', blocks: [
          _f("f \\text{ continue en } a \\iff \\lim_{x\\to a} f(x) = f(a)", "**La limite en \$a\$ coïncide avec la valeur en \$a\$**."),
          _p("Géométriquement : la courbe se trace sans lever le crayon. Pas de saut, pas de trou."),
          _callout('note', 'Fonctions continues partout',
              "Polynômes, sinus, cosinus, exponentielle sont continues sur \$\\mathbb{R}\$. \$1/x\$ est continue sur \$\\mathbb{R}^*\$ (mais pas définie en 0)."),
        ]),
        _section(kind: 'concept', titleFr: 'Continuité sur un intervalle', eyebrowFr: 'INTERVALLE', estimatedMinutes: '4', blocks: [
          _p("\$f\$ est continue sur \$[a,b]\$ si elle est continue en chaque point de l'intervalle. Cette propriété est cruciale pour le **TVI** (chapitre suivant)."),
          _example(
            title: "Étude de continuité",
            problem: "\$f(x) = \\begin{cases} x^2 \\text{ si } x \\le 1 \\\\ 2x - 1 \\text{ si } x > 1\\end{cases}\$. Est-elle continue en 1 ?",
            steps: [
              "\$\\lim_{x\\to 1^-} f(x) = 1^2 = 1\$.",
              "\$\\lim_{x\\to 1^+} f(x) = 2 \\cdot 1 - 1 = 1\$.",
              "Les deux limites coïncident avec \$f(1) = 1\$.",
              "Donc \$f\$ est continue en 1.",
            ],
            answer: "Oui, continue en 1.",
          ),
          _checkpoint("Continuité", [
            _q(stem: "\$f\$ continue en \$a\$ signifie :", choices: ['\$f(a) = 0\$', '\$\\lim_{x\\to a} f(x) = f(a)\$', '\$f\$ dérivable', '\$f\$ croissante'], correct: 1, explanation: "Définition exacte de la continuité."),
            _q(stem: "Quelle fonction n'est PAS continue sur \$\\mathbb{R}\$ ?", choices: ['\$\\sin x\$', '\$x^2\$', '\$1/x\$', '\$e^x\$'], correct: 2, explanation: "\$1/x\$ n'est pas définie en 0."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _tvi() => _lesson(
      titleFr: 'Théorème des valeurs intermédiaires',
      subtitleFr: "Garantir l'existence d'une solution sans la calculer.",
      sections: [
        _section(kind: 'concept', titleFr: 'Énoncé du TVI', eyebrowFr: 'THÉORÈME', estimatedMinutes: '5', blocks: [
          _f("\\text{Si } f \\text{ continue sur } [a,b] \\text{ et } k \\text{ entre } f(a) \\text{ et } f(b) \\text{, alors } \\exists c \\in [a,b] : f(c) = k.", "Énoncé du TVI."),
          _p("**Cas particulier ultra-utile** : si \$f(a) \\cdot f(b) < 0\$ (signes opposés), alors \$f\$ s'annule au moins une fois sur \$]a, b[\$."),
          _callout('warning', 'Le TVI ne donne PAS la valeur de \$c\$',
              "Il garantit qu'une solution existe, sans la calculer. Pour la trouver, il faut une autre méthode (calcul ou dichotomie)."),
        ]),
        _section(kind: 'exampleWalkthrough', titleFr: 'Application classique', eyebrowFr: 'EXEMPLE', estimatedMinutes: '5', blocks: [
          _example(
            title: "Existence d'une solution",
            problem: "Montre que \$x^3 + x - 1 = 0\$ admet une solution dans \$]0, 1[\$.",
            steps: [
              "Pose \$f(x) = x^3 + x - 1\$. \$f\$ est un polynôme, donc continue sur \$[0, 1]\$.",
              "\$f(0) = -1 < 0\$.",
              "\$f(1) = 1 + 1 - 1 = 1 > 0\$.",
              "\$f(0) \\cdot f(1) < 0\$, donc par le TVI il existe \$c \\in ]0, 1[\$ tel que \$f(c) = 0\$.",
            ],
            answer: "L'équation admet une solution dans \$]0, 1[\$.",
          ),
          _tryIt(
            title: "À toi",
            problem: "Montre que \$\\cos(x) = x\$ admet une solution dans \$[0, \\pi/2]\$.",
            hint: "Pose \$g(x) = \\cos(x) - x\$, et calcule \$g(0)\$ et \$g(\\pi/2)\$.",
            solution: "\$g(0) = 1 - 0 = 1 > 0\$. \$g(\\pi/2) = 0 - \\pi/2 < 0\$. \$g\$ est continue sur \$[0, \\pi/2]\$, donc par le TVI il existe une solution.",
          ),
          _checkpoint("TVI", [
            _q(stem: "Le TVI permet de :", choices: ['calculer une solution exacte', "garantir l'existence d'une solution", 'trouver une asymptote', 'dériver une fonction'], correct: 1, explanation: "Le TVI prouve l'existence sans donner la valeur."),
            _q(stem: "\$f\$ continue sur \$[0,1]\$, \$f(0) = 3\$, \$f(1) = -2\$. Le TVI garantit qu'il existe \$c\$ tel que :", choices: ['\$f(c) = 5\$', '\$f(c) = 0\$', '\$f(c) = -3\$', '\$f(c) = 4\$'], correct: 1, explanation: "0 est entre \$f(0) = 3\$ et \$f(1) = -2\$, donc \$\\exists c : f(c) = 0\$."),
          ]),
        ]),
      ],
    );

// ============================================================================
// MATH — Dérivation
// ============================================================================

Map<String, dynamic> _derivBasic() => _lesson(
      titleFr: 'Dérivées de base',
      subtitleFr: 'Dérivée en un point, fonction dérivée, formules à connaître.',
      sections: [
        _section(kind: 'concept', titleFr: 'Définition de la dérivée', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _f("f'(a) = \\lim_{h\\to 0} \\frac{f(a+h) - f(a)}{h}", "Définition formelle : limite du **taux d'accroissement**."),
          _p("Géométriquement, \$f'(a)\$ est la **pente de la tangente** à la courbe en \$a\$."),
          _interactive('derivative_graph', caption: "Bouge le point — observe que la pente de la tangente = \$f'(a)\$."),
        ]),
        _section(kind: 'concept', titleFr: 'Formules à mémoriser', eyebrowFr: 'FORMULES', estimatedMinutes: '5', blocks: [
          _f("(x^n)' = n x^{n-1} \\quad (\\sqrt{x})' = \\frac{1}{2\\sqrt{x}} \\quad (1/x)' = -1/x^2", "Dérivées des fonctions de référence."),
          _f("(\\sin x)' = \\cos x \\quad (\\cos x)' = -\\sin x \\quad (e^x)' = e^x \\quad (\\ln x)' = 1/x", "Trigo, exp, ln."),
          _example(
            title: "Calcul direct",
            problem: "Dérive \$f(x) = x^3 + 2x\$.",
            steps: ["\$(x^3)' = 3x^2\$, \$(2x)' = 2\$ — d'où \$f'(x) = 3x^2 + 2\$."],
            answer: "\$f'(x) = 3x^2 + 2\$.",
          ),
          _checkpoint("Bases", [
            _q(stem: "\$(x^4)' = ?\$", choices: ['\$x^3\$', '\$3x^3\$', '\$4x^3\$', '\$4x^4\$'], correct: 2, explanation: "\$n x^{n-1} = 4x^3\$."),
            _q(stem: "\$(\\sin x)' = ?\$", choices: ['\$\\sin x\$', '\$\\cos x\$', '\$-\\cos x\$', '\$-\\sin x\$'], correct: 1, explanation: "Formule de référence."),
            _q(stem: "\$(e^x)' = ?\$", choices: ['\$x e^{x-1}\$', '\$e^x\$', '\$e^{x+1}\$', '\$1\$'], correct: 1, explanation: "L'exponentielle est sa propre dérivée."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _derivRules() => _lesson(
      titleFr: 'Règles de dérivation',
      subtitleFr: 'Somme, produit, quotient, composition.',
      sections: [
        _section(kind: 'concept', titleFr: 'Les 4 règles', eyebrowFr: 'RÈGLES', estimatedMinutes: '5', blocks: [
          _f("(u + v)' = u' + v' \\qquad (\\lambda u)' = \\lambda u'", "Linéarité."),
          _f("(uv)' = u'v + uv'", "Produit."),
          _f("\\left(\\dfrac{u}{v}\\right)' = \\dfrac{u'v - uv'}{v^2}", "Quotient (\$v \\ne 0\$)."),
          _f("(u(v(x)))' = v'(x) \\cdot u'(v(x))", "Composition (chain rule)."),
          _interactive('chain_rule_visualizer', caption: "Visualise comment la dérivée d'une composée se construit."),
        ]),
        _section(kind: 'exampleWalkthrough', titleFr: 'Trois calculs typiques', eyebrowFr: 'EXEMPLES', estimatedMinutes: '5', blocks: [
          _example(
            title: "Produit",
            problem: "Dérive \$f(x) = x^2 \\sin x\$.",
            steps: [
              "Pose \$u = x^2\$, \$v = \\sin x\$. Alors \$u' = 2x\$, \$v' = \\cos x\$.",
              "\$f' = u'v + uv' = 2x \\sin x + x^2 \\cos x\$.",
            ],
            answer: "\$f'(x) = 2x \\sin x + x^2 \\cos x\$.",
          ),
          _example(
            title: "Quotient",
            problem: "Dérive \$g(x) = \\dfrac{x}{x^2 + 1}\$.",
            steps: [
              "\$u = x\$, \$v = x^2 + 1\$ : \$u' = 1\$, \$v' = 2x\$.",
              "\$g' = \\frac{u'v - uv'}{v^2} = \\frac{(x^2+1) - x(2x)}{(x^2+1)^2} = \\frac{1 - x^2}{(x^2+1)^2}\$.",
            ],
            answer: "\$g'(x) = \\dfrac{1 - x^2}{(x^2+1)^2}\$.",
          ),
          _checkpoint("Règles", [
            _q(stem: "\$(x \\cdot e^x)' = ?\$", choices: ['\$e^x\$', '\$x e^x\$', '\$(1+x) e^x\$', '\$xe^x + 1\$'], correct: 2, explanation: "Produit : \$(1)(e^x) + (x)(e^x) = (1+x)e^x\$."),
            _q(stem: "\$(\\cos(2x))' = ?\$", choices: ['\$-\\sin(2x)\$', '\$-2\\sin(2x)\$', '\$2\\cos(2x)\$', '\$-\\cos(2x)\$'], correct: 1, explanation: "Composition : \$2 \\cdot (-\\sin(2x))\$."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _derivApps() => _lesson(
      titleFr: 'Applications de la dérivée',
      subtitleFr: 'Tangente, sens de variation, extrema.',
      sections: [
        _section(kind: 'concept', titleFr: 'Équation de la tangente', eyebrowFr: 'TANGENTE', estimatedMinutes: '4', blocks: [
          _f("y = f'(a)(x - a) + f(a)", "Équation de la tangente à la courbe en \$x = a\$."),
          _example(
            title: "Tangente à la parabole",
            problem: "Tangente à \$y = x^2\$ au point \$x = 1\$.",
            steps: [
              "\$f(1) = 1\$, \$f'(x) = 2x\$, \$f'(1) = 2\$.",
              "\$y = 2(x - 1) + 1 = 2x - 1\$.",
            ],
            answer: "\$y = 2x - 1\$.",
          ),
        ]),
        _section(kind: 'concept', titleFr: 'Sens de variation', eyebrowFr: 'VARIATION', estimatedMinutes: '5', blocks: [
          _p("**Le signe de \$f'\$ donne le sens de variation de \$f\$.**"),
          _p("• \$f' > 0\$ sur \$I\$ : \$f\$ est strictement croissante sur \$I\$."),
          _p("• \$f' < 0\$ sur \$I\$ : \$f\$ est strictement décroissante sur \$I\$."),
          _p("• \$f'(a) = 0\$ avec changement de signe : \$f\$ a un **extremum** en \$a\$."),
          _interactive('sign_table', caption: "Construis le tableau de signes — déduis-en le tableau de variations."),
        ]),
        _section(kind: 'exampleWalkthrough', titleFr: 'Étude type', eyebrowFr: 'EXEMPLE', estimatedMinutes: '5', blocks: [
          _example(
            title: "Étude des variations",
            problem: "Étudie le sens de variation de \$f(x) = x^3 - 3x\$.",
            steps: [
              "\$f'(x) = 3x^2 - 3 = 3(x-1)(x+1)\$.",
              "Signe : positif sur \$]-\\infty, -1[\$ ∪ \$]1, +\\infty[\$, négatif sur \$]-1, 1[\$.",
              "Donc \$f\$ est croissante sur \$]-\\infty, -1]\$, décroissante sur \$[-1, 1]\$, croissante sur \$[1, +\\infty[\$.",
              "Maximum local en \$x=-1\$ : \$f(-1) = 2\$. Minimum local en \$x=1\$ : \$f(1) = -2\$.",
            ],
            answer: "Variations alternées avec extrema en \$\\pm 1\$.",
          ),
          _checkpoint("Variations", [
            _q(stem: "Si \$f'(a) = 0\$ avec changement de signe \$+ \\to -\$ :", choices: ['minimum', 'maximum', "rien", 'point d\'inflexion'], correct: 1, explanation: "\$f\$ croît puis décroît → maximum."),
            _q(stem: "Tangente à \$y = x^3\$ en \$x=2\$ a pour équation :", choices: ['\$y = 12x - 16\$', '\$y = 6x\$', '\$y = 12x\$', '\$y = 8x\$'], correct: 0, explanation: "\$f(2)=8\$, \$f'(x)=3x^2\$, \$f'(2)=12\$. Tangente : \$y = 12(x-2) + 8 = 12x - 16\$."),
          ]),
        ]),
      ],
    );

// ============================================================================
// MATH — Logarithme/Exponentielle (subsumés dans deriv pour SMB)
// — pas de chapitres séparés dans le skill_map SMB, on saute.
// ============================================================================

// ============================================================================
// MATH — Intégration
// ============================================================================

Map<String, dynamic> _primitives() => _lesson(
      titleFr: 'Primitives',
      subtitleFr: "Inverser la dérivation : trouver \$F\$ telle que \$F' = f\$.",
      sections: [
        _section(kind: 'concept', titleFr: 'Définition', eyebrowFr: 'CONCEPT', estimatedMinutes: '4', blocks: [
          _p("Une **primitive** de \$f\$ sur un intervalle \$I\$ est une fonction \$F\$ telle que \$F'(x) = f(x)\$ pour tout \$x \\in I\$."),
          _callout('insight', 'Unicité à une constante près',
              "Si \$F\$ est une primitive de \$f\$, alors \$F + c\$ aussi (pour toute constante \$c\$). Toutes les primitives diffèrent d'une constante."),
        ]),
        _section(kind: 'concept', titleFr: 'Tableau des primitives usuelles', eyebrowFr: 'FORMULES', estimatedMinutes: '5', blocks: [
          _f("\\int x^n \\, dx = \\frac{x^{n+1}}{n+1} + c \\quad (n \\ne -1)", "Puissances."),
          _f("\\int \\frac{1}{x} \\, dx = \\ln |x| + c", "Cas \$n = -1\$."),
          _f("\\int e^x \\, dx = e^x + c, \\quad \\int \\sin x\\, dx = -\\cos x + c, \\quad \\int \\cos x \\, dx = \\sin x + c", "Exp et trigo."),
          _example(
            title: "Trouver une primitive",
            problem: "Trouve une primitive de \$f(x) = 3x^2 + 1\$.",
            steps: [
              "\$\\int 3x^2 dx = x^3\$ et \$\\int 1 dx = x\$.",
              "Donc \$F(x) = x^3 + x + c\$.",
            ],
            answer: "\$F(x) = x^3 + x + c\$.",
          ),
          _checkpoint("Primitives", [
            _q(stem: "Une primitive de \$2x\$ est :", choices: ['\$x^2\$', '\$x\$', '\$2\$', '\$x^3/3\$'], correct: 0, explanation: "\$(x^2)' = 2x\$."),
            _q(stem: "Une primitive de \$\\cos x\$ est :", choices: ['\$\\sin x\$', '\$-\\sin x\$', '\$\\cos x\$', '\$-\\cos x\$'], correct: 0, explanation: "\$(\\sin x)' = \\cos x\$."),
            _q(stem: "Une primitive de \$e^x\$ est :", choices: ['\$x e^x\$', '\$e^x\$', '\$e^{x+1}\$', '\$x\$'], correct: 1, explanation: "\$e^x\$ est sa propre primitive."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _definiteIntegral() => _lesson(
      titleFr: 'Intégrale définie',
      subtitleFr: "Aire sous la courbe et théorème fondamental.",
      sections: [
        _section(kind: 'concept', titleFr: 'Théorème fondamental', eyebrowFr: 'THÉORÈME', estimatedMinutes: '5', blocks: [
          _f("\\int_a^b f(x) \\, dx = F(b) - F(a)", "où \$F\$ est **n'importe quelle** primitive de \$f\$."),
          _p("Cette **intégrale définie** est l'aire algébrique entre la courbe de \$f\$ et l'axe des abscisses, entre \$x = a\$ et \$x = b\$."),
          _interactive('area_curve', caption: "Visualise l'aire sous la courbe."),
        ]),
        _section(kind: 'concept', titleFr: 'Propriétés à connaître', eyebrowFr: 'PROPRIÉTÉS', estimatedMinutes: '4', blocks: [
          _f("\\int_a^a f = 0, \\quad \\int_a^b f = -\\int_b^a f, \\quad \\int_a^c f = \\int_a^b f + \\int_b^c f", "Relation de Chasles, antisymétrie."),
          _f("\\int_a^b (\\lambda f + \\mu g) = \\lambda \\int_a^b f + \\mu \\int_a^b g", "Linéarité."),
          _example(
            title: "Calcul direct",
            problem: "Calcule \$\\int_0^1 x^2 \\, dx\$.",
            steps: [
              "Primitive de \$x^2\$ : \$F(x) = x^3/3\$.",
              "\$F(1) - F(0) = 1/3 - 0 = 1/3\$.",
            ],
            answer: "\$1/3\$.",
          ),
          _checkpoint("Intégrale", [
            _q(stem: "\$\\int_0^1 1 \\, dx = ?\$", choices: ['0', '1', '\$1/2\$', '\$\\infty\$'], correct: 1, explanation: "Aire d'un rectangle 1×1."),
            _q(stem: "\$\\int_0^\\pi \\sin x \\, dx = ?\$", choices: ['0', '1', '2', '\$\\pi\$'], correct: 2, explanation: "\$[-\\cos x]_0^\\pi = -(-1) - (-1) = 2\$."),
            _q(stem: "Si \$F\$ est primitive de \$f\$, alors \$\\int_2^5 f = ?\$", choices: ['\$F(5)+F(2)\$', '\$F(5) - F(2)\$', '\$F(2) - F(5)\$', '\$F(5)\\cdot F(2)\$'], correct: 1, explanation: "Théorème fondamental."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _integralApps() => _lesson(
      titleFr: "Calcul d'aires",
      subtitleFr: "Aire entre une courbe et l'axe, entre deux courbes.",
      sections: [
        _section(kind: 'concept', titleFr: 'Aire sous une courbe positive', eyebrowFr: 'CONCEPT', estimatedMinutes: '4', blocks: [
          _p("Si \$f \\ge 0\$ sur \$[a, b]\$, alors \$\\int_a^b f(x) \\, dx\$ est **l'aire** (en unités d'aire) entre la courbe et l'axe Ox."),
          _f("\\mathcal{A} = \\int_a^b f(x) \\, dx", "Aire géométrique."),
          _callout('warning', 'Si \$f\$ change de signe',
              "L'intégrale est l'aire **algébrique** : positive au-dessus de l'axe, négative en-dessous. Pour l'aire géométrique, utilise \$\\int_a^b |f(x)| \\, dx\$."),
        ]),
        _section(kind: 'concept', titleFr: 'Aire entre deux courbes', eyebrowFr: 'COURBES', estimatedMinutes: '4', blocks: [
          _f("\\mathcal{A} = \\int_a^b (f(x) - g(x)) \\, dx \\quad \\text{si } f \\ge g \\text{ sur } [a, b]", "Aire entre deux courbes."),
          _example(
            title: "Aire entre y=x et y=x²",
            problem: "Calcule l'aire entre \$y = x\$ et \$y = x^2\$ entre 0 et 1.",
            steps: [
              "Sur \$[0, 1]\$ on a \$x \\ge x^2\$ (sauf aux bornes).",
              "\$\\mathcal{A} = \\int_0^1 (x - x^2) \\, dx = [x^2/2 - x^3/3]_0^1 = 1/2 - 1/3 = 1/6\$.",
            ],
            answer: "\$1/6\$.",
          ),
          _checkpoint("Aires", [
            _q(stem: "L'aire de la région entre \$y = 1\$ et l'axe sur \$[0, 4]\$ vaut :", choices: ['1', '2', '4', '8'], correct: 2, explanation: "Rectangle de hauteur 1 et largeur 4."),
            _q(stem: "Si \$f \\le 0\$ sur \$[a,b]\$, alors \$\\int_a^b f\$ est :", choices: ['positive', 'négative', 'nulle', 'indéterminée'], correct: 1, explanation: "\$f \\le 0\$ donne une intégrale négative."),
          ]),
        ]),
      ],
    );

// ============================================================================
// MATH — Probabilités
// ============================================================================

Map<String, dynamic> _probBasic() => _lesson(
      titleFr: 'Probabilités de base',
      subtitleFr: 'Univers, événements, probabilité uniforme.',
      sections: [
        _section(kind: 'concept', titleFr: 'Vocabulaire', eyebrowFr: 'CONCEPT', estimatedMinutes: '4', blocks: [
          _p("**Univers** \$\\Omega\$ : ensemble des résultats possibles d'une expérience aléatoire."),
          _p("**Événement** : sous-ensemble de \$\\Omega\$. **Événement élémentaire** : un seul résultat."),
          _f("P(A) = \\dfrac{\\text{nombre de cas favorables}}{\\text{nombre total de cas}}", "Probabilité **uniforme** (chaque issue équiprobable)."),
        ]),
        _section(kind: 'concept', titleFr: 'Règles de calcul', eyebrowFr: 'RÈGLES', estimatedMinutes: '4', blocks: [
          _f("P(\\bar{A}) = 1 - P(A)", "Événement contraire."),
          _f("P(A \\cup B) = P(A) + P(B) - P(A \\cap B)", "Réunion d'événements."),
          _example(
            title: "Lancer de dé",
            problem: "On lance un dé équilibré. Probabilité d'obtenir un nombre pair ?",
            steps: [
              "Univers : \$\\{1, 2, 3, 4, 5, 6\\}\$, 6 issues équiprobables.",
              "Cas favorables : \$\\{2, 4, 6\\}\$, soit 3.",
              "\$P = 3/6 = 1/2\$.",
            ],
            answer: "\$1/2\$.",
          ),
          _checkpoint("Probabilités", [
            _q(stem: "Probabilité de tirer un cœur dans un jeu de 52 cartes ?", choices: ['1/4', '1/13', '1/2', '13/52'], correct: 0, explanation: "13 cœurs sur 52 cartes : \$13/52 = 1/4\$."),
            _q(stem: "Si \$P(A) = 0{,}3\$ alors \$P(\\bar A) = ?\$", choices: ['0,3', '0,7', '1,3', '0'], correct: 1, explanation: "\$1 - 0{,}3 = 0{,}7\$."),
            _q(stem: "Pour un événement quelconque, \$P(A)\$ est dans :", choices: ['\$\\mathbb{R}\$', '\$[0, 1]\$', '\$[-1, 1]\$', '\$\\mathbb{N}\$'], correct: 1, explanation: "Une probabilité est toujours entre 0 et 1."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _conditionalProb() => _lesson(
      titleFr: 'Probabilités conditionnelles',
      subtitleFr: 'Conditionnement, indépendance, formule de Bayes.',
      sections: [
        _section(kind: 'concept', titleFr: 'Définition', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _f("P(A | B) = \\dfrac{P(A \\cap B)}{P(B)} \\quad (P(B) > 0)", "« probabilité de \$A\$ sachant \$B\$ »."),
          _f("P(A \\cap B) = P(B) \\cdot P(A | B) = P(A) \\cdot P(B | A)", "Probabilité d'une intersection."),
          _callout('insight', 'Indépendance',
              "Deux événements \$A\$ et \$B\$ sont **indépendants** si \$P(A \\cap B) = P(A)\\cdot P(B)\$, ce qui équivaut à \$P(A | B) = P(A)\$."),
        ]),
        _section(kind: 'exampleWalkthrough', titleFr: 'Exemple type', eyebrowFr: 'EXEMPLE', estimatedMinutes: '5', blocks: [
          _example(
            title: "Tirage successif sans remise",
            problem: "Une urne contient 3 boules rouges et 2 noires. On en tire 2 sans remise. Quelle est la probabilité d'obtenir 2 rouges ?",
            steps: [
              "Premier tirage rouge : \$P(R_1) = 3/5\$.",
              "Sachant \$R_1\$, il reste 2 rouges sur 4 : \$P(R_2 | R_1) = 2/4 = 1/2\$.",
              "\$P(R_1 \\cap R_2) = 3/5 \\cdot 1/2 = 3/10\$.",
            ],
            answer: "\$3/10\$.",
          ),
          _checkpoint("Conditionnelles", [
            _q(stem: "\$P(A | B) = ?\$", choices: ['\$P(A) \\cdot P(B)\$', '\$P(A \\cap B) / P(B)\$', '\$P(A) + P(B)\$', '\$P(B)/P(A)\$'], correct: 1, explanation: "Définition exacte."),
            _q(stem: "A et B indépendants ⟹ \$P(A \\cap B) = ?\$", choices: ['\$P(A) + P(B)\$', '\$P(A) - P(B)\$', '\$P(A) \\cdot P(B)\$', '\$1 - P(A)P(B)\$'], correct: 2, explanation: "Définition de l'indépendance."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _randomVariables() => _lesson(
      titleFr: 'Variables aléatoires',
      subtitleFr: "Loi, espérance, variance, écart-type.",
      sections: [
        _section(kind: 'concept', titleFr: 'Définition', eyebrowFr: 'CONCEPT', estimatedMinutes: '4', blocks: [
          _p("Une **variable aléatoire** \$X\$ associe un nombre à chaque issue de l'expérience aléatoire."),
          _p("Sa **loi de probabilité** est la donnée des valeurs prises par \$X\$ et leurs probabilités."),
        ]),
        _section(kind: 'concept', titleFr: 'Espérance et variance', eyebrowFr: 'PARAMÈTRES', estimatedMinutes: '5', blocks: [
          _f("E(X) = \\sum_i x_i \\cdot P(X = x_i)", "Espérance — moyenne pondérée."),
          _f("V(X) = E((X - E(X))^2) = \\sum_i (x_i - E(X))^2 P(X = x_i)", "Variance."),
          _f("\\sigma(X) = \\sqrt{V(X)}", "Écart-type."),
          _example(
            title: "Espérance d'un dé",
            problem: "Calcule \$E(X)\$ pour un dé équilibré (\$X\$ = numéro tiré).",
            steps: [
              "Chaque face : \$P = 1/6\$.",
              "\$E(X) = (1+2+3+4+5+6)/6 = 21/6 = 3{,}5\$.",
            ],
            answer: "\$E(X) = 3{,}5\$.",
          ),
          _checkpoint("Variables aléatoires", [
            _q(stem: "L'espérance d'une v.a. représente :", choices: ['valeur la plus probable', 'moyenne pondérée des valeurs', 'écart-type', 'maximum'], correct: 1, explanation: "Définition de l'espérance."),
            _q(stem: "Si \$X\$ vaut 0 ou 1 avec \$P(X=1) = p\$, alors \$E(X) = ?\$", choices: ['\$0\$', '\$1\$', '\$p\$', '\$1-p\$'], correct: 2, explanation: "\$0 \\cdot (1-p) + 1 \\cdot p = p\$."),
          ]),
        ]),
      ],
    );

// ============================================================================
// MATH — Nombres complexes
// ============================================================================

Map<String, dynamic> _complexBasics() => _lesson(
      titleFr: 'Nombres complexes — forme algébrique',
      subtitleFr: 'Définition, opérations, conjugué, module.',
      sections: [
        _section(kind: 'concept', titleFr: 'Définition', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _p("On note \$i\$ un nombre tel que \$i^2 = -1\$. Un **nombre complexe** s'écrit \$z = a + ib\$ avec \$a, b \\in \\mathbb{R}\$."),
          _p("\$a = \\text{Re}(z)\$ est la **partie réelle**, \$b = \\text{Im}(z)\$ la **partie imaginaire**."),
          _f("\\bar z = a - ib", "**Conjugué** : on change le signe de la partie imaginaire."),
          _f("|z| = \\sqrt{a^2 + b^2}", "**Module** — distance à l'origine dans le plan complexe."),
          _interactive('complex_plane', caption: "Place \$z = a + ib\$ dans le plan complexe."),
        ]),
        _section(kind: 'concept', titleFr: 'Opérations', eyebrowFr: 'OPÉRATIONS', estimatedMinutes: '4', blocks: [
          _f("(a + ib) + (c + id) = (a+c) + i(b+d)", "Addition."),
          _f("(a + ib)(c + id) = (ac - bd) + i(ad + bc)", "Multiplication (utilise \$i^2 = -1\$)."),
          _f("\\dfrac{z_1}{z_2} = \\dfrac{z_1 \\bar z_2}{|z_2|^2}", "Division : multiplie haut/bas par le conjugué du dénominateur."),
          _example(
            title: "Calcul de produit",
            problem: "Calcule \$(2 + 3i)(1 - i)\$.",
            steps: [
              "\$(2)(1) + (2)(-i) + (3i)(1) + (3i)(-i)\$",
              "\$= 2 - 2i + 3i - 3i^2 = 2 - 2i + 3i + 3 = 5 + i\$.",
            ],
            answer: "\$5 + i\$.",
          ),
          _checkpoint("Complexes", [
            _q(stem: "Le module de \$3 + 4i\$ vaut :", choices: ['3', '4', '5', '7'], correct: 2, explanation: "\$\\sqrt{9 + 16} = \\sqrt{25} = 5\$."),
            _q(stem: "Le conjugué de \$2 - 5i\$ est :", choices: ['\$-2 + 5i\$', '\$2 + 5i\$', '\$-2 - 5i\$', '\$5 + 2i\$'], correct: 1, explanation: "On change le signe de la partie imaginaire."),
            _q(stem: "\$i^2 = ?\$", choices: ['1', '−1', '\$i\$', '0'], correct: 1, explanation: "Définition du nombre \$i\$."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _complexTrig() => _lesson(
      titleFr: 'Forme trigonométrique',
      subtitleFr: 'Argument, forme \$re^{i\\theta}\$, formules de Moivre.',
      sections: [
        _section(kind: 'concept', titleFr: 'Module et argument', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _f("z = r(\\cos\\theta + i\\sin\\theta) = r e^{i\\theta}", "Forme **trigonométrique** (et exponentielle)."),
          _f("r = |z|, \\quad \\theta = \\arg(z) \\quad (\\text{mod } 2\\pi)", "Module et argument."),
          _callout('insight', 'Calcul de \$\\theta\$',
              "Si \$z = a + ib\$ avec \$z \\ne 0\$, alors \$\\cos\\theta = a/r\$ et \$\\sin\\theta = b/r\$. On choisit \$\\theta\$ dans \$]-\\pi, \\pi]\$."),
        ]),
        _section(kind: 'concept', titleFr: 'Formules de Moivre', eyebrowFr: 'MOIVRE', estimatedMinutes: '4', blocks: [
          _f("(r e^{i\\theta})^n = r^n e^{in\\theta}", "Puissance."),
          _f("e^{i\\alpha} \\cdot e^{i\\beta} = e^{i(\\alpha + \\beta)}, \\quad \\dfrac{e^{i\\alpha}}{e^{i\\beta}} = e^{i(\\alpha-\\beta)}", "Multiplication = addition des arguments."),
          _example(
            title: "Élever à la puissance",
            problem: "Calcule \$(1+i)^4\$.",
            steps: [
              "\$|1+i| = \\sqrt{2}\$, \$\\arg(1+i) = \\pi/4\$.",
              "\$1 + i = \\sqrt{2} e^{i\\pi/4}\$.",
              "\$(1+i)^4 = (\\sqrt{2})^4 \\cdot e^{i\\pi} = 4 \\cdot (-1) = -4\$.",
            ],
            answer: "\$-4\$.",
          ),
          _checkpoint("Trigo", [
            _q(stem: "Argument de \$i\$ ?", choices: ['0', '\$\\pi/2\$', '\$\\pi\$', '\$2\\pi\$'], correct: 1, explanation: "\$i\$ est sur l'axe imaginaire positif → \$\\pi/2\$."),
            _q(stem: "\$|e^{i\\theta}| = ?\$", choices: ['0', '1', '\$\\theta\$', '\$\\cos\\theta\$'], correct: 1, explanation: "\$|\\cos\\theta + i\\sin\\theta| = \\sqrt{\\cos^2 + \\sin^2} = 1\$."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _complexGeometry() => _lesson(
      titleFr: 'Applications géométriques des complexes',
      subtitleFr: 'Affixes, transformations, lignes de niveau.',
      sections: [
        _section(kind: 'concept', titleFr: 'Affixe et transformations', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _p("À chaque point \$M(a, b)\$ du plan, on associe son **affixe** \$z_M = a + ib\$."),
          _p("Transformations classiques :"),
          _p("• **Translation** de vecteur \$\\vec u\$ : \$z' = z + u\$."),
          _p("• **Rotation** de centre 0, angle \$\\theta\$ : \$z' = e^{i\\theta} z\$."),
          _p("• **Homothétie** de centre 0, rapport \$k\$ : \$z' = k z\$."),
          _f("|z_B - z_A| = AB \\quad ; \\quad \\arg(z_B - z_A) = (\\vec u, \\overrightarrow{AB})", "Distance et angle via les affixes."),
        ]),
        _section(kind: 'exampleWalkthrough', titleFr: 'Exemple : losange', eyebrowFr: 'EXEMPLE', estimatedMinutes: '4', blocks: [
          _example(
            title: "Reconnaître un losange",
            problem: "\$A, B, C, D\$ ont pour affixes \$0, 1, 1+i, i\$. Que peut-on dire de ABCD ?",
            steps: [
              "\$|z_B - z_A| = 1\$, \$|z_C - z_B| = 1\$, etc. — tous les côtés ont même longueur.",
              "Les diagonales \$AC\$ et \$BD\$ sont perpendiculaires (l'une est \$\\sqrt{2} e^{i\\pi/4}\$, l'autre \$\\sqrt{2} e^{i 3\\pi/4}\$).",
              "Donc ABCD est un **carré** (cas particulier de losange).",
            ],
            answer: "ABCD est un carré.",
          ),
          _checkpoint("Géométrie", [
            _q(stem: "L'affixe du milieu de \$[AB]\$ avec \$z_A = 1\$ et \$z_B = 3 + 2i\$ est :", choices: ['\$2 + i\$', '\$1 + i\$', '\$4 + 2i\$', '\$3 + 2i\$'], correct: 0, explanation: "Milieu : \$(z_A + z_B)/2 = (4 + 2i)/2 = 2 + i\$."),
          ]),
        ]),
      ],
    );

// ============================================================================
// MATH — Équations différentielles
// ============================================================================

Map<String, dynamic> _odeFirstOrder() => _lesson(
      titleFr: 'Équations différentielles du premier ordre',
      subtitleFr: "Forme \$y' = ay + b\$, solutions générales.",
      sections: [
        _section(kind: 'concept', titleFr: 'Équation \$y\' = ay\$', eyebrowFr: 'HOMOGÈNE', estimatedMinutes: '5', blocks: [
          _f("y' = a y \\implies y(x) = K e^{ax}, \\quad K \\in \\mathbb{R}", "Solutions générales."),
          _interactive('diff_eq_solver', caption: "Saisis l'équation et teste différentes conditions initiales."),
          _example(
            title: "Croissance exponentielle",
            problem: "Résous \$y' = 2y\$ avec \$y(0) = 3\$.",
            steps: [
              "Solution générale : \$y(x) = K e^{2x}\$.",
              "Condition initiale : \$y(0) = K = 3\$.",
              "Donc \$y(x) = 3 e^{2x}\$.",
            ],
            answer: "\$y(x) = 3 e^{2x}\$.",
          ),
        ]),
        _section(kind: 'concept', titleFr: 'Équation \$y\' = ay + b\$', eyebrowFr: 'COMPLÈTE', estimatedMinutes: '5', blocks: [
          _f("y' = a y + b \\implies y(x) = K e^{ax} - \\dfrac{b}{a} \\quad (a \\ne 0)", "Solution = solution homogène + solution particulière constante."),
          _example(
            title: "Refroidissement (loi de Newton)",
            problem: "Résous \$y' = -y + 5\$ avec \$y(0) = 0\$.",
            steps: [
              "Solution générale : \$y = K e^{-x} + 5\$.",
              "\$y(0) = K + 5 = 0 \\Rightarrow K = -5\$.",
              "\$y(x) = -5 e^{-x} + 5 = 5(1 - e^{-x})\$.",
            ],
            answer: "\$y(x) = 5(1 - e^{-x})\$.",
          ),
          _checkpoint("ODE 1er ordre", [
            _q(stem: "Solution générale de \$y' = 3y\$ ?", choices: ['\$3x\$', '\$K e^{3x}\$', '\$e^x + 3\$', '\$3 e^x\$'], correct: 1, explanation: "\$y' = ay\$ ⟹ \$y = K e^{ax}\$."),
            _q(stem: "Si \$y' = -2y\$ et \$y(0) = 4\$, alors \$y(x) = ?\$", choices: ['\$4 e^{2x}\$', '\$4 e^{-2x}\$', '\$-2 e^{4x}\$', '\$4 - 2x\$'], correct: 1, explanation: "Solution générale \$K e^{-2x}\$, condition initiale donne \$K = 4\$."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _odeSecondOrder() => _lesson(
      titleFr: 'Équations différentielles du second ordre',
      subtitleFr: "\$y'' + \\omega^2 y = 0\$ et oscillateur harmonique.",
      sections: [
        _section(kind: 'concept', titleFr: 'Cas \$y\'\' + \\omega^2 y = 0\$', eyebrowFr: 'OSCILLATEUR', estimatedMinutes: '5', blocks: [
          _f("y'' + \\omega^2 y = 0 \\implies y(x) = A\\cos(\\omega x) + B\\sin(\\omega x)", "Deux constantes d'intégration → deux conditions (souvent \$y(0)\$ et \$y'(0)\$)."),
          _callout('insight', 'Forme amplitude/phase',
              "On peut aussi écrire \$y(x) = R\\cos(\\omega x - \\varphi)\$ avec \$R = \\sqrt{A^2 + B^2}\$ et \$\\tan\\varphi = B/A\$. Plus parlant pour la physique."),
        ]),
        _section(kind: 'exampleWalkthrough', titleFr: 'Pendule simplifié', eyebrowFr: 'EXEMPLE', estimatedMinutes: '5', blocks: [
          _example(
            title: "Oscillations harmoniques",
            problem: "Résous \$y'' + 4y = 0\$ avec \$y(0) = 1\$, \$y'(0) = 0\$.",
            steps: [
              "Ici \$\\omega^2 = 4\$, donc \$\\omega = 2\$.",
              "Solution générale : \$y(x) = A\\cos(2x) + B\\sin(2x)\$.",
              "\$y(0) = A = 1\$.",
              "\$y'(x) = -2A\\sin(2x) + 2B\\cos(2x)\$, \$y'(0) = 2B = 0 \\Rightarrow B = 0\$.",
              "Donc \$y(x) = \\cos(2x)\$.",
            ],
            answer: "\$y(x) = \\cos(2x)\$.",
          ),
          _checkpoint("ODE 2nd ordre", [
            _q(stem: "Solution générale de \$y'' + 9y = 0\$ ?", choices: ['\$A e^{3x}\$', '\$A\\cos(3x) + B\\sin(3x)\$', '\$e^{9x}\$', '\$Ax + B\$'], correct: 1, explanation: "\$\\omega = 3\$ donc oscillation de pulsation 3."),
          ]),
        ]),
      ],
    );

// ============================================================================
// PHYSIQUE-CHIMIE
// ============================================================================

Map<String, dynamic> _kinematics() => _lesson(
      titleFr: 'Cinématique',
      subtitleFr: 'Position, vitesse, accélération — décrire un mouvement.',
      sections: [
        _section(kind: 'concept', titleFr: 'Vecteurs position, vitesse, accélération', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _f("\\vec v = \\dfrac{d\\vec{OM}}{dt}, \\quad \\vec a = \\dfrac{d\\vec v}{dt} = \\dfrac{d^2 \\vec{OM}}{dt^2}", "Définitions cinématiques."),
          _p("La **trajectoire** est la courbe décrite par \$M\$ au cours du temps. Le **mouvement** est défini par la trajectoire ET la loi horaire."),
          _interactive('motion_simulator', caption: "Joue avec position, vitesse, accélération."),
        ]),
        _section(kind: 'concept', titleFr: 'Mouvements de référence', eyebrowFr: 'TYPES', estimatedMinutes: '5', blocks: [
          _f("\\text{MRU} : x(t) = x_0 + v t \\quad (a = 0)", "Mouvement rectiligne uniforme."),
          _f("\\text{MRUA} : x(t) = x_0 + v_0 t + \\tfrac{1}{2} a t^2", "Mouvement rectiligne uniformément accéléré."),
          _example(
            title: "Chute libre",
            problem: "Un objet tombe sans vitesse initiale. Quelle hauteur a-t-il parcourue à \$t = 2\$ s ? (\$g = 10\$ m/s²)",
            steps: [
              "MRUA avec \$v_0 = 0\$, \$a = g = 10\$ m/s².",
              "\$h = \\tfrac{1}{2} g t^2 = \\tfrac{1}{2} \\cdot 10 \\cdot 4 = 20\$ m.",
            ],
            answer: "20 m.",
          ),
          _checkpoint("Cinématique", [
            _q(stem: "Si \$\\vec a = \\vec 0\$ alors le mouvement est :", choices: ['accéléré', 'uniforme', 'oscillant', 'circulaire'], correct: 1, explanation: "Pas d'accélération = vitesse constante = MRU."),
            _q(stem: "L'unité SI de l'accélération est :", choices: ['m/s', 'm/s²', 'N', 'J'], correct: 1, explanation: "Variation de vitesse par unité de temps."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _newtonsLaws() => _lesson(
      titleFr: 'Lois de Newton',
      subtitleFr: 'Inertie, principe fondamental, action-réaction.',
      sections: [
        _section(kind: 'concept', titleFr: 'Les trois lois', eyebrowFr: 'CONCEPT', estimatedMinutes: '6', blocks: [
          _p("**1ère loi (inertie)** : dans un référentiel galiléen, un solide isolé (ou pseudo-isolé) a un mouvement rectiligne uniforme."),
          _p("**2nde loi (PFD)** : \$\\sum \\vec F = m \\vec a\$ — la somme des forces extérieures égale la masse fois l'accélération."),
          _p("**3ème loi (action-réaction)** : si A exerce \$\\vec F_{A/B}\$ sur B, alors B exerce \$\\vec F_{B/A} = -\\vec F_{A/B}\$ sur A."),
          _f("\\sum \\vec F_{\\text{ext}} = m \\vec a", "Principe fondamental de la dynamique."),
          _interactive('force_diagram', caption: "Bilan des forces sur un solide."),
        ]),
        _section(kind: 'exampleWalkthrough', titleFr: 'Exemple type', eyebrowFr: 'EXEMPLE', estimatedMinutes: '5', blocks: [
          _example(
            title: "Solide sur plan incliné sans frottement",
            problem: "Solide de masse \$m\$ sur un plan d'inclinaison \$\\alpha\$, sans frottement. Trouve l'accélération.",
            steps: [
              "Forces : poids \$\\vec P\$ (vertical, vers le bas) et réaction normale \$\\vec R\$ (perpendiculaire au plan).",
              "Projection sur l'axe du plan (descente positive) : \$P \\sin\\alpha = m a\$.",
              "Avec \$P = mg\$ : \$a = g \\sin\\alpha\$.",
            ],
            answer: "\$a = g\\sin\\alpha\$.",
          ),
          _checkpoint("Newton", [
            _q(stem: "Le PFD s'écrit :", choices: ['\$\\vec F = m \\vec v\$', '\$\\sum \\vec F = m \\vec a\$', '\$\\vec F = mg\$', '\$\\vec a = m \\vec F\$'], correct: 1, explanation: "Somme des forces = masse × accélération."),
            _q(stem: "Un objet en équilibre :", choices: ['\$\\vec a = \\vec g\$', '\$\\sum \\vec F = \\vec 0\$', "n'existe pas", '\$\\vec v = \\vec 0\$ obligatoire'], correct: 1, explanation: "Équilibre = somme des forces nulle (peut être en MRU)."),
            _q(stem: "Action-réaction : si A pousse B avec 10 N, B pousse A avec :", choices: ['0 N', '5 N', '10 N en sens opposé', '20 N'], correct: 2, explanation: "Même intensité, sens opposé."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _energy() => _lesson(
      titleFr: 'Énergie mécanique',
      subtitleFr: 'Énergie cinétique, potentielle, conservation.',
      sections: [
        _section(kind: 'concept', titleFr: 'Définitions', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _f("E_c = \\tfrac{1}{2} m v^2", "**Énergie cinétique** — liée au mouvement."),
          _f("E_{pp} = m g z", "**Énergie potentielle de pesanteur** (z compté vers le haut)."),
          _f("E_m = E_c + E_p", "**Énergie mécanique totale**."),
        ]),
        _section(kind: 'concept', titleFr: 'Conservation', eyebrowFr: 'CONSERVATION', estimatedMinutes: '5', blocks: [
          _callout('insight', 'Système conservatif',
              "Si seules des forces conservatives agissent (poids, ressort), alors \$E_m\$ se conserve : \$\\Delta E_m = 0\$."),
          _f("\\Delta E_m = W(\\text{forces non conservatives})", "Théorème de l'énergie mécanique."),
          _example(
            title: "Chute libre",
            problem: "Un objet tombe d'une hauteur \$h\$. Sa vitesse au sol ?",
            steps: [
              "Au sommet : \$E_c = 0\$, \$E_p = mgh\$.",
              "Au sol : \$E_c = \\frac{1}{2} m v^2\$, \$E_p = 0\$.",
              "Conservation : \$mgh = \\frac{1}{2} m v^2\$ ⟹ \$v = \\sqrt{2gh}\$.",
            ],
            answer: "\$v = \\sqrt{2gh}\$.",
          ),
          _checkpoint("Énergie", [
            _q(stem: "L'énergie cinétique d'un objet de 2 kg à 5 m/s ?", choices: ['10 J', '25 J', '50 J', '100 J'], correct: 1, explanation: "\$\\frac{1}{2}\\cdot 2 \\cdot 25 = 25\$ J."),
            _q(stem: "Si seul le poids travaille, l'énergie mécanique :", choices: ['augmente', 'diminue', 'se conserve', 'oscille'], correct: 2, explanation: "Le poids est conservatif."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _waveProperties() => _lesson(
      titleFr: 'Propriétés des ondes',
      subtitleFr: 'Onde mécanique, célérité, période, longueur d\'onde.',
      sections: [
        _section(kind: 'concept', titleFr: 'Définitions', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _p("Une **onde** est la propagation d'une perturbation sans transport de matière, mais avec transport d'énergie."),
          _f("v = \\lambda / T = \\lambda \\cdot f", "Célérité, longueur d'onde, période, fréquence."),
          _interactive('wave', caption: "Modifie période et amplitude — observe la propagation."),
        ]),
        _section(kind: 'concept', titleFr: 'Périodicité spatiale et temporelle', eyebrowFr: 'PÉRIODICITÉ', estimatedMinutes: '4', blocks: [
          _p("Une onde **progressive sinusoïdale** est doublement périodique : en temps (période \$T\$) et en espace (longueur d'onde \$\\lambda\$)."),
          _f("y(x, t) = A \\cos\\left(2\\pi\\left(\\dfrac{t}{T} - \\dfrac{x}{\\lambda}\\right)\\right)", "Équation d'une onde plane progressive."),
          _example(
            title: "Calcul de longueur d'onde",
            problem: "Onde sonore à 1 kHz dans l'air (v = 340 m/s). \$\\lambda = ?\$",
            steps: [
              "\$\\lambda = v / f = 340 / 1000 = 0{,}34\$ m.",
            ],
            answer: "0,34 m = 34 cm.",
          ),
          _checkpoint("Ondes", [
            _q(stem: "Si f double, \$\\lambda\$ devient (à v constante) :", choices: ['double', 'inchangée', 'moitié', 'quadruple'], correct: 2, explanation: "\$\\lambda = v/f\$ : doubler f divise \$\\lambda\$ par 2."),
            _q(stem: "Une onde transporte :", choices: ['de la matière', 'de l\'énergie', 'rien', 'des charges'], correct: 1, explanation: "Énergie sans transport de matière."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _soundLight() => _lesson(
      titleFr: 'Ondes sonores et lumineuses',
      subtitleFr: 'Diffraction, réfraction, interférences.',
      sections: [
        _section(kind: 'concept', titleFr: 'Diffraction', eyebrowFr: 'DIFFRACTION', estimatedMinutes: '4', blocks: [
          _p("La **diffraction** apparaît quand une onde rencontre un obstacle ou une ouverture de taille comparable à \$\\lambda\$. L'onde s'étale au-delà de l'obstacle."),
          _f("\\theta \\approx \\dfrac{\\lambda}{a}", "Demi-angle de la tâche centrale (fente de largeur \$a\$)."),
        ]),
        _section(kind: 'concept', titleFr: 'Réfraction', eyebrowFr: 'RÉFRACTION', estimatedMinutes: '4', blocks: [
          _f("n_1 \\sin i_1 = n_2 \\sin i_2", "**Loi de Snell-Descartes**."),
          _interactive('refraction_simulator', caption: "Bouge l'angle d'incidence — observe l'angle réfracté."),
          _example(
            title: "Rayon air → eau",
            problem: "Rayon arrivant à 30° sur de l'eau (\$n = 1{,}33\$). Angle de réfraction ?",
            steps: [
              "\$\\sin i_2 = \\sin 30 / 1{,}33 = 0{,}5 / 1{,}33 \\approx 0{,}376\$.",
              "\$i_2 \\approx 22{,}1°\$.",
            ],
            answer: "\$\\approx 22°\$.",
          ),
          _checkpoint("Optique", [
            _q(stem: "La diffraction est marquée quand :", choices: ['\$\\lambda \\gg a\$', '\$\\lambda \\ll a\$', '\$\\lambda \\approx a\$', 'jamais'], correct: 2, explanation: "Effet visible quand l'ouverture est de l'ordre de \$\\lambda\$."),
            _q(stem: "Quand la lumière passe d'un milieu plus réfringent à un moins réfringent :", choices: ['l\'angle augmente', 'l\'angle diminue', 'reste identique', "elle s'arrête"], correct: 0, explanation: "Si \$n_1 > n_2\$, alors \$i_2 > i_1\$."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _rcRlCircuits() => _lesson(
      titleFr: 'Circuits RC et RL',
      subtitleFr: 'Charge/décharge d\'un condensateur, établissement du courant dans une bobine.',
      sections: [
        _section(kind: 'concept', titleFr: 'Circuit RC', eyebrowFr: 'RC', estimatedMinutes: '5', blocks: [
          _f("\\tau = RC", "**Constante de temps** RC — temps caractéristique de charge."),
          _f("u_C(t) = E (1 - e^{-t/\\tau})", "Charge d'un condensateur sous tension \$E\$."),
          _f("u_C(t) = U_0 e^{-t/\\tau}", "Décharge."),
          _interactive('capacitor_charge', caption: "Joue avec R et C — observe la courbe."),
        ]),
        _section(kind: 'concept', titleFr: 'Circuit RL', eyebrowFr: 'RL', estimatedMinutes: '5', blocks: [
          _f("\\tau = L/R", "Constante de temps RL."),
          _f("i(t) = \\dfrac{E}{R}\\left(1 - e^{-t/\\tau}\\right)", "Établissement du courant."),
          _example(
            title: "Calcul de constante de temps",
            problem: "\$R = 1\$ kΩ, \$C = 10\$ µF. \$\\tau = ?\$",
            steps: [
              "\$\\tau = RC = 10^3 \\cdot 10 \\cdot 10^{-6} = 10^{-2}\$ s = 10 ms.",
            ],
            answer: "10 ms.",
          ),
          _checkpoint("RC/RL", [
            _q(stem: "Au bout de \$5\\tau\$, la charge atteint :", choices: ['50%', '63%', '99%', '100%'], correct: 2, explanation: "\$1 - e^{-5} \\approx 0{,}993\$."),
            _q(stem: "Constante de temps d'un circuit RL :", choices: ['\$RL\$', '\$L/R\$', '\$R/L\$', '\$L+R\$'], correct: 1, explanation: "\$\\tau = L/R\$."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _rlcOscillations() => _lesson(
      titleFr: 'Oscillations RLC',
      subtitleFr: 'Régimes libres, période propre, amortissement.',
      sections: [
        _section(kind: 'concept', titleFr: 'Équation différentielle', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _f("LC \\dfrac{d^2 u_C}{dt^2} + RC \\dfrac{d u_C}{dt} + u_C = 0", "Circuit RLC série, décharge libre."),
          _f("T_0 = 2\\pi \\sqrt{LC}", "Période propre (cas non amorti)."),
          _interactive('rlc', caption: "Joue avec R, L, C — observe les trois régimes."),
        ]),
        _section(kind: 'concept', titleFr: 'Trois régimes', eyebrowFr: 'RÉGIMES', estimatedMinutes: '5', blocks: [
          _p("**Pseudo-périodique** (faible \$R\$) : oscillations amorties."),
          _p("**Critique** (\$R\$ critique) : retour exponentiel le plus rapide possible sans oscillation."),
          _p("**Apériodique** (\$R\$ grand) : retour lent à l'équilibre."),
          _example(
            title: "Période propre",
            problem: "\$L = 0{,}1\$ H, \$C = 10\$ µF. \$T_0 = ?\$",
            steps: [
              "\$T_0 = 2\\pi \\sqrt{0{,}1 \\cdot 10^{-5}} = 2\\pi \\sqrt{10^{-6}} = 2\\pi \\cdot 10^{-3}\$",
              "\$\\approx 6{,}28 \\cdot 10^{-3}\$ s = 6,28 ms.",
            ],
            answer: "≈ 6,28 ms.",
          ),
          _checkpoint("RLC", [
            _q(stem: "Période propre d'un RLC :", choices: ['\$2\\pi \\sqrt{RC}\$', '\$2\\pi \\sqrt{LC}\$', '\$2\\pi RL\$', '\$\\sqrt{L/C}\$'], correct: 1, explanation: "\$T_0 = 2\\pi\\sqrt{LC}\$."),
            _q(stem: "Régime critique :", choices: ['oscillations entretenues', 'pas d\'oscillation, retour le plus rapide', "rien ne se passe", 'instable'], correct: 1, explanation: "Frontière entre pseudo-périodique et apériodique."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _acidBase() => _lesson(
      titleFr: 'Réactions acido-basiques',
      subtitleFr: 'pH, couples acide/base, équilibre acide-base.',
      sections: [
        _section(kind: 'concept', titleFr: 'Définitions de Brønsted', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _p("**Acide** : espèce capable de céder un proton \$H^+\$. **Base** : espèce capable d'en capter."),
          _f("HA + H_2O \\rightleftharpoons A^- + H_3O^+", "Réaction acide-base d'un acide HA dans l'eau."),
          _f("\\text{pH} = -\\log [H_3O^+]", "Définition du pH (en mol/L)."),
          _interactive('acid_base_ph', caption: "Joue avec la concentration et le \$K_a\$ — lis le pH."),
        ]),
        _section(kind: 'concept', titleFr: 'Constante d\'acidité \$K_a\$', eyebrowFr: 'KA', estimatedMinutes: '5', blocks: [
          _f("K_a = \\dfrac{[A^-][H_3O^+]}{[HA]}", "Constante d'équilibre de l'acide HA."),
          _f("\\text{pK}_a = -\\log K_a", "Forme logarithmique."),
          _f("\\text{pH} = \\text{pK}_a + \\log\\dfrac{[A^-]}{[HA]}", "Équation d'Henderson-Hasselbalch."),
          _example(
            title: "pH d'une solution",
            problem: "Calcule le pH d'une solution avec \$[H_3O^+] = 10^{-4}\$ mol/L.",
            steps: [
              "pH = \$-\\log(10^{-4}) = 4\$.",
            ],
            answer: "pH = 4.",
          ),
          _checkpoint("Acido-base", [
            _q(stem: "Solution avec pH = 7 :", choices: ['acide', 'basique', 'neutre', 'inconnue'], correct: 2, explanation: "À 25°C, pH = 7 = neutre."),
            _q(stem: "Couple \$HCl/Cl^-\$ : qui est l'acide ?", choices: ['HCl', '\$Cl^-\$', 'les deux', 'aucun'], correct: 0, explanation: "HCl cède un \$H^+\$ pour donner \$Cl^-\$."),
            _q(stem: "Si \$[H_3O^+] = 10^{-3}\$, alors pH =", choices: ['1', '3', '7', '11'], correct: 1, explanation: "\$-\\log 10^{-3} = 3\$."),
          ]),
        ]),
      ],
    );

Map<String, dynamic> _redox() => _lesson(
      titleFr: 'Réactions d\'oxydoréduction',
      subtitleFr: 'Couples Ox/Red, demi-équations, piles.',
      sections: [
        _section(kind: 'concept', titleFr: 'Définitions', eyebrowFr: 'CONCEPT', estimatedMinutes: '5', blocks: [
          _p("**Oxydation** : perte d'électrons. **Réduction** : gain d'électrons. **Réaction redox** : transfert d'électrons d'un réducteur vers un oxydant."),
          _p("**Couple Ox/Red** : associe un oxydant et le réducteur conjugué — par ex. \$Cu^{2+}/Cu\$."),
          _f("Ox + n e^- \\rightleftharpoons Red", "Demi-équation redox."),
        ]),
        _section(kind: 'concept', titleFr: 'Piles électrochimiques', eyebrowFr: 'PILES', estimatedMinutes: '5', blocks: [
          _interactive('daniell_cell', caption: "Pile Daniell : Zn + Cu²⁺ → Zn²⁺ + Cu."),
          _f("\\Delta E^\\circ = E^\\circ(\\text{cathode}) - E^\\circ(\\text{anode})", "Force électromotrice standard."),
          _example(
            title: "Pile Daniell",
            problem: "Calcule la fem standard de la pile Daniell. \$E^\\circ(Cu^{2+}/Cu) = 0{,}34\$ V, \$E^\\circ(Zn^{2+}/Zn) = -0{,}76\$ V.",
            steps: [
              "Le cuivre est réduit (cathode), le zinc est oxydé (anode).",
              "\$\\Delta E^\\circ = 0{,}34 - (-0{,}76) = 1{,}10\$ V.",
            ],
            answer: "1,10 V.",
          ),
          _checkpoint("Redox", [
            _q(stem: "\$Zn \\to Zn^{2+} + 2e^-\$ est :", choices: ['une réduction', 'une oxydation', 'une combustion', 'une dissolution'], correct: 1, explanation: "Perte d'électrons = oxydation."),
            _q(stem: "Dans la pile Daniell, à l'anode :", choices: ['Cu se dépose', 'Zn s\'oxyde', 'rien', 'Cu²⁺ se réduit'], correct: 1, explanation: "Anode = oxydation = Zn → Zn²⁺ + 2e⁻."),
          ]),
        ]),
      ],
    );
