// Expanded textbook-depth solutions for SMB exam questions (migration 023).
// Targets the 80 SMB questions inserted by migration 021 — UPDATEs the
// answer JSONB with much longer step prose, richer mistake/tip callouts,
// and filled-out grading_notes.
//
// Pattern of each step's text: ~300-500 chars explaining (1) the situation,
// (2) why the naive approach fails or what technique to apply, (3) the
// derivation in narrative form, (4) the conclusion.
//
// Run: dart backend/seed/json_encode_exam_solutions_smb_v2.dart

import "dart:convert";
import "dart:io";

void main(List<String> args) {
  final out = StringBuffer();
  out.writeln("-- Migration 023: textbook-depth solutions for SMB exam questions.");
  out.writeln("-- Auto-generated by json_encode_exam_solutions_smb_v2.dart.");
  out.writeln("-- Overwrites the answer JSONB inserted by migration 021.");
  out.writeln("BEGIN;");
  out.writeln();

  var seq = 1;
  for (final qid in _questionIds) {
    final answer = _answers[seq - 1];
    final aJson = jsonEncode(answer).replaceAll("'", "''");
    out.writeln("UPDATE public.exam_questions SET answer = '$aJson'::jsonb WHERE id = '$qid';");
    seq++;
  }

  out.writeln();
  out.writeln("COMMIT;");

  final output = args.isNotEmpty ? args[0] : "backend/supabase/migrations/023_exam_solutions_smb_expanded.sql";
  File(output).writeAsStringSync(out.toString());
  stdout.writeln("Wrote $output (${seq - 1} answer updates).");
}

// ---------------------------------------------------------------------------
// Question IDs in order — matches migration 021's emission sequence.
// (8 papers × 10 questions = 80 IDs.)
// ---------------------------------------------------------------------------
final List<String> _questionIds = [
  for (var i = 1; i <= 80; i++)
    "c1b2c3d4-eeee-0000-0000-${i.toRadixString(16).padLeft(12, '0')}",
];

// ---------------------------------------------------------------------------
// Builder helpers (same shape as the v1 encoder's _Step / _Question)
// ---------------------------------------------------------------------------

Map<String, dynamic> _step(
  String text, {
  int points = 0,
  String? widgetSlug,
  Map<String, dynamic>? widgetConfig,
  String? mistake,
  String? tip,
}) =>
    {
      "text": text,
      if (points > 0) "points": points,
      if (widgetSlug != null) "widget_slug": widgetSlug,
      if (widgetConfig != null) "widget_config": widgetConfig,
      if (mistake != null) "mistake": mistake,
      if (tip != null) "tip": tip,
    };

Map<String, dynamic> _ans({
  required List<Map<String, dynamic>> steps,
  String? finalAnswer,
  String? gradingNotes,
  List<String> commonMistakes = const [],
  List<String> tips = const [],
}) =>
    {
      "steps": steps,
      if (finalAnswer != null) "final_answer": finalAnswer,
      if (gradingNotes != null) "grading_notes": gradingNotes,
      if (commonMistakes.isNotEmpty) "common_mistakes": commonMistakes,
      if (tips.isNotEmpty) "tips": tips,
    };

// ---------------------------------------------------------------------------
// THE EXPANDED ANSWERS — ordered identically to migration 021.
// ---------------------------------------------------------------------------

final List<Map<String, dynamic>> _answers = [
  // ============================================================
  // SMB Math 2024 normale (paper 1) — 10 questions
  // ============================================================

  // Q1 — Convergence de $u_{n+1}=(u_n+3)/2$, $u_0=1$
  _ans(
    steps: [
      _step(
        r"**Stabilité.** Pour pouvoir parler de la limite, on doit d'abord montrer que la suite reste dans un intervalle borné. Posons $f(x) = \dfrac{x+3}{2}$ ; on va prouver par récurrence que $u_n \in [0, 3]$ pour tout entier $n \ge 0$. **Initialisation :** $u_0 = 1 \in [0, 3]$, c'est bon. **Hérédité :** supposons $u_n \in [0, 3]$. Alors $u_n + 3 \in [3, 6]$, donc $u_{n+1} = (u_n+3)/2 \in [3/2, 3] \subset [0, 3]$. La propriété se transmet, donc $(u_n)$ est bornée par 0 et 3.",
        points: 2,
        widgetSlug: "recurrence_solver",
        widgetConfig: {"function": "(x + 3) / 2", "u0": 1.0, "iterations": 8},
      ),
      _step(
        r"**Monotonie.** Calcul direct : $u_1 = (1+3)/2 = 2 > u_0 = 1$, la suite démarre en augmentant. On démontre la monotonie globalement par récurrence sur la propriété $P_n$ : « $u_n \le u_{n+1}$ ». L'hérédité utilise la croissance de $f$ : si $u_n \le u_{n+1}$, alors $f(u_n) \le f(u_{n+1})$, c'est-à-dire $u_{n+1} \le u_{n+2}$. Donc $(u_n)$ est croissante sur $\mathbb{N}$.",
        points: 2,
        tip: r"On démontre la monotonie d'une suite récurrente $u_{n+1} = f(u_n)$ via la monotonie de $f$ : si $f$ est croissante, alors la monotonie initiale ($u_0$ vs $u_1$) se propage à toute la suite.",
      ),
      _step(
        r"**Convergence.** On combine : $(u_n)$ est croissante et majorée par 3, donc d'après le **théorème de la limite monotone**, elle converge vers une limite finie $\ell \in \mathbb{R}$. Comme $u_n \in [0, 3]$ pour tout $n$ et que la limite préserve les inégalités larges, on a aussi $\ell \in [0, 3]$. À ce stade, on sait que la limite existe sans la connaître explicitement.",
        points: 2,
      ),
      _step(
        r"**Calcul de la limite.** La fonction $f(x) = (x+3)/2$ est continue sur $\mathbb{R}$, donc en passant à la limite des deux côtés de la relation $u_{n+1} = f(u_n)$, on obtient $\ell = f(\ell)$, c'est-à-dire $\ell = \dfrac{\ell + 3}{2}$. On résout : $2\ell = \ell + 3$, soit $\ell = 3$. La valeur trouvée est bien dans $[0, 3]$, cohérente avec la stabilité.",
        points: 2,
        mistake: r"Erreur classique : passer à la limite sans vérifier la continuité de $f$. La relation $\ell = f(\ell)$ n'est valable que si $f$ est continue au point $\ell$ ; sinon le passage à la limite est illégitime.",
      ),
    ],
    finalAnswer: r"$(u_n)$ converge vers $\ell = 3$.",
    gradingNotes: r"Stabilité par récurrence (2 pts) + monotonie démontrée par croissance de $f$ (2 pts) + invocation du théorème de la limite monotone (2 pts) + résolution du point fixe avec mention de la continuité (2 pts). Le candidat qui « voit » directement $\ell = 3$ sans justifier la convergence perd les 6 premiers points.",
    commonMistakes: [
      r"Calculer $\ell = 3$ comme point fixe sans avoir prouvé la convergence — c'est fournir la limite d'une suite dont on n'a pas montré qu'elle converge.",
      r"Confondre « $(u_n)$ croissante et majorée » avec « $(u_n)$ atteint son majorant » : le théorème garantit la convergence, pas que la limite soit atteinte en un terme fini.",
    ],
    tips: [
      r"La méthode standard pour une suite récurrente $u_{n+1} = f(u_n)$ : (1) stabilité d'un intervalle, (2) monotonie via celle de $f$, (3) théorème de la limite monotone, (4) point fixe avec continuité.",
    ],
  ),

  // Q2 — limite de $(2x^2+3x-1)/(x^2-4)$ à l'infini
  _ans(
    steps: [
      _step(
        r"**Identification de la forme.** Quand $x \to +\infty$, le numérateur $2x^2 + 3x - 1$ tend vers $+\infty$ (terme dominant $2x^2$) et le dénominateur $x^2 - 4$ tend également vers $+\infty$. On obtient une **forme indéterminée** $\dfrac{\infty}{\infty}$ : la simple inspection des limites individuelles ne donne pas la réponse, il faut transformer l'expression.",
        points: 1,
      ),
      _step(
        r"**Technique : factoriser par la plus haute puissance.** Pour une fraction de polynômes à l'infini, on factorise au numérateur et au dénominateur par le **monôme dominant** — ici $x^2$. On écrit : $\dfrac{2x^2 + 3x - 1}{x^2 - 4} = \dfrac{x^2\bigl(2 + \dfrac{3}{x} - \dfrac{1}{x^2}\bigr)}{x^2\bigl(1 - \dfrac{4}{x^2}\bigr)}$. Le facteur $x^2$ se simplifie haut et bas, et il reste $\dfrac{2 + 3/x - 1/x^2}{1 - 4/x^2}$.",
        points: 2,
        tip: r"Cette technique fonctionne pour toute fraction rationnelle à l'infini : factoriser par la plus haute puissance fait apparaître des termes en $1/x^k$ qui tendent vers 0.",
      ),
      _step(
        r"**Passage à la limite.** Quand $x \to +\infty$, chaque terme $1/x^k$ ($k \ge 1$) tend vers 0, donc $3/x \to 0$, $1/x^2 \to 0$ et $4/x^2 \to 0$. La fraction tend alors vers $\dfrac{2 + 0 - 0}{1 - 0} = \dfrac{2}{1} = 2$. **Lecture rapide :** quand le numérateur et le dénominateur ont le même degré, la limite à l'infini est le quotient des coefficients dominants.",
        points: 2,
      ),
    ],
    finalAnswer: r"$\displaystyle\lim_{x\to+\infty} \dfrac{2x^2+3x-1}{x^2-4} = 2$.",
    gradingNotes: r"Identification de la forme $\infty/\infty$ (1 pt) + factorisation par $x^2$ (2 pts) + passage à la limite avec mention que les $1/x^k$ tendent vers 0 (2 pts).",
    tips: [
      r"Mémoriser le résultat général : pour $P(x)/Q(x)$ avec $\deg P = \deg Q$ à l'infini, la limite est le rapport des coefficients dominants. Si $\deg P > \deg Q$, c'est $\pm\infty$ ; si $\deg P < \deg Q$, c'est 0.",
    ],
  ),

  // Q3 — $\int_0^1 (3x^2 + 2x) dx$
  _ans(
    steps: [
      _step(
        r"**Recherche d'une primitive.** L'intégrale d'un polynôme se calcule terme à terme grâce à la linéarité : $\int (3x^2 + 2x) \, dx = \int 3x^2 \, dx + \int 2x \, dx$. Pour chaque monôme $ax^n$, une primitive est $\dfrac{a x^{n+1}}{n+1}$. Donc une primitive de $3x^2$ est $x^3$ (car $3 \cdot \dfrac{x^3}{3} = x^3$), et une primitive de $2x$ est $x^2$. On retient $F(x) = x^3 + x^2$.",
        points: 2,
      ),
      _step(
        r"**Évaluation aux bornes.** D'après le théorème fondamental du calcul intégral, $\int_0^1 f(x) \, dx = F(1) - F(0)$ pour toute primitive $F$ de $f$. Calcul : $F(1) = 1^3 + 1^2 = 1 + 1 = 2$ et $F(0) = 0 + 0 = 0$. Donc $\int_0^1 (3x^2 + 2x) \, dx = 2 - 0 = 2$. Géométriquement, c'est l'aire algébrique entre la courbe de $y = 3x^2 + 2x$ et l'axe des abscisses sur $[0, 1]$.",
        points: 2,
        widgetSlug: "area_curve",
        widgetConfig: {"function": "3*x*x + 2*x", "a": 0.0, "b": 1.0},
      ),
    ],
    finalAnswer: r"$\displaystyle\int_0^1 (3x^2 + 2x) \, dx = 2$.",
    gradingNotes: r"Primitive correcte (2 pts) + évaluation aux bornes avec citation du théorème fondamental (2 pts).",
    commonMistakes: [
      r"Oublier le coefficient lors de la primitive : écrire $\int 3x^2 dx = x^3/3$ au lieu de $x^3$. Vérifier en dérivant : $(x^3)' = 3x^2$, $(x^3/3)' = x^2$ — pas la même chose.",
    ],
  ),

  // Q4 — Variations de $f(x) = x^3 - 3x^2 + 4$
  _ans(
    steps: [
      _step(
        r"**Domaine et dérivée.** $f$ est polynômiale, donc dérivable sur tout $\mathbb{R}$. On dérive terme à terme : $f'(x) = 3x^2 - 6x$. On factorise pour étudier le signe : $f'(x) = 3x(x - 2)$. Cette forme factorisée fait apparaître les deux racines de $f'$ : $x = 0$ et $x = 2$.",
        points: 2,
      ),
      _step(
        r"**Tableau de signes de $f'$.** $f'(x) = 3x(x-2)$ est un polynôme de degré 2 dont le coefficient dominant est positif : la parabole $f'$ est positive en dehors de ses racines, négative entre. Concrètement : $f' > 0$ sur $]-\infty, 0[$, $f' < 0$ sur $]0, 2[$, $f' > 0$ sur $]2, +\infty[$. Ce tableau gouverne entièrement le sens de variation de $f$.",
        points: 2,
        widgetSlug: "sign_table",
        widgetConfig: {"function": "3*x*(x-2)"},
      ),
      _step(
        r"**Sens de variation de $f$.** D'après la règle « signe de $f'$ = sens de variation de $f$ » : $f$ est strictement croissante sur $]-\infty, 0]$, strictement décroissante sur $[0, 2]$, à nouveau strictement croissante sur $[2, +\infty[$. Ce comportement « croît-décroît-croît » est typique d'un polynôme cubique avec deux extrema locaux.",
        points: 2,
      ),
      _step(
        r"**Extrema.** Aux points où $f'$ change de signe, $f$ a un extremum local. En $x = 0$, $f'$ passe de $+$ à $-$ : c'est un **maximum local**, $f(0) = 0 - 0 + 4 = 4$. En $x = 2$, $f'$ passe de $-$ à $+$ : c'est un **minimum local**, $f(2) = 8 - 12 + 4 = 0$. À l'infini, $f \to \pm\infty$ selon le signe (c'est un cubique), donc pas d'extremum global.",
        points: 1,
      ),
    ],
    finalAnswer: r"$f$ croissante sur $]-\infty, 0]$ et $[2, +\infty[$, décroissante sur $[0, 2]$. Maximum local en $x=0$ ($f=4$), minimum local en $x=2$ ($f=0$).",
    gradingNotes: r"Calcul de $f'$ et factorisation (2 pts) + tableau de signes (2 pts) + sens de variation (2 pts) + extrema avec valeurs (1 pt).",
    commonMistakes: [
      r"Confondre le signe de $f'$ avec le signe de $f$. Le tableau qu'on construit donne le sens de variation de $f$, pas son signe.",
      r"Oublier de calculer $f$ aux points critiques. « $f$ admet un maximum en 0 » ne suffit pas, il faut donner $f(0) = 4$.",
    ],
    tips: [
      r"Pour un polynôme de degré 3 à coefficient dominant $> 0$, le profil typique est croît-décroît-croît si le discriminant de $f'$ est positif, sinon strictement croissant partout.",
    ],
  ),

  // Q5 — MCQ : module de $z = 1 + i\sqrt{3}$
  _ans(
    steps: [
      _step(
        r"**Définition du module.** Pour un complexe $z = a + ib$ avec $a, b \in \mathbb{R}$, le module est défini par $|z| = \sqrt{a^2 + b^2}$. C'est la distance du point d'affixe $z$ à l'origine du plan complexe. Ici, $z = 1 + i\sqrt{3}$ donc $a = 1$ et $b = \sqrt{3}$.",
        points: 1,
      ),
      _step(
        r"**Calcul.** On applique la formule : $|z|^2 = a^2 + b^2 = 1^2 + (\sqrt{3})^2 = 1 + 3 = 4$. En prenant la racine carrée (positive, car un module est toujours $\ge 0$), on obtient $|z| = \sqrt{4} = 2$. La bonne réponse est donc **C : 2**.",
        points: 1,
      ),
      _step(
        r"**Interprétation géométrique.** Dans le plan complexe, le point d'affixe $z = 1 + i\sqrt{3}$ a pour coordonnées $(1, \sqrt{3})$. Sa distance à l'origine — par le théorème de Pythagore — vaut $\sqrt{1 + 3} = 2$. C'est exactement le module. On peut aussi remarquer que $z = 2 e^{i\pi/3}$ : forme polaire de module 2 et argument $\pi/3$.",
        points: 1,
        widgetSlug: "complex_plane",
        widgetConfig: {"real": 1.0, "imaginary": 1.732},
      ),
    ],
    finalAnswer: r"C — $|z| = 2$",
    gradingNotes: r"Application correcte de la formule $|z|^2 = a^2 + b^2$ (2 pts) + valeur finale (1 pt).",
    commonMistakes: [
      r"Oublier d'élever au carré $\sqrt{3}$ : écrire $|z|^2 = 1 + \sqrt{3}$ au lieu de $1 + 3$. Toujours développer la partie imaginaire au carré explicitement.",
      r"Confondre module et argument. Le module est une longueur (toujours positive), l'argument est un angle.",
    ],
  ),

  // Q6 — Resolve $\sqrt{2x+1} = x - 1$
  _ans(
    steps: [
      _step(
        r"**Conditions de validité.** Avant toute manipulation, il faut s'assurer que les deux membres ont un sens. La racine carrée impose $2x + 1 \ge 0$, soit $x \ge -1/2$. Et puisque $\sqrt{...} \ge 0$ par définition, on doit avoir $x - 1 \ge 0$, soit $x \ge 1$. **Le domaine de l'équation est donc $[1, +\infty[$.** Toute solution candidate trouvée plus tard devra être dans cet intervalle, sinon on la rejette.",
        points: 2,
        mistake: r"L'erreur la plus fréquente : oublier la condition $x - 1 \ge 0$ avant d'élever au carré. Si on l'oublie, on peut aboutir à des solutions parasites — typiquement des $x < 1$ qui rendent $\sqrt{2x+1} = x - 1$ faux car le membre de droite serait négatif.",
      ),
      _step(
        r"**Élévation au carré.** Sur le domaine $[1, +\infty[$, les deux membres sont positifs, donc l'équation $\sqrt{2x+1} = x - 1$ équivaut à $2x + 1 = (x - 1)^2$. On développe : $(x-1)^2 = x^2 - 2x + 1$. L'équation devient $2x + 1 = x^2 - 2x + 1$, soit $x^2 - 4x = 0$ après simplification.",
        points: 2,
      ),
      _step(
        r"**Résolution de l'équation polynômiale.** $x^2 - 4x = 0$ se factorise en $x(x - 4) = 0$. Le produit est nul si et seulement si l'un des facteurs est nul, donc $x = 0$ ou $x = 4$.",
        points: 2,
      ),
      _step(
        r"**Vérification dans le domaine.** On confronte les candidats au domaine $[1, +\infty[$ : $x = 0 \notin [1, +\infty[$ donc à rejeter, $x = 4 \in [1, +\infty[$ donc à conserver. Vérification finale dans l'équation initiale : $\sqrt{2 \cdot 4 + 1} = \sqrt{9} = 3$ et $4 - 1 = 3$. Les deux membres valent 3 : $x = 4$ est bien solution.",
        points: 2,
      ),
    ],
    finalAnswer: r"$x = 4$.",
    gradingNotes: r"Conditions de validité explicites (2 pts) + élévation au carré sur le domaine (2 pts) + résolution polynômiale (2 pts) + vérification + rejet de la solution parasite (2 pts).",
    commonMistakes: [
      r"Élever au carré sans vérifier que les deux membres ont le même signe : crée des solutions parasites.",
      r"Vérifier mécaniquement les deux candidats sans réfléchir au domaine — on doit rejeter $x = 0$ par cohérence avec $x - 1 \ge 0$, pas par calcul.",
    ],
  ),

  // Q7 — y' = -2y, y(0) = 5
  _ans(
    steps: [
      _step(
        r"**Identification du type d'équation.** L'équation $y' = -2y$ est de la forme $y' = ay$ avec $a = -2$ : **équation différentielle linéaire homogène du premier ordre à coefficients constants**. On sait que les solutions de $y' = ay$ sur $\mathbb{R}$ forment un espace vectoriel de dimension 1, engendré par la fonction $x \mapsto e^{ax}$. Donc la **solution générale** est $y(x) = K e^{ax} = K e^{-2x}$, où $K \in \mathbb{R}$ est une constante à déterminer.",
        points: 2,
      ),
      _step(
        r"**Application de la condition initiale.** Le problème impose $y(0) = 5$. On évalue la solution générale en $0$ : $y(0) = K e^{-2 \cdot 0} = K \cdot e^0 = K \cdot 1 = K$. L'égalité $y(0) = 5$ donne donc $K = 5$. La constante d'intégration est complètement déterminée par cette condition.",
        points: 1,
      ),
      _step(
        r"**Écriture de la solution unique.** En substituant $K = 5$ dans la solution générale, on obtient $y(x) = 5 e^{-2x}$. C'est l'**unique** solution de $y' = -2y$ vérifiant $y(0) = 5$. On vérifie : $y'(x) = 5 \cdot (-2) e^{-2x} = -10 e^{-2x}$ et $-2 y(x) = -2 \cdot 5 e^{-2x} = -10 e^{-2x}$. Les deux coïncident, donc $y$ vérifie bien l'équation. Et $y(0) = 5 e^0 = 5$ : la condition initiale est respectée.",
        points: 2,
        widgetSlug: "diff_eq_solver",
        widgetConfig: {"a": -2.0, "b": 0.0, "y0": 5.0},
      ),
    ],
    finalAnswer: r"$y(x) = 5 e^{-2x}$.",
    gradingNotes: r"Identification du type + écriture de la solution générale (2 pts) + application de la condition initiale (1 pt) + solution finale + vérification (2 pts).",
    tips: [
      r"Pour toute équation $y' = ay$, la solution est $y = K e^{ax}$. Le signe de $a$ donne la nature : $a > 0$ exponentielle croissante, $a < 0$ décroissance vers 0, $a = 0$ solution constante.",
    ],
  ),

  // Q8 — Probabilité conditionnelle, urne 4R + 6N, 2 sans remise
  _ans(
    steps: [
      _step(
        r"**Probabilité du premier tirage.** L'urne contient 4 boules rouges et 6 noires, soit 10 boules au total. La probabilité d'obtenir une rouge au premier tirage est le rapport « cas favorables / cas possibles » : $P(R_1) = \dfrac{4}{10} = \dfrac{2}{5}$. À ce stade, l'urne ne contient plus que 9 boules : 3 rouges et 6 noires (la rouge tirée n'a pas été remise).",
        points: 1,
      ),
      _step(
        r"**Probabilité conditionnelle du second tirage.** Sachant qu'on vient de tirer une rouge, l'urne contient désormais 3 rouges et 6 noires (9 boules). La probabilité conditionnelle d'obtenir une rouge au second tirage **sachant que le premier était rouge** est : $P(R_2 \mid R_1) = \dfrac{3}{9} = \dfrac{1}{3}$. **Le « sachant que » est crucial** : sans cette information, la probabilité serait différente.",
        points: 2,
      ),
      _step(
        r"**Formule des probabilités composées.** L'événement « tirer 2 rouges » est l'intersection $R_1 \cap R_2$. La formule pour l'intersection de deux événements (avec ordre temporel) est : $P(R_1 \cap R_2) = P(R_1) \cdot P(R_2 \mid R_1)$. On substitue : $P = \dfrac{2}{5} \cdot \dfrac{1}{3} = \dfrac{2}{15}$. C'est la probabilité finale.",
        points: 2,
      ),
    ],
    finalAnswer: r"$P(\text{2 rouges}) = \dfrac{2}{15}$.",
    gradingNotes: r"Probabilité du premier tirage (1 pt) + probabilité conditionnelle du second avec mise à jour de l'urne (2 pts) + application de la formule des probabilités composées (2 pts).",
    commonMistakes: [
      r"Calculer comme si le tirage était avec remise : $P = (4/10)^2 = 16/100$. Faux car les tirages sont SANS remise — le second tirage dépend du premier.",
      r"Oublier la mise à jour de l'effectif total : écrire $P(R_2 | R_1) = 3/10$ au lieu de $3/9$. La boule retirée diminue le total.",
    ],
    tips: [
      r"Pour un tirage sans remise, on raisonne tirage par tirage, en mettant à jour la composition de l'urne après chaque tirage. La formule des probabilités composées capture cette dépendance.",
    ],
  ),

  // Q9 — somme géométrique 1 + 2 + 4 + ... + 2^10
  _ans(
    steps: [
      _step(
        r"**Identification de la suite.** On reconnaît une **suite géométrique** : chaque terme s'obtient en multipliant le précédent par 2. Premier terme $u_0 = 1 = 2^0$, raison $q = 2$. Le dernier terme de la somme est $2^{10}$, qui est $u_{10}$. La somme contient donc tous les termes de $u_0$ à $u_{10}$, soit **11 termes au total**.",
        points: 1,
      ),
      _step(
        r"**Formule de la somme géométrique.** Pour une suite géométrique de premier terme $u_0$, raison $q \ne 1$, et $n+1$ termes (de $u_0$ à $u_n$), la somme vaut $S = u_0 \cdot \dfrac{1 - q^{n+1}}{1 - q}$. Application directe avec $u_0 = 1$, $q = 2$, $n = 10$ : $S = 1 \cdot \dfrac{1 - 2^{11}}{1 - 2} = \dfrac{1 - 2048}{-1} = \dfrac{-2047}{-1} = 2047$.",
        points: 3,
      ),
    ],
    finalAnswer: r"$S = 2047$.",
    gradingNotes: r"Identification de la suite géométrique avec ses paramètres (1 pt) + application correcte de la formule de somme avec attention au nombre de termes (3 pts).",
    tips: [
      r"Astuce mémorable : $1 + 2 + 4 + \dots + 2^n = 2^{n+1} - 1$. C'est la somme géométrique de raison 2.",
    ],
    commonMistakes: [
      r"Compter 10 termes au lieu de 11 (du fait qu'on va de $u_0$ à $u_{10}$ inclus). La formule utilise $q^{n+1}$ avec $n = 10$, soit $2^{11}$.",
    ],
  ),

  // Q10 — TVI sur f(x) = x^3 + x - 5
  _ans(
    steps: [
      _step(
        r"**Continuité.** $f(x) = x^3 + x - 5$ est un polynôme, donc continu sur $\mathbb{R}$ (les polynômes sont C-infini). Cette continuité est l'hypothèse fondamentale du TVI ; sans elle, le théorème ne s'applique pas. **C'est aussi cette continuité qui permet de transmettre l'information « $f$ change de signe » en « $f$ s'annule ».**",
        points: 1,
      ),
      _step(
        r"**Stricte monotonie via la dérivée.** $f'(x) = 3x^2 + 1$. Comme $3x^2 \ge 0$ pour tout $x$, on a $f'(x) \ge 1 > 0$ partout sur $\mathbb{R}$ : $f$ est strictement croissante sur $\mathbb{R}$. Conséquence cruciale : si $f$ s'annule, c'est en **un seul point** (pas plus). Cela règle d'avance la question de l'unicité.",
        points: 2,
      ),
      _step(
        r"**Application du TVI.** On évalue $f$ en deux points choisis pour encadrer un changement de signe : $f(1) = 1 + 1 - 5 = -3 < 0$ et $f(2) = 8 + 2 - 5 = 5 > 0$. Comme $f$ est continue sur $[1, 2]$ et que $f(1) \cdot f(2) < 0$, le **théorème des valeurs intermédiaires** garantit qu'il existe (au moins) un $c \in ]1, 2[$ tel que $f(c) = 0$.",
        points: 2,
      ),
      _step(
        r"**Conclusion : existence ET unicité.** L'existence vient du TVI (étape précédente). L'unicité vient de la stricte croissance (étape 2) : si $f$ s'annulait deux fois, elle ne pourrait pas être strictement croissante entre les deux racines. Donc $f$ s'annule **exactement une fois** sur $\mathbb{R}$, et plus précisément dans l'intervalle $]1, 2[$.",
        points: 2,
      ),
    ],
    finalAnswer: r"$f$ admet une unique racine sur $\mathbb{R}$, située dans $]1, 2[$.",
    gradingNotes: r"Continuité justifiée (1 pt) + dérivée + stricte croissance (2 pts) + application du TVI sur un intervalle bien choisi (2 pts) + conclusion d'existence + unicité (2 pts). L'oubli de l'unicité coûte la moitié de la dernière étape.",
    commonMistakes: [
      r"Conclure « $f$ s'annule une seule fois » en invoquant uniquement le TVI : faux. Le TVI donne l'existence, pas l'unicité. L'unicité vient de la stricte monotonie.",
    ],
    tips: [
      r"La combinaison « TVI + stricte monotonie » est l'outil classique pour montrer l'existence ET l'unicité d'une racine. Toujours vérifier les deux ingrédients.",
    ],
  ),

  // ============================================================
  // SMB Math 2024 rattrapage (paper 2) — 10 questions, IDs 11-20
  // ============================================================

  // Q11 — lim (sin 3x)/x en 0
  _ans(
    steps: [
      _step(
        r"**Reconnaissance de la limite usuelle.** En $x = 0$ : numérateur $\sin(0) = 0$ et dénominateur $0$. C'est une forme indéterminée $0/0$. On utilise la **limite usuelle fondamentale** : $\lim_{u \to 0} \dfrac{\sin u}{u} = 1$. Cette limite est centrale en analyse — elle traduit le fait qu'au voisinage de 0, $\sin u \approx u$ (équivalence asymptotique).",
        points: 2,
      ),
      _step(
        r"**Mise en forme par changement de variable implicite.** Le numérateur $\sin(3x)$ « voudrait » être divisé par $3x$ pour utiliser la limite usuelle. On force cette forme : $\dfrac{\sin(3x)}{x} = \dfrac{\sin(3x)}{3x} \cdot \dfrac{3x}{x} = 3 \cdot \dfrac{\sin(3x)}{3x}$. Quand $x \to 0$, $u = 3x \to 0$ aussi, donc $\dfrac{\sin(3x)}{3x} \to 1$. La limite cherchée vaut $3 \cdot 1 = 3$.",
        points: 2,
      ),
    ],
    finalAnswer: r"$\displaystyle\lim_{x\to 0} \dfrac{\sin(3x)}{x} = 3$.",
    gradingNotes: r"Citation de la limite usuelle $\sin u/u \to 1$ (2 pts) + mise en forme par multiplication-division par 3 (2 pts).",
    tips: [
      r"Généralisation utile : $\lim_{x\to 0} \dfrac{\sin(\alpha x)}{x} = \alpha$ et $\lim_{x\to 0} \dfrac{\sin(\alpha x)}{\beta x} = \alpha/\beta$. À retenir.",
    ],
  ),

  // Q12 — f(x) = (x^2-1)/(x+2), f'(1) et tangente
  _ans(
    steps: [
      _step(
        r"**Application de la formule du quotient.** Pour $f = u/v$ avec $u, v$ dérivables et $v \ne 0$, la dérivée est $f' = \dfrac{u'v - uv'}{v^2}$. Ici $u(x) = x^2 - 1$ et $v(x) = x + 2$, donc $u'(x) = 2x$ et $v'(x) = 1$. On substitue : $f'(x) = \dfrac{2x(x+2) - (x^2 - 1) \cdot 1}{(x+2)^2}$.",
        points: 2,
      ),
      _step(
        r"**Simplification du numérateur.** $2x(x+2) - (x^2 - 1) = 2x^2 + 4x - x^2 + 1 = x^2 + 4x + 1$. Donc $f'(x) = \dfrac{x^2 + 4x + 1}{(x+2)^2}$. Cette expression est définie sur $\mathbb{R} \setminus \{-2\}$ (le dénominateur $(x+2)^2$ s'annule en $-2$, qui est aussi exclu du domaine de $f$).",
        points: 2,
      ),
      _step(
        r"**Évaluation au point d'intérêt.** En $x = 1$ : $f(1) = \dfrac{1 - 1}{1 + 2} = \dfrac{0}{3} = 0$ (le point de tangence est $(1, 0)$). $f'(1) = \dfrac{1 + 4 + 1}{(1+2)^2} = \dfrac{6}{9} = \dfrac{2}{3}$ (la pente de la tangente).",
        points: 2,
      ),
      _step(
        r"**Équation de la tangente.** La tangente à la courbe $y = f(x)$ au point d'abscisse $a$ a pour équation $y = f'(a)(x - a) + f(a)$. Ici $a = 1$, $f(a) = 0$, $f'(a) = 2/3$. Donc $y = \dfrac{2}{3}(x - 1) + 0 = \dfrac{2}{3}(x - 1) = \dfrac{2x - 2}{3}$. Cette droite passe par $(1, 0)$ avec une pente positive : croissance lente près du zéro de $f$.",
        points: 2,
      ),
    ],
    finalAnswer: r"$f'(x) = \dfrac{x^2+4x+1}{(x+2)^2}$. Tangente en $x=1$ : $y = \dfrac{2x-2}{3}$.",
    gradingNotes: r"Application de la formule du quotient avec identification de $u, v$ (2 pts) + simplification (2 pts) + évaluation correcte en $x=1$ (2 pts) + équation de la tangente (2 pts).",
    commonMistakes: [
      r"Inverser les termes dans la formule du quotient et écrire $\dfrac{uv' - u'v}{v^2}$. Toujours vérifier l'ordre : $u'v$ vient AVANT $uv'$.",
    ],
    tips: [
      r"Mémoriser l'équation de la tangente : $y = f'(a)(x-a) + f(a)$. Le point $(a, f(a))$ est sur la tangente, $f'(a)$ est la pente.",
    ],
  ),

  // Q13 — int_1^e (ln x)/x dx
  _ans(
    steps: [
      _step(
        r"**Reconnaissance de la forme $u' u$.** L'intégrande est $\dfrac{\ln x}{x}$. On pose $u(x) = \ln x$, alors $u'(x) = \dfrac{1}{x}$. L'intégrande s'écrit $u'(x) \cdot u(x)$, ce qui est la dérivée de $\dfrac{u^2}{2}$ (par la règle de dérivation de la composée $\bigl(\dfrac{u^2}{2}\bigr)' = u u'$). Donc une primitive est $F(x) = \dfrac{(\ln x)^2}{2}$.",
        points: 3,
      ),
      _step(
        r"**Évaluation entre 1 et e.** $F(e) = \dfrac{(\ln e)^2}{2} = \dfrac{1^2}{2} = \dfrac{1}{2}$. $F(1) = \dfrac{(\ln 1)^2}{2} = \dfrac{0}{2} = 0$. Donc $\int_1^e \dfrac{\ln x}{x} dx = F(e) - F(1) = \dfrac{1}{2} - 0 = \dfrac{1}{2}$.",
        points: 2,
      ),
    ],
    finalAnswer: r"$\displaystyle\int_1^e \dfrac{\ln x}{x} dx = \dfrac{1}{2}$.",
    gradingNotes: r"Reconnaissance de la forme $u'u$ + identification de la primitive $u^2/2$ (3 pts) + évaluation correcte aux bornes (2 pts).",
    tips: [
      r"Pattern à retenir : $\int u' u^n du = \dfrac{u^{n+1}}{n+1}$ pour $n \ne -1$. Ici $n = 1$, donc primitive en $u^2/2$.",
    ],
  ),

  // Q14 — MCQ z = e^{i pi/3}, z^6 = ?
  _ans(
    steps: [
      _step(
        r"**Application de la règle de De Moivre.** Pour $z = re^{i\theta}$, on a $z^n = r^n e^{i n \theta}$. Ici $r = 1$ (puisque $|e^{i\theta}| = 1$ toujours) et $\theta = \pi/3$, donc $z^6 = 1^6 \cdot e^{i \cdot 6\pi/3} = e^{i \cdot 2\pi}$.",
        points: 1,
      ),
      _step(
        r"**Calcul final.** $e^{i \cdot 2\pi} = \cos(2\pi) + i\sin(2\pi) = 1 + 0i = 1$. Géométriquement, $z = e^{i\pi/3}$ est à l'angle 60° sur le cercle unité ; élever à la puissance 6 fait tourner de $6 \times 60° = 360°$, donc on revient au point de départ $1 + 0i$. Réponse **B : 1**.",
        points: 2,
      ),
    ],
    finalAnswer: r"B — $z^6 = 1$",
    gradingNotes: r"De Moivre $z^n = r^n e^{in\theta}$ (1 pt) + calcul $e^{i 2\pi} = 1$ avec interprétation géométrique (2 pts).",
    tips: [
      r"Astuce : $e^{i\pi/3}$ est une racine 6e de l'unité — c'est précisément ce qui fait que $z^6 = 1$. Les racines $n$-ièmes de l'unité sont les $e^{i k 2\pi/n}$ pour $k = 0, ..., n-1$.",
    ],
  ),

  // Q15 — Variable aléatoire X, E(X), V(X)
  _ans(
    steps: [
      _step(
        r"**Espérance.** L'espérance d'une variable aléatoire discrète est la moyenne pondérée par les probabilités : $E(X) = \sum_i x_i P(X = x_i)$. Application : $E(X) = 0 \cdot 0{,}3 + 1 \cdot 0{,}5 + 2 \cdot 0{,}2 = 0 + 0{,}5 + 0{,}4 = 0{,}9$. C'est la valeur « moyenne » qu'on observerait sur un grand nombre de tirages indépendants.",
        points: 2,
      ),
      _step(
        r"**Calcul de $E(X^2)$.** Pour la variance, on a besoin de $E(X^2)$, qui se calcule avec la loi de $X$ et les valeurs $x_i^2$ : $E(X^2) = 0^2 \cdot 0{,}3 + 1^2 \cdot 0{,}5 + 2^2 \cdot 0{,}2 = 0 + 0{,}5 + 0{,}8 = 1{,}3$.",
        points: 2,
      ),
      _step(
        r"**Variance via la formule de König-Huygens.** $V(X) = E(X^2) - [E(X)]^2 = 1{,}3 - 0{,}9^2 = 1{,}3 - 0{,}81 = 0{,}49$. Cette formule est plus rapide que la définition originale $V(X) = E\bigl((X - E(X))^2\bigr)$. L'écart-type est $\sigma(X) = \sqrt{V(X)} = 0{,}7$ : il mesure la dispersion de $X$ autour de la moyenne.",
        points: 2,
      ),
    ],
    finalAnswer: r"$E(X) = 0{,}9$, $V(X) = 0{,}49$, $\sigma(X) = 0{,}7$.",
    gradingNotes: r"Espérance avec définition explicite (2 pts) + calcul de $E(X^2)$ (2 pts) + variance via König-Huygens (2 pts).",
    tips: [
      r"Formule de König-Huygens : $V(X) = E(X^2) - [E(X)]^2$. Toujours plus rapide que la définition pour les calculs.",
    ],
  ),

  // Q16 — Suite arithmetique u_0=5, r=3, u_20 et S_20
  _ans(
    steps: [
      _step(
        r"**Terme général d'une suite arithmétique.** Pour une suite arithmétique de premier terme $u_0$ et de raison $r$, le terme de rang $n$ est $u_n = u_0 + n \cdot r$. Ici $u_0 = 5$, $r = 3$, $n = 20$ : $u_{20} = 5 + 20 \cdot 3 = 5 + 60 = 65$. La raison étant positive, la suite est strictement croissante.",
        points: 2,
      ),
      _step(
        r"**Somme des termes.** La somme $S_n = u_0 + u_1 + \dots + u_n$ d'une suite arithmétique est donnée par la formule de Gauss : $S_n = (n+1) \cdot \dfrac{u_0 + u_n}{2}$ — autrement dit « nombre de termes × (premier + dernier) / 2 ». De $u_0$ à $u_{20}$ il y a **21 termes** (attention : $n+1$, pas $n$). Donc $S_{20} = 21 \cdot \dfrac{5 + 65}{2} = 21 \cdot \dfrac{70}{2} = 21 \cdot 35 = 735$.",
        points: 3,
      ),
    ],
    finalAnswer: r"$u_{20} = 65$ et $S_{20} = 735$.",
    gradingNotes: r"Terme général appliqué (2 pts) + somme via formule de Gauss avec attention au nombre de termes (3 pts).",
    commonMistakes: [
      r"Compter 20 termes au lieu de 21 : la somme va de $u_0$ à $u_{20}$ inclus, ce qui fait $20 - 0 + 1 = 21$ termes.",
    ],
    tips: [
      r"Formule mnémo : « somme = (nombre de termes) × (moyenne du premier et du dernier) ». La moyenne $(u_0+u_n)/2$ est la valeur centrale de la suite arithmétique.",
    ],
  ),

  // Q17 — TVI on continuous f, f(0)=-3, f(4)=5
  _ans(
    steps: [
      _step(
        r"**Application directe du TVI.** $f$ continue sur $[0, 4]$ avec $f(0) = -3 < 0$ et $f(4) = 5 > 0$ : les valeurs ont des signes opposés. Le **théorème des valeurs intermédiaires** énonce que pour toute valeur $k$ entre $f(0)$ et $f(4)$ (donc entre $-3$ et $5$), il existe au moins un point $c \in [0, 4]$ tel que $f(c) = k$. En particulier pour $k = 0$, il existe $c \in [0, 4]$ avec $f(c) = 0$. Mais comme $0$ n'est ni $f(0)$ ni $f(4)$, on a même $c \in ]0, 4[$ — un zéro **strictement** dans l'intervalle.",
        points: 3,
      ),
      _step(
        r"**Cas plus général.** Pour tout $k \in [-3, 5]$, l'argument est identique : il existe un (au moins un) $c \in [0, 4]$ avec $f(c) = k$. Le TVI ne donne aucune information sur l'unicité — pour cela il faudrait une hypothèse supplémentaire (stricte monotonie, par exemple).",
        points: 2,
      ),
    ],
    finalAnswer: r"Par le TVI, $f$ s'annule au moins une fois dans $]0, 4[$.",
    gradingNotes: r"Application correcte du TVI avec mention de la continuité comme hypothèse + signes opposés (3 pts) + généralisation à toute valeur intermédiaire $k$ (2 pts).",
    tips: [
      r"Le TVI donne l'**existence**, pas l'**unicité**. Pour l'unicité, ajouter la stricte monotonie via le signe de $f'$.",
    ],
  ),

  // Q18 — f'(x) = 6x-4, f(0)=2, f(3) = ?
  _ans(
    steps: [
      _step(
        r"**Recherche d'une primitive de $f'$.** $f'(x) = 6x - 4$. Une primitive de $6x$ est $3x^2$, et une primitive de $-4$ est $-4x$. Donc $f(x) = 3x^2 - 4x + C$, où $C$ est une constante d'intégration à déterminer par la condition initiale.",
        points: 2,
      ),
      _step(
        r"**Application de la condition initiale.** $f(0) = 3 \cdot 0 - 4 \cdot 0 + C = C$. La condition $f(0) = 2$ donne donc $C = 2$. Conclusion : $f(x) = 3x^2 - 4x + 2$.",
        points: 1,
      ),
      _step(
        r"**Évaluation en $x = 3$.** $f(3) = 3 \cdot 9 - 4 \cdot 3 + 2 = 27 - 12 + 2 = 17$.",
        points: 1,
      ),
    ],
    finalAnswer: r"$f(3) = 17$.",
    gradingNotes: r"Primitive (2 pts) + détermination de $C$ par la condition initiale (1 pt) + évaluation finale (1 pt).",
  ),

  // Q19 — MCQ y' = 3y
  _ans(
    steps: [
      _step(
        r"**Forme canonique.** L'équation $y' = 3y$ est une équation différentielle linéaire homogène du premier ordre, de la forme $y' = ay$ avec $a = 3$. Le théorème fondamental garantit que les solutions forment une droite vectorielle engendrée par $x \mapsto e^{ax} = e^{3x}$.",
        points: 1,
      ),
      _step(
        r"**Solution générale.** $y(x) = K e^{3x}$ pour $K \in \mathbb{R}$. Vérification : $y' = 3K e^{3x} = 3y$ — l'équation est satisfaite. Réponse **B**.",
        points: 2,
      ),
    ],
    finalAnswer: r"B — $y = K e^{3x}$",
    gradingNotes: r"Forme canonique reconnue (1 pt) + solution générale écrite + vérification (2 pts).",
    commonMistakes: [
      r"Confondre $y' = 3y$ avec $y = 3x$ : le premier est une équation différentielle, le second est une fonction simple. La solution est exponentielle, pas linéaire.",
    ],
  ),

  // Q20 — f(x) = (x-1) e^x, f' et signe
  _ans(
    steps: [
      _step(
        r"**Dérivée par la formule du produit.** $f(x) = (x-1) e^x$ est un produit de deux fonctions : $u(x) = x - 1$ et $v(x) = e^x$. La règle $(uv)' = u'v + uv'$ avec $u'(x) = 1$ et $v'(x) = e^x$ donne : $f'(x) = 1 \cdot e^x + (x-1) \cdot e^x = e^x + (x-1) e^x = e^x[1 + x - 1] = x e^x$.",
        points: 3,
      ),
      _step(
        r"**Étude du signe.** $f'(x) = x e^x$ est un produit de deux facteurs. $e^x > 0$ pour tout $x$, donc le signe de $f'$ est le signe de $x$ : $f' < 0$ sur $]-\infty, 0[$, $f' > 0$ sur $]0, +\infty[$. **$f$ est donc strictement décroissante sur $]-\infty, 0]$ puis strictement croissante sur $[0, +\infty[$.**",
        points: 2,
      ),
      _step(
        r"**Minimum global.** Aux bornes du tableau de variation, $f' = 0$ en $x = 0$ avec changement de signe $-/+$ : c'est un **minimum local** (et même global, vu que la fonction décroît partout avant et croît partout après). Valeur : $f(0) = (0-1) e^0 = -1$. Donc $f \ge -1$ sur tout $\mathbb{R}$, avec égalité atteinte en 0 uniquement.",
        points: 1,
      ),
    ],
    finalAnswer: r"$f'(x) = x e^x$. $f$ admet un minimum global en $x = 0$ valant $-1$.",
    gradingNotes: r"Dérivée par produit avec simplification (3 pts) + signe de $f'$ via le signe de $x$ (2 pts) + minimum global avec valeur (1 pt).",
    tips: [
      r"Quand on dérive un produit avec $e^x$, factoriser $e^x$ à la fin simplifie systématiquement le signe : il reste un polynôme en $x$.",
    ],
  ),

  // ============================================================
  // SMB Math 2023 normale (paper 3) — questions 21-30
  // ============================================================

  // Q21 — geometric series convergence
  _ans(
    steps: [
      _step(
        r"**Comportement à l'infini.** $(v_n)$ est géométrique avec $v_0 = 100$ et raison $q = 0{,}9$. Comme $|q| = 0{,}9 < 1$, la suite $q^n$ converge vers 0. Donc $v_n = 100 \cdot q^n \to 0$. C'est le résultat clé : **toute suite géométrique de raison strictement comprise entre $-1$ et $1$ tend vers 0**.",
        points: 2,
      ),
      _step(
        r"**Somme infinie.** Pour une suite géométrique de raison $|q| < 1$, la somme $\sum_{n=0}^{\infty} v_n$ converge et vaut $\dfrac{v_0}{1 - q}$. Application : $S = \dfrac{100}{1 - 0{,}9} = \dfrac{100}{0{,}1} = 1000$. Cette formule est fondamentale (apparait dans les fractales, l'économie, etc.).",
        points: 3,
      ),
    ],
    finalAnswer: r"$\lim v_n = 0$, $\sum_{n=0}^{\infty} v_n = 1000$.",
    gradingNotes: r"Limite de la suite géométrique (2 pts) + somme infinie via la formule $v_0/(1-q)$ (3 pts).",
    tips: [
      r"Formules à retenir pour $|q|<1$ : $q^n \to 0$, $\sum_{n=0}^{\infty} q^n = 1/(1-q)$, et $\sum_{n=0}^{\infty} v_0 q^n = v_0/(1-q)$.",
    ],
  ),

  // Q22 — lim (x^3-1)/(x-1) en 1
  _ans(
    steps: [
      _step(
        r"**Forme indéterminée.** En $x = 1$, le numérateur $x^3 - 1 = 0$ et le dénominateur $x - 1 = 0$. C'est une forme $0/0$ : il faut factoriser pour révéler la simplification cachée.",
        points: 1,
      ),
      _step(
        r"**Factorisation $x^n - 1$.** L'identité fondamentale $x^n - 1 = (x - 1)(x^{n-1} + x^{n-2} + \dots + x + 1)$ s'applique avec $n = 3$ : $x^3 - 1 = (x - 1)(x^2 + x + 1)$. La fraction se simplifie : $\dfrac{x^3 - 1}{x - 1} = x^2 + x + 1$ pour tout $x \ne 1$.",
        points: 2,
      ),
      _step(
        r"**Passage à la limite.** L'expression simplifiée $x^2 + x + 1$ est continue en $x = 1$, donc on peut substituer directement : $\lim_{x \to 1}(x^2 + x + 1) = 1 + 1 + 1 = 3$.",
        points: 1,
      ),
    ],
    finalAnswer: r"$\displaystyle\lim_{x\to 1} \dfrac{x^3-1}{x-1} = 3$.",
    gradingNotes: r"Identification de la forme $0/0$ (1 pt) + factorisation de $x^3-1$ (2 pts) + passage à la limite (1 pt).",
    tips: [
      r"Identité utile : $x^n - 1 = (x-1)(1 + x + x^2 + \dots + x^{n-1})$. À l'infini, ça donne aussi le DSE de $1/(1-x)$.",
    ],
  ),

  // Q23 — f(x) = ln(x^2+1), f' et int de f' sur [0,1]
  _ans(
    steps: [
      _step(
        r"**Dérivée d'une composée.** $f = \ln \circ u$ avec $u(x) = x^2 + 1$. La règle de dérivation d'une composée est $(\ln u)' = \dfrac{u'}{u}$ (à condition que $u > 0$, ce qui est le cas ici car $x^2 + 1 \ge 1$). On a $u'(x) = 2x$, donc $f'(x) = \dfrac{2x}{x^2 + 1}$.",
        points: 2,
      ),
      _step(
        r"**Intégrale par théorème fondamental.** $\int_0^1 f'(x) \, dx = f(1) - f(0)$ par le théorème fondamental du calcul intégral. $f(1) = \ln(1 + 1) = \ln 2$. $f(0) = \ln(0 + 1) = \ln 1 = 0$. Donc l'intégrale vaut $\ln 2 \approx 0{,}693$.",
        points: 3,
      ),
    ],
    finalAnswer: r"$f'(x) = \dfrac{2x}{x^2+1}$ et $\int_0^1 f'(x) \, dx = \ln 2$.",
    gradingNotes: r"Dérivée composée (2 pts) + théorème fondamental + évaluation (3 pts).",
    tips: [
      r"Astuce : $\int_a^b f'(x) dx = f(b) - f(a)$ — toujours vrai. Inutile de calculer une primitive autre que $f$ elle-même.",
    ],
  ),

  // Q24 — z1=1+i, z2=1-i, calcs
  _ans(
    steps: [
      _step(
        r"**Produit via identité remarquable.** $z_1 z_2 = (1+i)(1-i)$ est de la forme $(a+b)(a-b) = a^2 - b^2$ avec $a = 1$, $b = i$. Donc $z_1 z_2 = 1^2 - i^2 = 1 - (-1) = 2$. **Ce produit est réel** — c'est le produit d'un complexe par son conjugué, qui vaut toujours $|z_1|^2$.",
        points: 2,
      ),
      _step(
        r"**Somme.** $z_1 + z_2 = (1 + 1) + (i - i) = 2 + 0i = 2$. La somme d'un complexe et de son conjugué est toujours réelle, égale à $2 \mathrm{Re}(z_1)$.",
        points: 1,
      ),
      _step(
        r"**Module de $z_1$.** $|z_1| = \sqrt{1^2 + 1^2} = \sqrt{2}$. Géométriquement, le point $(1, 1)$ est à la diagonale du carré unité, donc à distance $\sqrt{2}$ de l'origine.",
        points: 2,
      ),
    ],
    finalAnswer: r"$z_1 z_2 = 2$, $z_1 + z_2 = 2$, $|z_1| = \sqrt{2}$.",
    gradingNotes: r"Produit via identité $(a+b)(a-b)$ (2 pts) + somme (1 pt) + module avec formule (2 pts).",
    tips: [
      r"Pour tout complexe $z$ : $z \bar z = |z|^2$ (réel positif), $z + \bar z = 2 \mathrm{Re}(z)$, $z - \bar z = 2i \mathrm{Im}(z)$.",
    ],
  ),

  // Q25 — P(somme=7) avec 2 dés
  _ans(
    steps: [
      _step(
        r"**Univers et équiprobabilité.** On lance 2 dés équilibrés : chaque dé peut donner 6 valeurs, donc l'univers compte $6 \times 6 = 36$ issues équiprobables (couples ordonnés $(d_1, d_2)$). La probabilité d'un événement est le ratio cas favorables / 36.",
        points: 1,
      ),
      _step(
        r"**Issues favorables (somme = 7).** On énumère : $(1,6), (2,5), (3,4), (4,3), (5,2), (6,1)$ — soit **6 couples**. **Attention** à compter les couples ordonnés ($(1,6)$ et $(6,1)$ sont distincts car les dés sont distinguables).",
        points: 2,
      ),
      _step(
        r"**Probabilité.** $P(\text{somme} = 7) = \dfrac{6}{36} = \dfrac{1}{6} \approx 0{,}1667$. C'est la valeur la plus probable parmi toutes les sommes possibles ($2$ à $12$) ; la distribution est symétrique autour de 7.",
        points: 1,
      ),
    ],
    finalAnswer: r"$P(\text{somme} = 7) = \dfrac{1}{6} \approx 0{,}167$.",
    gradingNotes: r"Univers de 36 issues (1 pt) + énumération exhaustive avec couples ordonnés (2 pts) + ratio final (1 pt).",
    commonMistakes: [
      r"Ne pas distinguer $(1,6)$ et $(6,1)$ et compter seulement 3 couples : faux. Si on raisonne avec couples non-ordonnés, l'univers n'est plus équiprobable.",
    ],
    tips: [
      r"Pour 2 dés, la somme la plus probable est 7 (6 couples favorables). 2 et 12 sont les moins probables (1 couple chacune). La distribution est triangulaire.",
    ],
  ),

  // Q26 — int_1^2 (1/x) dx
  _ans(
    steps: [
      _step(
        r"**Primitive de $1/x$.** Sur $]0, +\infty[$, une primitive de $\dfrac{1}{x}$ est $\ln x$ (par définition même du logarithme népérien : $\ln$ est l'unique primitive de $1/x$ qui vaut 0 en 1). On applique le théorème fondamental : $\int_1^2 \dfrac{1}{x} dx = [\ln x]_1^2 = \ln 2 - \ln 1 = \ln 2 - 0 = \ln 2$.",
        points: 3,
        widgetSlug: "area_curve",
        widgetConfig: {"function": "1/x", "a": 1.0, "b": 2.0},
      ),
      _step(
        r"**Interprétation géométrique.** Sur $[1, 2]$, la fonction $y = 1/x$ est positive et décroissante (de 1 à 0,5). L'intégrale $\int_1^2 \dfrac{1}{x} dx = \ln 2 \approx 0{,}693$ représente l'aire en unités d'aire, comprise entre la courbe, l'axe Ox, et les droites verticales $x = 1$ et $x = 2$. **C'est aussi la définition même de $\ln 2$.**",
        points: 2,
      ),
    ],
    finalAnswer: r"$\displaystyle\int_1^2 \dfrac{1}{x} dx = \ln 2 \approx 0{,}693$.",
    gradingNotes: r"Primitive $\ln x$ + théorème fondamental (3 pts) + interprétation géométrique (2 pts).",
    tips: [
      r"Définition équivalente de $\ln$ : $\ln x = \int_1^x \dfrac{1}{t} dt$ pour $x > 0$. C'est l'aire sous l'hyperbole de 1 à $x$.",
    ],
  ),

  // Q27 — y'' + 4y = 0, y(0)=1, y'(0)=0
  _ans(
    steps: [
      _step(
        r"**Identification du type.** $y'' + 4y = 0$ est de la forme $y'' + \omega^2 y = 0$ avec $\omega^2 = 4$, soit $\omega = 2$. C'est l'équation de l'**oscillateur harmonique** : ses solutions sont des combinaisons de $\cos(\omega x)$ et $\sin(\omega x)$. Solution générale : $y(x) = A \cos(2x) + B \sin(2x)$.",
        points: 2,
      ),
      _step(
        r"**Première condition initiale.** $y(0) = A \cos(0) + B \sin(0) = A \cdot 1 + B \cdot 0 = A$. La condition $y(0) = 1$ donne donc $A = 1$.",
        points: 1,
      ),
      _step(
        r"**Seconde condition initiale.** Dérivée : $y'(x) = -2A \sin(2x) + 2B \cos(2x)$. En $x = 0$ : $y'(0) = -2A \cdot 0 + 2B \cdot 1 = 2B$. La condition $y'(0) = 0$ donne $2B = 0$, soit $B = 0$.",
        points: 2,
      ),
      _step(
        r"**Solution finale.** Avec $A = 1$, $B = 0$ : $y(x) = \cos(2x)$. Vérification : $y'' = -4\cos(2x) = -4y$, donc $y'' + 4y = 0$ ✓. Et $y(0) = 1$, $y'(0) = -2\sin(0) = 0$ ✓.",
        points: 2,
      ),
    ],
    finalAnswer: r"$y(x) = \cos(2x)$.",
    gradingNotes: r"Solution générale via $\omega^2 = 4$ (2 pts) + première condition (1 pt) + seconde condition après dérivation (2 pts) + écriture finale (2 pts).",
    tips: [
      r"L'oscillateur $y'' + \omega^2 y = 0$ a pour pulsation $\omega$, période $T = 2\pi/\omega$. Ici $\omega = 2$ donc $T = \pi$.",
    ],
  ),

  // Q28 — MCQ primitive de sin(2x)
  _ans(
    steps: [
      _step(
        r"**Méthode du facteur intégrant.** On cherche $F$ telle que $F'(x) = \sin(2x)$. On sait que $(\cos u)' = -\sin(u) \cdot u'$. Avec $u = 2x$, $u' = 2$ : $(\cos(2x))' = -2\sin(2x)$. Pour récupérer $\sin(2x)$ tout court, on divise par $-2$ : $F(x) = -\dfrac{\cos(2x)}{2}$. Vérification : $F'(x) = -\dfrac{-2\sin(2x)}{2} = \sin(2x)$ ✓. Réponse **C**.",
        points: 3,
      ),
    ],
    finalAnswer: r"C — $-\dfrac{\cos(2x)}{2}$",
    gradingNotes: r"Application de la dérivation composée + récupération du facteur (3 pts).",
    commonMistakes: [
      r"Oublier le facteur $1/2$ : écrire $\cos(2x)$ ou $-\cos(2x)$. Le facteur vient de la dérivée de la composée $u = 2x$.",
    ],
    tips: [
      r"Pattern : $\int \sin(\alpha x) dx = -\dfrac{\cos(\alpha x)}{\alpha} + C$. Toujours diviser par le coefficient de $x$.",
    ],
  ),

  // Q29 — (u_n) croissante majorée
  _ans(
    steps: [
      _step(
        r"**Théorème de la limite monotone.** Une suite croissante et majorée converge vers une limite finie. Plus précisément, si $(u_n)$ est croissante et $u_n \le M$ pour tout $n$, alors $\lim u_n = \sup\{u_n : n \in \mathbb{N}\}$, et cette limite vérifie $\sup \le M$. La majoration par 5 garantit donc que la limite est finie.",
        points: 2,
      ),
      _step(
        r"**Localisation de la limite.** Soit $\ell = \lim u_n$. La croissance impose $u_n \le \ell$ pour tout $n$ (chaque terme est $\le$ tous les suivants, donc $\le$ la limite). La majoration par 5 donne $\ell \le 5$. Conclusion : $u_n \le \ell \le 5$ pour tout $n$.",
        points: 2,
      ),
    ],
    finalAnswer: r"$(u_n)$ converge vers une limite $\ell$ avec $u_n \le \ell \le 5$.",
    gradingNotes: r"Théorème de la limite monotone (2 pts) + localisation de la limite par rapport au majorant (2 pts).",
    tips: [
      r"Théorème dual : décroissante et minorée → converge. Croissante et non majorée → tend vers $+\infty$.",
    ],
  ),

  // Q30 — PGCD(84, 60) Euclide + Bezout
  _ans(
    steps: [
      _step(
        r"**Algorithme d'Euclide.** Divisions successives : $84 = 60 \cdot 1 + 24$ (reste 24), $60 = 24 \cdot 2 + 12$ (reste 12), $24 = 12 \cdot 2 + 0$ (reste 0). Le PGCD est le **dernier reste non nul**, soit $12$. Vérification : $84 = 7 \cdot 12$ et $60 = 5 \cdot 12$, et $\mathrm{pgcd}(7, 5) = 1$, donc $\mathrm{pgcd}(84, 60) = 12$ ✓.",
        points: 3,
        widgetSlug: "euclid_visualizer",
        widgetConfig: {"a": 84, "b": 60},
      ),
      _step(
        r"**Remontée de Bézout.** L'identité de Bézout dit qu'il existe $a, b \in \mathbb{Z}$ tels que $84 a + 60 b = 12$. On remonte les divisions : de la 2e ligne, $12 = 60 - 24 \cdot 2$. On substitue $24 = 84 - 60 \cdot 1$ : $12 = 60 - (84 - 60) \cdot 2 = 60 - 2 \cdot 84 + 2 \cdot 60 = 3 \cdot 60 - 2 \cdot 84$. Donc $a = -2$, $b = 3$.",
        points: 3,
      ),
      _step(
        r"**Vérification.** $84 \cdot (-2) + 60 \cdot 3 = -168 + 180 = 12$ ✓. La solution n'est pas unique (on peut ajouter $60k/12 = 5k$ à $a$ et retrancher $84k/12 = 7k$ à $b$ pour tout $k \in \mathbb{Z}$), mais le PGCD lui est unique.",
        points: 2,
      ),
    ],
    finalAnswer: r"$\mathrm{pgcd}(84, 60) = 12$. Identité de Bézout : $84 \cdot (-2) + 60 \cdot 3 = 12$.",
    gradingNotes: r"Euclide complet (3 pts) + remontée de Bézout avec substitution (3 pts) + vérification (2 pts).",
    tips: [
      r"Pour vérifier rapidement un PGCD : si $d = \mathrm{pgcd}(a, b)$, alors $a/d$ et $b/d$ sont premiers entre eux. Ici $7$ et $5$ sont bien premiers entre eux, donc 12 est correct.",
    ],
  ),

  // ============================================================
  // SMB Math 2023 rattrapage (paper 4) — questions 31-40
  // ============================================================

  // Q31 — lim (e^x-1)/(e^x+1) à l'infini
  _ans(
    steps: [
      _step(
        r"**Forme indéterminée et factorisation.** Quand $x \to +\infty$, $e^x \to +\infty$, donc le numérateur et le dénominateur tendent vers $+\infty$. Forme $\infty/\infty$. **Astuce** : factoriser par $e^x$ haut et bas : $\dfrac{e^x - 1}{e^x + 1} = \dfrac{e^x(1 - e^{-x})}{e^x(1 + e^{-x})} = \dfrac{1 - e^{-x}}{1 + e^{-x}}$.",
        points: 2,
      ),
      _step(
        r"**Passage à la limite.** Quand $x \to +\infty$, $e^{-x} \to 0$. Donc la fraction tend vers $\dfrac{1 - 0}{1 + 0} = 1$.",
        points: 1,
      ),
    ],
    finalAnswer: r"$\displaystyle\lim_{x \to +\infty} \dfrac{e^x-1}{e^x+1} = 1$.",
    gradingNotes: r"Factorisation par $e^x$ (2 pts) + limite (1 pt).",
    tips: [
      r"À l'infini, $e^x$ domine tout polynôme. Quand on a une fraction de combinaisons d'exponentielles, factoriser par l'exponentielle de plus grand exposant.",
    ],
  ),

  // Q32 — étude de f(x) = x e^{-x}
  _ans(
    steps: [
      _step(
        r"**Dérivée par produit.** $f(x) = x e^{-x}$ est un produit. La règle $(uv)' = u'v + uv'$ avec $u = x$, $v = e^{-x}$ donne $u' = 1$, $v' = -e^{-x}$. Donc $f'(x) = 1 \cdot e^{-x} + x \cdot (-e^{-x}) = e^{-x}(1 - x)$.",
        points: 2,
      ),
      _step(
        r"**Étude du signe.** $e^{-x} > 0$ partout, donc le signe de $f'(x) = e^{-x}(1 - x)$ est celui de $(1 - x)$. $f' > 0$ ssi $x < 1$, $f' < 0$ ssi $x > 1$. Donc $f$ croît sur $]-\infty, 1]$, décroît sur $[1, +\infty[$, avec un **maximum global en $x = 1$**.",
        points: 2,
      ),
      _step(
        r"**Limites aux bornes.** $f(1) = 1 \cdot e^{-1} = 1/e \approx 0{,}368$ (maximum). En $-\infty$ : $x \to -\infty$ et $e^{-x} \to +\infty$, donc $f(x) = x e^{-x} \to -\infty$ (le terme $x$ négatif l'emporte). En $+\infty$ : par croissance comparée, $e^{-x}$ tend vers 0 plus vite que $x$ ne croît, donc $f(x) \to 0^+$. Asymptote horizontale $y = 0$.",
        points: 2,
      ),
    ],
    finalAnswer: r"Maximum en $x=1$ valant $1/e$. $f(-\infty) = -\infty$, $f(+\infty) = 0$.",
    gradingNotes: r"Dérivée (2 pts) + signe + variations (2 pts) + limites avec croissance comparée (2 pts).",
    tips: [
      r"Croissance comparée : pour tout $\alpha > 0$, $\lim_{x\to+\infty} \dfrac{x^\alpha}{e^x} = 0$. L'exponentielle l'emporte sur toute puissance.",
    ],
  ),

  // Q33 — int cos x sur [0, pi/2]
  _ans(
    steps: [
      _step(
        r"**Primitive et évaluation.** Une primitive de $\cos x$ est $\sin x$ (puisque $(\sin x)' = \cos x$). Donc $\int_0^{\pi/2} \cos x \, dx = [\sin x]_0^{\pi/2} = \sin(\pi/2) - \sin(0) = 1 - 0 = 1$.",
        points: 3,
      ),
    ],
    finalAnswer: r"$\displaystyle\int_0^{\pi/2} \cos x \, dx = 1$.",
    gradingNotes: r"Primitive correcte + évaluation aux bornes (3 pts).",
  ),

  // Q34 — z = (1+i)/(1-i), forme algébrique
  _ans(
    steps: [
      _step(
        r"**Multiplication par le conjugué du dénominateur.** Pour mettre $z = \dfrac{1+i}{1-i}$ sous forme algébrique, on multiplie haut et bas par le conjugué du dénominateur, $\overline{1-i} = 1+i$ : $z = \dfrac{(1+i)(1+i)}{(1-i)(1+i)} = \dfrac{(1+i)^2}{1 - i^2}$. Le dénominateur devient $1 - (-1) = 2$, **réel positif** — c'est tout l'intérêt de la technique.",
        points: 2,
      ),
      _step(
        r"**Développement et simplification.** $(1+i)^2 = 1 + 2i + i^2 = 1 + 2i - 1 = 2i$. Donc $z = \dfrac{2i}{2} = i$. Conclusion : $z = i$, partie réelle 0, partie imaginaire 1.",
        points: 2,
      ),
    ],
    finalAnswer: r"$z = i$.",
    gradingNotes: r"Multiplication par le conjugué (2 pts) + développement (2 pts).",
    tips: [
      r"Pour diviser par $(a + ib)$, multiplier par $\dfrac{a - ib}{a - ib}$ : le dénominateur devient $a^2 + b^2$ (réel positif).",
    ],
  ),

  // Q35 — MCQ A et B independants
  _ans(
    steps: [
      _step(
        r"**Définition de l'indépendance.** Deux événements $A$ et $B$ sont **indépendants** si et seulement si $P(A \cap B) = P(A) \cdot P(B)$. C'est la définition même de l'indépendance — pas une propriété déduite. Application : $P(A \cap B) = 0{,}4 \cdot 0{,}3 = 0{,}12$. Réponse **B**.",
        points: 3,
      ),
    ],
    finalAnswer: r"B — $0{,}12$",
    gradingNotes: r"Application directe de la définition d'indépendance (3 pts).",
    commonMistakes: [
      r"Confondre indépendance et incompatibilité. **Incompatibles** : $P(A \cap B) = 0$. **Indépendants** : $P(A \cap B) = P(A)P(B)$. Deux événements de proba non nulle ne peuvent pas être à la fois incompatibles et indépendants.",
    ],
  ),

  // Q36 — somme géométrique infinie 1 + 1/2 + 1/4 + ...
  _ans(
    steps: [
      _step(
        r"**Identification.** Suite géométrique avec $u_0 = 1$, raison $q = 1/2$. Comme $|q| = 1/2 < 1$, la somme infinie converge vers $\dfrac{u_0}{1 - q} = \dfrac{1}{1 - 1/2} = \dfrac{1}{1/2} = 2$.",
        points: 3,
      ),
    ],
    finalAnswer: r"$1 + \dfrac{1}{2} + \dfrac{1}{4} + \dots = 2$.",
    gradingNotes: r"Reconnaissance + formule de somme infinie (3 pts).",
    tips: [
      r"Cette somme est célèbre — c'est le paradoxe de Zénon : la somme des distances « moitié restante » converge à 2 fois la distance initiale.",
    ],
  ),

  // Q37 — points d'inflexion de x^4 - 4x^3
  _ans(
    steps: [
      _step(
        r"**Calcul des dérivées.** Les **points d'inflexion** sont les points où la concavité change, càd où $f''$ change de signe. $f(x) = x^4 - 4x^3$ donne $f'(x) = 4x^3 - 12x^2$ puis $f''(x) = 12x^2 - 24x = 12x(x - 2)$.",
        points: 2,
      ),
      _step(
        r"**Signe de $f''$.** Le polynôme $f''(x) = 12x(x-2)$ a pour racines $0$ et $2$. Coefficient dominant positif → $f'' > 0$ en dehors des racines, $f'' < 0$ entre. Concrètement : convexe sur $]-\infty, 0[$ ∪ $]2, +\infty[$, concave sur $]0, 2[$. **Changements de signe en $x = 0$ et $x = 2$ : ce sont les deux points d'inflexion.**",
        points: 2,
      ),
      _step(
        r"**Coordonnées.** $f(0) = 0$ et $f(2) = 16 - 32 = -16$. Les points d'inflexion sont donc $(0, 0)$ et $(2, -16)$.",
        points: 2,
      ),
    ],
    finalAnswer: r"Points d'inflexion : $(0, 0)$ et $(2, -16)$.",
    gradingNotes: r"$f'$ et $f''$ correctement calculés (2 pts) + signe de $f''$ + identification des inflexions (2 pts) + coordonnées (2 pts).",
    tips: [
      r"Distinction : $f'(x_0) = 0$ → extremum potentiel. $f''(x_0) = 0$ avec changement de signe → inflexion potentielle. Toujours vérifier le changement de signe.",
    ],
  ),

  // Q38 — y' + 3y = 6, y(0) = 0
  _ans(
    steps: [
      _step(
        r"**Solution générale = homogène + particulière.** L'équation $y' + 3y = 6$ est linéaire d'ordre 1 avec second membre constant. La solution générale est la somme d'une solution particulière et de la solution générale de l'équation homogène associée. **Solution homogène** ($y' + 3y = 0$, soit $y' = -3y$) : $y_h = K e^{-3x}$. **Solution particulière** : on cherche $y_p$ constante (le second membre est constant). $y_p' = 0$, donc $0 + 3 y_p = 6$ ⟹ $y_p = 2$.",
        points: 2,
      ),
      _step(
        r"**Solution générale.** $y(x) = y_h + y_p = K e^{-3x} + 2$. Application de la condition initiale : $y(0) = K + 2 = 0$ ⟹ $K = -2$.",
        points: 1,
      ),
      _step(
        r"**Solution finale.** $y(x) = -2 e^{-3x} + 2 = 2(1 - e^{-3x})$. Comportement : $y(0) = 0$, $y(+\infty) = 2$ (asymptote), croissante (établissement vers le régime permanent). Forme typique d'un système amorti vers une consigne.",
        points: 2,
      ),
    ],
    finalAnswer: r"$y(x) = 2(1 - e^{-3x})$.",
    gradingNotes: r"Décomposition homogène + particulière (2 pts) + condition initiale (1 pt) + écriture finale (2 pts).",
    tips: [
      r"Pour $y' + ay = b$ ($a, b$ constantes, $a \ne 0$) : solution = $K e^{-ax} + b/a$. Le terme $b/a$ est le régime permanent, $K e^{-ax}$ est le régime transitoire.",
    ],
  ),

  // Q39 — |3-4i|^2
  _ans(
    steps: [
      _step(
        r"**Définition.** Pour $z = a + ib$, $|z|^2 = a^2 + b^2$. Ici $z = 3 - 4i$ : $a = 3$, $b = -4$. Donc $|z|^2 = 9 + 16 = 25$. À noter : $|z|^2$ est toujours réel positif (même quand $z$ a une partie imaginaire négative — le carré annule le signe).",
        points: 2,
      ),
    ],
    finalAnswer: r"$|3 - 4i|^2 = 25$.",
    gradingNotes: r"Application directe de la formule (2 pts).",
    tips: [
      r"$3 - 4i$ a pour module $5$ : c'est un classique du « triangle de Pythagore » 3-4-5. À reconnaître pour gagner du temps.",
    ],
  ),

  // Q40 — u_n = (2n+1)/(n+1), limite et monotonie
  _ans(
    steps: [
      _step(
        r"**Décomposition par division euclidienne.** On décompose $\dfrac{2n+1}{n+1}$ pour faire apparaître la limite plus clairement. Astuce : $2n + 1 = 2(n + 1) - 1$, donc $u_n = \dfrac{2(n+1) - 1}{n+1} = 2 - \dfrac{1}{n+1}$.",
        points: 2,
      ),
      _step(
        r"**Limite.** Quand $n \to +\infty$, $\dfrac{1}{n+1} \to 0$, donc $u_n \to 2 - 0 = 2$. La suite tend vers 2 par valeurs inférieures (puisque $u_n = 2 - $ quelque chose de positif).",
        points: 2,
      ),
      _step(
        r"**Monotonie via différence.** $u_{n+1} - u_n = \bigl(2 - \dfrac{1}{n+2}\bigr) - \bigl(2 - \dfrac{1}{n+1}\bigr) = \dfrac{1}{n+1} - \dfrac{1}{n+2}$. Comme $n+1 < n+2$ (donc $\dfrac{1}{n+1} > \dfrac{1}{n+2}$), cette différence est strictement positive : la suite est **strictement croissante**. Cohérent avec « tend vers 2 par valeurs inférieures ».",
        points: 2,
      ),
    ],
    finalAnswer: r"$\lim u_n = 2$ ; $(u_n)$ strictement croissante.",
    gradingNotes: r"Décomposition (2 pts) + limite (2 pts) + monotonie via différence (2 pts).",
    tips: [
      r"Quand $\dfrac{P(n)}{Q(n)}$ avec $\deg P = \deg Q$, la décomposition $\dfrac{P}{Q} = q + \dfrac{R}{Q}$ (division euclidienne) sépare la limite (= $q$) du comportement vers cette limite.",
    ],
  ),

  // ============================================================
  // SMB PC 2024 normale (paper 5) — questions 41-50
  // ============================================================

  // Q41 — projectile v0=20, 30°
  _ans(
    steps: [
      _step(
        r"**Décomposition de la vitesse initiale.** Pour étudier un projectile, on projette la vitesse initiale sur les axes horizontal et vertical : $v_{0x} = v_0 \cos\alpha = 20 \cos 30° = 20 \cdot \dfrac{\sqrt{3}}{2} \approx 17{,}32$ m/s (composante horizontale, conservée car pas de frottement). $v_{0y} = v_0 \sin\alpha = 20 \cdot 0{,}5 = 10$ m/s (composante verticale, freinée par la gravité).",
        points: 2,
      ),
      _step(
        r"**Hauteur maximale.** Sur l'axe vertical, équation horaire $y(t) = v_{0y} t - \dfrac{1}{2} g t^2$ et vitesse verticale $v_y(t) = v_{0y} - g t$. La hauteur max est atteinte quand $v_y = 0$ : $t_h = v_{0y}/g = 10/10 = 1$ s. Hauteur correspondante : $h_{max} = v_{0y} \cdot t_h - \dfrac{1}{2} g t_h^2 = 10 - 5 = 5$ m.",
        points: 3,
        widgetSlug: "projectile",
        widgetConfig: {"v0": 20.0, "angle": 30.0},
      ),
      _step(
        r"**Portée horizontale.** Par symétrie de la parabole, le temps de vol total est $T = 2 t_h = 2$ s (descente symétrique de la montée, en l'absence de frottements). La portée est la distance horizontale parcourue : $R = v_{0x} \cdot T = 17{,}32 \cdot 2 \approx 34{,}64$ m. Formule générale : $R = \dfrac{v_0^2 \sin(2\alpha)}{g}$.",
        points: 3,
      ),
    ],
    finalAnswer: r"$h_{max} = 5$ m, portée $R \approx 34{,}64$ m.",
    gradingNotes: r"Décomposition (2 pts) + hauteur max via $v_y = 0$ (3 pts) + portée par symétrie (3 pts).",
    commonMistakes: [
      r"Utiliser $T = t_h$ pour la portée — faux. Le temps de vol total est $2 t_h$ (montée + descente symétrique).",
      r"Oublier de décomposer la vitesse initiale et utiliser $v_0$ entier dans les équations — donne des résultats incohérents.",
    ],
    tips: [
      r"Formules à mémoriser pour le tir balistique : $h_{max} = \dfrac{v_0^2 \sin^2\alpha}{2g}$, $R = \dfrac{v_0^2 \sin(2\alpha)}{g}$, portée maximale pour $\alpha = 45°$.",
    ],
  ),

  // Q42 — F = ma
  _ans(
    steps: [
      _step(
        r"**Application directe du PFD.** Le principe fondamental de la dynamique (deuxième loi de Newton) s'écrit $\sum \vec F_{ext} = m \vec a$. Pour une seule force et un mouvement rectiligne, en intensité : $F = ma = 4 \cdot 2{,}5 = 10$ N. Unité cohérente : N = kg·m/s².",
        points: 3,
      ),
    ],
    finalAnswer: r"$F = 10$ N.",
    gradingNotes: r"PFD appliqué (3 pts).",
  ),

  // Q43 — RC charge complete
  _ans(
    steps: [
      _step(
        r"**Constante de temps.** Pour un circuit RC en charge, la constante de temps est $\tau = RC = 10^4 \cdot 10^{-4} = 1$ s. C'est le temps caractéristique de l'établissement du régime : à $t = \tau$, on a atteint environ 63% de la tension finale.",
        points: 2,
      ),
      _step(
        r"**Tension à $t = \tau$.** L'équation de la charge d'un condensateur sous tension $E$ via une résistance $R$ est $u_C(t) = E(1 - e^{-t/\tau})$. À $t = \tau$ : $u_C(\tau) = E(1 - e^{-1}) = 12 \cdot (1 - 0{,}368) \approx 12 \cdot 0{,}632 \approx 7{,}59$ V. C'est le célèbre « 63% du régime établi à $\tau$ ».",
        points: 3,
        widgetSlug: "capacitor_charge",
        widgetConfig: {"R": 10000.0, "C": 0.0001, "E": 12.0},
      ),
      _step(
        r"**Atteinte du régime permanent.** Pour atteindre 99% de $E$, il faut $1 - e^{-t/\tau} = 0{,}99$, soit $e^{-t/\tau} = 0{,}01$, donc $t/\tau = \ln(100) \approx 4{,}6$. En pratique on dit que le régime est atteint à $5\tau = 5$ s : le résiduel à $5\tau$ est $e^{-5} \approx 0{,}007$, soit moins de 1%.",
        points: 2,
      ),
    ],
    finalAnswer: r"$\tau = 1$ s, $u_C(\tau) \approx 7{,}59$ V, 99% atteint en environ $5\tau = 5$ s.",
    gradingNotes: r"$\tau = RC$ (2 pts) + équation de charge + valeur à $\tau$ (3 pts) + critère $5\tau$ pour 99% (2 pts).",
    tips: [
      r"Repères mémorisables : à $\tau$ → 63%, à $2\tau$ → 86%, à $3\tau$ → 95%, à $5\tau$ → 99,3%. Identique pour la décharge inversée.",
    ],
  ),

  // Q44 — wave lambda
  _ans(
    steps: [
      _step(
        r"**Relation onde-périodicité.** La célérité d'une onde, sa longueur d'onde et sa fréquence sont liées par $v = \lambda f$, autrement dit $\lambda = v/f$. C'est l'identité fondamentale des ondes périodiques : « la longueur d'onde est la distance parcourue en une période ».",
        points: 1,
      ),
      _step(
        r"**Application numérique.** $\lambda = v/f = 340/500 = 0{,}68$ m. Cohérence dimensionnelle : (m/s)/Hz = (m/s)/(1/s) = m ✓.",
        points: 2,
      ),
    ],
    finalAnswer: r"$\lambda = 0{,}68$ m.",
    gradingNotes: r"Relation $\lambda = v/f$ (1 pt) + application numérique avec contrôle dimensionnel (2 pts).",
    tips: [
      r"Pour les sons audibles dans l'air (20 Hz à 20 kHz), $\lambda$ varie de 17 m (graves) à 1,7 cm (aigus). Cela explique pourquoi les graves se diffractent autour des obstacles, pas les aigus.",
    ],
  ),

  // Q45 — Titrage HCl par NaOH
  _ans(
    steps: [
      _step(
        r"**Réaction de titrage.** $HCl$ et $NaOH$ sont des électrolytes forts ; en solution, on a en réalité la réaction acide-base nette : $H_3O^+ + OH^- \to 2 H_2O$. À l'équivalence, exactement autant de moles d'acide que de base : $n(HCl) = n(NaOH)$. C'est l'unique condition qui définit l'équivalence en titrage acide fort / base forte.",
        points: 1,
      ),
      _step(
        r"**Bilan en moles.** $n(HCl) = C_a \cdot V_a$ (concentration acide × volume acide) et $n(NaOH)_{verse} = C_b \cdot V_E$ (concentration base × volume versé à l'équivalence). Égalité : $C_a V_a = C_b V_E$. On isole $C_a$ : $C_a = \dfrac{C_b V_E}{V_a}$.",
        points: 2,
      ),
      _step(
        r"**Application numérique.** $C_a = \dfrac{0{,}1 \cdot 15 \cdot 10^{-3}}{20 \cdot 10^{-3}} = \dfrac{0{,}1 \cdot 15}{20} = 0{,}075$ mol/L. Les volumes en mL ou L donnent le même rapport, donc on peut se passer du facteur $10^{-3}$.",
        points: 2,
        widgetSlug: "titration_simulator",
        widgetConfig: {"cAcid": 0.075, "cBase": 0.1, "vAcid": 20.0},
      ),
    ],
    finalAnswer: r"$C_a = 0{,}075$ mol/L = $7{,}5 \cdot 10^{-2}$ mol/L.",
    gradingNotes: r"Définition de l'équivalence (1 pt) + bilan molaire $C_a V_a = C_b V_E$ (2 pts) + application numérique (2 pts).",
    tips: [
      r"Pour acide fort / base forte, le pH à l'équivalence est exactement 7 (à 25 °C). Pour acide faible / base forte, il est > 7 (par hydrolyse de la base conjuguée).",
    ],
  ),

  // Q46 — chute libre 0.5 kg, 2m
  _ans(
    steps: [
      _step(
        r"**Conservation de l'énergie mécanique.** Sans frottement, la somme $E_m = E_c + E_p$ se conserve. Au sommet (lâcher) : $E_c = 0$ (vitesse nulle) et $E_p = mgh$. Au sol : $E_c = \dfrac{1}{2} m v^2$ et $E_p = 0$ (référentiel au sol). L'égalité $\Delta E_m = 0$ donne $mgh = \dfrac{1}{2} m v^2$ — la masse se simplifie.",
        points: 2,
      ),
      _step(
        r"**Calcul de la vitesse.** $v^2 = 2gh$, donc $v = \sqrt{2gh} = \sqrt{2 \cdot 10 \cdot 2} = \sqrt{40} \approx 6{,}32$ m/s. **Indépendant de la masse** — Galilée avait raison : tous les objets tombent à la même vitesse en chute libre (en l'absence de résistance de l'air).",
        points: 3,
      ),
    ],
    finalAnswer: r"$v \approx 6{,}32$ m/s.",
    gradingNotes: r"Conservation de $E_m$ (2 pts) + calcul de $v$ avec mention de l'indépendance par rapport à la masse (3 pts).",
    tips: [
      r"$v = \sqrt{2gh}$ est universel pour la chute libre. À retenir.",
    ],
  ),

  // Q47 — pH de [H3O+]=5e-3
  _ans(
    steps: [
      _step(
        r"**Définition du pH.** $pH = -\log_{10}[H_3O^+]$ avec $[H_3O^+]$ en mol/L. Application : $pH = -\log(5 \cdot 10^{-3})$. On décompose le log : $\log(5 \cdot 10^{-3}) = \log 5 + \log(10^{-3}) = 0{,}699 - 3 = -2{,}301$. Donc $pH = -(-2{,}301) = 2{,}301 \approx 2{,}3$.",
        points: 3,
      ),
    ],
    finalAnswer: r"$pH \approx 2{,}3$.",
    gradingNotes: r"Définition + calcul du log (3 pts).",
    tips: [
      r"Repères utiles : $\log 2 \approx 0{,}30$, $\log 3 \approx 0{,}48$, $\log 5 \approx 0{,}70$, $\log 7 \approx 0{,}85$. Permet de calculer un pH sans calculatrice.",
    ],
  ),

  // Q48 — anode pile Daniell
  _ans(
    steps: [
      _step(
        r"**Définition anode/cathode.** Dans une pile, l'**anode est l'électrode où a lieu l'oxydation** (perte d'électrons), la **cathode est l'électrode où a lieu la réduction** (gain d'électrons). Dans la pile Daniell, le zinc est moins noble que le cuivre (potentiel $E^° (Zn^{2+}/Zn) = -0{,}76$ V plus négatif que $E^°(Cu^{2+}/Cu) = +0{,}34$ V), donc le zinc s'oxyde et le cuivre se réduit.",
        points: 1,
      ),
      _step(
        r"**Demi-équation à l'anode.** L'oxydation du zinc s'écrit $Zn \to Zn^{2+} + 2 e^-$. Les électrons libérés circulent dans le fil extérieur vers la cathode où ils réduiront $Cu^{2+}$ en $Cu$. Réponse **B**.",
        points: 2,
        widgetSlug: "daniell_cell",
        widgetConfig: {},
      ),
    ],
    finalAnswer: r"B — $Zn \to Zn^{2+} + 2 e^-$ (oxydation à l'anode).",
    gradingNotes: r"Définition anode = oxydation + identification du Zn comme oxydé (1 pt) + demi-équation (2 pts).",
    commonMistakes: [
      r"Confondre anode et cathode. Mnémo : **A**node ↔ **A**node a la borne moins (en pile), **A**node = **A**xidation (oxydation, en anglais). Ou : « la cathode CAtche les électrons » (réduction).",
    ],
  ),

  // Q49 — RLC L=0.5, C=50µF, R=20
  _ans(
    steps: [
      _step(
        r"**Période propre de l'oscillateur LC.** Pour un circuit RLC série en oscillation libre, la pulsation propre est $\omega_0 = 1/\sqrt{LC}$, et la période propre $T_0 = 2\pi/\omega_0 = 2\pi\sqrt{LC}$. Application : $LC = 0{,}5 \cdot 5 \cdot 10^{-5} = 2{,}5 \cdot 10^{-5}$, $\sqrt{LC} \approx 5 \cdot 10^{-3}$ s. $T_0 = 2\pi \cdot 5 \cdot 10^{-3} \approx 31{,}4$ ms.",
        points: 3,
        widgetSlug: "rlc",
        widgetConfig: {"R": 20.0, "L": 0.5, "C": 0.00005},
      ),
      _step(
        r"**Régime via comparaison à $R_c$.** Le régime dépend du rapport entre $R$ et la résistance critique $R_c = 2\sqrt{L/C}$. Calcul : $L/C = 0{,}5 / 5 \cdot 10^{-5} = 10^4$, $\sqrt{L/C} = 100$, $R_c = 200$ Ω. Comme $R = 20 < R_c = 200$, le régime est **pseudo-périodique** : oscillations amorties, le système oscille en perdant progressivement de l'énergie par effet Joule.",
        points: 3,
      ),
    ],
    finalAnswer: r"$T_0 \approx 31{,}4$ ms, régime pseudo-périodique (oscillations amorties).",
    gradingNotes: r"Période propre (3 pts) + identification du régime via $R$ vs $R_c$ (3 pts).",
    tips: [
      r"Trois régimes pour un RLC libre : $R < R_c$ pseudo-périodique, $R = R_c$ critique (retour le plus rapide), $R > R_c$ apériodique (lent, sans oscillation).",
    ],
  ),

  // Q50 — Snell, air -> eau, 45°
  _ans(
    steps: [
      _step(
        r"**Loi de Snell-Descartes.** Pour le passage entre deux milieux d'indices $n_1$ et $n_2$, la loi de la réfraction est $n_1 \sin i_1 = n_2 \sin i_2$, où $i_1$ et $i_2$ sont les angles avec la normale. Application : $1 \cdot \sin 45° = 1{,}33 \cdot \sin i_2$, soit $\sin i_2 = \dfrac{\sin 45°}{1{,}33} = \dfrac{0{,}707}{1{,}33} \approx 0{,}532$.",
        points: 2,
      ),
      _step(
        r"**Calcul de l'angle.** $i_2 = \arcsin(0{,}532) \approx 32{,}1°$. **Le rayon est rapproché de la normale** quand on passe d'un milieu moins réfringent (air, $n=1$) à un milieu plus réfringent (eau, $n=1{,}33$). Comportement classique de la réfraction quand $n_2 > n_1$.",
        points: 2,
        widgetSlug: "refraction_simulator",
        widgetConfig: {"n1": 1.0, "n2": 1.33, "angle": 45.0},
      ),
    ],
    finalAnswer: r"$i_2 \approx 32{,}1°$.",
    gradingNotes: r"Loi de Snell (2 pts) + arcsin + commentaire « rapproché de la normale » (2 pts).",
    tips: [
      r"Mnémo : « plus dense = plus proche de la normale ». L'eau est plus dense optiquement que l'air, donc le rayon se rapproche de la verticale.",
    ],
  ),

  // ============================================================
  // SMB PC 2024 rattrapage (paper 6) — questions 51-60
  // ============================================================

  _ans(
    steps: [
      _step(
        r"**Bilan des forces sur le solide.** Sur le plan incliné, les forces extérieures sont : poids $\vec P$ (vertical, vers le bas), réaction normale $\vec R_N$ (perpendiculaire au plan), force de frottement $\vec f$ (parallèle au plan, opposée au mouvement). Pas de tension. On choisit l'axe parallèle au plan (descente positive).",
        points: 2,
      ),
      _step(
        r"**Projection du PFD sur l'axe du plan.** Le poids se projette en $P\sin\alpha$ (descend), la réaction normale a une projection nulle (perpendiculaire), le frottement vaut $f = \mu R_N = \mu m g \cos\alpha$ (vertical au plan, donc projection sur l'axe = $\mu m g \cos\alpha$ remonte). Bilan : $m a = m g \sin\alpha - \mu m g \cos\alpha$, soit $a = g(\sin\alpha - \mu\cos\alpha)$. **La masse se simplifie** — l'accélération est indépendante de la masse.",
        points: 2,
      ),
      _step(
        r"**Application numérique.** $\sin 25° \approx 0{,}423$, $\cos 25° \approx 0{,}906$. $a = 10 \cdot (0{,}423 - 0{,}2 \cdot 0{,}906) = 10 \cdot (0{,}423 - 0{,}181) = 10 \cdot 0{,}241 \approx 2{,}41$ m/s².",
        points: 4,
        widgetSlug: "force_diagram",
        widgetConfig: {"mass": 3.0, "angle": 25.0, "friction": 0.2},
      ),
    ],
    finalAnswer: r"$a \approx 2{,}41$ m/s².",
    gradingNotes: r"Bilan des forces avec schéma (2 pts) + projection avec dépendance en $\sin$ et $\cos$ (2 pts) + numérique (4 pts).",
    tips: [
      r"Pour qu'un solide commence à glisser, il faut $\sin\alpha > \mu \cos\alpha$, soit $\tan\alpha > \mu$ (« angle de frottement »). Sinon adhérence.",
    ],
  ),

  // Q52 — half-life T=5, 15 ans
  _ans(
    steps: [
      _step(
        r"**Loi de décroissance par demi-vies.** Au bout de $n$ demi-vies, il reste $1/2^n$ de la quantité initiale. Ici $15 / 5 = 3$ demi-vies, donc reste $1/2^3 = 1/8 = 0{,}125 = 12{,}5\%$.",
        points: 3,
      ),
    ],
    finalAnswer: r"$1/8 = 12{,}5\%$.",
    gradingNotes: r"Loi des demi-vies + ratio (3 pts).",
    tips: [
      r"Loi continue : $N(t) = N_0 \cdot (1/2)^{t/T_{1/2}} = N_0 e^{-\lambda t}$ avec $\lambda = \ln 2 / T_{1/2}$. Les deux formulations coïncident.",
    ],
  ),

  // Q53 — RLC L=1H C=10µF, f0
  _ans(
    steps: [
      _step(
        r"**Formule.** Fréquence propre : $f_0 = \dfrac{1}{2\pi\sqrt{LC}}$. Application : $LC = 1 \cdot 10^{-5}$, $\sqrt{LC} = \sqrt{10^{-5}} \approx 3{,}162 \cdot 10^{-3}$ s. $f_0 = \dfrac{1}{2\pi \cdot 3{,}162 \cdot 10^{-3}} \approx \dfrac{1}{0{,}01987} \approx 50{,}3$ Hz.",
        points: 4,
      ),
    ],
    finalAnswer: r"$f_0 \approx 50{,}3$ Hz.",
    gradingNotes: r"Formule + application (4 pts).",
    tips: [
      r"Cette fréquence est suspecte (≈ 50 Hz) — c'est exactement la fréquence du secteur EU. Coïncidence du choix des valeurs $L$ et $C$.",
    ],
  ),

  // Q54 — Force de Laplace
  _ans(
    steps: [
      _step(
        r"**Force de Laplace sur fil dans champ uniforme.** Pour un fil rectiligne de longueur $L$ parcouru par un courant $I$ dans un champ magnétique $\vec B$ uniforme, la force est $\vec F = I \vec L \wedge \vec B$. En intensité, si le fil est perpendiculaire au champ : $F = BIL$. Application : $F = 0{,}3 \cdot 2 \cdot 0{,}5 = 0{,}3$ N.",
        points: 3,
        widgetSlug: "b_field_uniform",
        widgetConfig: {"B": 0.3, "I": 2.0},
      ),
    ],
    finalAnswer: r"$F = 0{,}3$ N.",
    gradingNotes: r"Formule de Laplace + numérique (3 pts).",
    tips: [
      r"Direction de $\vec F$ : règle de la main droite (ou des trois doigts). Force perpendiculaire au plan formé par $\vec I$ et $\vec B$.",
    ],
  ),

  // Q55 — MCQ esterification rendement
  _ans(
    steps: [
      _step(
        r"**Catalyseur ne change pas le rendement.** Un catalyseur abaisse l'énergie d'activation et accélère la réaction, mais ne déplace pas l'équilibre — il ne modifie ni $K$ ni le rendement final. Éliminer la réponse « ajouter un catalyseur ».",
        points: 1,
      ),
      _step(
        r"**Le Chatelier : éliminer un produit.** L'estérification est une réaction limitée (à l'équilibre). Selon la loi de modération de Le Chatelier, retirer un produit de la phase réactionnelle déplace l'équilibre vers la formation de plus de produit pour compenser. Éliminer l'eau (sous-produit) est donc efficace : c'est la méthode de Dean-Stark en pratique. Réponse **C : éliminer l'eau formée**.",
        points: 2,
        widgetSlug: "esterification_animator",
        widgetConfig: {},
      ),
    ],
    finalAnswer: r"C — éliminer l'eau formée.",
    gradingNotes: r"Catalyseur n'agit pas sur le rendement (1 pt) + Le Chatelier + élimination eau (2 pts).",
    tips: [
      r"Loi de Le Chatelier : tout système à l'équilibre soumis à une perturbation évolue dans le sens qui s'oppose à la perturbation. Retirer un produit → produire plus.",
    ],
  ),

  // Q56 — [H3O+] from pH=5.3
  _ans(
    steps: [
      _step(
        r"**Inversion de la définition du pH.** $pH = -\log[H_3O^+]$ ⟹ $[H_3O^+] = 10^{-pH}$. Application : $[H_3O^+] = 10^{-5{,}3}$. Décomposition : $10^{-5{,}3} = 10^{0{,}7} \cdot 10^{-6} \approx 5{,}01 \cdot 10^{-6}$. Donc $[H_3O^+] \approx 5 \cdot 10^{-6}$ mol/L.",
        points: 3,
      ),
    ],
    finalAnswer: r"$[H_3O^+] \approx 5 \cdot 10^{-6}$ mol/L.",
    gradingNotes: r"Inversion + calcul (3 pts).",
    tips: [
      r"Astuce : $10^{0{,}7} \approx 5$ (puisque $\log 5 \approx 0{,}7$). Donc $10^{-x{,}3}$ se calcule comme $10^{0{,}7} \cdot 10^{-(x+1)} \approx 5 \cdot 10^{-(x+1)}$.",
    ],
  ),

  // Q57 — pendule, T=2s, L?
  _ans(
    steps: [
      _step(
        r"**Formule du pendule simple.** Pour les petites oscillations, la période d'un pendule simple est $T = 2\pi\sqrt{L/g}$. On isole $L$ : $T^2 = 4\pi^2 \dfrac{L}{g}$, donc $L = \dfrac{g T^2}{4\pi^2}$.",
        points: 2,
      ),
      _step(
        r"**Application numérique.** $L = \dfrac{9{,}81 \cdot 4}{4\pi^2} = \dfrac{9{,}81}{\pi^2} \approx \dfrac{9{,}81}{9{,}87} \approx 0{,}994$ m. Presque exactement 1 m — c'est pourquoi historiquement le « pendule à seconde » (T = 2 s, soit aller-retour 2 s) avait une longueur d'environ 1 m.",
        points: 3,
        widgetSlug: "pendulum_lab",
        widgetConfig: {"length": 1.0},
      ),
    ],
    finalAnswer: r"$L \approx 0{,}994$ m.",
    gradingNotes: r"Formule (2 pts) + numérique avec contexte historique (3 pts).",
    tips: [
      r"La période d'un pendule simple est indépendante de la masse et de l'amplitude (pour petits angles). Seuls $L$ et $g$ comptent.",
    ],
  ),

  // Q58 — wave f=50, v=200
  _ans(
    steps: [
      _step(
        r"**Application directe.** $\lambda = v/f = 200/50 = 4$ m. À retenir comme exemple simple de la relation onde-périodicité.",
        points: 3,
        widgetSlug: "wave",
        widgetConfig: {"frequency": 50.0, "velocity": 200.0},
      ),
    ],
    finalAnswer: r"$\lambda = 4$ m.",
    gradingNotes: r"Formule + numérique (3 pts).",
  ),

  // Q59 — RL tau
  _ans(
    steps: [
      _step(
        r"**Constante de temps RL.** Pour un circuit RL en série, l'équation $L \dfrac{di}{dt} + R i = 0$ (régime libre) ou avec second membre $E$ (régime forcé) a pour constante de temps $\tau = L/R$. **Attention** : différente de RC (qui est $RC$, pas $L/R$). Application : $\tau = 0{,}2/50 = 4 \cdot 10^{-3}$ s = 4 ms.",
        points: 3,
      ),
    ],
    finalAnswer: r"$\tau = 4$ ms.",
    gradingNotes: r"Formule $\tau = L/R$ + numérique (3 pts).",
    commonMistakes: [
      r"Mélanger RC ($\tau = RC$) et RL ($\tau = L/R$). Mnémo : dans RL la self ralentit le courant, donc $\tau$ croît avec $L$ et décroît avec $R$ (forte $R$ = courant établi rapidement).",
    ],
  ),

  // Q60 — Qr > K
  _ans(
    steps: [
      _step(
        r"**Critère d'évolution.** Le quotient de réaction $Q_r$ dépend des concentrations actuelles ; la constante $K$ caractérise l'équilibre (à $T$ donnée). Si $Q_r < K$, le système évolue dans le sens direct (formation des produits). Si $Q_r = K$, il est à l'équilibre. **Si $Q_r > K$, il y a trop de produits par rapport à l'équilibre : le système évolue dans le sens inverse pour les consommer et reformer les réactifs.** Réponse **C : sens inverse**.",
        points: 2,
        widgetSlug: "equilibrium_qr_k",
        widgetConfig: {},
      ),
    ],
    finalAnswer: r"C — sens inverse.",
    gradingNotes: r"Critère $Q_r$ vs $K$ + sens d'évolution (2 pts).",
    tips: [
      r"Mnémo : $Q_r$ « tire vers $K$ ». Trop haut → on baisse en consommant les produits. Trop bas → on monte en produisant.",
    ],
  ),

  // ============================================================
  // SMB PC 2023 normale (paper 7) — questions 61-70
  // ============================================================

  _ans(steps: [
    _step(
      r"**Mouvement rectiligne uniformément accéléré (MRUA).** Le mobile part du repos, donc $v_0 = 0$. La distance parcourue en MRUA est $x(t) = \dfrac{1}{2} a t^2$. Application : $x = \dfrac{1}{2} \cdot 3 \cdot 16 = 24$ m. La vitesse à $t = 4$ s est $v(t) = at = 12$ m/s.",
      points: 3,
    ),
  ], finalAnswer: r"$x = 24$ m.", gradingNotes: r"MRUA (3 pts)."),

  _ans(steps: [
    _step(
      r"**Vitesse en MRUA depuis le repos.** $v(t) = v_0 + at = 0 + 3 \cdot 4 = 12$ m/s. Cohérent avec $\Delta v / \Delta t = a$.",
      points: 2,
    ),
  ], finalAnswer: r"$v = 12$ m/s.", gradingNotes: r"Application (2 pts)."),

  _ans(steps: [
    _step(
      r"**Théorème de l'énergie cinétique.** $\Delta E_c = W_{ext}$. Travail d'une force constante sur un déplacement parallèle : $W = F \cdot d = 10 \cdot 5 = 50$ J. Donc $\Delta E_c = 50$ J. Si l'objet part du repos, $E_c$ finale = 50 J et $v = \sqrt{2 E_c/m} = \sqrt{50} \approx 7{,}07$ m/s.",
      points: 4,
    ),
  ], finalAnswer: r"$\Delta E_c = 50$ J.", gradingNotes: r"TEC (4 pts).", tips: [r"Théorème de l'énergie cinétique : $\Delta E_c = \sum W_{ext}$. Outil-clé quand on s'intéresse aux variations de vitesse sans détailler le mouvement."]),

  _ans(steps: [
    _step(
      r"**Énergie d'un condensateur chargé.** $E = \dfrac{1}{2} C U^2$. Application : $E = 0{,}5 \cdot 220 \cdot 10^{-6} \cdot 400 = 0{,}044$ J = 44 mJ. C'est l'énergie stockée, libérée à la décharge.",
      points: 3,
    ),
  ], finalAnswer: r"$E = 44$ mJ.", gradingNotes: r"Formule + numérique (3 pts).", tips: [r"Trois formules équivalentes pour l'énergie d'un condensateur : $\dfrac{1}{2}CU^2 = \dfrac{1}{2}QU = \dfrac{Q^2}{2C}$."]),

  _ans(steps: [
    _step(
      r"**Effet de la dilution sur acide fort.** Pour un acide fort, $[H_3O^+] = C$ (totalement dissocié). Si on dilue 10×, la concentration $C$ est divisée par 10, donc $[H_3O^+]$ aussi. Comme $pH = -\log[H_3O^+]$, diviser par 10 fait monter le pH de 1 unité.",
      points: 2,
      widgetSlug: "acid_base_ph",
      widgetConfig: {"pH": 4.0},
    ),
    _step(
      r"**Application.** pH initial = 3. Après dilution 10× : $pH = 3 + 1 = 4$. **Limite** : on ne peut pas faire monter le pH au-dessus de 7 par dilution d'acide (l'eau elle-même apporte des $H_3O^+$).",
      points: 1,
    ),
  ], finalAnswer: r"$pH = 4$.", gradingNotes: r"Effet de la dilution (2 pts) + valeur (1 pt).", tips: [r"Dilution × 10 → pH augmente de 1 (pour acide). Dilution illimitée d'un acide fort tend vers 7, jamais au-delà."]),

  _ans(steps: [
    _step(
      r"**Constante d'équilibre et thermodynamique.** $K$ est définie comme l'expression $\prod [\text{produits}]^{\nu_i} / \prod [\text{réactifs}]^{\nu_j}$ à l'équilibre. Sa valeur dépend uniquement de la température (relation de Van't Hoff : $\dfrac{d\ln K}{dT} = \dfrac{\Delta H°}{RT^2}$). Concentrations initiales, volume, pression — tous changent $Q_r$ pendant l'évolution mais pas $K$. Réponse **C**.",
      points: 2,
    ),
  ], finalAnswer: r"C — température.", gradingNotes: r"$K$ ne dépend que de $T$ (2 pts).", commonMistakes: [r"Confondre $K$ et $Q_r$. $Q_r$ change pendant la réaction ; $K$ est fixe à $T$ donnée."]),

  _ans(steps: [
    _step(
      r"**Demi-vies pour le carbone-14.** $T_{1/2} = 5730$ ans. Au bout de 17 190 ans, on a $17190/5730 = 3$ demi-vies. Reste $(1/2)^3 = 1/8 = 12{,}5\%$. Le carbone-14 est utilisé en datation archéologique précisément parce que sa demi-vie est de l'ordre du millénaire — adapté aux objets de quelques milliers d'années.",
      points: 3,
    ),
  ], finalAnswer: r"$12{,}5\%$.", gradingNotes: r"Demi-vies (3 pts).", tips: [r"Au-delà de ~10 demi-vies (≈ 60 000 ans pour C-14), il ne reste plus assez de noyaux pour mesurer fiablement → autre méthode."]),

  _ans(steps: [
    _step(
      r"**fem standard d'une pile.** $\Delta E° = E°_{cathode} - E°_{anode}$. Pour la pile Daniell, cathode = Cu (potentiel le plus haut), anode = Zn (potentiel le plus bas). $\Delta E° = 0{,}34 - (-0{,}76) = 1{,}10$ V. Cette différence positive garantit que la pile fonctionne spontanément (génératrice d'énergie).",
      points: 2,
    ),
  ], finalAnswer: r"$\Delta E° = 1{,}10$ V.", gradingNotes: r"Formule + signe (2 pts).", tips: [r"Une pile fonctionne en génératrice ssi $\Delta E° > 0$. Sinon il faut fournir de l'énergie (électrolyse)."]),

  _ans(steps: [
    _step(
      r"**Diffraction par une fente.** Pour une fente de largeur $a$ traversée par une onde de longueur $\lambda$, le demi-angle de la tâche centrale de diffraction est $\theta \approx \lambda / a$ (en radians, pour $a \gg \lambda$). Application : $\theta = 6 \cdot 10^{-7} / 10^{-4} = 6 \cdot 10^{-3}$ rad = 6 mrad.",
      points: 3,
    ),
    _step(
      r"**Conversion en degrés.** $6 \cdot 10^{-3}$ rad × $\dfrac{180°}{\pi}$ ≈ $0{,}344°$. Très faible — la lumière reste bien collimatée pour cette taille de fente.",
      points: 1,
    ),
  ], finalAnswer: r"$\theta \approx 6$ mrad ≈ $0{,}34°$.", gradingNotes: r"Formule diffraction (3 pts) + conversion (1 pt).", tips: [r"Plus la fente est étroite (par rapport à $\lambda$), plus la diffraction est marquée. C'est pourquoi la diffraction est invisible à grande échelle (fenêtres) mais notable pour les ondes radio."]),

  _ans(steps: [
    _step(
      r"**Constante d'équilibre de la réaction.** $K = \dfrac{[C]}{[A][B]}$ pour $A + B \rightleftharpoons C$. Application : $4 = \dfrac{[C]}{0{,}5 \cdot 0{,}5} = \dfrac{[C]}{0{,}25}$, donc $[C] = 4 \cdot 0{,}25 = 1$ mol/L.",
      points: 3,
    ),
  ], finalAnswer: r"$[C] = 1$ mol/L.", gradingNotes: r"Définition de $K$ + numérique (3 pts)."),

  // ============================================================
  // SMB PC 2023 rattrapage (paper 8) — questions 71-80
  // ============================================================

  _ans(steps: [
    _step(
      r"**Hauteur max d'un projectile vertical.** Lancé verticalement avec vitesse $v_0$, le projectile monte jusqu'à $v = 0$. Bilan énergétique (sans frottement) : $\dfrac{1}{2} v_0^2 = g h_{max}$, donc $h_{max} = \dfrac{v_0^2}{2g} = \dfrac{900}{20} = 45$ m.",
      points: 3,
    ),
  ], finalAnswer: r"$h_{max} = 45$ m.", gradingNotes: r"Bilan énergétique + numérique (3 pts).", tips: [r"$h_{max} = v_0^2/(2g)$ pour un lancer vertical. Le double de l'énergie cinétique initiale, divisé par le poids."]),

  _ans(steps: [
    _step(
      r"**Période d'un système masse-ressort.** $T = 2\pi\sqrt{m/k}$. Application : $m/k = 2/200 = 0{,}01$, $\sqrt{m/k} = 0{,}1$ s. $T = 2\pi \cdot 0{,}1 \approx 0{,}628$ s. Indépendant de l'amplitude (pour petites oscillations), comme le pendule.",
      points: 3,
    ),
  ], finalAnswer: r"$T \approx 0{,}628$ s.", gradingNotes: r"Formule + numérique (3 pts)."),

  _ans(steps: [
    _step(
      r"**Champ électrique entre plaques.** Pour deux plaques planes parallèles distantes de $d$, sous tension $U$, le champ uniforme entre elles est $E = U/d = 100/0{,}005 = 20\,000$ V/m = $2 \cdot 10^4$ V/m. Direction : de la plaque + vers la plaque −.",
      points: 2,
    ),
    _step(
      r"**Force sur l'électron.** $F = |q| E$ avec $|q| = e = 1{,}6 \cdot 10^{-19}$ C (charge de l'électron en valeur absolue). $F = 1{,}6 \cdot 10^{-19} \cdot 2 \cdot 10^4 = 3{,}2 \cdot 10^{-15}$ N. Direction : opposée au champ (l'électron est négatif), donc de la plaque − vers la plaque +.",
      points: 3,
      widgetSlug: "e_field_uniform",
      widgetConfig: {"voltage": 100.0, "distance": 0.005},
    ),
  ], finalAnswer: r"$F \approx 3{,}2 \cdot 10^{-15}$ N (vers la plaque +).", gradingNotes: r"Champ (2 pts) + force avec direction (3 pts)."),

  _ans(steps: [
    _step(
      r"**Inverse de la période.** $f = 1/T$. Application : $f = 1/(2 \cdot 10^{-3}) = 500$ Hz.",
      points: 2,
    ),
  ], finalAnswer: r"$f = 500$ Hz.", gradingNotes: r"Inverse (2 pts)."),

  _ans(steps: [
    _step(
      r"**Charge à 99% en RC.** $u_C(t) = E(1 - e^{-t/\tau})$. Pour atteindre 99% de $E$, on résout $1 - e^{-t/\tau} = 0{,}99$, soit $e^{-t/\tau} = 0{,}01$, $t = \tau \ln 100 \approx 4{,}6 \tau$. **En pratique, on dit que le régime est établi à $5\tau$**, valeur conventionnelle. Réponse **D**.",
      points: 2,
    ),
  ], finalAnswer: r"D — $5\tau$.", gradingNotes: r"Critère + valeur (2 pts).", tips: [r"À retenir : $\tau$ = 63%, $2\tau$ = 86%, $3\tau$ = 95%, $5\tau$ = 99%."]),

  _ans(steps: [
    _step(
      r"**Base forte totalement dissociée.** $NaOH \to Na^+ + OH^-$ totalement, donc $[OH^-] = C = 0{,}01$ mol/L = $10^{-2}$ mol/L.",
      points: 1,
    ),
    _step(
      r"**Produit ionique de l'eau.** $K_e = [H_3O^+][OH^-] = 10^{-14}$ (à 25°C). Donc $[H_3O^+] = K_e/[OH^-] = 10^{-14}/10^{-2} = 10^{-12}$ mol/L.",
      points: 2,
    ),
    _step(
      r"**pH.** $pH = -\log(10^{-12}) = 12$.",
      points: 1,
    ),
  ], finalAnswer: r"$pH = 12$.", gradingNotes: r"Dissociation (1 pt) + $K_e$ (2 pts) + pH (1 pt).", tips: [r"Pour base forte de concentration $C$ : $pH = 14 + \log C$. Ici $14 + \log(0{,}01) = 14 - 2 = 12$."]),

  _ans(steps: [
    _step(
      r"**fem d'une pile par différence de potentiels.** $\Delta E° = E°_{cathode} - E°_{anode}$. Le couple le plus oxydant est cathode, l'autre anode. Ag/Ag⁺ a $E° = 0{,}80$ V > Cu/Cu²⁺ ($E° = 0{,}34$ V) ; donc Ag est cathode, Cu est anode. $\Delta E° = 0{,}80 - 0{,}34 = 0{,}46$ V.",
      points: 3,
    ),
  ], finalAnswer: r"$\Delta E° = 0{,}46$ V.", gradingNotes: r"Identification cathode/anode + différence (3 pts)."),

  _ans(steps: [
    _step(
      r"**Réactance d'une bobine.** $X_L = L\omega = 2\pi f L$. On isole $f$ : $f = X_L / (2\pi L) = 31{,}4 / (2\pi \cdot 0{,}05) = 31{,}4 / 0{,}314 \approx 100$ Hz.",
      points: 3,
    ),
  ], finalAnswer: r"$f = 100$ Hz.", gradingNotes: r"Formule de réactance + numérique (3 pts)."),

  _ans(steps: [
    _step(
      r"**Identification de l'oxydant.** Dans la réaction $2H_2 + O_2 \to 2H_2O$, on regarde les variations des nombres d'oxydation. $H$ passe de $0$ (dans $H_2$) à $+I$ (dans $H_2O$) : il s'oxyde. $O$ passe de $0$ (dans $O_2$) à $-II$ (dans $H_2O$) : il se réduit. **L'oxydant est l'espèce qui se réduit** (gagne des électrons), donc c'est $O_2$. Réponse **B**.",
      points: 2,
    ),
  ], finalAnswer: r"B — $O_2$.", gradingNotes: r"Variations des nombres d'oxydation + identification (2 pts).", commonMistakes: [r"Confondre oxydant et oxydé. **L'oxydant** est l'espèce qui **fait s'oxyder** l'autre — donc qui se réduit elle-même."]),

  _ans(steps: [
    _step(
      r"**Vitesse maximale en mouvement harmonique simple.** Pour un point oscillant comme $x(t) = A\cos(\omega t + \varphi)$, la vitesse est $\dot x(t) = -A\omega \sin(\omega t + \varphi)$, avec $|\dot x|_{max} = A\omega$. Application : $\omega = 2\pi/T = 2\pi/0{,}2 = 10\pi$ rad/s. $v_{max} = A\omega = 0{,}05 \cdot 10\pi = 0{,}5\pi \approx 1{,}57$ m/s.",
      points: 3,
    ),
  ], finalAnswer: r"$v_{max} \approx 1{,}57$ m/s.", gradingNotes: r"Formule + numérique (3 pts).", tips: [r"En MHS, $v_{max} = A\omega$ et $a_{max} = A\omega^2$. Le rapport $a_{max}/v_{max} = \omega$."]),
];
