// Expanded textbook-depth solutions for SMA exam questions (migration 024).
// Targets the 80 SMA questions inserted by migration 022. Mirrors the
// SMB v2 encoder shape — UPDATEs answer JSONB by deterministic ID.
// Run: dart backend/seed/json_encode_exam_solutions_sma_v2.dart

import "dart:convert";
import "dart:io";

void main(List<String> args) {
  final out = StringBuffer();
  out.writeln("-- Migration 024: textbook-depth solutions for SMA exam questions.");
  out.writeln("-- Auto-generated by json_encode_exam_solutions_sma_v2.dart.");
  out.writeln("-- Overwrites the answer JSONB inserted by migration 022.");
  out.writeln("BEGIN;");
  out.writeln();

  var seq = 1;
  for (final qid in _questionIds) {
    final answer = _answers[seq - 1];
    final aJson = jsonEncode(answer).replaceAll("'", "''");
    out.writeln("UPDATE public.exam_questions SET answer = '$aJson'::jsonb WHERE id = '$qid';");
    seq++;
  }

  out.writeln();
  out.writeln("COMMIT;");

  final output = args.isNotEmpty ? args[0] : "backend/supabase/migrations/024_exam_solutions_sma_expanded.sql";
  File(output).writeAsStringSync(out.toString());
  stdout.writeln("Wrote $output (${seq - 1} answer updates).");
}

final List<String> _questionIds = [
  for (var i = 1; i <= 80; i++)
    "c1b2c3d4-ffff-0000-0000-${i.toRadixString(16).padLeft(12, '0')}",
];

Map<String, dynamic> _step(
  String text, {
  int points = 0,
  String? widgetSlug,
  Map<String, dynamic>? widgetConfig,
  String? mistake,
  String? tip,
}) =>
    {
      "text": text,
      if (points > 0) "points": points,
      if (widgetSlug != null) "widget_slug": widgetSlug,
      if (widgetConfig != null) "widget_config": widgetConfig,
      if (mistake != null) "mistake": mistake,
      if (tip != null) "tip": tip,
    };

Map<String, dynamic> _ans({
  required List<Map<String, dynamic>> steps,
  String? finalAnswer,
  String? gradingNotes,
  List<String> commonMistakes = const [],
  List<String> tips = const [],
}) =>
    {
      "steps": steps,
      if (finalAnswer != null) "final_answer": finalAnswer,
      if (gradingNotes != null) "grading_notes": gradingNotes,
      if (commonMistakes.isNotEmpty) "common_mistakes": commonMistakes,
      if (tips.isNotEmpty) "tips": tips,
    };

// ---------------------------------------------------------------------------
// THE EXPANDED SMA ANSWERS — ordered identically to migration 022.
// ---------------------------------------------------------------------------

final List<Map<String, dynamic>> _answers = [
  // ====== SMA Math 2024 normale (paper 1, IDs 1-10) ======

  // Q1 — convergence de u_{n+1} = sqrt(u_n + 2), u_0 = 0
  _ans(
    steps: [
      _step(
        r"**Stabilité de l'intervalle.** Posons $f(x) = \sqrt{x + 2}$, définie sur $[-2, +\infty[$. On démontre par récurrence que $u_n \in [0, 2]$ pour tout $n$. **Initialisation** : $u_0 = 0 \in [0, 2]$ ✓. **Hérédité** : si $u_n \in [0, 2]$, alors $u_n + 2 \in [2, 4]$, donc $\sqrt{u_n + 2} \in [\sqrt{2}, 2]$. Or $\sqrt{2} \approx 1{,}41 \ge 0$, donc $u_{n+1} \in [\sqrt{2}, 2] \subset [0, 2]$. La suite reste bornée par 0 et 2.",
        points: 2,
        widgetSlug: "recurrence_solver",
        widgetConfig: {"function": "sqrt(x + 2)", "u0": 0.0, "iterations": 8},
      ),
      _step(
        r"**Monotonie.** $u_1 = \sqrt{0+2} = \sqrt{2} > 0 = u_0$. La fonction $f(x) = \sqrt{x+2}$ est croissante sur son domaine. Si $u_n \le u_{n+1}$, alors $u_n + 2 \le u_{n+1} + 2$ et donc $\sqrt{u_n + 2} \le \sqrt{u_{n+1} + 2}$, soit $u_{n+1} \le u_{n+2}$. Par récurrence, $(u_n)$ est strictement croissante.",
        points: 2,
      ),
      _step(
        r"**Convergence par théorème de la limite monotone.** $(u_n)$ est croissante et majorée par 2 ; elle converge donc vers une limite finie $\ell$ avec $0 \le \ell \le 2$. À ce stade, l'existence de la limite est assurée — il reste à la calculer.",
        points: 2,
      ),
      _step(
        r"**Recherche du point fixe.** $f$ est continue sur $[-2, +\infty[$, donc on passe à la limite dans $u_{n+1} = f(u_n)$ : $\ell = \sqrt{\ell + 2}$. On élève au carré (légitime car les deux membres sont positifs) : $\ell^2 = \ell + 2$, soit $\ell^2 - \ell - 2 = 0$. Discriminant $\Delta = 1 + 8 = 9$, racines $\ell = (1 \pm 3)/2 = 2$ ou $-1$. **On rejette $-1$ car $\ell \ge 0$**. Donc $\ell = 2$.",
        points: 3,
        mistake: r"Erreur classique : oublier la condition $\ell \ge 0$ (héritée de $u_n \ge 0$) et accepter la racine $\ell = -1$. Toujours vérifier la cohérence avec l'intervalle de stabilité.",
      ),
    ],
    finalAnswer: r"$(u_n)$ converge vers $\ell = 2$.",
    gradingNotes: r"Stabilité (2 pts) + monotonie (2 pts) + convergence (2 pts) + équation du point fixe + sélection de la bonne racine (3 pts).",
    commonMistakes: [r"Oublier la stabilité, partir directement sur la monotonie sans avoir borné la suite.", r"Conclure trop vite que $\ell = 2$ sans rejeter explicitement $\ell = -1$."],
    tips: [r"Pour suite récurrente avec $f$ croissante : (1) stabilité d'un intervalle, (2) monotonie initiale + récurrence, (3) théorème de la limite monotone, (4) résolution $\ell = f(\ell)$ avec sélection cohérente."],
  ),

  // Q2 — lim (e^x - 1 - x)/x^2 en 0
  _ans(
    steps: [
      _step(
        r"**Forme indéterminée 0/0 et développement limité.** En $x = 0$ : numérateur $e^0 - 1 - 0 = 0$, dénominateur $0$. Forme $0/0$. La méthode efficace ici est le développement limité de $e^x$ au voisinage de 0 : $e^x = 1 + x + \dfrac{x^2}{2} + \dfrac{x^3}{6} + o(x^3)$.",
        points: 2,
      ),
      _step(
        r"**Substitution dans l'expression.** $e^x - 1 - x = \dfrac{x^2}{2} + \dfrac{x^3}{6} + o(x^3)$ — les termes $1$ et $x$ disparaissent. En divisant par $x^2$ : $\dfrac{e^x - 1 - x}{x^2} = \dfrac{1}{2} + \dfrac{x}{6} + o(x)$.",
        points: 2,
      ),
      _step(
        r"**Passage à la limite.** Quand $x \to 0$, $\dfrac{x}{6} \to 0$ et $o(x) \to 0$. La limite vaut donc $\dfrac{1}{2}$.",
        points: 1,
      ),
    ],
    finalAnswer: r"$\dfrac{1}{2}$.",
    gradingNotes: r"DL de $e^x$ à l'ordre 2 (2 pts) + substitution + simplification (2 pts) + limite (1 pt).",
    tips: [r"Pour les limites en 0 avec exponentielles ou trigos, le DL est presque toujours la voie la plus rapide. Mémoriser $e^x = 1 + x + x^2/2 + ...$ et $\sin x = x - x^3/6 + ...$"],
  ),

  // Q3 — f(x) = ln(x^2-4x+5), domaine, dérivée, variations
  _ans(
    steps: [
      _step(
        r"**Étude du domaine.** Pour que $\ln(x^2 - 4x + 5)$ soit défini, il faut $x^2 - 4x + 5 > 0$. On reconnaît une forme canonique : $x^2 - 4x + 5 = (x - 2)^2 + 1$. Comme $(x-2)^2 \ge 0$, on a $x^2 - 4x + 5 \ge 1 > 0$ partout. Donc $D_f = \mathbb{R}$.",
        points: 2,
      ),
      _step(
        r"**Dérivée par composition.** $f = \ln \circ u$ avec $u(x) = x^2 - 4x + 5$. La règle de dérivation $(\ln u)' = u'/u$ donne $f'(x) = \dfrac{2x - 4}{x^2 - 4x + 5}$. Le dénominateur est strictement positif (on l'a montré), donc le signe de $f'$ ne dépend que de $2x - 4$.",
        points: 2,
      ),
      _step(
        r"**Tableau de signes de $f'$.** $2x - 4 < 0$ ssi $x < 2$, $2x - 4 > 0$ ssi $x > 2$, et $f'(2) = 0$. Donc $f$ est strictement décroissante sur $]-\infty, 2]$, strictement croissante sur $[2, +\infty[$.",
        points: 2,
        widgetSlug: "sign_table",
        widgetConfig: {"function": "2*x - 4"},
      ),
      _step(
        r"**Minimum global.** En $x = 2$, $f$ admet un minimum (changement de signe de $f'$ : $-$ à $+$). $f(2) = \ln((2-2)^2 + 1) = \ln 1 = 0$. Donc $f \ge 0$ sur $\mathbb{R}$, avec égalité seulement en $x = 2$.",
        points: 2,
      ),
    ],
    finalAnswer: r"$D_f = \mathbb{R}$, minimum global en $x = 2$, $f(2) = 0$.",
    gradingNotes: r"Domaine via forme canonique (2 pts) + dérivée composée (2 pts) + signe (2 pts) + minimum + valeur (2 pts).",
    tips: [r"$x^2 + bx + c$ s'écrit toujours $(x + b/2)^2 + (c - b^2/4)$ — c'est la forme canonique, qui révèle si l'expression est toujours positive."],
  ),

  // Q4 — int_0^1 x e^x dx (IPP)
  _ans(
    steps: [
      _step(
        r"**Choix de l'IPP.** $\int x e^x \, dx$ a un produit avec $x$ (dont la dérivée se simplifie) et $e^x$ (dont la primitive est immédiate). On pose $u = x$, $dv = e^x \, dx$, donc $u' = 1$ et $v = e^x$. Formule : $\int u \, dv = uv - \int v \, du$.",
        points: 2,
        widgetSlug: "ipp_calculator",
        widgetConfig: {"u": "x", "dv": "e^x"},
      ),
      _step(
        r"**Application.** $\int_0^1 x e^x \, dx = [x e^x]_0^1 - \int_0^1 e^x \, dx = (1 \cdot e - 0 \cdot 1) - [e^x]_0^1 = e - (e - 1) = e - e + 1 = 1$.",
        points: 3,
      ),
    ],
    finalAnswer: r"$\int_0^1 x e^x \, dx = 1$.",
    gradingNotes: r"Choix d'IPP justifié (2 pts) + calcul + simplification (3 pts).",
    tips: [r"Règle pour choisir $u$ en IPP : ALPES (Arctan, Logarithme, Polynôme, Exponentielle, Sinus). Choisir $u$ = la fonction la plus à gauche dans cette liste."],
  ),

  // Q5 — z^2 - 2z + 5 = 0
  _ans(
    steps: [
      _step(
        r"**Discriminant et racines complexes.** $z^2 - 2z + 5 = 0$. Discriminant $\Delta = b^2 - 4ac = 4 - 20 = -16 < 0$. Comme $\Delta < 0$, l'équation n'a pas de racines réelles, mais elle a deux racines **complexes conjuguées**. On écrit $\sqrt{\Delta} = \sqrt{-16} = 4i$ (ou $\pm 4i$).",
        points: 2,
      ),
      _step(
        r"**Calcul des racines.** $z = \dfrac{-b \pm \sqrt{\Delta}}{2a} = \dfrac{2 \pm 4i}{2} = 1 \pm 2i$. Les deux racines sont $z_1 = 1 + 2i$ et $z_2 = 1 - 2i$, conjuguées l'une de l'autre comme prévu.",
        points: 3,
        widgetSlug: "complex_plane",
        widgetConfig: {"real": 1.0, "imaginary": 2.0},
      ),
    ],
    finalAnswer: r"$z = 1 + 2i$ ou $z = 1 - 2i$.",
    gradingNotes: r"Discriminant + racine carrée complexe (2 pts) + formule des racines + écriture finale (3 pts).",
    tips: [r"Pour un trinôme à coefficients réels, si $\Delta < 0$ les racines sont complexes conjuguées. La somme reste $-b/a$ et le produit $c/a$, identités valables aussi avec des racines complexes."],
  ),

  // Q6 — f(x) = e^x/x sur R*
  _ans(
    steps: [
      _step(
        r"**Dérivée par quotient.** $f(x) = \dfrac{e^x}{x}$ sur $\mathbb{R}^*$. Avec $u = e^x$, $v = x$ : $u' = e^x$, $v' = 1$. Formule du quotient : $f'(x) = \dfrac{u'v - uv'}{v^2} = \dfrac{e^x \cdot x - e^x \cdot 1}{x^2} = \dfrac{e^x(x - 1)}{x^2}$.",
        points: 3,
      ),
      _step(
        r"**Étude du signe.** $e^x > 0$ et $x^2 > 0$ pour $x \ne 0$. Le signe de $f'$ est donc celui de $x - 1$ : négatif pour $x < 1$, positif pour $x > 1$. **Mais attention** : sur $]-\infty, 0[$ et sur $]0, +\infty[$ séparément, car $f$ n'est pas définie en 0.",
        points: 2,
      ),
      _step(
        r"**Minimum local sur $]0, +\infty[$.** Sur $]0, +\infty[$ : $f' < 0$ pour $x < 1$, $f' > 0$ pour $x > 1$. Donc $f$ a un minimum en $x = 1$ : $f(1) = e^1/1 = e$. Sur $]-\infty, 0[$ : $f' < 0$ partout (puisque $x - 1 < 0$ pour $x < 0$), donc $f$ décroît strictement vers $-\infty$ (car $e^x/x \to 0^-$ quand $x \to -\infty$ et $e^x/x \to -\infty$ quand $x \to 0^-$).",
        points: 2,
      ),
    ],
    finalAnswer: r"Minimum local sur $]0, +\infty[$ en $x = 1$, valant $e \approx 2{,}718$.",
    gradingNotes: r"Dérivée (3 pts) + signe (2 pts) + minimum (2 pts).",
    tips: [r"Pour les fonctions définies sur $\mathbb{R}^*$, toujours étudier les deux branches séparément : $]-\infty, 0[$ et $]0, +\infty[$."],
  ),

  // Q7 — MCQ lim x e^{-x} en +infty
  _ans(
    steps: [
      _step(
        r"**Forme indéterminée $\infty \cdot 0$.** Quand $x \to +\infty$, $x \to +\infty$ et $e^{-x} \to 0$. Forme indéterminée $\infty \cdot 0$. On réécrit : $x e^{-x} = \dfrac{x}{e^x}$, ce qui devient une forme $\infty / \infty$ — où s'applique la **croissance comparée**.",
        points: 2,
      ),
      _step(
        r"**Théorème de croissance comparée.** Pour tout $\alpha > 0$, $\dfrac{x^\alpha}{e^x} \to 0$ quand $x \to +\infty$ : l'exponentielle l'emporte sur toute puissance polynomiale. Avec $\alpha = 1$, $\dfrac{x}{e^x} \to 0$. Réponse **A : 0**.",
        points: 2,
      ),
    ],
    finalAnswer: r"A — $0$.",
    gradingNotes: r"Réécriture en $x/e^x$ (2 pts) + croissance comparée (2 pts).",
    tips: [r"Hiérarchie des croissances à l'infini : $\ln x \ll x^\alpha \ll e^{\beta x}$ (pour tous $\alpha, \beta > 0$). Mémoriser cette hiérarchie résout 90% des limites en $+\infty$."],
  ),

  // Q8 — dé équilibré, E(X) et V(X)
  _ans(
    steps: [
      _step(
        r"**Espérance d'un dé équilibré.** $X$ prend les valeurs 1 à 6 avec probabilité 1/6 chacune. $E(X) = \sum_{k=1}^{6} k \cdot \dfrac{1}{6} = \dfrac{1 + 2 + 3 + 4 + 5 + 6}{6} = \dfrac{21}{6} = 3{,}5$. C'est la moyenne arithmétique des valeurs équiprobables, située entre 3 et 4 (car 6 valeurs).",
        points: 2,
      ),
      _step(
        r"**Calcul de $E(X^2)$.** $E(X^2) = \sum_{k=1}^{6} k^2 \cdot \dfrac{1}{6} = \dfrac{1 + 4 + 9 + 16 + 25 + 36}{6} = \dfrac{91}{6}$.",
        points: 2,
      ),
      _step(
        r"**Variance via König-Huygens.** $V(X) = E(X^2) - E(X)^2 = \dfrac{91}{6} - (3{,}5)^2 = \dfrac{91}{6} - \dfrac{49}{4}$. Mise au même dénominateur (12) : $V(X) = \dfrac{182}{12} - \dfrac{147}{12} = \dfrac{35}{12} \approx 2{,}92$.",
        points: 3,
      ),
    ],
    finalAnswer: r"$E(X) = 3{,}5$, $V(X) = 35/12 \approx 2{,}92$.",
    gradingNotes: r"Espérance (2 pts) + $E(X^2)$ (2 pts) + variance (3 pts).",
  ),

  // Q9 — PGCD(156, 132) Euclide + Bézout
  _ans(
    steps: [
      _step(
        r"**Algorithme d'Euclide.** Divisions successives : $156 = 132 \cdot 1 + 24$, $132 = 24 \cdot 5 + 12$, $24 = 12 \cdot 2 + 0$. Le dernier reste non nul est 12, donc $\mathrm{pgcd}(156, 132) = 12$.",
        points: 3,
        widgetSlug: "euclid_visualizer",
        widgetConfig: {"a": 156, "b": 132},
      ),
      _step(
        r"**Remontée de Bézout.** Reprendre les divisions à l'envers. De la 2e : $12 = 132 - 24 \cdot 5$. Substituer $24 = 156 - 132$ : $12 = 132 - (156 - 132) \cdot 5 = 132 - 5 \cdot 156 + 5 \cdot 132 = 6 \cdot 132 - 5 \cdot 156$. Donc $a = -5$, $b = 6$ conviennent : $156 \cdot (-5) + 132 \cdot 6 = 12$.",
        points: 3,
      ),
    ],
    finalAnswer: r"$\mathrm{pgcd}(156, 132) = 12$. Identité de Bézout : $156 \cdot (-5) + 132 \cdot 6 = 12$.",
    gradingNotes: r"Euclide (3 pts) + remontée de Bézout (3 pts).",
    tips: [r"Vérification rapide : $156/12 = 13$, $132/12 = 11$, et $\mathrm{pgcd}(13, 11) = 1$ — les quotients par le pgcd sont premiers entre eux."],
  ),

  // Q10 — y'' + 9y = 0, y(0) = 2, y'(0) = 6
  _ans(
    steps: [
      _step(
        r"**Identification.** $y'' + 9y = 0$ est de la forme $y'' + \omega^2 y = 0$ avec $\omega = 3$. Solution générale : $y(x) = A\cos(3x) + B\sin(3x)$, avec $A, B \in \mathbb{R}$ à déterminer.",
        points: 2,
      ),
      _step(
        r"**Première condition initiale.** $y(0) = A\cos 0 + B\sin 0 = A$. La condition $y(0) = 2$ donne $A = 2$.",
        points: 1,
      ),
      _step(
        r"**Seconde condition initiale (dérivée).** $y'(x) = -3A\sin(3x) + 3B\cos(3x)$. $y'(0) = 3B$. La condition $y'(0) = 6$ donne $3B = 6$, soit $B = 2$.",
        points: 2,
      ),
      _step(
        r"**Solution finale.** $y(x) = 2\cos(3x) + 2\sin(3x)$. On peut aussi l'écrire sous la forme amplitude-phase : $y(x) = 2\sqrt{2} \cos(3x - \pi/4)$, où $2\sqrt{2}$ est l'amplitude maximale et $\pi/4$ le déphasage.",
        points: 2,
      ),
    ],
    finalAnswer: r"$y(x) = 2\cos(3x) + 2\sin(3x) = 2\sqrt{2}\cos(3x - \pi/4)$.",
    gradingNotes: r"Solution générale (2 pts) + première condition (1 pt) + dérivée + seconde condition (2 pts) + écriture finale (2 pts).",
  ),

  // ====== SMA Math 2024 rattrapage (paper 2, IDs 11-20) ======

  _ans(steps: [
    _step(
      r"**Forme $0 \cdot (-\infty)$.** Quand $x \to 0^+$, $x \to 0$ et $\ln x \to -\infty$. Forme indéterminée $0 \cdot (-\infty)$. On réécrit : $x \ln x = \dfrac{\ln x}{1/x}$, ce qui devient $\dfrac{-\infty}{+\infty}$.",
      points: 1,
    ),
    _step(
      r"**Croissance comparée.** Pour tout $\alpha > 0$, $\lim_{x \to 0^+} x^\alpha \ln x = 0$ — la puissance positive l'emporte sur le logarithme. Avec $\alpha = 1$ : $x \ln x \to 0$ en $0^+$.",
      points: 2,
    ),
  ], finalAnswer: r"$\lim_{x\to 0^+} x \ln x = 0$.", gradingNotes: r"Identification (1 pt) + croissance comparée (2 pts).", tips: [r"Variantes utiles : $\lim_{x\to+\infty} \dfrac{\ln x}{x^\alpha} = 0$, $\lim_{x\to 0^+} x^\alpha \ln x = 0$, $\lim_{x\to+\infty} \dfrac{x^\alpha}{e^x} = 0$."]),

  _ans(steps: [
    _step(
      r"**Conditions de validité.** $\ln(x+1)$ exige $x > -1$ ; $\ln(x-1)$ exige $x > 1$. Domaine commun : $x > 1$. Toute solution doit être dans cet intervalle.",
      points: 1,
      mistake: r"L'oubli du domaine est la cause #1 d'erreurs sur les équations logarithmiques. Toujours commencer par lui.",
    ),
    _step(
      r"**Combinaison des logs.** Sur $D = ]1, +\infty[$, propriété fondamentale du logarithme : $\ln a + \ln b = \ln(ab)$. Donc $\ln(x+1) + \ln(x-1) = \ln((x+1)(x-1)) = \ln(x^2 - 1)$ (identité remarquable).",
      points: 2,
    ),
    _step(
      r"**Résolution.** L'équation devient $\ln(x^2 - 1) = \ln 3$. Comme $\ln$ est strictement croissante (donc injective), cela équivaut à $x^2 - 1 = 3$, soit $x^2 = 4$, donc $x = 2$ ou $x = -2$. Vérification dans le domaine : seul $x = 2 \in ]1, +\infty[$ convient.",
      points: 2,
    ),
  ], finalAnswer: r"$x = 2$.", gradingNotes: r"Domaine (1 pt) + propriété du log (2 pts) + résolution + filtrage par domaine (2 pts).", tips: [r"$\ln$ est une bijection croissante de $]0, +\infty[$ sur $\mathbb{R}$ : on peut « simplifier » de part et d'autre, mais seulement après avoir vérifié que tout existe."]),

  _ans(steps: [
    _step(
      r"**Dérivée.** $f(x) = e^x - x$, $f'(x) = e^x - 1$.",
      points: 2,
    ),
    _step(
      r"**Signe et variations.** $e^x - 1 \ge 0 \Leftrightarrow e^x \ge 1 \Leftrightarrow x \ge 0$. Donc $f' < 0$ pour $x < 0$ (décroissante), $f' > 0$ pour $x > 0$ (croissante). Minimum en $x = 0$ : $f(0) = e^0 - 0 = 1$.",
      points: 2,
    ),
    _step(
      r"**Limites.** En $-\infty$ : $e^x \to 0$ et $-x \to +\infty$, donc $f(x) \to +\infty$. En $+\infty$ : $e^x \to +\infty$ et $-x \to -\infty$, mais croissance comparée — l'exponentielle gagne — donc $f(x) \to +\infty$.",
      points: 2,
    ),
  ], finalAnswer: r"Minimum global en $x = 0$, $f(0) = 1$. $f(x) \ge 1$ partout.", gradingNotes: r"Dérivée (2 pts) + signe + min (2 pts) + limites (2 pts).", tips: [r"L'inégalité $e^x \ge 1 + x$ pour tout $x \in \mathbb{R}$ est précisément ce que cet exercice démontre : la tangente en 0 est la droite $y = 1 + x$, et l'exponentielle est convexe (au-dessus de ses tangentes)."]),

  _ans(steps: [
    _step(
      r"**Linéarisation de $\sin^2 x$.** L'identité trigonométrique $\sin^2 x = \dfrac{1 - \cos(2x)}{2}$ transforme un carré en somme — ce qui rend la primitive immédiate.",
      points: 2,
    ),
    _step(
      r"**Calcul.** $\int_0^\pi \sin^2 x \, dx = \int_0^\pi \dfrac{1 - \cos(2x)}{2} dx = \dfrac{1}{2}\bigl[x - \dfrac{\sin(2x)}{2}\bigr]_0^\pi = \dfrac{1}{2}(\pi - 0) = \dfrac{\pi}{2}$.",
      points: 3,
    ),
  ], finalAnswer: r"$\int_0^\pi \sin^2 x \, dx = \dfrac{\pi}{2}$.", gradingNotes: r"Linéarisation (2 pts) + calcul (3 pts).", tips: [r"Linéarisations utiles : $\sin^2 = (1-\cos 2x)/2$, $\cos^2 = (1+\cos 2x)/2$, $\sin a \cos a = \sin(2a)/2$."]),

  _ans(steps: [
    _step(
      r"**Module.** $z = -1 + i\sqrt{3}$. $|z| = \sqrt{(-1)^2 + (\sqrt{3})^2} = \sqrt{1 + 3} = 2$.",
      points: 2,
    ),
    _step(
      r"**Argument.** $\cos\theta = -1/2$ et $\sin\theta = \sqrt{3}/2$. Le point est dans le 2e quadrant (Re < 0, Im > 0). La référence $\cos\theta = -1/2$, $\sin\theta = \sqrt{3}/2$ correspond à $\theta = 2\pi/3$ (mod $2\pi$).",
      points: 2,
    ),
    _step(
      r"**Forme exponentielle.** $z = 2 e^{i \cdot 2\pi/3}$. Vérification : $2(\cos(2\pi/3) + i\sin(2\pi/3)) = 2(-1/2 + i\sqrt{3}/2) = -1 + i\sqrt{3}$ ✓.",
      points: 2,
      widgetSlug: "complex_plane",
      widgetConfig: {"real": -1.0, "imaginary": 1.732},
    ),
  ], finalAnswer: r"$z = 2 e^{i \cdot 2\pi/3}$.", gradingNotes: r"Module (2 pts) + argument avec quadrant (2 pts) + écriture finale (2 pts).", tips: [r"Pour trouver l'argument, partir de $\cos\theta = a/r$ et $\sin\theta = b/r$, puis se servir du quadrant pour lever l'ambiguïté entre $\theta$ et $-\theta$ ou $\pi - \theta$."]),

  _ans(steps: [
    _step(
      r"**Reconnaissance de la primitive.** $(\arctan x)' = \dfrac{1}{1 + x^2}$ — c'est une formule fondamentale à mémoriser. Donc une primitive de $\dfrac{1}{1+x^2}$ est $\arctan x + C$. Réponse **A**.",
      points: 3,
    ),
  ], finalAnswer: r"A — $\arctan x$.", gradingNotes: r"Identification (3 pts).", tips: [r"Tableau des primitives à connaître : $\int \dfrac{1}{1+x^2} dx = \arctan x$, $\int \dfrac{1}{\sqrt{1-x^2}} dx = \arcsin x$, $\int \dfrac{1}{x} dx = \ln|x|$."]),

  _ans(steps: [
    _step(
      r"**Dérivée par produit.** $f(x) = x^2 \ln x$, $u = x^2$, $v = \ln x$, $u' = 2x$, $v' = 1/x$. Formule : $f'(x) = u'v + uv' = 2x \ln x + x^2 \cdot \dfrac{1}{x} = 2x \ln x + x = x(2\ln x + 1)$.",
      points: 3,
    ),
    _step(
      r"**Étude du signe.** Sur $]0, +\infty[$, $x > 0$ donc le signe de $f'$ est celui de $2\ln x + 1$. $2\ln x + 1 = 0 \Leftrightarrow \ln x = -1/2 \Leftrightarrow x = e^{-1/2} = 1/\sqrt{e}$.",
      points: 2,
    ),
    _step(
      r"**Variations et minimum.** $f' < 0$ pour $x < 1/\sqrt{e}$, $f' > 0$ pour $x > 1/\sqrt{e}$. Donc $f$ admet un minimum en $x = 1/\sqrt{e}$, $f(1/\sqrt{e}) = (1/\sqrt{e})^2 \cdot \ln(1/\sqrt{e}) = (1/e)(-1/2) = -1/(2e) \approx -0{,}184$.",
      points: 2,
    ),
  ], finalAnswer: r"Minimum en $x = 1/\sqrt{e}$ valant $-1/(2e)$.", gradingNotes: r"Dérivée (3 pts) + signe via $\ln$ (2 pts) + minimum (2 pts).", tips: [r"Dérivées de produit avec $\ln$ : factoriser $x^k$ dehors fait apparaître un terme en $\ln x + $ constante, dont le signe est facile à étudier."]),

  _ans(steps: [
    _step(
      r"**Combinaisons et tirage.** On choisit 2 valets parmi les 4 du jeu : $\binom{4}{2} = 6$ façons. On choisit 3 cartes non-valets parmi $32 - 4 = 28$ cartes : $\binom{28}{3} = \dfrac{28 \cdot 27 \cdot 26}{6} = 3276$.",
      points: 2,
    ),
    _step(
      r"**Multiplication et total.** Toute main de 5 cartes avec exactement 2 valets s'obtient en associant une combinaison de 2 valets et une combinaison de 3 non-valets, indépendamment. Total : $6 \cdot 3276 = 19656$ mains.",
      points: 2,
    ),
    _step(
      r"**Vérification cohérence.** Le total des mains de 5 cartes parmi 32 est $\binom{32}{5} = 201376$. La probabilité d'avoir exactement 2 valets vaut $19656/201376 \approx 0{,}098$, soit ~9,8%. Ordre de grandeur cohérent.",
      points: 1,
    ),
  ], finalAnswer: r"$19\,656$ mains.", gradingNotes: r"Combinaisons (2 pts) + multiplication (2 pts) + cohérence (1 pt).", tips: [r"Pour les comptages avec « exactement $k$ d'un type », factoriser : $\binom{a}{k} \cdot \binom{n-a}{m-k}$ où $a$ = effectif du type recherché, $m$ = taille du tirage."]),

  _ans(steps: [
    _step(
      r"**Solution homogène.** L'équation $y' + 2y = e^{-2x}$ a pour homogène $y' + 2y = 0$, soit $y' = -2y$, donnant $y_h = K e^{-2x}$.",
      points: 2,
    ),
    _step(
      r"**Solution particulière (méthode du second membre résonant).** Le second membre $e^{-2x}$ est une solution de l'homogène (résonance), donc on cherche $y_p$ sous la forme $y_p = a x e^{-2x}$. Calcul : $y_p' = a e^{-2x} - 2ax e^{-2x}$, et $y_p' + 2 y_p = a e^{-2x} - 2ax e^{-2x} + 2ax e^{-2x} = a e^{-2x}$. Pour avoir $y_p' + 2y_p = e^{-2x}$, il faut $a = 1$.",
      points: 2,
    ),
    _step(
      r"**Solution générale.** Solution complète = $y_h + y_p = K e^{-2x} + x e^{-2x} = (K + x) e^{-2x}$.",
      points: 2,
    ),
  ], finalAnswer: r"$y(x) = (K + x) e^{-2x}$.", gradingNotes: r"Homogène (2 pts) + ansatz résonant + détermination de $a$ (2 pts) + solution générale (2 pts).", tips: [r"Pour $y' + ay = e^{-ax}$ (résonance), l'ansatz est $y_p = bx e^{-ax}$ — on multiplie par $x$ pour casser la résonance."]),

  _ans(steps: [
    _step(
      r"**Distance via les affixes.** Pour deux points $A$ et $B$ d'affixes $z_A$ et $z_B$, la distance $AB = |z_B - z_A|$. C'est la formule fondamentale qui relie géométrie et complexes.",
      points: 1,
    ),
    _step(
      r"**Calcul.** $z_B - z_A = (5 - i) - (2 + 3i) = 3 - 4i$. $|3 - 4i| = \sqrt{9 + 16} = \sqrt{25} = 5$. Donc $AB = 5$.",
      points: 3,
    ),
  ], finalAnswer: r"$AB = 5$.", gradingNotes: r"Formule + numérique (4 pts).", tips: [r"Le triangle 3-4-5 est l'archétype du triangle rectangle pythagoricien — apparaît partout dans les exos de complexes."]),

  // ====== SMA Math 2023 normale (paper 3, IDs 21-30) ======

  _ans(steps: [
    _step(
      r"**Dérivée par produit avec carré.** $f(x) = (x-1)^2 (x+2)$. On dérive : $f'(x) = 2(x-1)(x+2) + (x-1)^2 \cdot 1 = (x-1)[2(x+2) + (x-1)] = (x-1)(2x + 4 + x - 1) = (x-1)(3x+3) = 3(x-1)(x+1)$.",
      points: 3,
    ),
    _step(
      r"**Signe.** $f'(x) = 3(x-1)(x+1)$ : produit de deux facteurs linéaires. Racines $-1$ et $1$. Coefficient dominant positif → $f' > 0$ en dehors $]-1, 1[$, $f' < 0$ entre.",
      points: 2,
    ),
    _step(
      r"**Extrema.** Max local en $x = -1$ : $f(-1) = (-2)^2 \cdot 1 = 4$. Min local en $x = 1$ : $f(1) = 0 \cdot 3 = 0$.",
      points: 2,
    ),
  ], finalAnswer: r"Max local en $x = -1$ ($f = 4$), min local en $x = 1$ ($f = 0$).", gradingNotes: r"Dérivée factorisée (3 pts) + signe (2 pts) + extrema (2 pts)."),

  _ans(steps: [
    _step(
      r"**Limite usuelle.** $\lim_{x \to 0} \dfrac{\ln(1+x)}{x} = 1$ — c'est l'une des limites fondamentales liée à la dérivée de $\ln$ en 1. Équivalent : $\ln(1+x) \sim x$ quand $x \to 0$.",
      points: 3,
    ),
  ], finalAnswer: r"$\lim_{x\to 0} \dfrac{\ln(1+x)}{x} = 1$.", gradingNotes: r"Citation de la limite usuelle (3 pts).", tips: [r"Famille de limites usuelles : $\dfrac{\sin x}{x}\to 1$, $\dfrac{\ln(1+x)}{x}\to 1$, $\dfrac{e^x-1}{x}\to 1$, tous quand $x \to 0$. Toutes traduisent une dérivabilité en 0."]),

  _ans(steps: [
    _step(
      r"**Division euclidienne polynômiale.** $u_n = \dfrac{n^2 + 1}{n+1}$. Effectuer la division : $n^2 + 1 = (n+1)(n-1) + 2$, donc $u_n = (n - 1) + \dfrac{2}{n+1}$.",
      points: 3,
    ),
    _step(
      r"**Comportement à l'infini.** $\dfrac{2}{n+1} \to 0$, donc $u_n \sim n - 1 \to +\infty$. La suite diverge, mais on a un équivalent précis : $u_n - (n-1) \to 0$.",
      points: 2,
    ),
  ], finalAnswer: r"$u_n \to +\infty$, équivalent $\sim n$.", gradingNotes: r"Division (3 pts) + équivalent (2 pts).", tips: [r"Pour les fractions de polynômes à l'infini, la division euclidienne sépare la « partie polynômiale » (équivalent à l'infini) de la « partie résiduelle » (qui tend vers 0)."]),

  _ans(steps: [
    _step(
      r"**Reconnaissance $u'/u$.** L'intégrande $\dfrac{x}{x^2+1}$ vaut $\dfrac{1}{2} \cdot \dfrac{2x}{x^2+1}$, où $2x = (x^2+1)'$. Donc $\dfrac{x}{x^2+1} = \dfrac{1}{2} \cdot \dfrac{u'}{u}$ avec $u = x^2 + 1$. Une primitive est $\dfrac{1}{2} \ln|u| = \dfrac{1}{2} \ln(x^2+1)$.",
      points: 2,
    ),
    _step(
      r"**Évaluation aux bornes.** $\int_0^1 \dfrac{x}{x^2+1} dx = \bigl[\dfrac{1}{2}\ln(x^2+1)\bigr]_0^1 = \dfrac{1}{2}(\ln 2 - \ln 1) = \dfrac{\ln 2}{2}$.",
      points: 3,
    ),
  ], finalAnswer: r"$\int_0^1 \dfrac{x}{x^2+1} dx = \dfrac{\ln 2}{2}$.", gradingNotes: r"Reconnaissance $u'/u$ (2 pts) + évaluation (3 pts).", tips: [r"Patron $u'/u$ → primitive $\ln|u|$. Toujours regarder si le numérateur est (à un facteur près) la dérivée du dénominateur."]),

  _ans(steps: [
    _step(
      r"**Forme exponentielle.** $z_1 = 1 + i$ : $|z_1| = \sqrt{2}$, $\arg z_1 = \pi/4$. Donc $z_1 = \sqrt{2} e^{i\pi/4}$. $z_2 = 1 + i\sqrt{3}$ : $|z_2| = 2$, $\cos\theta = 1/2$, $\sin\theta = \sqrt{3}/2$, donc $\arg z_2 = \pi/3$. $z_2 = 2 e^{i\pi/3}$.",
      points: 3,
    ),
    _step(
      r"**Quotient en forme exponentielle.** $\dfrac{z_1}{z_2} = \dfrac{\sqrt{2} e^{i\pi/4}}{2 e^{i\pi/3}} = \dfrac{\sqrt{2}}{2} e^{i(\pi/4 - \pi/3)}$. Calcul de l'angle : $\pi/4 - \pi/3 = (3\pi - 4\pi)/12 = -\pi/12$. Donc $z_1/z_2 = \dfrac{\sqrt{2}}{2} e^{-i\pi/12}$.",
      points: 3,
    ),
  ], finalAnswer: r"$z_1/z_2 = \dfrac{\sqrt{2}}{2} e^{-i\pi/12}$.", gradingNotes: r"Forme exp des deux complexes (3 pts) + quotient avec différence d'arguments (3 pts).", tips: [r"Pour multiplier ou diviser des complexes, la forme exponentielle est presque toujours plus rapide que la forme algébrique : on multiplie/divise les modules et on ajoute/soustrait les arguments."]),

  _ans(steps: [
    _step(
      r"**Racines $n$-ièmes de l'unité.** Les solutions de $z^n = 1$ sont les $z_k = e^{i k \cdot 2\pi/n}$ pour $k = 0, 1, ..., n-1$ — il y en a exactement $n$, espacées sur le cercle unité. Pour $n = 6$, les angles sont $0, \pi/3, 2\pi/3, \pi, 4\pi/3, 5\pi/3$, soit $k\pi/3$ pour $k = 0, ..., 5$. C'est exactement la liste donnée. Réponse **A**.",
      points: 3,
    ),
  ], finalAnswer: r"A — $z^6 = 1$.", gradingNotes: r"Identification + comptage (3 pts).", tips: [r"Les racines $n$-ièmes de l'unité forment un polygone régulier à $n$ sommets inscrit dans le cercle unité, l'un des sommets en $z = 1$."]),

  _ans(steps: [
    _step(
      r"**Dérivée.** $f(x) = \dfrac{\ln x}{x}$ sur $]0, +\infty[$. Par quotient avec $u = \ln x$, $v = x$, $u' = 1/x$, $v' = 1$ : $f'(x) = \dfrac{(1/x) \cdot x - \ln x \cdot 1}{x^2} = \dfrac{1 - \ln x}{x^2}$.",
      points: 3,
    ),
    _step(
      r"**Signe et extremum.** $x^2 > 0$, donc le signe de $f'$ est celui de $1 - \ln x$. $f' > 0 \Leftrightarrow \ln x < 1 \Leftrightarrow x < e$. Donc $f$ croît sur $]0, e]$, décroît sur $[e, +\infty[$. **Maximum global en $x = e$**, $f(e) = \ln e / e = 1/e$.",
      points: 2,
    ),
  ], finalAnswer: r"Maximum global en $x = e$ valant $1/e$.", gradingNotes: r"Dérivée (3 pts) + signe + max (2 pts).", tips: [r"Cette fonction $(\ln x)/x$ est célèbre — son maximum en $e$ est utile en théorie analytique des nombres (relation avec $\pi(x)$)."]),

  _ans(steps: [
    _step(
      r"**Primitive.** $\int e^{-x} dx = -e^{-x} + C$. Vérification : $(-e^{-x})' = -(-1) e^{-x} = e^{-x}$ ✓.",
      points: 1,
    ),
    _step(
      r"**Évaluation.** $\int_0^1 e^{-x} dx = [-e^{-x}]_0^1 = -e^{-1} + e^0 = 1 - 1/e \approx 1 - 0{,}368 = 0{,}632$.",
      points: 2,
    ),
  ], finalAnswer: r"$\int_0^1 e^{-x} dx = 1 - 1/e \approx 0{,}632$.", gradingNotes: r"Primitive (1 pt) + évaluation (2 pts)."),

  _ans(steps: [
    _step(
      r"**Loi des probabilités totales.** Le tirage se décompose en deux étapes : choix d'urne, puis tirage de boule. Les urnes sont équiprobables : $P(U_1) = P(U_2) = P(U_3) = 1/3$. La proba de tirer rouge sachant l'urne est : $P(R|U_1) = 3/5$, $P(R|U_2) = 1/5$, $P(R|U_3) = 2/4 = 1/2$.",
      points: 2,
    ),
    _step(
      r"**Application.** $P(R) = \sum_i P(U_i) \cdot P(R|U_i) = \dfrac{1}{3}(\dfrac{3}{5} + \dfrac{1}{5} + \dfrac{1}{2}) = \dfrac{1}{3} \cdot \dfrac{6 + 2 + 5}{10} = \dfrac{1}{3} \cdot \dfrac{13}{10} = \dfrac{13}{30}$.",
      points: 3,
    ),
    _step(
      r"**Vérification numérique.** $13/30 \approx 0{,}433$. Cohérent avec une moyenne pondérée des trois probabilités $0{,}6, 0{,}2, 0{,}5$, dont la moyenne arithmétique est environ $0{,}43$. Note : 6/5 + 2/5 + 5/2 mis à 10 = (6+2+5)/10 = 13/10 — l'approximation par moyenne arithmétique fonctionne car les urnes sont équiprobables.",
      points: 2,
    ),
  ], finalAnswer: r"$P(R) = 13/30 \approx 0{,}433$.", gradingNotes: r"Décomposition par urnes + probas conditionnelles (2 pts) + formule des probas totales (3 pts) + cohérence (2 pts).", tips: [r"La formule des probabilités totales : $P(B) = \sum_i P(A_i) P(B|A_i)$ pour $\{A_i\}$ une partition de l'univers. C'est la version probabiliste de « somme pondérée »."]),

  _ans(steps: [
    _step(
      r"**Forme exponentielle de 8.** $8 = 8 e^{i \cdot 0}$ (réel positif, argument 0). Plus généralement, $8 = 8 e^{i \cdot 2k\pi}$ pour tout entier $k$.",
      points: 1,
    ),
    _step(
      r"**Racines cubiques.** Les solutions de $z^3 = 8$ sont $z_k = 8^{1/3} e^{i \cdot 2k\pi/3}$ pour $k = 0, 1, 2$. $8^{1/3} = 2$. Calculs : $z_0 = 2$, $z_1 = 2 e^{i 2\pi/3} = 2(-1/2 + i\sqrt{3}/2) = -1 + i\sqrt{3}$, $z_2 = 2 e^{i 4\pi/3} = -1 - i\sqrt{3}$ (conjugué de $z_1$).",
      points: 3,
    ),
    _step(
      r"**Vérification.** Somme des racines : $2 + (-1 + i\sqrt{3}) + (-1 - i\sqrt{3}) = 0$. **Toujours 0** pour les racines $n$-ièmes d'un nombre — c'est le centre de gravité du polygone régulier inscrit, qui coïncide avec l'origine quand $n \ge 2$.",
      points: 2,
    ),
  ], finalAnswer: r"$z = 2$, $-1 + i\sqrt{3}$, $-1 - i\sqrt{3}$.", gradingNotes: r"Forme exp (1 pt) + racines (3 pts) + vérification (2 pts).", tips: [r"Pour $z^n = a$ avec $a = re^{i\theta}$, les $n$ racines sont $r^{1/n} e^{i(\theta + 2k\pi)/n}$, $k = 0, ..., n-1$. Espacées de $2\pi/n$ sur un cercle de rayon $r^{1/n}$."]),

  // ====== SMA Math 2023 rattrapage (paper 4, IDs 31-40) ======

  _ans(steps: [
    _step(
      r"**Croissance comparée.** Quand $x \to +\infty$, $\ln x$ et $\sqrt{x}$ tendent tous deux vers $+\infty$. Mais le théorème de croissance comparée dit : pour tout $\alpha > 0$, $(\ln x)^k$ croît plus lentement que $x^\alpha$. Avec $k = 2$, $\alpha = 1/2$ : $(\ln x)^2 / \sqrt{x} \to 0$. Tous les polynômes positifs battent toutes les puissances de $\ln$.",
      points: 3,
    ),
  ], finalAnswer: r"$0$.", gradingNotes: r"Croissance comparée (3 pts).", tips: [r"Hiérarchie ultra-importante : $(\ln x)^k \ll x^\alpha \ll e^{\beta x}$ pour tous $k, \alpha, \beta > 0$ à l'infini."]),

  _ans(steps: [
    _step(
      r"**Substitution $X = e^x$.** L'équation $e^{2x} - 5e^x + 6 = 0$ devient, avec $X = e^x > 0$ : $X^2 - 5X + 6 = 0$. Trinôme classique.",
      points: 1,
    ),
    _step(
      r"**Résolution du trinôme.** $\Delta = 25 - 24 = 1$, $X = (5 \pm 1)/2$, soit $X = 2$ ou $X = 3$. Les deux sont $> 0$, donc admissibles.",
      points: 2,
    ),
    _step(
      r"**Retour à $x$.** $e^x = 2 \Leftrightarrow x = \ln 2$ ; $e^x = 3 \Leftrightarrow x = \ln 3$. Donc deux solutions : $x = \ln 2$ et $x = \ln 3$.",
      points: 2,
    ),
  ], finalAnswer: r"$x = \ln 2$ ou $x = \ln 3$.", gradingNotes: r"Substitution (1 pt) + trinôme (2 pts) + retour à $x$ (2 pts).", tips: [r"Quand on voit une combinaison de $e^{kx}$ avec $k$ entier, poser $X = e^x$ ramène souvent à un polynôme en $X$ — méthode systématique."]),

  _ans(steps: [
    _step(
      r"**Domaine et dérivée.** $f(x) = x - 2\sqrt{x}$ est définie sur $[0, +\infty[$. Pour $x > 0$, $f'(x) = 1 - \dfrac{1}{\sqrt{x}}$. En 0, la dérivée n'existe pas (tangente verticale), mais $f$ est continue.",
      points: 2,
    ),
    _step(
      r"**Signe.** $f'(x) > 0 \Leftrightarrow \dfrac{1}{\sqrt{x}} < 1 \Leftrightarrow \sqrt{x} > 1 \Leftrightarrow x > 1$. Donc $f' < 0$ sur $]0, 1[$, $f' > 0$ sur $]1, +\infty[$. Minimum en $x = 1$.",
      points: 2,
    ),
    _step(
      r"**Valeur du minimum.** $f(1) = 1 - 2\sqrt{1} = 1 - 2 = -1$. Donc $f \ge -1$ sur tout $[0, +\infty[$.",
      points: 2,
    ),
  ], finalAnswer: r"Minimum global en $x = 1$, $f(1) = -1$.", gradingNotes: r"Dérivée (2 pts) + signe (2 pts) + minimum (2 pts)."),

  _ans(steps: [
    _step(
      r"**IPP avec $u = \ln x$, $dv = dx$.** $u' = 1/x$, $v = x$. Formule : $\int \ln x \, dx = x \ln x - \int x \cdot \dfrac{1}{x} \, dx = x \ln x - x + C$.",
      points: 3,
    ),
    _step(
      r"**Évaluation.** $\int_1^e \ln x \, dx = [x \ln x - x]_1^e = (e \cdot 1 - e) - (1 \cdot 0 - 1) = 0 - (-1) = 1$.",
      points: 2,
    ),
  ], finalAnswer: r"$\int_1^e \ln x \, dx = 1$.", gradingNotes: r"IPP avec choix correct (3 pts) + évaluation (2 pts).", tips: [r"Astuce : pour intégrer $\ln x$, IPP avec $u = \ln x$ et $dv = dx$. La primitive de $\ln$ est $x\ln x - x$, à mémoriser."]),

  _ans(steps: [
    _step(
      r"**Multiplication par le conjugué.** $z = \dfrac{1+i}{2-i} \cdot \dfrac{2+i}{2+i} = \dfrac{(1+i)(2+i)}{(2-i)(2+i)}$. Le dénominateur devient $4 - i^2 = 5$ (réel).",
      points: 2,
    ),
    _step(
      r"**Développement du numérateur.** $(1+i)(2+i) = 2 + i + 2i + i^2 = 2 + 3i - 1 = 1 + 3i$. Donc $z = \dfrac{1 + 3i}{5} = \dfrac{1}{5} + \dfrac{3}{5} i$.",
      points: 2,
    ),
  ], finalAnswer: r"$z = \dfrac{1}{5} + \dfrac{3}{5} i$.", gradingNotes: r"Multiplication par le conjugué (2 pts) + développement (2 pts)."),

  _ans(steps: [
    _step(
      r"**TVI et signe constant.** Si $f$ est continue sur $[a, b]$ et ne s'annule pas, alors par le TVI elle ne peut pas changer de signe (sinon, par TVI sur $[a,b]$, elle s'annulerait quelque part). Donc $f$ garde un signe constant. Réponse **B**.",
      points: 3,
    ),
  ], finalAnswer: r"B — garde un signe constant.", gradingNotes: r"Argument TVI (3 pts).", tips: [r"Conséquence pratique : pour montrer qu'une fonction continue est positive (ou négative) sur un intervalle, il suffit de montrer (1) qu'elle ne s'annule pas, (2) qu'elle est positive (resp. négative) en un seul point."]),

  _ans(steps: [
    _step(
      r"**Recherche du point fixe.** $u_{n+1} = (u_n + 3) \cdot 1/2 + 1$ ... attention, l'énoncé donne $u_{n+1} = u_n/2 + 1$. Point fixe : $\ell = \ell/2 + 1 \Leftrightarrow \ell/2 = 1 \Leftrightarrow \ell = 2$.",
      points: 2,
    ),
    _step(
      r"**Suite auxiliaire géométrique.** Posons $v_n = u_n - 2$. Alors $v_{n+1} = u_{n+1} - 2 = u_n/2 + 1 - 2 = u_n/2 - 1 = (u_n - 2)/2 = v_n / 2$. Donc $(v_n)$ est géométrique de raison $1/2$, premier terme $v_0 = u_0 - 2 = -2$.",
      points: 2,
    ),
    _step(
      r"**Forme explicite et limite.** $v_n = -2 \cdot (1/2)^n$, donc $u_n = 2 - 2/2^n = 2(1 - 1/2^n)$. Quand $n \to +\infty$, $1/2^n \to 0$, donc $u_n \to 2$. La suite converge vers son point fixe.",
      points: 3,
    ),
  ], finalAnswer: r"$u_n = 2(1 - 1/2^n)$, $\lim u_n = 2$.", gradingNotes: r"Point fixe (2 pts) + suite auxiliaire (2 pts) + forme explicite + limite (3 pts).", tips: [r"Technique standard : pour suite affine $u_{n+1} = au_n + b$ avec $a \ne 1$, point fixe $\ell = b/(1-a)$, suite auxiliaire $v_n = u_n - \ell$ est géométrique de raison $a$."]),

  _ans(steps: [
    _step(
      r"**Anagrammes avec lettres répétées.** MISSISSIPPI a 11 lettres : M (1), I (4), S (4), P (2). Le nombre d'anagrammes est $\dfrac{11!}{1! \cdot 4! \cdot 4! \cdot 2!}$.",
      points: 2,
    ),
    _step(
      r"**Calcul.** $11! = 39\,916\,800$. $4! = 24$, $4! \cdot 4! = 576$, $\cdot 2! = 1152$. $11!/1152 = 34\,650$.",
      points: 2,
    ),
  ], finalAnswer: r"$34\,650$ anagrammes.", gradingNotes: r"Formule (2 pts) + calcul (2 pts).", tips: [r"Formule générale : nombre d'anagrammes d'un mot avec $n_i$ exemplaires de la lettre $i$, total $N$ lettres : $N!/(n_1! n_2! \dots)$."]),

  _ans(steps: [
    _step(
      r"**Solution homogène.** $y' - 3y = 0 \Rightarrow y' = 3y \Rightarrow y_h = K e^{3x}$.",
      points: 2,
    ),
    _step(
      r"**Solution particulière (résonance).** Le second membre $e^{3x}$ est solution de l'homogène : résonance. Ansatz $y_p = ax e^{3x}$. Calcul : $y_p' = a e^{3x} + 3ax e^{3x}$. Substitution : $y_p' - 3y_p = a e^{3x} + 3ax e^{3x} - 3ax e^{3x} = a e^{3x}$. Pour avoir $a e^{3x} = e^{3x}$, $a = 1$.",
      points: 3,
    ),
    _step(
      r"**Solution générale.** $y(x) = (K + x) e^{3x}$.",
      points: 2,
    ),
  ], finalAnswer: r"$y(x) = (K + x) e^{3x}$.", gradingNotes: r"Homogène (2 pts) + particulière par ansatz résonant (3 pts) + générale (2 pts)."),

  _ans(steps: [
    _step(
      r"**Algorithme d'Euclide.** $1071 = 462 \cdot 2 + 147$, $462 = 147 \cdot 3 + 21$, $147 = 21 \cdot 7 + 0$. Dernier reste non nul : 21. $\mathrm{pgcd}(1071, 462) = 21$.",
      points: 4,
      widgetSlug: "euclid_visualizer",
      widgetConfig: {"a": 1071, "b": 462},
    ),
  ], finalAnswer: r"$\mathrm{pgcd}(1071, 462) = 21$.", gradingNotes: r"Euclide (4 pts).", tips: [r"Vérification : $1071 = 21 \cdot 51$, $462 = 21 \cdot 22$, $\mathrm{pgcd}(51, 22)$ ? $51 = 22 \cdot 2 + 7$, $22 = 7 \cdot 3 + 1$, $7 = 1 \cdot 7$. $\mathrm{pgcd}(51, 22) = 1$ — cohérent."]),

  // ====== SMA PC 2024 normale (paper 5, IDs 41-50) ======

  _ans(steps: [
    _step(
      r"**Décomposition du mouvement.** Le projectile est lancé horizontalement depuis une falaise de 50 m. Pas de vitesse verticale initiale ($v_{0y} = 0$), juste la chute libre verticale et un mouvement uniforme horizontal. **Sur l'axe vertical** : $y(t) = h - \dfrac{1}{2} g t^2$ (origine au sol, $h = 50$ m). **Sur l'axe horizontal** : $x(t) = v_0 t = 20 t$.",
      points: 2,
      widgetSlug: "projectile",
      widgetConfig: {"v0": 20.0, "angle": 0.0},
    ),
    _step(
      r"**Temps de chute.** L'objet touche le sol quand $y(t) = 0$ : $h = \dfrac{1}{2} g t^2$, soit $t = \sqrt{2h/g} = \sqrt{100/10} = \sqrt{10} \approx 3{,}16$ s.",
      points: 2,
    ),
    _step(
      r"**Distance horizontale.** Pendant ce temps, le projectile se déplace horizontalement à $v_0 = 20$ m/s sans frottement. $d = v_0 \cdot t = 20 \cdot 3{,}16 \approx 63{,}25$ m.",
      points: 3,
    ),
  ], finalAnswer: r"$d \approx 63{,}25$ m.", gradingNotes: r"Décomposition + équations horaires (2 pts) + temps de chute (2 pts) + distance (3 pts).", tips: [r"En tir horizontal, les axes sont **indépendants** : la chute verticale est la même que pour un objet simplement lâché ; la vitesse horizontale est constante."]),

  _ans(steps: [
    _step(
      r"**Formule du pendule simple.** $T = 2\pi\sqrt{L/g}$ pour les petites oscillations. Application : $L/g = 0{,}25/9{,}81 \approx 0{,}0255$, $\sqrt{L/g} \approx 0{,}1597$. $T = 2\pi \cdot 0{,}1597 \approx 1{,}004$ s.",
      points: 3,
      widgetSlug: "pendulum_lab",
      widgetConfig: {"length": 0.25},
    ),
  ], finalAnswer: r"$T \approx 1{,}004$ s ≈ 1 s.", gradingNotes: r"Formule + numérique (3 pts).", tips: [r"Repère : un pendule de 25 cm a une période d'environ 1 s. Le pendule à seconde (T = 2 s) fait environ 1 m."]),

  _ans(steps: [
    _step(
      r"**Conversion d'unités et calcul.** Vitesse : $72$ km/h = $72/3{,}6 = 20$ m/s. Énergie cinétique : $E_c = \dfrac{1}{2} m v^2 = 0{,}5 \cdot 1500 \cdot 20^2 = 0{,}5 \cdot 1500 \cdot 400 = 300\,000$ J = 300 kJ.",
      points: 4,
    ),
  ], finalAnswer: r"$E_c = 300$ kJ.", gradingNotes: r"Conversion + formule + numérique (4 pts).", tips: [r"À 100 km/h, une voiture de 1500 kg a $E_c = 0{,}5 \cdot 1500 \cdot 27{,}8^2 \approx 580$ kJ — équivalent énergétique d'une grenade."]),

  _ans(steps: [
    _step(
      r"**Constante de temps.** $\tau = RC = 5 \cdot 10^3 \cdot 200 \cdot 10^{-6} = 10^{-3} \cdot 10^3 = 1$ s.",
      points: 1,
    ),
    _step(
      r"**Charge à $\tau$.** $u_C(\tau) = E(1 - e^{-1}) = 24 \cdot 0{,}632 \approx 15{,}17$ V.",
      points: 2,
      widgetSlug: "capacitor_charge",
      widgetConfig: {"R": 5000.0, "C": 0.0002, "E": 24.0},
    ),
    _step(
      r"**Charge à $3\tau$.** $u_C(3\tau) = E(1 - e^{-3}) = 24 \cdot 0{,}9502 \approx 22{,}80$ V (95% de $E$).",
      points: 2,
    ),
  ], finalAnswer: r"$\tau = 1$ s, $u_C(\tau) \approx 15{,}2$ V, $u_C(3\tau) \approx 22{,}8$ V.", gradingNotes: r"$\tau$ (1 pt) + charge à $\tau$ (2 pts) + charge à $3\tau$ (2 pts)."),

  _ans(steps: [
    _step(
      r"**Loi de décroissance.** Au bout de $n$ demi-vies, l'activité est divisée par $2^n$ par rapport à l'activité initiale. Pour la diviser par 32, il faut $2^n = 32$, soit $n = 5$ demi-vies.",
      points: 1,
    ),
    _step(
      r"**Calcul du temps.** $5 \cdot T_{1/2} = 5 \cdot 8 = 40$ jours.",
      points: 3,
    ),
  ], finalAnswer: r"40 jours.", gradingNotes: r"Loi $A/A_0 = 1/2^n$ (1 pt) + calcul (3 pts)."),

  _ans(steps: [
    _step(
      r"**Champ uniforme entre plaques.** $E = U/d = 200/(2 \cdot 10^{-3}) = 10^5$ V/m.",
      points: 3,
      widgetSlug: "e_field_uniform",
      widgetConfig: {"voltage": 200.0, "distance": 0.002},
    ),
  ], finalAnswer: r"$E = 10^5$ V/m.", gradingNotes: r"Formule + numérique (3 pts)."),

  _ans(steps: [
    _step(
      r"**Modulation d'amplitude.** AM = Amplitude Modulation. On module l'amplitude d'une porteuse haute fréquence par le signal informatif basse fréquence. La fréquence et la phase de la porteuse restent inchangées. Réponse **B**.",
      points: 2,
      widgetSlug: "am_modulation",
      widgetConfig: {},
    ),
  ], finalAnswer: r"B — l'amplitude.", gradingNotes: r"Identification (2 pts).", tips: [r"AM (Amplitude Modulation) vs FM (Frequency Modulation) : AM module l'amplitude, FM la fréquence. AM est plus simple mais plus sensible au bruit."]),

  _ans(steps: [
    _step(
      r"**Acide fort totalement dissocié.** Pour un acide fort de concentration $C$, $[H_3O^+] = C$. Ici $C = 0{,}01$ mol/L = $10^{-2}$ mol/L. $pH = -\log(10^{-2}) = 2$.",
      points: 4,
    ),
  ], finalAnswer: r"$pH = 2$.", gradingNotes: r"Dissociation totale + définition (4 pts)."),

  _ans(steps: [
    _step(
      r"**À la demi-équivalence d'un titrage acide faible / base forte.** À ce stade, on a versé exactement la moitié du volume d'équivalence ; la moitié de l'acide $HA$ a été transformée en sa base conjuguée $A^-$. Donc $[HA] = [A^-]$.",
      points: 2,
    ),
    _step(
      r"**Équation de Henderson-Hasselbalch.** $pH = pK_a + \log\dfrac{[A^-]}{[HA]}$. À la demi-équivalence, $[A^-]/[HA] = 1$, donc $\log(1) = 0$, et $pH = pK_a = 4{,}8$.",
      points: 3,
      widgetSlug: "titration_simulator",
      widgetConfig: {"cAcid": 0.1, "cBase": 0.1, "vAcid": 25.0, "pKa": 4.8},
    ),
  ], finalAnswer: r"$pH = pK_a = 4{,}8$.", gradingNotes: r"Demi-équivalence + équilibre (2 pts) + Henderson-Hasselbalch (3 pts).", tips: [r"La demi-équivalence est le point d'inflexion de la courbe de titrage acide faible / base forte — c'est là que le pouvoir tampon est maximum."]),

  _ans(steps: [
    _step(
      r"**Calcul du quotient de réaction.** $Q_r = \dfrac{[HI]^2}{[H_2][I_2]} = \dfrac{(0{,}5)^2}{(0{,}1)(0{,}1)} = \dfrac{0{,}25}{0{,}01} = 25$.",
      points: 3,
    ),
    _step(
      r"**Comparaison à $K$ et sens d'évolution.** $Q_r = 25 < K = 50$. Critère : $Q_r < K$ → le système évolue dans le **sens direct** (formation de plus de produits) pour faire croître $Q_r$ vers $K$.",
      points: 3,
      widgetSlug: "equilibrium_qr_k",
      widgetConfig: {},
    ),
  ], finalAnswer: r"Sens direct (formation de HI).", gradingNotes: r"Calcul de $Q_r$ (3 pts) + comparaison + sens (3 pts).", tips: [r"Critère résumé : $Q_r$ tire vers $K$. Si $Q_r < K$, on produit. Si $Q_r > K$, on consomme. À l'équilibre, $Q_r = K$."]),

  // ====== SMA PC 2023 normale (paper 6, IDs 51-60) ======

  _ans(steps: [
    _step(
      r"**Théorème de l'énergie cinétique.** Sur un plan horizontal, le travail des frottements vaut $W_f = -f \cdot d$ (force opposée au déplacement). Pas d'autre force qui travaille (poids et réaction normale perpendiculaires au déplacement). Donc $\Delta E_c = -fd$.",
      points: 2,
    ),
    _step(
      r"**Bilan énergétique.** L'objet s'arrête : $E_{c,final} = 0$. $E_{c,initial} = \dfrac{1}{2} m v_0^2 = 0{,}5 \cdot 0{,}5 \cdot 16 = 4$ J. $\Delta E_c = 0 - 4 = -4$ J. Donc $-f d = -4$, soit $d = 4/f = 4/2 = 2$ m.",
      points: 4,
    ),
  ], finalAnswer: r"$d = 2$ m.", gradingNotes: r"TEC (2 pts) + bilan + numérique (4 pts).", tips: [r"Pour un freinage, l'énergie cinétique se dissipe en chaleur via les frottements. Distance d'arrêt = $E_c/f$."]),

  _ans(steps: [
    _step(
      r"**Fréquence propre.** $f_0 = \dfrac{1}{2\pi\sqrt{LC}}$. Application : $LC = 0{,}1 \cdot 10^{-6} = 10^{-7}$. $\sqrt{LC} = \sqrt{10^{-7}} \approx 3{,}162 \cdot 10^{-4}$ s.",
      points: 2,
      widgetSlug: "rlc",
      widgetConfig: {"R": 10.0, "L": 0.1, "C": 0.000001},
    ),
    _step(
      r"**Application numérique.** $f_0 = \dfrac{1}{2\pi \cdot 3{,}162 \cdot 10^{-4}} = \dfrac{1}{1{,}987 \cdot 10^{-3}} \approx 503{,}3$ Hz.",
      points: 2,
    ),
  ], finalAnswer: r"$f_0 \approx 503$ Hz.", gradingNotes: r"Formule (2 pts) + numérique (2 pts)."),

  _ans(steps: [
    _step(
      r"**Définition du niveau sonore.** $L = 10 \log(I/I_0)$ avec $I_0 = 10^{-12}$ W/m² (seuil d'audition à 1000 Hz).",
      points: 1,
    ),
    _step(
      r"**Application.** $I/I_0 = 10^{-6}/10^{-12} = 10^6$. $L = 10 \log(10^6) = 10 \cdot 6 = 60$ dB. Correspond au bruit ambiant d'une conversation normale.",
      points: 2,
    ),
  ], finalAnswer: r"$L = 60$ dB.", gradingNotes: r"Définition (1 pt) + numérique (2 pts).", tips: [r"Échelle dB : 0 dB seuil d'audition, 60 dB conversation, 90 dB trafic, 120 dB seuil de douleur. Chaque +10 dB correspond à $\times 10$ d'intensité."]),

  _ans(steps: [
    _step(
      r"**Loi de Biot-Savart pour un fil rectiligne.** $B = \dfrac{\mu_0 I}{2\pi d}$ à distance $d$ d'un fil rectiligne infini parcouru par un courant $I$.",
      points: 1,
    ),
    _step(
      r"**Application.** $B = \dfrac{4\pi \cdot 10^{-7} \cdot 5}{2\pi \cdot 0{,}2} = \dfrac{4\pi \cdot 5 \cdot 10^{-7}}{2\pi \cdot 0{,}2} = \dfrac{2 \cdot 5 \cdot 10^{-7}}{0{,}2} = \dfrac{10^{-6}}{0{,}2} = 5 \cdot 10^{-6}$ T = 5 µT.",
      points: 3,
      widgetSlug: "b_field_uniform",
      widgetConfig: {"B": 5e-6, "I": 5.0},
    ),
  ], finalAnswer: r"$B = 5$ µT.", gradingNotes: r"Formule (1 pt) + numérique (3 pts).", tips: [r"Le champ magnétique terrestre est de l'ordre de 50 µT — un fil de 5 A à 20 cm produit donc 1/10 du champ terrestre."]),

  _ans(steps: [
    _step(
      r"**Loi des mailles en RL libre.** En régime libre (pas de générateur), $u_R + u_L = 0$. $u_R = Ri$, $u_L = L \cdot di/dt$. Donc $Ri + L \dfrac{di}{dt} = 0$.",
      points: 1,
    ),
    _step(
      r"**Mise sous forme normalisée.** Diviser par $L$ : $\dfrac{di}{dt} + \dfrac{R}{L} i = 0$. C'est l'équation différentielle linéaire d'ordre 1 homogène, identique à $y' = ay$ avec $a = -R/L$.",
      points: 2,
    ),
    _step(
      r"**Solution.** $i(t) = I_0 e^{-Rt/L} = I_0 e^{-t/\tau}$ avec $\tau = L/R$ la constante de temps. Le courant initial $I_0$ s'amortit exponentiellement.",
      points: 3,
    ),
  ], finalAnswer: r"$i(t) = I_0 e^{-Rt/L}$, constante de temps $\tau = L/R$.", gradingNotes: r"Loi des mailles (1 pt) + équation différentielle (2 pts) + solution (3 pts)."),

  _ans(steps: [
    _step(
      r"**Loi cinétique d'ordre 1.** $C(t) = C_0 e^{-kt}$ pour une réaction d'ordre 1.",
      points: 1,
    ),
    _step(
      r"**Application.** $C(20) = 0{,}1 \cdot e^{-0{,}05 \cdot 20} = 0{,}1 \cdot e^{-1} \approx 0{,}1 \cdot 0{,}368 = 0{,}0368$ mol/L.",
      points: 3,
    ),
  ], finalAnswer: r"$C(20) \approx 0{,}037$ mol/L.", gradingNotes: r"Loi (1 pt) + numérique (3 pts).", tips: [r"Pour une cinétique d'ordre 1, la demi-vie est $T_{1/2} = \ln 2 / k$ — ici $T_{1/2} \approx 13{,}9$ s, donc à $t = 20$ s on est à environ 1,4 demi-vies, ce qui donne $0{,}1 \cdot 2^{-1{,}4} \approx 0{,}038$ ✓."]),

  _ans(steps: [
    _step(
      r"**Spontanéité d'une pile.** $\Delta E° = E°_{cathode} - E°_{anode}$. Si l'on choisit l'électrode de potentiel le plus haut comme cathode (c'est la convention), alors $\Delta E° > 0$ et la pile fournit du courant spontanément. Réponse **B**.",
      points: 2,
      widgetSlug: "daniell_cell",
      widgetConfig: {},
    ),
  ], finalAnswer: r"B — $\Delta E° > 0$.", gradingNotes: r"Convention + spontanéité (2 pts).", tips: [r"$\Delta E° > 0$ ⟺ $\Delta G° < 0$ ⟺ réaction spontanée. Lien thermodynamique : $\Delta G° = -nF\Delta E°$."]),

  _ans(steps: [
    _step(
      r"**Définition du rendement.** Le rendement est le rapport quantité formée / quantité maximale théorique. Ici, mélange équimolaire de 1 mol acide + 1 mol alcool, donc maximum théorique = 1 mol d'ester. Rendement de 67% ⟹ $n(\text{ester formé}) = 0{,}67 \cdot 1 = 0{,}67$ mol.",
      points: 3,
      widgetSlug: "esterification_animator",
      widgetConfig: {},
    ),
  ], finalAnswer: r"$n_{ester} = 0{,}67$ mol.", gradingNotes: r"Définition + calcul (3 pts).", tips: [r"L'estérification équimolaire plafonne à environ 67% de rendement par effet d'équilibre. Pour augmenter : excès d'un réactif ou élimination de l'eau."]),

  _ans(steps: [
    _step(
      r"**Approximation pH d'une base faible.** Pour $NH_3$ base faible de $pK_b$ donné, l'approximation usuelle (si la base est peu dissociée) donne $pOH \approx \dfrac{1}{2}(pK_b + pC)$ avec $pC = -\log C$.",
      points: 2,
    ),
    _step(
      r"**Calcul.** $pC = -\log(0{,}1) = 1$. $pOH \approx \dfrac{1}{2}(4{,}75 + 1) = 2{,}875$. $pH = 14 - pOH = 11{,}125 \approx 11{,}13$.",
      points: 3,
    ),
  ], finalAnswer: r"$pH \approx 11{,}13$.", gradingNotes: r"Formule approchée (2 pts) + numérique (3 pts).", tips: [r"Approximation valable si $pK_b + pC < 12$ environ (sinon il faut la formule complète prenant en compte l'équilibre exact)."]),

  _ans(steps: [
    _step(
      r"**Période propre RLC.** $T_0 = 2\pi\sqrt{LC}$. Application : $LC = 1 \cdot 10^{-4} = 10^{-4}$, $\sqrt{LC} = 10^{-2}$ s. $T_0 = 2\pi \cdot 10^{-2} \approx 0{,}0628$ s = 62,8 ms.",
      points: 5,
    ),
  ], finalAnswer: r"$T_0 \approx 62{,}8$ ms.", gradingNotes: r"Formule + numérique (5 pts)."),

  // ====== SMA Math 2022 normale (paper 7, IDs 61-70) ======

  _ans(steps: [
    _step(
      r"**DL de $\sin x$ à l'ordre 3.** $\sin x = x - \dfrac{x^3}{6} + o(x^3)$ au voisinage de 0.",
      points: 2,
    ),
    _step(
      r"**Substitution et limite.** $\sin x - x = -\dfrac{x^3}{6} + o(x^3)$. Donc $\dfrac{\sin x - x}{x^3} = -\dfrac{1}{6} + o(1) \to -\dfrac{1}{6} \approx -0{,}167$.",
      points: 2,
    ),
  ], finalAnswer: r"$-1/6 \approx -0{,}167$.", gradingNotes: r"DL (2 pts) + limite (2 pts)."),

  _ans(steps: [
    _step(
      r"**Dérivée par produit.** $f(x) = e^x \cos x$, $u = e^x$, $v = \cos x$, $u' = e^x$, $v' = -\sin x$. $f'(x) = e^x \cos x + e^x (-\sin x) = e^x(\cos x - \sin x)$.",
      points: 2,
    ),
    _step(
      r"**Dérivée seconde.** $f''(x) = (e^x(\cos x - \sin x))'$. À nouveau produit : $u = e^x$, $v = \cos x - \sin x$, $u' = e^x$, $v' = -\sin x - \cos x$. $f''(x) = e^x(\cos x - \sin x) + e^x(-\sin x - \cos x) = e^x[(\cos - \sin) + (-\sin - \cos)] = e^x \cdot (-2 \sin x) = -2 e^x \sin x$.",
      points: 3,
    ),
  ], finalAnswer: r"$f' = e^x(\cos x - \sin x)$ ; $f'' = -2 e^x \sin x$.", gradingNotes: r"$f'$ (2 pts) + $f''$ (3 pts)."),

  _ans(steps: [
    _step(
      r"**Discriminant.** $z^2 + 2z + 5 = 0$, $\Delta = 4 - 20 = -16 < 0$. Racines complexes conjuguées.",
      points: 1,
    ),
    _step(
      r"**Calcul.** $\sqrt{\Delta} = 4i$. $z = (-2 \pm 4i)/2 = -1 \pm 2i$. Donc $z = -1 + 2i$ ou $z = -1 - 2i$.",
      points: 3,
    ),
  ], finalAnswer: r"$z = -1 + 2i$ ou $z = -1 - 2i$.", gradingNotes: r"Discriminant (1 pt) + racines (3 pts)."),

  _ans(steps: [
    _step(
      r"**Substitution trigonométrique.** Pour $\int \sqrt{1 - x^2} \, dx$, poser $x = \sin t$, $dx = \cos t \, dt$. Bornes : $x = 0 \to t = 0$, $x = 1 \to t = \pi/2$. $\sqrt{1 - x^2} = \sqrt{1 - \sin^2 t} = |\cos t| = \cos t$ (positif sur $[0, \pi/2]$).",
      points: 2,
    ),
    _step(
      r"**Calcul.** L'intégrale devient $\int_0^{\pi/2} \cos t \cdot \cos t \, dt = \int_0^{\pi/2} \cos^2 t \, dt = \dfrac{\pi}{4}$ (linéarisation comme à la Q14 mais sur $[0, \pi/2]$).",
      points: 3,
    ),
  ], finalAnswer: r"$\int_0^1 \sqrt{1-x^2} dx = \pi/4$.", gradingNotes: r"Substitution (2 pts) + calcul (3 pts).", tips: [r"Cette intégrale est l'aire d'un quart de cercle de rayon 1 — d'où $\pi r^2/4 = \pi/4$. Vérification géométrique cohérente."]),

  _ans(steps: [
    _step(
      r"**Combinaison.** $\binom{10}{3} = \dfrac{10!}{3! 7!} = \dfrac{10 \cdot 9 \cdot 8}{3 \cdot 2 \cdot 1} = \dfrac{720}{6} = 120$.",
      points: 3,
    ),
  ], finalAnswer: r"$\binom{10}{3} = 120$.", gradingNotes: r"Calcul direct (3 pts).", tips: [r"Astuces : $\binom{n}{k} = \binom{n}{n-k}$. $\binom{10}{3} = \binom{10}{7}$ — on prend la formulation avec le plus petit $k$ pour calculer."]),

  _ans(steps: [
    _step(
      r"**Construction de $g(x) = f(x) - x$.** $g$ est continue sur $[0, 1]$ (différence de continues). $g(0) = f(0) - 0 = 0$ et $g(1) = f(1) - 1 = 0$. Si $g$ est identiquement nulle, c'est immédiat. Sinon, $g$ admet un signe sur l'intervalle ; supposons $g > 0$ quelque part. Alors $g$ doit changer de signe pour revenir à 0 en 1 — par TVI, elle s'annule à un autre point $c \in ]0, 1[$.",
      points: 4,
    ),
    _step(
      r"**Conclusion.** Dans tous les cas, il existe $c \in [0, 1]$ tel que $g(c) = 0$, soit $f(c) = c$. **Tout point qui satisfait $f(c) = c$ est un point fixe** de $f$ — théorème de Brouwer en dimension 1.",
      points: 2,
    ),
  ], finalAnswer: r"Existence d'un point fixe $c \in [0, 1]$.", gradingNotes: r"Construction de $g$ (4 pts) + conclusion (2 pts).", tips: [r"Théorème du point fixe (cas dim 1) : toute fonction continue $[0, 1] \to [0, 1]$ admet un point fixe. Généralise en dimension supérieure (Brouwer)."]),

  _ans(steps: [
    _step(
      r"**Suite alternée.** $u_n = (-1)^n / n$. La valeur absolue $|u_n| = 1/n \to 0$, donc par théorème d'encadrement, $u_n \to 0$.",
      points: 3,
    ),
  ], finalAnswer: r"$u_n \to 0$.", gradingNotes: r"Argument $|u_n| \to 0$ (3 pts).", tips: [r"Pour suite alternée, si $|u_n| \to 0$ alors $u_n \to 0$. Mais ATTENTION : si $|u_n|$ ne tend pas vers 0, $u_n$ peut diverger même borné (ex : $(-1)^n$)."]),

  _ans(steps: [
    _step(
      r"**Équation caractéristique.** $y'' - 4y' + 4y = 0$ a pour équation caractéristique $r^2 - 4r + 4 = 0$. $\Delta = 16 - 16 = 0$ : racine double $r = 2$.",
      points: 2,
    ),
    _step(
      r"**Solution avec racine double.** Pour racine double $r$, la solution générale est $y = (A + Bx) e^{rx}$. Ici : $y = (A + Bx) e^{2x}$.",
      points: 3,
    ),
  ], finalAnswer: r"$y = (A + Bx) e^{2x}$.", gradingNotes: r"Caractéristique (2 pts) + solution (3 pts).", tips: [r"3 cas pour $y'' + ay' + by = 0$ : $\Delta > 0$ deux exponentielles, $\Delta = 0$ exponentielle × polynôme, $\Delta < 0$ exponentielle × cosinus/sinus."]),

  _ans(steps: [
    _step(
      r"**Argument.** $z = 1 + i\sqrt{3}$. $\cos\theta = 1/2$, $\sin\theta = \sqrt{3}/2$, premier quadrant : $\theta = \pi/3 \approx 1{,}047$ rad.",
      points: 3,
    ),
  ], finalAnswer: r"$\arg(1 + i\sqrt{3}) = \pi/3 \approx 1{,}047$ rad.", gradingNotes: r"Calcul (3 pts).", tips: [r"Mémoriser les arguments de référence : $1 + i \to \pi/4$, $1 + i\sqrt{3} \to \pi/3$, $\sqrt{3} + i \to \pi/6$."]),

  _ans(steps: [
    _step(
      r"**Formule binomiale.** $X \sim B(n=10, p=0{,}3)$. $P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}$. Pour $k = 3$ : $P(X=3) = \binom{10}{3} \cdot 0{,}3^3 \cdot 0{,}7^7$.",
      points: 2,
    ),
    _step(
      r"**Numérique.** $\binom{10}{3} = 120$, $0{,}3^3 = 0{,}027$, $0{,}7^7 \approx 0{,}0824$. $P = 120 \cdot 0{,}027 \cdot 0{,}0824 \approx 0{,}267$. C'est environ le mode de la distribution (qui est en $\lfloor (n+1)p \rfloor = 3$).",
      points: 3,
    ),
  ], finalAnswer: r"$P(X=3) \approx 0{,}267$.", gradingNotes: r"Formule (2 pts) + numérique (3 pts).", tips: [r"Pour $X \sim B(n, p)$ : $E(X) = np$, $V(X) = np(1-p)$, mode $\approx (n+1)p$. Ici $E = 3$, $V = 2{,}1$ — le mode 3 est cohérent."]),

  // ====== SMA Math 2022 rattrapage (paper 8, IDs 71-80) ======

  _ans(steps: [
    _step(
      r"**Croissance comparée.** $\sqrt{x} = x^{1/2}$, $(\ln x)$ avec puissance polynômiale 1. Pour tout $\alpha > 0$, $(\ln x)/x^\alpha \to 0$ quand $x \to +\infty$.",
      points: 3,
    ),
  ], finalAnswer: r"$\lim_{x \to +\infty} \dfrac{\ln x}{\sqrt{x}} = 0$.", gradingNotes: r"Croissance comparée (3 pts)."),

  _ans(steps: [
    _step(
      r"**Dérivée par produit.** $f(x) = x e^{-x^2}$, $u = x$, $v = e^{-x^2}$, $u' = 1$, $v' = -2x e^{-x^2}$ (chain rule). $f'(x) = e^{-x^2} + x \cdot (-2x e^{-x^2}) = e^{-x^2}(1 - 2x^2)$.",
      points: 2,
    ),
    _step(
      r"**Signe et zéros.** $e^{-x^2} > 0$, donc le signe est celui de $1 - 2x^2$. $1 - 2x^2 > 0 \Leftrightarrow x^2 < 1/2 \Leftrightarrow |x| < 1/\sqrt{2}$. Donc $f' > 0$ sur $(-1/\sqrt{2}, 1/\sqrt{2})$, négative ailleurs.",
      points: 2,
    ),
    _step(
      r"**Extrema.** Maximum local en $x = 1/\sqrt{2}$ : $f(1/\sqrt{2}) = (1/\sqrt{2}) e^{-1/2} \approx 0{,}429$. Minimum local en $x = -1/\sqrt{2}$ : $f(-1/\sqrt{2}) = -0{,}429$ (par symétrie).",
      points: 3,
    ),
  ], finalAnswer: r"Max en $x = 1/\sqrt{2}$ valant $\approx 0{,}429$, min en $x = -1/\sqrt{2}$ valant $\approx -0{,}429$.", gradingNotes: r"Dérivée (2 pts) + signe (2 pts) + extrema (3 pts).", tips: [r"$f(x) = x e^{-x^2}$ est impaire — d'où la symétrie des extrema. Aussi : $f \to 0$ à $\pm\infty$ par croissance comparée."]),

  _ans(steps: [
    _step(
      r"**Domaine.** $\ln(x^2 - 5x + 6)$ exige $x^2 - 5x + 6 > 0$. Racines de $x^2 - 5x + 6 = 0$ : $\Delta = 25 - 24 = 1$, $x = 2$ ou $x = 3$. Le polynôme est positif en dehors $[2, 3]$ (coeff dom +). Domaine : $]-\infty, 2[ \cup ]3, +\infty[$.",
      points: 1,
    ),
    _step(
      r"**Résolution.** $\ln(...) = 0 \Leftrightarrow x^2 - 5x + 6 = 1 \Leftrightarrow x^2 - 5x + 5 = 0$. $\Delta' = 25 - 20 = 5$. $x = (5 \pm \sqrt{5})/2$.",
      points: 2,
    ),
    _step(
      r"**Vérification du domaine.** $x_1 = (5 - \sqrt{5})/2 \approx 1{,}38 \in ]-\infty, 2[$ ✓. $x_2 = (5 + \sqrt{5})/2 \approx 3{,}62 \in ]3, +\infty[$ ✓. Les deux solutions sont dans le domaine.",
      points: 3,
    ),
  ], finalAnswer: r"$x = (5 - \sqrt{5})/2$ ou $x = (5 + \sqrt{5})/2$.", gradingNotes: r"Domaine (1 pt) + résolution (2 pts) + filtrage (3 pts)."),

  _ans(steps: [
    _step(
      r"**Primitive d'arctangente.** $(\arctan x)' = \dfrac{1}{1 + x^2}$. Donc $\int_0^1 \dfrac{dx}{1 + x^2} = [\arctan x]_0^1 = \arctan 1 - \arctan 0 = \pi/4 - 0 = \pi/4$.",
      points: 3,
    ),
  ], finalAnswer: r"$\int_0^1 \dfrac{dx}{1+x^2} = \pi/4$.", gradingNotes: r"Reconnaissance + numérique (3 pts)."),

  _ans(steps: [
    _step(
      r"**Produit avec conjugué.** Pour $z = a + ib$, $z \bar z = a^2 + b^2 = |z|^2$. Application : $z_1 \bar z_1 = 4 + 9 = 13$. **Réel positif** — propriété fondamentale.",
      points: 2,
    ),
    _step(
      r"**Somme avec conjugué.** $z + \bar z = 2 \mathrm{Re}(z) = 2 \cdot 2 = 4$.",
      points: 2,
    ),
  ], finalAnswer: r"$z_1 \bar z_1 = 13$, $z_1 + \bar z_1 = 4$.", gradingNotes: r"Produit (2 pts) + somme (2 pts)."),

  _ans(steps: [
    _step(
      r"**Limite d'une suite géométrique selon $|q|$.** Trois cas : $|q| < 1 \Rightarrow q^n \to 0$. $|q| = 1$ : si $q = 1$ constante, si $q = -1$ alterne sans limite. $|q| > 1 \Rightarrow |q^n| \to +\infty$, donc divergence (vers $+\infty$ si $q > 1$, sinon oscille). Réponse **C**.",
      points: 3,
    ),
  ], finalAnswer: r"C — diverge vers $\pm\infty$.", gradingNotes: r"Trichotomie selon $|q|$ (3 pts)."),

  _ans(steps: [
    _step(
      r"**Univers et équiprobabilité.** 3 dés équilibrés indépendants : $6^3 = 216$ triplets ordonnés équiprobables.",
      points: 1,
    ),
    _step(
      r"**Décompositions de 7.** Triplets non ordonnés sommant à 7 : (1,1,5), (1,2,4), (1,3,3), (2,2,3). Permutations : (1,1,5) → 3 (les positions du 5), (1,2,4) → 6 (toutes distinctes), (1,3,3) → 3, (2,2,3) → 3. Total : 3 + 6 + 3 + 3 = 15 triplets ordonnés.",
      points: 3,
    ),
    _step(
      r"**Probabilité.** $P = 15/216 = 5/72 \approx 0{,}069$. Soit environ 6,9%.",
      points: 2,
    ),
  ], finalAnswer: r"$P = 5/72 \approx 0{,}069$.", gradingNotes: r"Univers (1 pt) + énumération exhaustive (3 pts) + ratio (2 pts).", tips: [r"Pour $n$ dés, la somme la plus probable est environ $3{,}5n$ (l'espérance). Ici $n = 3$, $E = 10{,}5$, et 7 est en-dessous — mais reste possible."]),

  _ans(steps: [
    _step(
      r"**Algorithme d'Euclide.** $420 = 168 \cdot 2 + 84$, $168 = 84 \cdot 2 + 0$. PGCD = 84.",
      points: 3,
    ),
  ], finalAnswer: r"$\mathrm{pgcd}(420, 168) = 84$.", gradingNotes: r"Euclide (3 pts).", tips: [r"$420 / 84 = 5$, $168/84 = 2$. $\mathrm{pgcd}(5, 2) = 1$ — cohérent."]),

  _ans(steps: [
    _step(
      r"**Équation caractéristique.** $r^2 + r - 6 = 0$. $\Delta = 1 + 24 = 25$. $r = (-1 \pm 5)/2$, donc $r = 2$ ou $r = -3$.",
      points: 2,
    ),
    _step(
      r"**Solution générale.** Deux racines réelles distinctes ⟹ $y = A e^{-3x} + B e^{2x}$.",
      points: 3,
    ),
  ], finalAnswer: r"$y = A e^{-3x} + B e^{2x}$.", gradingNotes: r"Caractéristique (2 pts) + solution (3 pts)."),

  _ans(steps: [
    _step(
      r"**Dérivée.** $f(x) = \tan x$ sur $]-\pi/2, \pi/2[$. $\tan = \sin/\cos$, donc par quotient : $f'(x) = \dfrac{\cos x \cdot \cos x - \sin x \cdot (-\sin x)}{\cos^2 x} = \dfrac{\cos^2 x + \sin^2 x}{\cos^2 x} = \dfrac{1}{\cos^2 x} = 1 + \tan^2 x$. Strictement positive partout.",
      points: 3,
    ),
    _step(
      r"**Limites aux bornes.** Quand $x \to (\pi/2)^-$, $\cos x \to 0^+$ et $\sin x \to 1$, donc $\tan x \to +\infty$. Symétriquement, quand $x \to (-\pi/2)^+$, $\tan x \to -\infty$. Asymptotes verticales aux bornes.",
      points: 2,
    ),
  ], finalAnswer: r"Strictement croissante. Asymptotes verticales en $\pm \pi/2$.", gradingNotes: r"Dérivée (3 pts) + limites (2 pts)."),
];
