// Long-form lesson content for SMA chapters → migration 013.
//
// Run:
//   dart backend/seed/json_encode_long_lessons.dart
//
// Authors 7 chapters as v2 LessonV2-shaped JSON, emits an idempotent
// PostgreSQL migration that UPDATEs `skills.lesson` for the 7 target
// skills. All other skills retain their v1 cards from migration 012.

import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final out = StringBuffer();
  out.writeln('-- ============================================================');
  out.writeln('-- Migration 013: Seed long-form (v2) lessons for 7 SMA chapters.');
  out.writeln('-- Auto-generated by backend/seed/json_encode_long_lessons.dart.');
  out.writeln('-- Idempotent: re-running rewrites the same JSON.');
  out.writeln('-- Targets:');
  out.writeln("--   Math      : sma_limit_def, sma_deriv_definition, sma_sequences_review");
  out.writeln("--   Physique  : sma_newton_laws, sma_rlc_regimes");
  out.writeln("--   Chimie    : sma_ph_definition, sma_titration_curve");
  out.writeln('-- ============================================================');
  out.writeln();
  out.writeln('BEGIN;');
  out.writeln();

  for (final entry in _chapters.entries) {
    final code = entry.key;
    final lesson = entry.value;
    final json = jsonEncode(lesson);
    final escaped = json.replaceAll("'", "''");
    out.writeln('-- ===== $code =====');
    out.writeln(
        "UPDATE public.skills SET lesson = '$escaped'::jsonb WHERE code = '$code';");
    out.writeln();
  }

  out.writeln('COMMIT;');

  final output = args.isNotEmpty
      ? args[0]
      : 'backend/supabase/migrations/013_long_lessons_sma.sql';
  File(output).writeAsStringSync(out.toString());
  stdout.writeln('Wrote $output (${_chapters.length} chapters).');
  for (final code in _chapters.keys) {
    final l = _chapters[code]!;
    final n = (l['sections'] as List).length;
    stdout.writeln('  $code → ${l['title_fr']} ($n sections)');
  }
}

// ============================================================================
// Builder helpers — keeps the chapter literals readable.
// ============================================================================

Map<String, dynamic> _lesson({
  required String titleFr,
  String? subtitleFr,
  required List<Map<String, dynamic>> sections,
}) =>
    {
      'version': 2,
      'title_fr': titleFr,
      if (subtitleFr != null) 'subtitle_fr': subtitleFr,
      'sections': sections,
    };

Map<String, dynamic> _section({
  required String kind,
  required String titleFr,
  String? eyebrowFr,
  required String estimatedMinutes,
  required List<Map<String, dynamic>> blocks,
}) =>
    {
      'kind': kind,
      'title_fr': titleFr,
      if (eyebrowFr != null) 'eyebrow_fr': eyebrowFr,
      'estimated_minutes': estimatedMinutes,
      'blocks': blocks,
    };

Map<String, dynamic> _p(String md) => {'kind': 'paragraph', 'md': md};
Map<String, dynamic> _h(String text, [int level = 2]) =>
    {'kind': 'heading', 'text': text, 'level': level};
Map<String, dynamic> _f(String latex, [String? caption]) =>
    {'kind': 'formula', 'latex': latex, if (caption != null) 'caption_fr': caption};
Map<String, dynamic> _div() => {'kind': 'divider'};
Map<String, dynamic> _callout(String tone, String title, String body) =>
    {'kind': 'callout', 'tone': tone, 'title_fr': title, 'body_fr': body};
Map<String, dynamic> _example({
  required String title,
  required String problem,
  required List<String> steps,
  String? answer,
}) =>
    {
      'kind': 'example',
      'title_fr': title,
      'problem_fr': problem,
      'steps_fr': steps,
      if (answer != null) 'answer_fr': answer,
    };
Map<String, dynamic> _interactive(String widgetType,
        {Map<String, dynamic>? config, String? caption}) =>
    {
      'kind': 'interactive',
      'widget_type': widgetType,
      if (config != null) 'config': config,
      if (caption != null) 'caption_fr': caption,
    };
Map<String, dynamic> _checkpoint(String title, List<Map<String, dynamic>> qs) =>
    {'kind': 'checkpoint', 'title_fr': title, 'questions': qs};
Map<String, dynamic> _q(
        {required String stem,
        required List<String> choices,
        required int correct,
        required String explanation}) =>
    {
      'stem_fr': stem,
      'choices_fr': choices,
      'correct_index': correct,
      'explanation_fr': explanation,
    };
Map<String, dynamic> _tryIt({
  required String title,
  required String problem,
  required String hint,
  required String solution,
}) =>
    {
      'kind': 'try_it',
      'title_fr': title,
      'problem_fr': problem,
      'hint_fr': hint,
      'solution_fr': solution,
    };

// ============================================================================
// THE CONTENT — 7 chapters
// ============================================================================

final Map<String, Map<String, dynamic>> _chapters = {
  'sma_limit_def': _ch1Limites(),
  'sma_deriv_definition': _ch2Derivabilite(),
  'sma_sequences_review': _ch3Suites(),
  'sma_newton_laws': _ch4Newton(),
  'sma_rlc_regimes': _ch5Rlc(),
  'sma_ph_definition': _ch6AcidBase(),
  'sma_titration_curve': _ch7Titration(),
};

// ----------------------------------------------------------------------------
// Chapter 1 — Limites et continuité
// ----------------------------------------------------------------------------

Map<String, dynamic> _ch1Limites() => _lesson(
      titleFr: 'Limites et continuité',
      subtitleFr:
          "Du concept intuitif de « tendre vers » au théorème des valeurs intermédiaires.",
      sections: [
        _section(
          kind: 'prerequisite',
          titleFr: 'Prérequis : ce que tu dois maîtriser',
          eyebrowFr: 'PRÉREQUIS',
          estimatedMinutes: '3',
          blocks: [
            _p("Avant de parler de limites, on doit être à l'aise avec le langage des fonctions. Une fonction \$f\$ associe à chaque valeur \$x\$ de son **ensemble de définition** une unique valeur \$f(x)\$. On note \$f: x \\mapsto f(x)\$."),
            _p("Trois outils d'algèbre te seront indispensables tout au long du chapitre. Garde-les à portée de main."),
            _f('a^2 - b^2 = (a-b)(a+b)', "Différence de deux carrés."),
            _f('(a+b)^2 = a^2 + 2ab + b^2 \\qquad (a-b)^2 = a^2 - 2ab + b^2', "Identités remarquables."),
            _f('\\frac{a-b}{\\sqrt{a} - \\sqrt{b}} = \\sqrt{a} + \\sqrt{b}', "Multiplication par le conjugué."),
            _callout('note', 'Avant de continuer',
                "Si l'une de ces formules t'arrête, prends 2 minutes pour réviser tes identités remarquables. Tout le reste du chapitre repose dessus."),
            _checkpoint("Vérifie que tes bases tiennent", [
              _q(
                stem: "Factorise \$x^2 - 9\$.",
                choices: ['\$(x-3)^2\$', '\$(x+3)^2\$', '\$(x-3)(x+3)\$', '\$x(x-9)\$'],
                correct: 2,
                explanation:
                    "C'est une différence de deux carrés : \$x^2 - 9 = x^2 - 3^2 = (x-3)(x+3)\$.",
              ),
              _q(
                stem: "Quel est l'ensemble de définition de \$f(x) = \\dfrac{1}{x-1}\$ ?",
                choices: ['\$\\mathbb{R}\$', '\$\\mathbb{R} \\setminus \\{0\\}\$', '\$\\mathbb{R} \\setminus \\{1\\}\$', '\$[1, +\\infty[\$'],
                correct: 2,
                explanation:
                    "Le dénominateur \$x-1\$ s'annule pour \$x=1\$. La fonction n'est définie que pour \$x \\ne 1\$.",
              ),
              _q(
                stem: "Simplifie \$\\dfrac{2x^2 - 8}{x - 2}\$ pour \$x \\ne 2\$.",
                choices: ['\$2x + 4\$', '\$2x - 4\$', '\$x + 4\$', "On ne peut pas simplifier."],
                correct: 0,
                explanation:
                    "On factorise : \$2x^2 - 8 = 2(x^2 - 4) = 2(x-2)(x+2)\$. Donc \$\\frac{2x^2-8}{x-2} = 2(x+2) = 2x+4\$.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'Le concept de limite : intuition d\'abord',
          eyebrowFr: 'CONCEPT',
          estimatedMinutes: '5',
          blocks: [
            _h("Que veut dire « tendre vers » ?"),
            _p("Imagine la fonction \$f(x) = \\dfrac{x^2 - 4}{x - 2}\$. En \$x = 2\$, elle n'est pas définie (division par zéro). Pourtant, regarde ce qui se passe quand \$x\$ se rapproche de 2 :"),
            _p("Pour \$x = 1{,}9\$ : \$f(x) = 3{,}9\$. Pour \$x = 1{,}99\$ : \$f(x) = 3{,}99\$. Pour \$x = 2{,}01\$ : \$f(x) = 4{,}01\$."),
            _p("Plus \$x\$ s'approche de 2, plus \$f(x)\$ s'approche de 4. **\$f(x)\$ tend vers 4 quand \$x\$ tend vers 2**, sans jamais l'atteindre exactement. C'est ça, l'idée de limite."),
            _f('\\lim_{x \\to a} f(x) = L', "Notation : « la limite de f(x) quand x tend vers a vaut L »."),
            _interactive('function_graph',
                config: {'function': '(x*x - 4) / (x - 2)'},
                caption: "Déplace le curseur — observe que f(x) approche 4 sans que x = 2."),
            _h("Les trois cas qu'on rencontre", 3),
            _p("Une limite peut exister et être **finie** (un nombre). Elle peut être **infinie** : \$f(x)\$ devient arbitrairement grand. Ou elle peut **ne pas exister** : \$f(x)\$ ne se rapproche d'aucune valeur."),
            _callout('insight', 'La définition formelle (ε-δ)',
                "On dit que \$\\lim_{x\\to a} f(x) = L\$ lorsque pour toute marge \$\\varepsilon>0\$ aussi petite soit-elle, on peut trouver une marge \$\\delta>0\$ telle que \$|x - a| < \\delta\$ entraîne \$|f(x) - L| < \\varepsilon\$. Au Bac, tu n'auras pas à manipuler cette définition, mais elle te dit ce que « aussi proche que voulu » veut dire mathématiquement."),
            _example(
              title: "Exemple — Limite par substitution directe",
              problem: "Calcule \$\\lim_{x \\to 3} (x^2 + 1)\$.",
              steps: [
                "La fonction \$x \\mapsto x^2 + 1\$ est définie pour tout \$x\$ réel, et c'est un polynôme — il est continu partout.",
                "On peut donc remplacer directement : \$\\lim_{x\\to 3}(x^2+1) = 3^2 + 1\$.",
                "Calcul : \$9 + 1 = 10\$.",
              ],
              answer: "\$\\lim_{x \\to 3} (x^2 + 1) = 10\$.",
            ),
            _checkpoint("Tu as l'intuition ?", [
              _q(
                stem: "Que vaut \$\\lim_{x \\to 0} x^2\$ ?",
                choices: ['\$0\$', '\$1\$', "\$+\\infty\$", "Elle n'existe pas"],
                correct: 0,
                explanation:
                    "On substitue : \$x^2\$ en \$x=0\$ vaut \$0\$. La fonction est continue, donc la limite est la valeur de la fonction.",
              ),
              _q(
                stem: "Que vaut \$\\lim_{x \\to +\\infty} \\dfrac{1}{x}\$ ?",
                choices: ['\$0\$', '\$1\$', "\$+\\infty\$", "Elle n'existe pas"],
                correct: 0,
                explanation:
                    "Quand \$x\$ devient très grand, \$\\frac{1}{x}\$ devient très petit. La limite est 0.",
              ),
              _q(
                stem: "Vers quoi tend \$\\dfrac{2x+1}{x+3}\$ quand \$x \\to +\\infty\$ ?",
                choices: ['\$0\$', '\$1\$', '\$2\$', "\$+\\infty\$"],
                correct: 2,
                explanation:
                    "Numérateur et dénominateur sont du même degré (1). On regarde le rapport des coefficients dominants : \$\\frac{2}{1} = 2\$.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: "Calculer des limites : les techniques de base",
          eyebrowFr: 'TECHNIQUES',
          estimatedMinutes: '6',
          blocks: [
            _h("Les 4 outils que tu utiliseras 90 % du temps"),
            _p("**1. Substitution directe.** Si la fonction est continue en \$a\$, alors \$\\lim_{x\\to a} f(x) = f(a)\$. Tente toujours ça en premier."),
            _p("**2. Forme indéterminée \$\\frac{0}{0}\$.** Quand la substitution donne \$\\frac{0}{0}\$, il y a une simplification cachée. Factorise et simplifie."),
            _p("**3. Forme indéterminée \$\\frac{\\infty}{\\infty}\$.** Quand \$x \\to \\pm\\infty\$ dans une fraction de polynômes, divise haut et bas par la plus haute puissance de \$x\$."),
            _p("**4. Multiplication par le conjugué.** Quand il y a une racine carrée et une indétermination, multiplie par \$\\frac{\\sqrt{a} + \\sqrt{b}}{\\sqrt{a} + \\sqrt{b}}\$ pour faire disparaître la racine du numérateur."),
            _f('\\lim(f \\pm g) = \\lim f \\pm \\lim g \\quad ; \\quad \\lim(f \\cdot g) = \\lim f \\cdot \\lim g \\quad ; \\quad \\lim \\frac{f}{g} = \\frac{\\lim f}{\\lim g}',
                "Opérations sur les limites — valables quand toutes les limites existent et que le dénominateur ne s'annule pas."),
            _example(
              title: "Forme indéterminée 0/0",
              problem: "Calcule \$\\displaystyle\\lim_{x\\to 2} \\dfrac{x^2-4}{x-2}\$.",
              steps: [
                "Substitution directe : \$\\frac{2^2-4}{2-2} = \\frac{0}{0}\$. **Forme indéterminée**.",
                "Factorise le numérateur : \$x^2 - 4 = (x-2)(x+2)\$.",
                "Simplifie : \$\\frac{(x-2)(x+2)}{x-2} = x+2\$ (pour \$x \\ne 2\$).",
                "Maintenant la limite est immédiate : \$\\lim_{x\\to 2}(x+2) = 4\$.",
              ],
              answer: "\$\\lim_{x\\to 2} \\dfrac{x^2-4}{x-2} = 4\$.",
            ),
            _example(
              title: "Forme indéterminée à l'infini",
              problem: "Calcule \$\\displaystyle\\lim_{x\\to +\\infty} \\dfrac{2x^2 + 3}{x^2 - 1}\$.",
              steps: [
                "Numérateur et dénominateur tendent vers \$+\\infty\$ — forme \$\\frac{\\infty}{\\infty}\$, indéterminée.",
                "Plus haute puissance : \$x^2\$. Divise haut et bas : \$\\frac{2x^2+3}{x^2-1} = \\frac{2 + 3/x^2}{1 - 1/x^2}\$.",
                "Quand \$x \\to +\\infty\$ : \$\\frac{3}{x^2} \\to 0\$ et \$\\frac{1}{x^2} \\to 0\$.",
                "Donc la limite vaut \$\\frac{2 + 0}{1 - 0} = 2\$.",
              ],
              answer: "\$\\lim_{x\\to +\\infty} \\dfrac{2x^2+3}{x^2-1} = 2\$.",
            ),
            _callout('pitfall', "Erreur classique : limite à droite vs à gauche",
                "\$\\lim_{x\\to 0} \\frac{1}{x}\$ n'existe **pas**. Mais \$\\lim_{x\\to 0^+} \\frac{1}{x} = +\\infty\$ et \$\\lim_{x\\to 0^-} \\frac{1}{x} = -\\infty\$. Sur Bac, lis bien si on te demande la limite à droite (\$0^+\$), à gauche (\$0^-\$), ou les deux."),
            _tryIt(
              title: "Calcule cette limite",
              problem: "Détermine \$\\displaystyle\\lim_{x\\to 1} \\dfrac{x^2 - 1}{x - 1}\$.",
              hint: "Substitution donne \$0/0\$. Factorise le numérateur — c'est encore une différence de carrés.",
              solution:
                  "\$x^2 - 1 = (x-1)(x+1)\$. Donc \$\\frac{x^2-1}{x-1} = x+1\$ pour \$x \\ne 1\$. La limite vaut donc \$\\lim_{x\\to 1}(x+1) = 2\$.",
            ),
            _checkpoint("Mets-toi à l'épreuve", [
              _q(
                stem: "Quelle est \$\\displaystyle\\lim_{x\\to 4} \\dfrac{x^2 - 16}{x-4}\$ ?",
                choices: ['\$0\$', '\$4\$', '\$8\$', '\$16\$'],
                correct: 2,
                explanation:
                    "Forme \$0/0\$. Factorise : \$x^2-16 = (x-4)(x+4)\$. Limite = \$x+4\$ en \$x=4\$ = 8.",
              ),
              _q(
                stem: "Quelle est \$\\displaystyle\\lim_{x\\to +\\infty} \\dfrac{3x+1}{x+5}\$ ?",
                choices: ['\$0\$', '\$1\$', '\$3\$', "\$+\\infty\$"],
                correct: 2,
                explanation:
                    "Même degré au numérateur et dénominateur (1). Rapport des coefficients dominants = 3.",
              ),
              _q(
                stem: "Que vaut \$\\displaystyle\\lim_{x\\to 0^+} \\dfrac{1}{x}\$ ?",
                choices: ['\$0\$', "\$+\\infty\$", "\$-\\infty\$", "Elle n'existe pas"],
                correct: 1,
                explanation:
                    "À droite de 0, \$x\$ est positif et tend vers 0. \$\\frac{1}{x}\$ tend donc vers \$+\\infty\$.",
              ),
              _q(
                stem: "Et \$\\displaystyle\\lim_{x\\to +\\infty} \\dfrac{x^2+1}{x+2}\$ ?",
                choices: ['\$0\$', '\$1\$', "\$+\\infty\$", '\$2\$'],
                correct: 2,
                explanation:
                    "Numérateur de degré 2, dénominateur de degré 1. Le numérateur l'emporte : limite \$+\\infty\$.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'synthesis',
          titleFr: "Continuité et théorème des valeurs intermédiaires",
          eyebrowFr: 'SYNTHÈSE',
          estimatedMinutes: '5',
          blocks: [
            _h("De la limite à la continuité"),
            _p("La limite décrit ce qui se passe quand \$x\$ s'approche de \$a\$. La continuité, elle, dit que ce qui se passe « près de \$a\$ » coïncide avec ce qui se passe **en \$a\$**."),
            _f('f \\text{ continue en } a \\iff \\lim_{x\\to a} f(x) = f(a)',
                "Définition formelle de la continuité en un point."),
            _p("Concrètement, **la courbe se trace sans lever le crayon** au voisinage de \$a\$. Les fonctions polynômes, sinus, cosinus, exponentielle sont continues partout. La fonction \$1/x\$ est continue sur \$\\mathbb{R}^*\$ — mais pas en 0, où elle n'est même pas définie."),
            _h("Le théorème des valeurs intermédiaires (TVI)", 2),
            _p("C'est l'un des théorèmes les plus utiles du programme. Il sert à démontrer **l'existence** d'une solution à une équation, sans la calculer."),
            _f('\\text{Si } f \\text{ continue sur } [a,b] \\text{ et } k \\text{ entre } f(a) \\text{ et } f(b), \\text{ alors } \\exists c \\in [a,b] : f(c) = k.',
                "Énoncé du TVI. Cas particulier : si \$f(a)\\cdot f(b) < 0\$, alors \$f\$ s'annule sur \$]a,b[\$."),
            _callout('note', 'Ce que le TVI ne fait PAS',
                "Le TVI ne te donne **pas** la valeur de \$c\$. Il garantit juste qu'elle existe. Pour la trouver précisément, il faut une autre méthode (calcul, dichotomie, etc.)."),
            _example(
              title: "Application directe du TVI",
              problem: "Montre que l'équation \$x^3 + x - 1 = 0\$ admet au moins une solution dans \$]0, 1[\$.",
              steps: [
                "Pose \$f(x) = x^3 + x - 1\$. C'est un polynôme, donc \$f\$ est continue sur \$[0, 1]\$.",
                "Calcule \$f(0) = 0 + 0 - 1 = -1 < 0\$.",
                "Calcule \$f(1) = 1 + 1 - 1 = 1 > 0\$.",
                "Comme \$f\$ est continue sur \$[0,1]\$ et que \$f(0) \\cdot f(1) < 0\$, par le TVI il existe \$c \\in ]0,1[\$ tel que \$f(c) = 0\$.",
              ],
              answer: "L'équation admet (au moins) une solution dans \$]0, 1[\$.",
            ),
            _checkpoint("Synthèse — limites et continuité", [
              _q(
                stem:
                    "Une fonction \$f\$ telle que \$\\lim_{x\\to 2} f(x) = 5\$ et \$f(2) = 5\$ est :",
                choices: [
                  "discontinue en 2",
                  "continue en 2",
                  "non définie en 2",
                  "ne signifie rien",
                ],
                correct: 1,
                explanation:
                    "C'est exactement la définition de la continuité : limite = valeur en ce point.",
              ),
              _q(
                stem: "Le TVI permet de :",
                choices: [
                  "calculer une solution exacte",
                  "garantir l'existence d'une solution",
                  "trouver une asymptote",
                  "dériver une fonction",
                ],
                correct: 1,
                explanation:
                    "Le TVI prouve qu'une solution existe — il ne donne pas sa valeur.",
              ),
              _q(
                stem:
                    "Soit \$g\$ continue sur \$[0,1]\$, avec \$g(0) = 3\$ et \$g(1) = -2\$. Le TVI garantit qu'il existe \$c \\in [0,1]\$ tel que :",
                choices: [
                  "\$g(c) = 5\$",
                  "\$g(c) = 0\$",
                  "\$g(c) = -3\$",
                  "\$g(c) = 4\$",
                ],
                correct: 1,
                explanation:
                    "0 est entre \$-2\$ et \$3\$. Par le TVI, il existe \$c\$ tel que \$g(c)=0\$. Pour 5, \$-3\$, 4 — pas dans l'intervalle des valeurs.",
              ),
            ]),
          ],
        ),
      ],
    );

// ----------------------------------------------------------------------------
// Chapter 2 — Dérivabilité et étude de fonctions
// ----------------------------------------------------------------------------

Map<String, dynamic> _ch2Derivabilite() => _lesson(
      titleFr: 'Dérivabilité et étude de fonctions',
      subtitleFr:
          "Du nombre dérivé en un point à l'étude complète d'une fonction.",
      sections: [
        _section(
          kind: 'prerequisite',
          titleFr: 'Prérequis : taux d\'accroissement et lecture graphique',
          eyebrowFr: 'PRÉREQUIS',
          estimatedMinutes: '3',
          blocks: [
            _p("La dérivée naît d'une question simple : **comment varie \$f(x)\$ quand \$x\$ varie un peu ?** La réponse passe par le **taux d'accroissement**."),
            _f('\\tau = \\frac{f(b) - f(a)}{b - a}',
                "Taux d'accroissement de \$f\$ entre \$a\$ et \$b\$. C'est la pente de la corde reliant \$(a, f(a))\$ et \$(b, f(b))\$."),
            _p("Géométriquement, c'est un nombre. Plus \$b\$ s'approche de \$a\$, plus la corde se rapproche de la **tangente** à la courbe en \$(a, f(a))\$."),
            _checkpoint("Bases : taux et pentes", [
              _q(
                stem: "Quel est le taux d'accroissement de \$f(x) = x^2\$ entre 1 et 3 ?",
                choices: ['\$2\$', '\$3\$', '\$4\$', '\$8\$'],
                correct: 2,
                explanation: "\$\\tau = \\frac{f(3) - f(1)}{3 - 1} = \\frac{9 - 1}{2} = 4\$.",
              ),
              _q(
                stem: "Une droite de pente 2 passant par \$(0, 1)\$ a pour équation :",
                choices: [
                  '\$y = 2x\$',
                  '\$y = 2x + 1\$',
                  '\$y = x + 2\$',
                  '\$y = x/2 + 1\$',
                ],
                correct: 1,
                explanation:
                    "Forme \$y = mx + p\$ avec \$m = 2\$ et \$p = 1\$ (l'ordonnée à l'origine).",
              ),
              _q(
                stem: "Sur le graphe de \$x \\mapsto x^2\$, la pente de la tangente en \$x = 0\$ vaut :",
                choices: ['\$0\$', '\$1\$', '\$2\$', "\$-1\$"],
                correct: 0,
                explanation:
                    "En \$x = 0\$ la parabole admet un minimum — sa tangente est horizontale, donc de pente 0.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'Le nombre dérivé en un point',
          eyebrowFr: 'CONCEPT',
          estimatedMinutes: '5',
          blocks: [
            _p("Faire tendre \$b\$ vers \$a\$ dans le taux d'accroissement, c'est définir le **nombre dérivé** de \$f\$ en \$a\$."),
            _f("f'(a) = \\lim_{h \\to 0} \\frac{f(a+h) - f(a)}{h}",
                "Définition du nombre dérivé. Quand cette limite existe et est finie, on dit que \$f\$ est dérivable en \$a\$."),
            _p("Géométriquement, **\$f'(a)\$ est la pente de la tangente à la courbe au point d'abscisse \$a\$**. C'est aussi le **coefficient directeur instantané** de \$f\$ au voisinage de \$a\$."),
            _f("y = f'(a)(x - a) + f(a)",
                "Équation de la tangente à la courbe de \$f\$ au point d'abscisse \$a\$."),
            _interactive('derivative_graph',
                config: {'function': 'x*x'},
                caption:
                    "Déplace le point \$M\$ — la sécante (rouge) bascule en tangente (bleue) à mesure que \$h \\to 0\$."),
            _example(
              title: "Calculer \$f'(2)\$ pour \$f(x) = x^2\$",
              problem:
                  "Calcule le nombre dérivé de \$f(x) = x^2\$ au point \$a = 2\$ en utilisant la définition.",
              steps: [
                "Forme le taux : \$\\frac{f(2+h) - f(2)}{h} = \\frac{(2+h)^2 - 4}{h}\$.",
                "Développe : \$(2+h)^2 = 4 + 4h + h^2\$, donc \$(2+h)^2 - 4 = 4h + h^2\$.",
                "Simplifie : \$\\frac{4h + h^2}{h} = 4 + h\$.",
                "Fais tendre \$h\\to 0\$ : la limite vaut 4.",
              ],
              answer: "\$f'(2) = 4\$. La tangente en \$x=2\$ a pour équation \$y = 4(x-2) + 4 = 4x - 4\$.",
            ),
            _checkpoint("Nombre dérivé", [
              _q(
                stem: "Si \$f'(3) = -2\$, la tangente en \$x = 3\$ a pour pente :",
                choices: ['\$3\$', "\$-2\$", '\$2\$', "\$f(3)\$"],
                correct: 1,
                explanation: "Par définition, \$f'(a)\$ EST la pente de la tangente en \$a\$.",
              ),
              _q(
                stem:
                    "Pour \$f(x) = x^2\$, le nombre dérivé en 0 vaut :",
                choices: ['\$0\$', '\$1\$', '\$2\$', "\$+\\infty\$"],
                correct: 0,
                explanation:
                    "On peut le voir avec la définition (\$\\frac{(0+h)^2 - 0}{h} = h \\to 0\$) ou directement : \$f'(x) = 2x\$, donc \$f'(0) = 0\$.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'La fonction dérivée et les dérivées usuelles',
          eyebrowFr: 'TABLE',
          estimatedMinutes: '4',
          blocks: [
            _p("Si \$f\$ est dérivable en chaque point de son ensemble de définition, on peut considérer **la fonction \$f'\$** qui à chaque \$x\$ associe \$f'(x)\$. C'est la fonction dérivée."),
            _h("Les dérivées à connaître par cœur"),
            _f("(c)' = 0", "Dérivée d'une constante : zéro."),
            _f("(x^n)' = n \\cdot x^{n-1}", "Dérivée d'une puissance entière. Cas particulier : \$(x)'=1\$, \$(x^2)'=2x\$, \$(x^3)'=3x^2\$."),
            _f("(\\sqrt{x})' = \\frac{1}{2\\sqrt{x}}", "Dérivée de la racine carrée — pour \$x>0\$."),
            _f("\\left(\\frac{1}{x}\\right)' = -\\frac{1}{x^2}", "Dérivée de l'inverse — pour \$x \\ne 0\$."),
            _f("(\\sin x)' = \\cos x \\qquad (\\cos x)' = -\\sin x", "Dérivées trigonométriques de base."),
            _f("(e^x)' = e^x \\qquad (\\ln x)' = \\frac{1}{x}",
                "Les deux stars du programme — exponentielle et logarithme."),
            _example(
              title: "Dériver un polynôme",
              problem: "Calcule \$f'(x)\$ pour \$f(x) = 3x^2 - 5x + 2\$.",
              steps: [
                "On dérive terme par terme.",
                "\$(3x^2)' = 3 \\cdot 2x = 6x\$.",
                "\$(-5x)' = -5\$.",
                "\$(2)' = 0\$ (constante).",
                "Somme : \$f'(x) = 6x - 5\$.",
              ],
              answer: "\$f'(x) = 6x - 5\$.",
            ),
            _checkpoint("Dérivées usuelles", [
              _q(
                stem: "Quelle est la dérivée de \$f(x) = x^4\$ ?",
                choices: ['\$4x^3\$', '\$x^3\$', '\$3x^4\$', '\$4x\$'],
                correct: 0,
                explanation: "\$(x^n)' = n x^{n-1}\$, donc \$(x^4)' = 4x^3\$.",
              ),
              _q(
                stem: "Quelle est la dérivée de \$g(x) = e^x\$ ?",
                choices: ['\$0\$', '\$x e^{x-1}\$', '\$e^x\$', '\$\\ln x\$'],
                correct: 2,
                explanation:
                    "L'exponentielle est sa propre dérivée — c'est sa propriété fondamentale.",
              ),
              _q(
                stem: "Que vaut \$h'(x)\$ pour \$h(x) = -2x^3 + 7\$ ?",
                choices: ['\$-6x^2\$', '\$-6x^2 + 7\$', '\$6x^2\$', '\$3x^2\$'],
                correct: 0,
                explanation:
                    "\$(-2x^3)' = -6x^2\$ ; \$(7)' = 0\$. Somme : \$-6x^2\$.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'Règles de dérivation : somme, produit, quotient, composition',
          eyebrowFr: 'RÈGLES',
          estimatedMinutes: '5',
          blocks: [
            _f("(u + v)' = u' + v' \\qquad (k u)' = k u'", "Linéarité — dériver, c'est additif et homogène."),
            _f("(uv)' = u'v + uv'", "Règle du produit."),
            _f("\\left(\\frac{u}{v}\\right)' = \\frac{u'v - uv'}{v^2}", "Règle du quotient — attention au signe et au carré au dénominateur."),
            _f("(u \\circ v)'(x) = v'(x) \\cdot u'(v(x))", "Règle de la composition (chain rule). Cas typique : \$(u(ax+b))' = a \\cdot u'(ax+b)\$."),
            _example(
              title: "Règle du produit",
              problem: "Calcule \$f'(x)\$ pour \$f(x) = (2x+1)\\cdot x^2\$.",
              steps: [
                "Pose \$u(x) = 2x+1\$ et \$v(x) = x^2\$. Alors \$u'(x) = 2\$ et \$v'(x) = 2x\$.",
                "Applique \$(uv)' = u'v + uv'\$ : \$f'(x) = 2 \\cdot x^2 + (2x+1) \\cdot 2x\$.",
                "Développe : \$2x^2 + 4x^2 + 2x = 6x^2 + 2x\$.",
              ],
              answer: "\$f'(x) = 6x^2 + 2x\$.",
            ),
            _example(
              title: "Règle du quotient",
              problem: "Dérive \$g(x) = \\dfrac{x+1}{x-1}\$ (pour \$x\\ne 1\$).",
              steps: [
                "\$u(x) = x+1\$, \$v(x) = x-1\$. \$u' = 1\$, \$v' = 1\$.",
                "Applique : \$g'(x) = \\frac{1\\cdot(x-1) - (x+1)\\cdot 1}{(x-1)^2}\$.",
                "Numérateur : \$(x-1) - (x+1) = -2\$.",
              ],
              answer: "\$g'(x) = \\dfrac{-2}{(x-1)^2}\$.",
            ),
            _example(
              title: "Composition (chain rule)",
              problem: "Dérive \$h(x) = (3x+2)^4\$.",
              steps: [
                "Pose \$v(x) = 3x+2\$ (la fonction interne) et \$u(t) = t^4\$ (la fonction externe).",
                "On a \$u'(t) = 4t^3\$ et \$v'(x) = 3\$.",
                "Chain rule : \$h'(x) = v'(x) \\cdot u'(v(x)) = 3 \\cdot 4(3x+2)^3\$.",
              ],
              answer: "\$h'(x) = 12(3x+2)^3\$.",
            ),
            _tryIt(
              title: "À toi de jouer",
              problem: "Dérive \$f(x) = (2x+1)^3\$.",
              hint: "C'est une composition. Pose \$v = 2x+1\$ et utilise \$(v^3)' = 3v^2 \\cdot v'\$.",
              solution:
                  "\$v(x) = 2x+1\$, \$v'(x) = 2\$. Donc \$f'(x) = 3(2x+1)^2 \\cdot 2 = 6(2x+1)^2\$.",
            ),
            _checkpoint("Règles de dérivation", [
              _q(
                stem: "La dérivée de \$f(x) = x \\cdot \\sin x\$ est :",
                choices: [
                  '\$\\cos x\$',
                  '\$\\sin x + x \\cos x\$',
                  '\$x \\cos x\$',
                  '\$\\sin x \\cos x\$',
                ],
                correct: 1,
                explanation:
                    "Produit : \$f' = (x)' \\sin x + x (\\sin x)' = 1 \\cdot \\sin x + x \\cos x\$.",
              ),
              _q(
                stem: "Que vaut la dérivée de \$g(x) = \\dfrac{1}{x^2 + 1}\$ ?",
                choices: [
                  '\$\\dfrac{-1}{(x^2+1)^2}\$',
                  '\$\\dfrac{-2x}{(x^2+1)^2}\$',
                  '\$\\dfrac{2x}{x^2+1}\$',
                  '\$\\dfrac{-2x}{x^2+1}\$',
                ],
                correct: 1,
                explanation:
                    "Composition de \$1/u\$ avec \$u = x^2+1\$. \$u' = 2x\$, et \$(1/u)' = -u'/u^2\$. Donc \$g'(x) = -2x/(x^2+1)^2\$.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'synthesis',
          titleFr: "Étude de fonction : la recette en 6 étapes",
          eyebrowFr: 'SYNTHÈSE',
          estimatedMinutes: '6',
          blocks: [
            _p("L'étude complète d'une fonction est l'exercice central du Bac. Voici la recette à appliquer mécaniquement, dans l'ordre."),
            _h("La recette"),
            _p("**1. Ensemble de définition** \$D_f\$ — où la fonction existe."),
            _p("**2. Limites aux bornes** de \$D_f\$ — déduit les **asymptotes**."),
            _p("**3. Dérivée \$f'\$** et son **signe**."),
            _p("**4. Tableau de variations** — résume signes de \$f'\$ et variations de \$f\$."),
            _p("**5. Extremums** — points où \$f'\$ change de signe."),
            _p("**6. Tracé de la courbe** — guidé par les variations et les asymptotes."),
            _example(
              title: "Étude complète : \$f(x) = x^3 - 3x + 1\$",
              problem: "Étudie complètement la fonction \$f\$ définie sur \$\\mathbb{R}\$ par \$f(x) = x^3 - 3x + 1\$.",
              steps: [
                "**Ensemble de définition.** \$f\$ est un polynôme : \$D_f = \\mathbb{R}\$.",
                "**Limites.** Quand \$x \\to +\\infty\$, \$f(x) \\to +\\infty\$. Quand \$x \\to -\\infty\$, \$f(x) \\to -\\infty\$. Pas d'asymptote (un polynôme n'en a jamais).",
                "**Dérivée.** \$f'(x) = 3x^2 - 3 = 3(x^2 - 1) = 3(x-1)(x+1)\$.",
                "**Signe de \$f'\$.** \$f'(x) > 0\$ pour \$x < -1\$ ou \$x > 1\$ ; \$f'(x) < 0\$ pour \$-1 < x < 1\$.",
                "**Variations.** \$f\$ est croissante sur \$]-\\infty, -1]\$, décroissante sur \$[-1, 1]\$, croissante sur \$[1, +\\infty[\$.",
                "**Extremums.** Maximum local en \$x=-1\$ : \$f(-1) = -1 + 3 + 1 = 3\$. Minimum local en \$x=1\$ : \$f(1) = 1 - 3 + 1 = -1\$.",
              ],
              answer:
                  "Tableau de variations : \$f\$ croît jusqu'au max \$(−1, 3)\$, décroît jusqu'au min \$(1, −1)\$, puis croît. Trois racines réelles, distribuées de part et d'autre.",
            ),
            _interactive('sign_table',
                caption:
                    "Outil pratique : tableaux de signes — base de toute étude de fonction."),
            _checkpoint("Étude de fonction", [
              _q(
                stem:
                    "Si \$f'(x) > 0\$ sur \$]a, b[\$, alors \$f\$ est :",
                choices: [
                  "constante sur \$]a,b[\$",
                  "décroissante sur \$]a,b[\$",
                  "croissante sur \$]a,b[\$",
                  "ne dit rien",
                ],
                correct: 2,
                explanation:
                    "Dérivée strictement positive ⟹ fonction strictement croissante. C'est la règle fondamentale.",
              ),
              _q(
                stem:
                    "Un point où \$f'\$ s'annule en changeant de signe est :",
                choices: [
                  "un point d'inflexion",
                  "un extremum local",
                  "une asymptote",
                  "un point de discontinuité",
                ],
                correct: 1,
                explanation:
                    "Maximum si \$f'\$ passe de \$+\$ à \$-\$ ; minimum si elle passe de \$-\$ à \$+\$.",
              ),
            ]),
          ],
        ),
      ],
    );

// ----------------------------------------------------------------------------
// Chapter 3 — Suites numériques
// ----------------------------------------------------------------------------

Map<String, dynamic> _ch3Suites() => _lesson(
      titleFr: 'Suites numériques',
      subtitleFr:
          "Des suites arithmétiques et géométriques aux suites récurrentes.",
      sections: [
        _section(
          kind: 'prerequisite',
          titleFr: 'Prérequis : qu\'est-ce qu\'une suite ?',
          eyebrowFr: 'PRÉREQUIS',
          estimatedMinutes: '3',
          blocks: [
            _p("Une **suite numérique** \$(u_n)\$ est une fonction qui à chaque entier \$n\\in\\mathbb{N}\$ associe un nombre réel \$u_n\$. Tu peux la voir comme une liste infinie ordonnée : \$u_0, u_1, u_2, \\ldots\$."),
            _p("Une suite peut être définie de deux façons : **explicite** (\$u_n = f(n)\$, on calcule directement le terme \$n\$) ou **récurrente** (\$u_{n+1} = f(u_n)\$, chaque terme dépend du précédent)."),
            _checkpoint("Notation et premiers termes", [
              _q(
                stem:
                    "Soit \$(u_n)\$ définie par \$u_n = 2n + 1\$. Que vaut \$u_3\$ ?",
                choices: ['\$5\$', '\$6\$', '\$7\$', '\$8\$'],
                correct: 2,
                explanation: "\$u_3 = 2 \\times 3 + 1 = 7\$.",
              ),
              _q(
                stem:
                    "Soit \$(v_n)\$ définie par \$v_0 = 1\$ et \$v_{n+1} = 3 v_n\$. Que vaut \$v_2\$ ?",
                choices: ['\$3\$', '\$6\$', '\$9\$', '\$27\$'],
                correct: 2,
                explanation:
                    "\$v_1 = 3 v_0 = 3\$, puis \$v_2 = 3 v_1 = 9\$.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'Suites arithmétiques et géométriques',
          eyebrowFr: 'CONCEPT',
          estimatedMinutes: '5',
          blocks: [
            _h("Suite arithmétique : on ajoute toujours la même chose"),
            _f("u_{n+1} = u_n + r", "Une suite est arithmétique de raison \$r\$ si chaque terme s'obtient en ajoutant \$r\$ au précédent."),
            _f("u_n = u_0 + n r", "Forme explicite — utile quand on veut un terme lointain sans calculer tous les précédents."),
            _f("S_n = u_0 + u_1 + \\cdots + u_n = (n+1) \\cdot \\frac{u_0 + u_n}{2}",
                "Somme des \$n+1\$ premiers termes — moyenne des extrêmes × nombre de termes."),
            _h("Suite géométrique : on multiplie toujours par la même chose"),
            _f("u_{n+1} = q \\cdot u_n", "Suite géométrique de raison \$q\$ — chaque terme est obtenu en multipliant le précédent par \$q\$."),
            _f("u_n = u_0 \\cdot q^n", "Forme explicite."),
            _f("S_n = u_0 \\cdot \\frac{1 - q^{n+1}}{1 - q} \\quad (q \\ne 1)",
                "Somme des \$n+1\$ premiers termes."),
            _example(
              title: "Suite arithmétique",
              problem:
                  "Soit \$(u_n)\$ arithmétique, \$u_0 = 5\$, \$r = 3\$. Calcule \$u_{10}\$ et \$S_{10} = u_0 + u_1 + \\cdots + u_{10}\$.",
              steps: [
                "\$u_n = u_0 + nr\$. Donc \$u_{10} = 5 + 10 \\times 3 = 35\$.",
                "\$S_{10} = 11 \\cdot \\frac{u_0 + u_{10}}{2} = 11 \\cdot \\frac{5 + 35}{2} = 11 \\cdot 20 = 220\$.",
              ],
              answer: "\$u_{10} = 35\$, \$S_{10} = 220\$.",
            ),
            _example(
              title: "Suite géométrique",
              problem: "Soit \$(v_n)\$ géométrique, \$v_0 = 2\$, \$q = 3\$. Calcule \$v_5\$ et \$S_5\$.",
              steps: [
                "\$v_n = v_0 q^n\$. Donc \$v_5 = 2 \\cdot 3^5 = 2 \\cdot 243 = 486\$.",
                "\$S_5 = 2 \\cdot \\frac{1 - 3^6}{1 - 3} = 2 \\cdot \\frac{1 - 729}{-2} = 728\$.",
              ],
              answer: "\$v_5 = 486\$, \$S_5 = 728\$.",
            ),
            _interactive('sequence_viz',
                caption:
                    "Visualise les premiers termes d'une suite et son comportement à long terme."),
            _checkpoint("Identifier et calculer", [
              _q(
                stem:
                    "Soit \$(u_n)\$ arithmétique, \$u_0 = 7\$, \$u_5 = 22\$. Quelle est la raison ?",
                choices: ['\$2\$', '\$3\$', '\$4\$', '\$5\$'],
                correct: 1,
                explanation: "\$u_5 = u_0 + 5r\$ donne \$22 = 7 + 5r\$, soit \$r = 3\$.",
              ),
              _q(
                stem: "Soit \$(v_n)\$ géométrique de raison \$q = 2\$, \$v_0 = 5\$. \$v_3\$ ?",
                choices: ['\$10\$', '\$20\$', '\$40\$', '\$80\$'],
                correct: 2,
                explanation: "\$v_3 = 5 \\cdot 2^3 = 5 \\cdot 8 = 40\$.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'Convergence : intuition et critères',
          eyebrowFr: 'CONVERGENCE',
          estimatedMinutes: '5',
          blocks: [
            _p("Une suite **converge** vers \$L\$ si ses termes se rapprochent indéfiniment de \$L\$ quand \$n\$ devient grand. On note \$\\lim_{n\\to+\\infty} u_n = L\$. Sinon, on dit qu'elle **diverge** (vers \$\\pm\\infty\$ ou en oscillant)."),
            _h("Suites de référence"),
            _f("\\lim_{n\\to+\\infty} \\frac{1}{n} = 0 \\qquad \\lim_{n\\to+\\infty} \\frac{1}{n^k} = 0 \\ (k>0)",
                "Toutes les puissances négatives de \$n\$ tendent vers 0."),
            _f("\\lim_{n\\to+\\infty} q^n = \\begin{cases} 0 & \\text{si } |q|<1 \\\\ 1 & \\text{si } q=1 \\\\ +\\infty & \\text{si } q>1 \\end{cases}",
                "Comportement asymptotique d'une géométrique selon la raison."),
            _callout('insight', "Théorèmes de comparaison",
                "Si \$u_n \\le v_n\$ pour tout \$n\$ assez grand et \$\\lim u_n = +\\infty\$, alors \$\\lim v_n = +\\infty\$. **Théorème des gendarmes** : si \$u_n \\le w_n \\le v_n\$ et \$\\lim u_n = \\lim v_n = L\$, alors \$\\lim w_n = L\$."),
            _example(
              title: "Limite d'une suite",
              problem: "Calcule \$\\lim_{n \\to +\\infty} \\dfrac{2n + 1}{n + 3}\$.",
              steps: [
                "Numérateur et dénominateur tendent vers \$+\\infty\$. Forme indéterminée \$\\infty/\\infty\$.",
                "Divise haut et bas par \$n\$ : \$\\frac{2n+1}{n+3} = \\frac{2 + 1/n}{1 + 3/n}\$.",
                "Quand \$n \\to +\\infty\$, \$1/n \\to 0\$ et \$3/n \\to 0\$.",
                "Donc la limite vaut \$\\frac{2}{1} = 2\$.",
              ],
              answer: "\$\\lim_{n\\to+\\infty} \\dfrac{2n+1}{n+3} = 2\$.",
            ),
            _interactive('sequence_viz',
                caption:
                    "Observe la convergence : les termes s'agglutinent autour d'une valeur limite."),
            _checkpoint("Convergence", [
              _q(
                stem: "Que vaut \$\\lim_{n\\to+\\infty} \\left(\\frac{1}{2}\\right)^n\$ ?",
                choices: ['\$0\$', '\$1\$', '\$1/2\$', "\$+\\infty\$"],
                correct: 0,
                explanation: "\$|q| = 1/2 < 1\$, donc la géométrique tend vers 0.",
              ),
              _q(
                stem: "La suite \$u_n = (-1)^n\$ :",
                choices: [
                  "converge vers 0",
                  "converge vers 1",
                  "converge vers \$-1\$",
                  "ne converge pas",
                ],
                correct: 3,
                explanation:
                    "Elle oscille entre 1 (\$n\$ pair) et \$-1\$ (\$n\$ impair). Pas de limite unique.",
              ),
              _q(
                stem: "\$\\lim_{n\\to+\\infty} \\dfrac{n^2 + 1}{n+5}\$ vaut :",
                choices: ['\$0\$', '\$1\$', "\$+\\infty\$", '\$2\$'],
                correct: 2,
                explanation:
                    "Numérateur de degré 2, dénominateur de degré 1. Le numérateur l'emporte ⟹ limite \$+\\infty\$.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'synthesis',
          titleFr: "Suites récurrentes \$u_{n+1} = f(u_n)\$",
          eyebrowFr: 'RÉCURRENCE',
          estimatedMinutes: '6',
          blocks: [
            _p("Beaucoup de problèmes du Bac portent sur des suites définies par récurrence : \$u_{n+1} = f(u_n)\$ pour une certaine fonction \$f\$. Comprendre leur comportement demande deux outils."),
            _h("1. Le raisonnement par récurrence"),
            _p("Pour démontrer une propriété \$P(n)\$ pour tout \$n \\ge n_0\$ : montre **(initialisation)** que \$P(n_0)\$ est vraie, puis **(hérédité)** que si \$P(n)\$ est vraie alors \$P(n+1)\$ l'est aussi."),
            _h("2. Le point fixe"),
            _p("Si \$(u_n)\$ converge vers \$L\$ et que \$f\$ est continue, alors \$L\$ est un **point fixe** de \$f\$ : \$f(L) = L\$. Trouver les points fixes de \$f\$ donne les **candidats** de limite."),
            _example(
              title: "Étude complète d'une suite récurrente",
              problem:
                  "Soit \$(u_n)\$ définie par \$u_0 = 0\$ et \$u_{n+1} = \\sqrt{u_n + 2}\$. Étudie \$(u_n)\$.",
              steps: [
                "**Recherche du point fixe.** Si la limite \$L\$ existe, elle vérifie \$L = \\sqrt{L+2}\$, donc \$L^2 = L+2\$, soit \$L^2 - L - 2 = 0\$. Solutions : \$L = 2\$ ou \$L = -1\$. Comme \$u_n \\ge 0\$, on garde \$L = 2\$.",
                "**\$(u_n)\$ est majorée par 2.** On montre par récurrence que \$u_n \\le 2\$. Initialisation : \$u_0 = 0 \\le 2\$ ✓. Hérédité : si \$u_n \\le 2\$, alors \$u_n + 2 \\le 4\$, donc \$\\sqrt{u_n+2} \\le 2\$, soit \$u_{n+1} \\le 2\$ ✓.",
                "**\$(u_n)\$ est croissante.** On vérifie \$u_{n+1} \\ge u_n\$ ⟺ \$\\sqrt{u_n+2} \\ge u_n\$ ⟺ \$u_n + 2 \\ge u_n^2\$ (vrai car \$u_n \\le 2\$).",
                "**Conclusion.** \$(u_n)\$ croissante et majorée par 2 ⟹ elle converge. Sa limite est l'unique point fixe \$L = 2\$.",
              ],
              answer:
                  "\$(u_n)\$ converge vers \$2\$ — la suite « grimpe » vers son point fixe à partir de \$u_0 = 0\$.",
            ),
            _interactive('sequence_viz',
                caption:
                    "Diagramme en escalier (cobweb) : visualise la convergence vers le point fixe."),
            _tryIt(
              title: "À toi",
              problem:
                  "Soit \$(v_n)\$ définie par \$v_0 = 4\$ et \$v_{n+1} = \\frac{v_n}{2} + 1\$. Trouve son point fixe.",
              hint: "Pose \$L = \\frac{L}{2} + 1\$ et résous.",
              solution:
                  "\$L = L/2 + 1 \\Rightarrow L/2 = 1 \\Rightarrow L = 2\$. C'est l'unique point fixe — la limite de \$(v_n)\$.",
            ),
            _checkpoint("Récurrence et point fixe", [
              _q(
                stem:
                    "Si \$u_{n+1} = \\frac{u_n + 6}{2}\$ converge vers \$L\$, alors \$L\$ vaut :",
                choices: ['\$3\$', '\$6\$', '\$0\$', '\$12\$'],
                correct: 1,
                explanation:
                    "Point fixe : \$L = (L+6)/2\$, soit \$2L = L + 6\$, donc \$L = 6\$.",
              ),
              _q(
                stem:
                    "Une suite croissante et majorée :",
                choices: [
                  "diverge toujours",
                  "n'a pas de comportement clair",
                  "converge",
                  "tend vers \$+\\infty\$",
                ],
                correct: 2,
                explanation:
                    "C'est le théorème de la convergence monotone — pilier des suites récurrentes.",
              ),
            ]),
          ],
        ),
      ],
    );

// ----------------------------------------------------------------------------
// Chapter 4 — Lois de Newton (Physique)
// ----------------------------------------------------------------------------

Map<String, dynamic> _ch4Newton() => _lesson(
      titleFr: 'Lois de Newton',
      subtitleFr:
          "Du principe d'inertie à l'application : MRU, MRUV, plan incliné.",
      sections: [
        _section(
          kind: 'prerequisite',
          titleFr: 'Prérequis : vecteurs et cinématique',
          eyebrowFr: 'PRÉREQUIS',
          estimatedMinutes: '4',
          blocks: [
            _p("La mécanique de Newton parle le langage des **vecteurs**. Une force, une vitesse, une accélération : ce sont des vecteurs (avec une direction, un sens, une norme), pas juste des nombres."),
            _f("\\vec{v} = \\frac{d\\vec{OM}}{dt} \\qquad \\vec{a} = \\frac{d\\vec{v}}{dt}",
                "Vitesse = dérivée de la position. Accélération = dérivée de la vitesse."),
            _p("Sur un repère cartésien, on projette : \$\\vec{v} = (v_x, v_y, v_z)\$. Une dérivée temporelle se note avec un point : \$\\dot{x}\$ pour \$dx/dt\$."),
            _checkpoint("Vecteurs et cinématique", [
              _q(
                stem:
                    "Un mobile a pour position \$x(t) = 3t^2 + 5\$. Sa vitesse à \$t=2\$s vaut :",
                choices: ['\$6\$ m/s', '\$12\$ m/s', '\$17\$ m/s', '\$3\$ m/s'],
                correct: 1,
                explanation:
                    "\$v(t) = \\dot{x} = 6t\$. À \$t=2\$s : \$v = 12\$ m/s.",
              ),
              _q(
                stem:
                    "Une accélération constante de \$2\$ m/s² signifie que :",
                choices: [
                  "la vitesse est constante",
                  "la vitesse augmente de \$2\$ m/s chaque seconde",
                  "la position est constante",
                  "le mobile est immobile",
                ],
                correct: 1,
                explanation:
                    "Accélération = variation de vitesse par unité de temps. \$2\$ m/s² ⟹ \$+2\$ m/s par seconde.",
              ),
              _q(
                stem:
                    "Un vecteur \$\\vec{F}\$ a une norme de 10 N et fait un angle de 60° avec l'axe Ox. Sa composante \$F_x\$ vaut :",
                choices: ['\$0\$ N', '\$5\$ N', '\$10\$ N', '\$8{,}66\$ N'],
                correct: 1,
                explanation: "\$F_x = F \\cos 60° = 10 \\times 0{,}5 = 5\$ N.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'Première et deuxième lois : inertie et \$\\Sigma \\vec{F} = m\\vec{a}\$',
          eyebrowFr: 'CONCEPT',
          estimatedMinutes: '6',
          blocks: [
            _h("Première loi : le principe d'inertie"),
            _p("Dans un référentiel galiléen (terrestre approximé), un objet sur lequel la **somme des forces est nulle** reste immobile s'il l'était, ou continue en mouvement rectiligne uniforme. **Pas de force ⟹ pas de changement de mouvement.**"),
            _f("\\sum \\vec{F} = \\vec{0} \\iff \\vec{v} = \\overrightarrow{\\text{cste}}",
                "Principe d'inertie : équilibre ⟺ mouvement rectiligne uniforme (ou repos)."),
            _h("Deuxième loi : la relation fondamentale de la dynamique"),
            _f("\\sum \\vec{F} = m \\vec{a}",
                "RFD — la somme vectorielle des forces appliquées à un solide de masse \$m\$ est égale à \$m \\vec{a}\$."),
            _p("Cette équation est **vectorielle** : on la projette sur les axes du repère. Sur un plan, c'est typiquement un système de deux équations scalaires (Ox et Oy)."),
            _interactive('force_diagram',
                caption:
                    "Diagramme des forces : visualise les vecteurs sur un objet et leur résultante."),
            _example(
              title: "Solide sur plan incliné (sans frottement)",
              problem:
                  "Un solide de masse \$m = 2\$ kg glisse sans frottement sur un plan incliné de 30° par rapport à l'horizontale. Détermine son accélération.",
              steps: [
                "**Bilan des forces** : poids \$\\vec{P}\$ (vertical, vers le bas) et réaction normale \$\\vec{R}_n\$ (perpendiculaire au plan).",
                "**Repère** : axe \$x\$ le long du plan vers le bas, axe \$y\$ perpendiculaire au plan.",
                "**Projection RFD sur \$x\$** : \$P \\sin\\alpha = m a_x\$, soit \$mg \\sin\\alpha = m a_x\$.",
                "**Simplification** : \$a_x = g \\sin\\alpha = 9{,}81 \\times \\sin 30° = 9{,}81 \\times 0{,}5 \$",
              ],
              answer: "\$a_x \\approx 4{,}9\$ m/s² — le long du plan, vers le bas. La réaction normale équilibre la composante perpendiculaire du poids ; elle ne contribue pas à l'accélération.",
            ),
            _checkpoint("Inertie et RFD", [
              _q(
                stem:
                    "Un objet en mouvement à vitesse constante en ligne droite est soumis à :",
                choices: [
                  "aucune force",
                  "des forces équilibrées (somme nulle)",
                  "une force motrice unique",
                  "uniquement son poids",
                ],
                correct: 1,
                explanation:
                    "\$\\Sigma \\vec{F} = \\vec{0}\$ — équivalent à mouvement uniforme. Il peut très bien y avoir plusieurs forces, mais leur somme est nulle.",
              ),
              _q(
                stem:
                    "Si \$\\Sigma \\vec{F} = 10\\,\\vec{i}\$ N s'applique à un objet de \$m = 2\$ kg, son accélération vaut :",
                choices: ["\$5\\,\\vec{i}\$ m/s²", "\$20\\,\\vec{i}\$ m/s²", "\$10\\,\\vec{i}\$ m/s²", "\$0\$"],
                correct: 0,
                explanation: "RFD : \$\\vec{a} = \\vec{F}/m = 10/2 \\cdot \\vec{i} = 5\\,\\vec{i}\$ m/s².",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: "Troisième loi : action et réaction",
          eyebrowFr: 'INTERACTION',
          estimatedMinutes: '4',
          blocks: [
            _p("Quand un objet \$A\$ exerce une force sur un objet \$B\$, alors \$B\$ exerce sur \$A\$ une force **opposée** : même direction, même intensité, sens contraire."),
            _f("\\vec{F}_{A \\to B} = -\\vec{F}_{B \\to A}", "Loi de l'action-réaction (3ème loi)."),
            _callout('pitfall', 'Erreur classique',
                "Action et réaction s'appliquent **à des objets DIFFÉRENTS**. Elles ne s'annulent jamais entre elles. Quand on dit « le sol pousse mes pieds vers le haut » et « mes pieds poussent le sol vers le bas », ce sont deux forces sur deux corps distincts. Sur le bilan des forces sur **moi**, on n'a que celle qui m'est appliquée."),
            _example(
              title: "Marche et propulsion",
              problem:
                  "Quand tu marches, qu'est-ce qui te fait avancer ?",
              steps: [
                "Quand tu pousses le sol vers l'arrière (force \$\\vec{F}_{\\text{pied}\\to\\text{sol}}\$)…",
                "…le sol te pousse vers l'avant avec \$\\vec{F}_{\\text{sol}\\to\\text{pied}} = -\\vec{F}_{\\text{pied}\\to\\text{sol}}\$.",
                "C'est cette **réaction du sol** sur ton pied qui te fait avancer — pas tes muscles directement.",
              ],
              answer:
                  "C'est la 3ème loi de Newton : sans le frottement (et donc la réaction du sol), pas de marche possible. Sur la glace mouillée, tu glisses car la réaction tangentielle est trop faible.",
            ),
            _checkpoint("Action-réaction", [
              _q(
                stem:
                    "Un livre posé sur une table. La réaction de la table sur le livre :",
                choices: [
                  "annule le poids du livre (donc somme = 0)",
                  "est opposée à l'action du livre sur la table — pas au poids",
                  "est plus grande que le poids",
                  "est nulle",
                ],
                correct: 1,
                explanation:
                    "La réaction de la table SUR le livre n'est pas la « réaction » du poids. Elle s'oppose à la force que le livre exerce SUR la table (3ème loi). Sur le livre, deux forces s'équilibrent : son poids et la réaction normale — c'est la 1ère loi.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'synthesis',
          titleFr: "Application : mouvement rectiligne",
          eyebrowFr: 'APPLICATION',
          estimatedMinutes: '5',
          blocks: [
            _h("MRU : Mouvement Rectiligne Uniforme"),
            _f("a = 0 \\quad ; \\quad v = v_0 \\quad ; \\quad x(t) = x_0 + v_0 t",
                "Sans accélération, vitesse constante, position linéaire en \$t\$."),
            _h("MRUV : Mouvement Rectiligne Uniformément Varié"),
            _f("a = \\text{cste} \\quad ; \\quad v(t) = v_0 + a t \\quad ; \\quad x(t) = x_0 + v_0 t + \\tfrac{1}{2} a t^2",
                "Avec accélération constante, vitesse linéaire et position quadratique."),
            _f("v^2 - v_0^2 = 2 a (x - x_0)",
                "Relation utile sans \$t\$ — pratique quand on veut une vitesse à une position donnée."),
            _interactive('motion_simulator',
                caption:
                    "Compare MRU et MRUV — joue avec \$v_0\$ et \$a\$, observe \$x(t), v(t), a(t)\$."),
            _example(
              title: "Freinage d'urgence",
              problem:
                  "Une voiture roule à 90 km/h (= 25 m/s). Elle freine avec une décélération constante de \$5\$ m/s². Quelle distance parcourt-elle avant l'arrêt ?",
              steps: [
                "**Données.** \$v_0 = 25\$ m/s, \$v = 0\$ (à l'arrêt), \$a = -5\$ m/s² (négatif car décélération).",
                "**Outil.** On connaît les vitesses, on cherche la distance — relation sans \$t\$ : \$v^2 - v_0^2 = 2a(x - x_0)\$.",
                "**Application.** \$0 - 25^2 = 2 \\cdot (-5) \\cdot d\$, soit \$-625 = -10 d\$, donc \$d = 62{,}5\$ m.",
              ],
              answer:
                  "La voiture parcourt **62,5 mètres** avant de s'arrêter — environ 6 longueurs de voiture.",
            ),
            _checkpoint("MRU et MRUV", [
              _q(
                stem:
                    "Un objet en MRU parcourt 100 m en 4 s. Sa vitesse est :",
                choices: ['\$10\$ m/s', '\$25\$ m/s', '\$400\$ m/s', '\$0{,}25\$ m/s'],
                correct: 1,
                explanation: "MRU : \$v = d/t = 100/4 = 25\$ m/s.",
              ),
              _q(
                stem:
                    "Un mobile en MRUV part de \$v_0 = 0\$ avec \$a = 2\$ m/s². Sa vitesse à \$t = 5\$ s vaut :",
                choices: ['\$2\$ m/s', '\$5\$ m/s', '\$10\$ m/s', '\$25\$ m/s'],
                correct: 2,
                explanation: "\$v = v_0 + at = 0 + 2 \\times 5 = 10\$ m/s.",
              ),
              _q(
                stem:
                    "Distance parcourue dans le même cas (\$v_0=0\$, \$a=2\$ m/s², \$t=5\$ s) :",
                choices: ['\$10\$ m', '\$25\$ m', '\$50\$ m', '\$5\$ m'],
                correct: 1,
                explanation:
                    "\$x = \\frac{1}{2} a t^2 = \\frac{1}{2} \\times 2 \\times 25 = 25\$ m.",
              ),
            ]),
          ],
        ),
      ],
    );

// ----------------------------------------------------------------------------
// Chapter 5 — Oscillations RLC libres
// ----------------------------------------------------------------------------

Map<String, dynamic> _ch5Rlc() => _lesson(
      titleFr: 'Oscillations RLC libres',
      subtitleFr:
          "Trois régimes possibles selon l'amortissement, équation différentielle, pseudo-période.",
      sections: [
        _section(
          kind: 'prerequisite',
          titleFr: 'Prérequis : condensateur, bobine, équation diff',
          eyebrowFr: 'PRÉREQUIS',
          estimatedMinutes: '4',
          blocks: [
            _p("Un circuit RLC, c'est l'association en série d'un condensateur \$(C)\$, d'une bobine \$(L)\$ et d'un conducteur ohmique \$(R)\$. Avant de l'analyser, rappel des lois constitutives."),
            _f("u_C = \\frac{q}{C} \\quad ; \\quad i = \\frac{dq}{dt} = C \\frac{du_C}{dt}",
                "Condensateur : tension proportionnelle à la charge ; courant = dérivée de la charge."),
            _f("u_L = L \\frac{di}{dt}",
                "Bobine : tension proportionnelle à la dérivée temporelle du courant."),
            _f("u_R = R i", "Conducteur ohmique : loi d'Ohm."),
            _checkpoint("Lois constitutives", [
              _q(
                stem:
                    "Un condensateur de capacité \$C = 10\\,\\mu F\$ porte la charge \$q = 5\\times 10^{-5}\$ C. Sa tension vaut :",
                choices: ["\$0{,}5\$ V", "\$2\$ V", "\$5\$ V", "\$50\$ V"],
                correct: 2,
                explanation:
                    "\$u = q/C = 5\\times10^{-5} / (10\\times 10^{-6}) = 5\$ V.",
              ),
              _q(
                stem:
                    "Une bobine \$L = 0{,}1\$ H. Si \$di/dt = 4\$ A/s, sa tension vaut :",
                choices: ["\$0{,}025\$ V", "\$0{,}4\$ V", "\$4\$ V", "\$40\$ V"],
                correct: 1,
                explanation: "\$u_L = L\\,di/dt = 0{,}1 \\times 4 = 0{,}4\$ V.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'Le circuit RLC série : équation différentielle',
          eyebrowFr: 'ÉQUATION',
          estimatedMinutes: '5',
          blocks: [
            _p("On charge le condensateur, puis on ferme l'interrupteur. La somme des tensions sur la maille s'annule (loi des mailles) :"),
            _f("u_C + u_R + u_L = 0",
                "Loi des mailles dans un circuit RLC série en évolution libre."),
            _p("On exprime tout en fonction de \$q\$, en utilisant \$i = dq/dt\$ et \$di/dt = d^2q/dt^2\$ :"),
            _f("\\frac{q}{C} + R \\frac{dq}{dt} + L \\frac{d^2 q}{dt^2} = 0",
                "Équation différentielle linéaire du second ordre à coefficients constants."),
            _f("L \\ddot{q} + R \\dot{q} + \\frac{q}{C} = 0",
                "Forme compacte (notation Newton)."),
            _callout('insight', "L'analogie mécanique",
                "Cette équation est exactement celle d'un système masse-ressort avec frottement : \$m \\ddot{x} + f \\dot{x} + k x = 0\$, où \$L \\leftrightarrow m\$, \$R \\leftrightarrow f\$, \$1/C \\leftrightarrow k\$. La même physique avec d'autres mots."),
            _checkpoint("Équation différentielle RLC", [
              _q(
                stem:
                    "L'équation \$L \\ddot q + R \\dot q + q/C = 0\$ est :",
                choices: [
                  "linéaire d'ordre 1",
                  "non linéaire d'ordre 2",
                  "linéaire d'ordre 2 à coefficients constants",
                  "linéaire avec second membre",
                ],
                correct: 2,
                explanation:
                    "Coefficients \$L, R, 1/C\$ tous constants. Ordre 2 (\$\\ddot q\$). Pas de second membre (régime libre).",
              ),
              _q(
                stem:
                    "L'analogie mécanique RLC ↔ masse-ressort avec frottement : qu'est-ce qui correspond au coefficient de frottement \$f\$ ?",
                choices: ["\$L\$", "\$R\$", "\$C\$", "\$1/C\$"],
                correct: 1,
                explanation:
                    "\$R\$ — la résistance dissipe l'énergie comme le frottement.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'Les trois régimes',
          eyebrowFr: 'RÉGIMES',
          estimatedMinutes: '6',
          blocks: [
            _p("Selon la valeur de \$R\$ comparée à un seuil critique \$R_c = 2\\sqrt{L/C}\$, le système se comporte de trois façons radicalement différentes."),
            _h("Régime apériodique (\$R > R_c\$, fort amortissement)"),
            _p("La charge décroît vers 0 **sans osciller**. Le frottement est si fort que l'oscillation n'a pas le temps de se développer."),
            _h("Régime critique (\$R = R_c\$)"),
            _p("Cas limite — décroissance la plus rapide possible **sans oscillation**. On l'utilise quand on veut amortir vite (suspensions de voiture)."),
            _h("Régime pseudo-périodique (\$R < R_c\$, faible amortissement)"),
            _p("La charge **oscille** avec une amplitude qui décroît exponentiellement. C'est le régime intéressant — celui qu'on étudie au Bac."),
            _f("q(t) = Q_0 e^{-t/\\tau} \\cos(\\omega t + \\varphi)",
                "Solution typique en régime pseudo-périodique. \$\\tau = 2L/R\$ est la constante de temps d'amortissement, \$\\omega\$ est la pseudo-pulsation."),
            _interactive('rlc',
                caption:
                    "Joue avec \$R\$, \$L\$, \$C\$ — passe les trois régimes en faisant varier \$R\$."),
            _example(
              title: "Identifier le régime",
              problem:
                  "Soit un circuit avec \$L = 0{,}1\$ H, \$C = 10\\,\\mu F\$. Quelle est la valeur critique \$R_c\$ ? Si \$R = 50\\,\\Omega\$, dans quel régime sommes-nous ?",
              steps: [
                "\$R_c = 2\\sqrt{L/C} = 2\\sqrt{0{,}1/(10\\times 10^{-6})} = 2\\sqrt{10000} = 2 \\times 100\$",
                "\$R_c = 200\\,\\Omega\$.",
                "Comparaison : \$R = 50 < R_c = 200\$, donc \$R < R_c\$.",
              ],
              answer:
                  "**Régime pseudo-périodique** — la charge va osciller en s'amortissant.",
            ),
            _checkpoint("Trois régimes", [
              _q(
                stem: "Régime sans oscillation, retour rapide à zéro :",
                choices: [
                  "pseudo-périodique",
                  "apériodique",
                  "critique",
                  "instable",
                ],
                correct: 2,
                explanation:
                    "C'est le régime critique — exactement le seuil où l'oscillation disparaît.",
              ),
              _q(
                stem:
                    "Si \$R \\to 0\$ (très peu d'amortissement), le régime devient :",
                choices: [
                  "apériodique",
                  "périodique pur",
                  "instable",
                  "constant",
                ],
                correct: 1,
                explanation:
                    "Sans \$R\$, oscillations sinusoïdales de pulsation propre \$\\omega_0 = 1/\\sqrt{LC}\$ — c'est l'oscillateur idéal.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'synthesis',
          titleFr: 'Pseudo-période et amortissement',
          eyebrowFr: 'SYNTHÈSE',
          estimatedMinutes: '5',
          blocks: [
            _p("En régime pseudo-périodique avec faible amortissement (\$R \\ll R_c\$), la pseudo-période \$T\$ est proche de la période propre \$T_0\$ de l'oscillateur idéal sans amortissement."),
            _f("T_0 = 2\\pi \\sqrt{L C}",
                "Période propre — celle d'un LC pur, sans dissipation. Première chose à calculer pour estimer \$T\$."),
            _f("\\tau = \\frac{2L}{R}",
                "Constante de temps d'amortissement. Au bout de quelques \$\\tau\$, l'amplitude est négligeable."),
            _example(
              title: "Calcul Bac-style",
              problem:
                  "Un circuit RLC série a \$L = 0{,}5\$ H, \$C = 1\\,\\mu F\$, \$R = 20\\,\\Omega\$. Calcule la pseudo-période et la constante de temps d'amortissement.",
              steps: [
                "**Période propre** : \$T_0 = 2\\pi \\sqrt{LC} = 2\\pi \\sqrt{0{,}5 \\times 10^{-6}}\$.",
                "Calcul : \$\\sqrt{0{,}5 \\times 10^{-6}} = \\sqrt{5 \\times 10^{-7}} \\approx 7{,}07 \\times 10^{-4}\$.",
                "\$T_0 \\approx 2\\pi \\times 7{,}07 \\times 10^{-4} \\approx 4{,}44\$ ms. C'est aussi (à très peu près) la pseudo-période.",
                "**Constante de temps d'amortissement** : \$\\tau = 2L/R = 2 \\times 0{,}5 / 20 = 0{,}05\$ s = 50 ms.",
                "**Comparaison** : \$\\tau \\gg T_0\$ — l'oscillation a le temps de se développer sur plusieurs périodes avant de s'éteindre.",
              ],
              answer:
                  "\$T \\approx 4{,}44\$ ms ; \$\\tau \\approx 50\$ ms — environ une dizaine de pseudo-oscillations visibles.",
            ),
            _checkpoint("Pseudo-période et amortissement", [
              _q(
                stem:
                    "Si on **double** \$L\$ tout en gardant \$C\$, comment évolue la période propre \$T_0\$ ?",
                choices: [
                  "\$T_0\$ est divisée par 2",
                  "\$T_0\$ est multipliée par \$\\sqrt{2}\$",
                  "\$T_0\$ est multipliée par 2",
                  "\$T_0\$ ne change pas",
                ],
                correct: 1,
                explanation:
                    "\$T_0 = 2\\pi\\sqrt{LC}\$ : doubler \$L\$ multiplie \$T_0\$ par \$\\sqrt{2}\$.",
              ),
              _q(
                stem:
                    "Pour qu'un RLC pseudo-périodique s'amortisse plus vite, il faut :",
                choices: [
                  "diminuer \$R\$",
                  "augmenter \$R\$",
                  "diminuer \$L\$",
                  "augmenter \$C\$",
                ],
                correct: 1,
                explanation:
                    "Plus \$R\$ est grand, plus \$\\tau = 2L/R\$ est petit ⟹ amortissement plus rapide.",
              ),
            ]),
          ],
        ),
      ],
    );

// ----------------------------------------------------------------------------
// Chapter 6 — Acide-base et pH
// ----------------------------------------------------------------------------

Map<String, dynamic> _ch6AcidBase() => _lesson(
      titleFr: 'Acide-base et pH',
      subtitleFr:
          "De la définition du pH au diagramme de prédominance d'un couple acido-basique.",
      sections: [
        _section(
          kind: 'prerequisite',
          titleFr: 'Prérequis : ions et autoprotolyse de l\'eau',
          eyebrowFr: 'PRÉREQUIS',
          estimatedMinutes: '3',
          blocks: [
            _p("Une **concentration molaire** \$[X]\$ exprime la quantité de matière de \$X\$ par litre de solution, en mol/L (ou mol·L⁻¹)."),
            _p("Dans toute solution aqueuse, deux ions règnent : l'**ion oxonium** \$\\text{H}_3\\text{O}^+\$ (l'ion porteur de l'acidité) et l'**ion hydroxyde** \$\\text{OH}^-\$ (porteur de la basicité)."),
            _f("2 \\text{H}_2\\text{O} \\rightleftharpoons \\text{H}_3\\text{O}^+ + \\text{OH}^-",
                "Autoprotolyse de l'eau — réaction d'équilibre dans toute solution aqueuse."),
            _f("[\\text{H}_3\\text{O}^+] \\cdot [\\text{OH}^-] = K_e = 10^{-14} \\text{ à } 25°C",
                "Produit ionique de l'eau \$K_e\$ — relation **toujours vraie** en solution aqueuse."),
            _checkpoint("Concentrations et autoprotolyse", [
              _q(
                stem:
                    "Dans l'eau pure à 25°C, \$[\\text{H}_3\\text{O}^+]\$ vaut :",
                choices: [
                  "\$10^{-7}\$ mol/L",
                  "\$10^{-14}\$ mol/L",
                  "\$10^7\$ mol/L",
                  "0",
                ],
                correct: 0,
                explanation:
                    "Eau pure : \$[\\text{H}_3\\text{O}^+] = [\\text{OH}^-]\$ et leur produit vaut \$10^{-14}\$ ⟹ chacun vaut \$10^{-7}\$ mol/L.",
              ),
              _q(
                stem:
                    "Si \$[\\text{H}_3\\text{O}^+] = 10^{-3}\$ mol/L, alors \$[\\text{OH}^-]\$ vaut :",
                choices: [
                  "\$10^{-11}\$ mol/L",
                  "\$10^{-3}\$ mol/L",
                  "\$10^{-14}\$ mol/L",
                  "\$10^{-17}\$ mol/L",
                ],
                correct: 0,
                explanation:
                    "\$[\\text{OH}^-] = K_e / [\\text{H}_3\\text{O}^+] = 10^{-14} / 10^{-3} = 10^{-11}\$ mol/L.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'Définition du pH',
          eyebrowFr: 'CONCEPT',
          estimatedMinutes: '5',
          blocks: [
            _p("Les concentrations d'ions oxonium varient sur des ordres de grandeur énormes (de \$10^{-1}\$ à \$10^{-14}\$ mol/L). Pour les manipuler, on prend leur logarithme. C'est l'idée du pH."),
            _f("\\text{pH} = -\\log [\\text{H}_3\\text{O}^+]",
                "Définition du pH — sans unité. En pratique, varie de 0 (très acide) à 14 (très basique). pH = 7 ⟺ neutre à 25°C."),
            _f("[\\text{H}_3\\text{O}^+] = 10^{-\\text{pH}}",
                "Réciproque — utile pour passer du pH à la concentration."),
            _interactive('acid_base_ph',
                caption:
                    "Manipule la concentration et le pKa — observe le pH et le diagramme de prédominance."),
            _example(
              title: "pH d'un acide fort",
              problem:
                  "Calcule le pH d'une solution d'acide chlorhydrique HCl de concentration \$C = 10^{-2}\$ mol/L.",
              steps: [
                "HCl est un **acide fort** — il se dissocie totalement dans l'eau : \$\\text{HCl} + \\text{H}_2\\text{O} \\to \\text{H}_3\\text{O}^+ + \\text{Cl}^-\$.",
                "Donc \$[\\text{H}_3\\text{O}^+] = C = 10^{-2}\$ mol/L.",
                "\$\\text{pH} = -\\log(10^{-2}) = 2\$.",
              ],
              answer: "\$\\text{pH} = 2\$.",
            ),
            _example(
              title: "pH d'une base forte",
              problem:
                  "Calcule le pH d'une solution de soude NaOH de concentration \$C = 10^{-3}\$ mol/L.",
              steps: [
                "NaOH est une **base forte** : \$\\text{NaOH} \\to \\text{Na}^+ + \\text{OH}^-\$. Dissociation totale.",
                "Donc \$[\\text{OH}^-] = C = 10^{-3}\$ mol/L.",
                "\$[\\text{H}_3\\text{O}^+] = K_e/[\\text{OH}^-] = 10^{-14}/10^{-3} = 10^{-11}\$ mol/L.",
                "\$\\text{pH} = -\\log(10^{-11}) = 11\$.",
              ],
              answer: "\$\\text{pH} = 11\$.",
            ),
            _checkpoint("Définition du pH", [
              _q(
                stem:
                    "Si le pH d'une solution est 4, \$[\\text{H}_3\\text{O}^+]\$ vaut :",
                choices: [
                  "\$10^{-4}\$ mol/L",
                  "\$10^{4}\$ mol/L",
                  "\$4\$ mol/L",
                  "\$\\log 4\$ mol/L",
                ],
                correct: 0,
                explanation:
                    "\$[\\text{H}_3\\text{O}^+] = 10^{-\\text{pH}} = 10^{-4}\$ mol/L.",
              ),
              _q(
                stem: "Une solution avec \$\\text{pH} = 9\$ est :",
                choices: [
                  "acide",
                  "neutre",
                  "basique",
                  "ne dit rien",
                ],
                correct: 2,
                explanation: "pH > 7 ⟹ basique.",
              ),
              _q(
                stem:
                    "Si on dilue dix fois une solution acide forte initialement à pH = 3, le nouveau pH vaut environ :",
                choices: ["\$2\$", "\$4\$", "\$6\$", "\$13\$"],
                correct: 1,
                explanation:
                    "Dilution × 10 ⟹ \$[\\text{H}_3\\text{O}^+]\$ divisé par 10 ⟹ pH augmente de 1 ⟹ pH ≈ 4.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'Acides et bases faibles : Ka, pKa',
          eyebrowFr: 'ÉQUILIBRE',
          estimatedMinutes: '6',
          blocks: [
            _p("Tous les acides ne se dissocient pas totalement. Un **acide faible** AH est en équilibre avec sa base conjuguée \$A^-\$ :"),
            _f("\\text{AH} + \\text{H}_2\\text{O} \\rightleftharpoons \\text{A}^- + \\text{H}_3\\text{O}^+",
                "Équilibre acide faible / base conjuguée."),
            _f("K_a = \\frac{[\\text{A}^-][\\text{H}_3\\text{O}^+]}{[\\text{AH}]}",
                "Constante d'acidité. Plus \$K_a\$ est grand, plus l'acide est dissocié — donc plus il est fort."),
            _f("\\text{pK}_a = -\\log K_a",
                "Plus le pKa est petit, plus l'acide est fort. L'acide acétique (\$\\text{CH}_3\\text{COOH}\$) a pKa = 4,75 ; l'acide chlorhydrique a pKa ≈ \$-7\$ — beaucoup plus fort."),
            _example(
              title: "pH d'un acide faible",
              problem:
                  "Calcule le pH d'une solution d'acide acétique \$\\text{CH}_3\\text{COOH}\$ de concentration \$C = 0{,}1\$ mol/L (pKa = 4,75).",
              steps: [
                "Pour un acide faible peu dissocié, l'approximation usuelle donne : \$\\text{pH} = \\frac{1}{2}(\\text{pK}_a - \\log C)\$.",
                "\$\\log(0{,}1) = -1\$, donc \$-\\log C = 1\$.",
                "\$\\text{pH} = \\frac{1}{2}(4{,}75 + 1) = \\frac{5{,}75}{2} = 2{,}875\$.",
              ],
              answer: "\$\\text{pH} \\approx 2{,}9\$. Beaucoup moins acide qu'un acide fort à la même concentration (qui donnerait pH = 1).",
            ),
            _interactive('acid_base_ph',
                caption:
                    "Compare acides forts vs faibles à la même concentration — l'acide faible est moins dissocié."),
            _checkpoint("Ka et pKa", [
              _q(
                stem:
                    "Plus le \$\\text{pK}_a\$ est petit :",
                choices: [
                  "plus l'acide est faible",
                  "plus l'acide est fort",
                  "plus la base est forte",
                  "ne dépend pas de la force de l'acide",
                ],
                correct: 1,
                explanation:
                    "pKa petit ⟺ \$K_a\$ grand ⟺ équilibre déplacé vers la dissociation ⟺ acide fort.",
              ),
              _q(
                stem:
                    "Pour un acide faible AH dissous dans l'eau :",
                choices: [
                  "\$[\\text{AH}]\$ devient nulle",
                  "\$[\\text{AH}]\$ et \$[\\text{A}^-]\$ coexistent à l'équilibre",
                  "\$[\\text{H}_3\\text{O}^+]\$ devient nulle",
                  "le pH vaut toujours 7",
                ],
                correct: 1,
                explanation:
                    "C'est la définition même d'un acide faible : équilibre, dissociation partielle.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'synthesis',
          titleFr: "Diagramme de prédominance",
          eyebrowFr: 'SYNTHÈSE',
          estimatedMinutes: '4',
          blocks: [
            _p("Le diagramme de prédominance résume **quelle forme du couple AH/A⁻ domine** selon le pH de la solution. C'est l'outil pratique du Bac."),
            _f("\\text{pH} < \\text{pK}_a \\Rightarrow [\\text{AH}] > [\\text{A}^-] \\quad ; \\quad \\text{pH} > \\text{pK}_a \\Rightarrow [\\text{A}^-] > [\\text{AH}]",
                "Règle de prédominance — le pH compare au pKa, pas à 7."),
            _callout('insight', 'À retenir',
                "À \$\\text{pH} = \\text{pK}_a\$, les deux formes sont en quantités égales. C'est la frontière du diagramme."),
            _example(
              title: "Quelle forme domine ?",
              problem:
                  "Pour le couple \$\\text{CH}_3\\text{COOH}/\\text{CH}_3\\text{COO}^-\$ (pKa = 4,75), quelle forme domine à pH = 5 ? À pH = 3 ?",
              steps: [
                "**À pH = 5** : pH > pKa ⟹ la base \$\\text{CH}_3\\text{COO}^-\$ (acétate) domine.",
                "**À pH = 3** : pH < pKa ⟹ l'acide \$\\text{CH}_3\\text{COOH}\$ domine.",
              ],
              answer:
                  "À pH = 5 : forme basique (acétate). À pH = 3 : forme acide (acide acétique).",
            ),
            _tryIt(
              title: "À toi",
              problem:
                  "Pour l'acide nitreux \$\\text{HNO}_2/\\text{NO}_2^-\$ (pKa = 3,4), à pH = 4, quelle forme prédomine ?",
              hint: "Compare pH au pKa.",
              solution:
                  "pH = 4 > pKa = 3,4 ⟹ la **base \$\\text{NO}_2^-\$** prédomine.",
            ),
            _checkpoint("Diagramme de prédominance", [
              _q(
                stem:
                    "Pour un couple AH/A⁻ avec pKa = 6, à pH = 8 :",
                choices: [
                  "\$[\\text{AH}] > [\\text{A}^-]\$",
                  "\$[\\text{AH}] = [\\text{A}^-]\$",
                  "\$[\\text{A}^-] > [\\text{AH}]\$",
                  "On ne peut pas conclure",
                ],
                correct: 2,
                explanation: "pH > pKa ⟹ la base domine.",
              ),
              _q(
                stem:
                    "À pH = pKa exactement :",
                choices: [
                  "l'acide domine",
                  "la base domine",
                  "les deux formes sont en quantités égales",
                  "le pH ne peut pas être égal au pKa",
                ],
                correct: 2,
                explanation:
                    "C'est la frontière exacte, où \$[\\text{AH}] = [\\text{A}^-]\$.",
              ),
            ]),
          ],
        ),
      ],
    );

// ----------------------------------------------------------------------------
// Chapter 7 — Dosage acide-base
// ----------------------------------------------------------------------------

Map<String, dynamic> _ch7Titration() => _lesson(
      titleFr: 'Dosage acide-base',
      subtitleFr:
          "Lire et exploiter une courbe pH = f(V), trouver l'équivalence, choisir le bon indicateur.",
      sections: [
        _section(
          kind: 'prerequisite',
          titleFr: "Prérequis : équivalence et mole",
          eyebrowFr: 'PRÉREQUIS',
          estimatedMinutes: '3',
          blocks: [
            _p("Doser une solution \$S_a\$ d'**acide** par une solution \$S_b\$ de **base** (de concentration connue), c'est trouver la concentration \$C_a\$ de \$S_a\$. On verse progressivement \$S_b\$ et on mesure le pH. Le moment clé est l'**équivalence**."),
            _f("n_{\\text{acide initial}} = n_{\\text{base versée à l'équivalence}}",
                "À l'équivalence, les quantités de matière des réactifs sont stœchiométriques."),
            _f("C_a V_a = C_b V_{b,\\text{éq}}",
                "Pour un dosage 1:1 (acide monoprotique / base monoprotique). \$V_{b,\\text{éq}}\$ est le volume de base versé pour atteindre l'équivalence."),
            _checkpoint("Équivalence et stœchiométrie", [
              _q(
                stem:
                    "Si on dose 20 mL d'un acide à 0,1 mol/L par une base à 0,05 mol/L, le volume à l'équivalence vaut :",
                choices: ["10 mL", "20 mL", "40 mL", "100 mL"],
                correct: 2,
                explanation:
                    "\$V_{b,\\text{éq}} = C_a V_a / C_b = 0{,}1 \\times 20 / 0{,}05 = 40\$ mL.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'La courbe pH = f(V)',
          eyebrowFr: 'COURBE',
          estimatedMinutes: '6',
          blocks: [
            _p("La forme de la courbe pH = f(V) dépend de la nature des réactifs. **Acide fort + base forte** : courbe régulière avec un saut **brutal** au point d'équivalence, qui se trouve à pH = 7."),
            _p("**Acide faible + base forte** : la courbe est **incurvée au début** (zone tampon, pH ≈ pKa au demi-équivalent), avec un saut moins marqué et un pH d'équivalence > 7."),
            _interactive('titration_simulator',
                caption:
                    "Joue avec acide fort vs faible, change pKa et concentrations. Observe la courbe + l'indicateur coloré."),
            _callout('insight', 'Le saut localise l\'équivalence',
                "C'est la zone où le pH change le plus vite par millilitre versé. Plus l'acide et la base sont forts, plus le saut est marqué — souvent 4 à 6 unités de pH en moins de 1 mL."),
            _checkpoint("Lire une courbe", [
              _q(
                stem:
                    "Le saut brusque sur la courbe pH = f(V) localise :",
                choices: [
                  "le début du dosage",
                  "le point d'équivalence",
                  "la fin du dosage",
                  "rien de particulier",
                ],
                correct: 1,
                explanation:
                    "Le saut signale qu'on bascule brutalement de l'excès d'acide à l'excès de base.",
              ),
              _q(
                stem:
                    "Pour un dosage acide fort / base forte, le pH à l'équivalence vaut :",
                choices: ["\$3\$", "\$5\$", "\$7\$", "\$> 8\$"],
                correct: 2,
                explanation:
                    "À l'équivalence, on a juste le sel \$\\text{NaCl}\$ neutre dans de l'eau ⟹ pH = 7.",
              ),
              _q(
                stem:
                    "Pour un dosage acide faible / base forte, le pH d'équivalence est :",
                choices: [
                  "inférieur à 7",
                  "égal à 7",
                  "supérieur à 7",
                  "imprévisible",
                ],
                correct: 2,
                explanation:
                    "À l'équivalence, on a la base conjuguée du faible \$+\$ eau ⟹ basique ⟹ pH > 7.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'concept',
          titleFr: 'Détermination du point d\'équivalence',
          eyebrowFr: 'MÉTHODE',
          estimatedMinutes: '6',
          blocks: [
            _h("Trois méthodes graphiques"),
            _p("**1. Méthode des tangentes parallèles.** Trace deux tangentes parallèles à la courbe, de part et d'autre du saut. La parallèle équidistante coupe la courbe au point d'équivalence."),
            _p("**2. Méthode de la dérivée.** Trace \$\\frac{d\\text{pH}}{dV}\$ : son maximum est à \$V_\\text{éq}\$. Indispensable pour les dosages où le saut est peu marqué."),
            _p("**3. Lecture directe.** Sur un saut bien marqué, on identifie son milieu visuellement — précis à ±0,1 mL."),
            _interactive('titration_simulator',
                caption:
                    "L'équivalence est marquée d'un point rouge sur la courbe en temps réel."),
            _example(
              title: "Dosage Bac-style",
              problem:
                  "On dose 20 mL d'une solution d'acide acétique de concentration \$C_a\$ inconnue par une solution d'hydroxyde de sodium à \$C_b = 0{,}1\$ mol/L. La courbe montre une équivalence à \$V_{b,\\text{éq}} = 18{,}0\$ mL. Quelle est \$C_a\$ ?",
              steps: [
                "**Relation à l'équivalence** : \$C_a V_a = C_b V_{b,\\text{éq}}\$.",
                "**Application numérique** : \$C_a = \\frac{C_b V_{b,\\text{éq}}}{V_a} = \\frac{0{,}1 \\times 18{,}0}{20}\$.",
                "**Calcul** : \$C_a = 1{,}8/20 = 0{,}09\$ mol/L.",
              ],
              answer: "\$C_a = 0{,}09\$ mol/L = \$9{,}0 \\times 10^{-2}\$ mol/L.",
            ),
            _checkpoint("Détermination de l'équivalence", [
              _q(
                stem:
                    "La méthode la plus fiable pour un saut peu marqué (acide très faible) est :",
                choices: [
                  "lecture directe au milieu du saut",
                  "tangentes parallèles",
                  "dérivée \$d\\text{pH}/dV\$",
                  "moyenne des pH initial et final",
                ],
                correct: 2,
                explanation:
                    "La dérivée a un maximum bien défini même quand le saut est peu visible à l'œil — c'est la méthode quantitative.",
              ),
            ]),
          ],
        ),
        _section(
          kind: 'synthesis',
          titleFr: "Choix de l\'indicateur coloré",
          eyebrowFr: 'INDICATEUR',
          estimatedMinutes: '4',
          blocks: [
            _p("Un indicateur coloré change de couleur sur une **zone de virage** spécifique. Le bon indicateur a une zone de virage qui **contient le pH d'équivalence** du dosage."),
            _h("Les trois indicateurs incontournables"),
            _p("**Hélianthine** (méthyl-orange) : zone de virage 3,1 → 4,4 (rouge → jaune). Adapté aux acides forts dosés par bases faibles (pH éq < 7)."),
            _p("**B.B.T.** (bleu de bromothymol) : zone 6,0 → 7,6 (jaune → bleu). Adapté aux dosages forts/forts (pH éq = 7)."),
            _p("**Phénolphtaléine** : zone 8,2 → 10 (incolore → rose). Adapté aux acides faibles dosés par bases fortes (pH éq > 7)."),
            _example(
              title: "Choisir l'indicateur",
              problem:
                  "Tu doses de l'acide acétique par de la soude. Le pH à l'équivalence vaut environ 8,7. Quel indicateur choisir ?",
              steps: [
                "**pH éq = 8,7.** Cherche un indicateur dont la zone de virage contient 8,7.",
                "Hélianthine (3,1–4,4) : non, trop acide.",
                "B.B.T. (6,0–7,6) : non, trop bas.",
                "Phénolphtaléine (8,2–10) : **oui** — 8,7 est dans la zone.",
              ],
              answer:
                  "Choisir la **phénolphtaléine** — elle vire de l'incolore au rose précisément autour du pH d'équivalence.",
            ),
            _checkpoint("Choix d'indicateur", [
              _q(
                stem:
                    "Pour doser HCl par NaOH, l'indicateur le plus adapté est :",
                choices: [
                  "hélianthine",
                  "B.B.T.",
                  "phénolphtaléine",
                  "tous conviennent",
                ],
                correct: 1,
                explanation:
                    "Acide fort + base forte ⟹ pH éq = 7 ⟹ B.B.T. (zone 6,0–7,6). En pratique, phénolphtaléine fonctionne aussi car le saut est très brutal.",
              ),
              _q(
                stem:
                    "L'hélianthine est adaptée aux dosages où le pH d'équivalence vaut :",
                choices: [
                  "environ 4",
                  "environ 7",
                  "environ 9",
                  "indifférent",
                ],
                correct: 0,
                explanation: "Zone de virage 3,1–4,4 ⟹ pH éq autour de 4.",
              ),
            ]),
          ],
        ),
      ],
    );
