-- ============================================================================
-- Migration 042: Seed SMA (Sciences Mathématiques A) prerequisite edges.
-- ----------------------------------------------------------------------------
-- Closes audit finding E-1 (docs/grounding/known-issues.md): 89 of 108 SMA
-- skills declare prereqs in shared/skill_map_sciences_maths_a.json but the
-- encoder previously discarded them, leaving SMA at 0 edges in the DB.
--
-- Auto-generated by backend/seed/json_encode_sma.dart (extended in Stage 3).
-- Acyclicity verified at encode time via Kahn's algorithm.
-- Curriculum cull applied — 3 edge(s) removed per bac-curriculum
-- review (ADR 0004):
--   - ode_second_order ← ode_first_order: Not cadre-mandated: 2nd-order ODEs are introduced as an independent form, not as a generalisation of 1st-order.
--   - ode_apps ← ode_second_order: Inverted orientation: SM-A cadre introduces 2nd-order ODE via the physical application, not the other way round.
--   - rings_fields ← groups: Structures algébriques are out of SM-A cadre (belong to SM-B).
-- Source: 98 edges emitted, 101 declared in JSON.
--
-- Idempotent: ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING.
-- ============================================================================

BEGIN;

-- ==== Topic: Limites et continuité  (5 edges) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000002', '33333333-aaaa-0000-0000-000000000001'),  -- limit_calc ← limit_def
  ('33333333-aaaa-0000-0000-000000000003', '33333333-aaaa-0000-0000-000000000002'),  -- limit_ops ← limit_calc
  ('33333333-aaaa-0000-0000-000000000004', '33333333-aaaa-0000-0000-000000000002'),  -- continuity ← limit_calc
  ('33333333-aaaa-0000-0000-000000000005', '33333333-aaaa-0000-0000-000000000004'),  -- tvi ← continuity
  ('33333333-aaaa-0000-0000-000000000006', '33333333-aaaa-0000-0000-000000000003')  -- asymptotes ← limit_ops
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Dérivabilité et étude de fonctions  (5 edges, 2 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000007', '33333333-aaaa-0000-0000-000000000002'),  -- deriv_definition ← limit_calc
  ('33333333-aaaa-0000-0000-000000000009', '33333333-aaaa-0000-0000-000000000008'),  -- deriv_rules ← deriv_basic
  ('33333333-aaaa-0000-0000-000000000010', '33333333-aaaa-0000-0000-000000000009'),  -- deriv_apps ← deriv_rules
  ('33333333-aaaa-0000-0000-000000000011', '33333333-aaaa-0000-0000-000000000010'),  -- function_study ← deriv_apps
  ('33333333-aaaa-0000-0000-000000000011', '33333333-aaaa-0000-0000-000000000006')  -- function_study ← asymptotes
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Fonction logarithme népérien  (6 edges, 3 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000012', '33333333-aaaa-0000-0000-000000000002'),  -- ln_basics ← limit_calc
  ('33333333-aaaa-0000-0000-000000000013', '33333333-aaaa-0000-0000-000000000012'),  -- ln_derivative ← ln_basics
  ('33333333-aaaa-0000-0000-000000000013', '33333333-aaaa-0000-0000-000000000009'),  -- ln_derivative ← deriv_rules
  ('33333333-aaaa-0000-0000-000000000014', '33333333-aaaa-0000-0000-000000000012'),  -- ln_equations ← ln_basics
  ('33333333-aaaa-0000-0000-000000000015', '33333333-aaaa-0000-0000-000000000013'),  -- ln_study ← ln_derivative
  ('33333333-aaaa-0000-0000-000000000015', '33333333-aaaa-0000-0000-000000000011')  -- ln_study ← function_study
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Fonctions exponentielles  (8 edges, 4 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000016', '33333333-aaaa-0000-0000-000000000012'),  -- exp_basics ← ln_basics
  ('33333333-aaaa-0000-0000-000000000017', '33333333-aaaa-0000-0000-000000000016'),  -- exp_derivative ← exp_basics
  ('33333333-aaaa-0000-0000-000000000017', '33333333-aaaa-0000-0000-000000000009'),  -- exp_derivative ← deriv_rules
  ('33333333-aaaa-0000-0000-000000000018', '33333333-aaaa-0000-0000-000000000016'),  -- exp_equations ← exp_basics
  ('33333333-aaaa-0000-0000-000000000019', '33333333-aaaa-0000-0000-000000000017'),  -- exp_study ← exp_derivative
  ('33333333-aaaa-0000-0000-000000000019', '33333333-aaaa-0000-0000-000000000011'),  -- exp_study ← function_study
  ('33333333-aaaa-0000-0000-000000000020', '33333333-aaaa-0000-0000-000000000016'),  -- exp_general ← exp_basics
  ('33333333-aaaa-0000-0000-000000000020', '33333333-aaaa-0000-0000-000000000012')  -- exp_general ← ln_basics
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Suites numériques  (5 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000022', '33333333-aaaa-0000-0000-000000000021'),  -- sequence_convergence ← sequences_review
  ('33333333-aaaa-0000-0000-000000000022', '33333333-aaaa-0000-0000-000000000002'),  -- sequence_convergence ← limit_calc
  ('33333333-aaaa-0000-0000-000000000023', '33333333-aaaa-0000-0000-000000000022'),  -- recurrent_sequences ← sequence_convergence
  ('33333333-aaaa-0000-0000-000000000024', '33333333-aaaa-0000-0000-000000000023'),  -- fixed_point ← recurrent_sequences
  ('33333333-aaaa-0000-0000-000000000025', '33333333-aaaa-0000-0000-000000000022')  -- adjacent_sequences ← sequence_convergence
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Calcul intégral et primitives  (6 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000026', '33333333-aaaa-0000-0000-000000000009'),  -- primitives ← deriv_rules
  ('33333333-aaaa-0000-0000-000000000027', '33333333-aaaa-0000-0000-000000000026'),  -- definite_integral ← primitives
  ('33333333-aaaa-0000-0000-000000000028', '33333333-aaaa-0000-0000-000000000027'),  -- riemann_sums ← definite_integral
  ('33333333-aaaa-0000-0000-000000000029', '33333333-aaaa-0000-0000-000000000027'),  -- ipp ← definite_integral
  ('33333333-aaaa-0000-0000-000000000030', '33333333-aaaa-0000-0000-000000000027'),  -- substitution ← definite_integral
  ('33333333-aaaa-0000-0000-000000000031', '33333333-aaaa-0000-0000-000000000027')  -- integral_apps ← definite_integral
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Équations différentielles  (2 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000032', '33333333-aaaa-0000-0000-000000000026'),  -- ode_first_order ← primitives
  ('33333333-aaaa-0000-0000-000000000034', '33333333-aaaa-0000-0000-000000000032')  -- ode_apps ← ode_first_order
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Nombres complexes  (5 edges) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000036', '33333333-aaaa-0000-0000-000000000035'),  -- complex_trig ← complex_basics
  ('33333333-aaaa-0000-0000-000000000037', '33333333-aaaa-0000-0000-000000000036'),  -- complex_multiplication ← complex_trig
  ('33333333-aaaa-0000-0000-000000000038', '33333333-aaaa-0000-0000-000000000037'),  -- complex_geometry ← complex_multiplication
  ('33333333-aaaa-0000-0000-000000000039', '33333333-aaaa-0000-0000-000000000035'),  -- complex_equations ← complex_basics
  ('33333333-aaaa-0000-0000-000000000040', '33333333-aaaa-0000-0000-000000000036')  -- moivre ← complex_trig
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Géométrie dans l'espace  (3 edges) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000042', '33333333-aaaa-0000-0000-000000000041'),  -- lines_planes ← vectors_3d
  ('33333333-aaaa-0000-0000-000000000043', '33333333-aaaa-0000-0000-000000000042'),  -- distances_3d ← lines_planes
  ('33333333-aaaa-0000-0000-000000000044', '33333333-aaaa-0000-0000-000000000042')  -- sphere_3d ← lines_planes
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Dénombrement et probabilités  (5 edges) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000046', '33333333-aaaa-0000-0000-000000000045'),  -- prob_basics ← counting
  ('33333333-aaaa-0000-0000-000000000047', '33333333-aaaa-0000-0000-000000000046'),  -- conditional_prob ← prob_basics
  ('33333333-aaaa-0000-0000-000000000048', '33333333-aaaa-0000-0000-000000000047'),  -- independence ← conditional_prob
  ('33333333-aaaa-0000-0000-000000000049', '33333333-aaaa-0000-0000-000000000046'),  -- random_variables ← prob_basics
  ('33333333-aaaa-0000-0000-000000000050', '33333333-aaaa-0000-0000-000000000049')  -- binomial_law ← random_variables
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Arithmétique dans ℤ  (4 edges) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000052', '33333333-aaaa-0000-0000-000000000051'),  -- euclid_division ← divisibility
  ('33333333-aaaa-0000-0000-000000000053', '33333333-aaaa-0000-0000-000000000052'),  -- gcd ← euclid_division
  ('33333333-aaaa-0000-0000-000000000054', '33333333-aaaa-0000-0000-000000000053'),  -- bezout ← gcd
  ('33333333-aaaa-0000-0000-000000000055', '33333333-aaaa-0000-0000-000000000052')  -- congruences ← euclid_division
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Ondes mécaniques progressives  (1 edge) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000059', '33333333-aaaa-0000-0000-000000000058')  -- wave_propagation ← wave_basics
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Ondes périodiques, diffraction et interférences  (3 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000060', '33333333-aaaa-0000-0000-000000000058'),  -- periodic_waves ← wave_basics
  ('33333333-aaaa-0000-0000-000000000061', '33333333-aaaa-0000-0000-000000000060'),  -- diffraction ← periodic_waves
  ('33333333-aaaa-0000-0000-000000000062', '33333333-aaaa-0000-0000-000000000061')  -- interference ← diffraction
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Transformations nucléaires  (2 edges) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000064', '33333333-aaaa-0000-0000-000000000063'),  -- nuclear_fission_fusion ← nuclear_radioactivity
  ('33333333-aaaa-0000-0000-000000000065', '33333333-aaaa-0000-0000-000000000063')  -- half_life ← nuclear_radioactivity
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Dipôle RC  (1 edge) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000067', '33333333-aaaa-0000-0000-000000000066')  -- rc_time_constant ← rc_charge_discharge
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Dipôle RL  (1 edge) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000069', '33333333-aaaa-0000-0000-000000000068')  -- rl_time_constant ← rl_establishment
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Oscillations RLC libres  (3 edges, 2 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000070', '33333333-aaaa-0000-0000-000000000066'),  -- rlc_regimes ← rc_charge_discharge
  ('33333333-aaaa-0000-0000-000000000070', '33333333-aaaa-0000-0000-000000000068'),  -- rlc_regimes ← rl_establishment
  ('33333333-aaaa-0000-0000-000000000071', '33333333-aaaa-0000-0000-000000000070')  -- rlc_period ← rlc_regimes
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Oscillations RLC forcées et résonance  (2 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000072', '33333333-aaaa-0000-0000-000000000070'),  -- forced_oscillations ← rlc_regimes
  ('33333333-aaaa-0000-0000-000000000073', '33333333-aaaa-0000-0000-000000000072')  -- resonance ← forced_oscillations
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Modulation d'amplitude  (1 edge) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000075', '33333333-aaaa-0000-0000-000000000074')  -- am_demodulation ← am_basics
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Lois de Newton  (1 edge) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000077', '33333333-aaaa-0000-0000-000000000076')  -- mrur ← newton_laws
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Champ de pesanteur uniforme  (2 edges, 2 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000078', '33333333-aaaa-0000-0000-000000000076'),  -- projectile_motion ← newton_laws
  ('33333333-aaaa-0000-0000-000000000079', '33333333-aaaa-0000-0000-000000000076')  -- free_fall ← newton_laws
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Champ électrique uniforme  (2 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000080', '33333333-aaaa-0000-0000-000000000076'),  -- e_field_basics ← newton_laws
  ('33333333-aaaa-0000-0000-000000000081', '33333333-aaaa-0000-0000-000000000080')  -- cathode_oscilloscope ← e_field_basics
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Champ magnétique uniforme  (3 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000082', '33333333-aaaa-0000-0000-000000000076'),  -- b_field_basics ← newton_laws
  ('33333333-aaaa-0000-0000-000000000083', '33333333-aaaa-0000-0000-000000000082'),  -- circular_motion_charge ← b_field_basics
  ('33333333-aaaa-0000-0000-000000000084', '33333333-aaaa-0000-0000-000000000082')  -- laplace_force ← b_field_basics
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Pendule pesant et élastique  (3 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000085', '33333333-aaaa-0000-0000-000000000076'),  -- pendulum_simple ← newton_laws
  ('33333333-aaaa-0000-0000-000000000086', '33333333-aaaa-0000-0000-000000000085'),  -- pendulum_elastic ← pendulum_simple
  ('33333333-aaaa-0000-0000-000000000087', '33333333-aaaa-0000-0000-000000000085')  -- pendulum_period ← pendulum_simple
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Aspects énergétiques  (4 edges, 2 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000088', '33333333-aaaa-0000-0000-000000000076'),  -- kinetic_potential ← newton_laws
  ('33333333-aaaa-0000-0000-000000000089', '33333333-aaaa-0000-0000-000000000088'),  -- mechanical_energy ← kinetic_potential
  ('33333333-aaaa-0000-0000-000000000090', '33333333-aaaa-0000-0000-000000000089'),  -- oscillator_energy ← mechanical_energy
  ('33333333-aaaa-0000-0000-000000000090', '33333333-aaaa-0000-0000-000000000085')  -- oscillator_energy ← pendulum_simple
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Cinétique chimique  (2 edges) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000092', '33333333-aaaa-0000-0000-000000000091'),  -- kinetic_factors ← reaction_speed
  ('33333333-aaaa-0000-0000-000000000093', '33333333-aaaa-0000-0000-000000000091')  -- half_time ← reaction_speed
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Transformations dans les deux sens  (1 edge) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000095', '33333333-aaaa-0000-0000-000000000094')  -- equilibrium_evolution ← reversible_basics
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: État d'équilibre (Qr, K)  (2 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000096', '33333333-aaaa-0000-0000-000000000095'),  -- qr_k ← equilibrium_evolution
  ('33333333-aaaa-0000-0000-000000000097', '33333333-aaaa-0000-0000-000000000096')  -- evolution_direction ← qr_k
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Acide-base et pH  (3 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000099', '33333333-aaaa-0000-0000-000000000098'),  -- ka_pka ← ph_definition
  ('33333333-aaaa-0000-0000-000000000099', '33333333-aaaa-0000-0000-000000000096'),  -- ka_pka ← qr_k
  ('33333333-aaaa-0000-0000-000000000100', '33333333-aaaa-0000-0000-000000000099')  -- predominance ← ka_pka
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Dosage acide-base  (3 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000101', '33333333-aaaa-0000-0000-000000000099'),  -- titration_curve ← ka_pka
  ('33333333-aaaa-0000-0000-000000000102', '33333333-aaaa-0000-0000-000000000101'),  -- equivalence_point ← titration_curve
  ('33333333-aaaa-0000-0000-000000000103', '33333333-aaaa-0000-0000-000000000102')  -- indicators ← equivalence_point
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Piles et électrolyse  (2 edges) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000105', '33333333-aaaa-0000-0000-000000000104'),  -- emf_potential ← daniell_cell_basics
  ('33333333-aaaa-0000-0000-000000000106', '33333333-aaaa-0000-0000-000000000104')  -- electrolysis ← daniell_cell_basics
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ==== Topic: Estérification et hydrolyse  (2 edges, 1 cross-topic) ====
INSERT INTO public.skill_prerequisites (skill_id, prerequisite_skill_id) VALUES
  ('33333333-aaaa-0000-0000-000000000108', '33333333-aaaa-0000-0000-000000000107'),  -- esterification_yield ← esterification_mechanism
  ('33333333-aaaa-0000-0000-000000000108', '33333333-aaaa-0000-0000-000000000096')  -- esterification_yield ← qr_k
ON CONFLICT (skill_id, prerequisite_skill_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Verification — asserts the new per-stream baseline. A failure rolls the
-- whole migration back (BEGIN/COMMIT). Mirrors migration 041's pattern.
-- ----------------------------------------------------------------------------
DO $verify$
DECLARE
  v_total       INT;
  v_sma         INT;
  v_smb         INT;
  v_pc          INT;
  v_svt         INT;
  v_humanities  INT;
  v_cross       INT;
BEGIN
  WITH skill_stream AS (
    SELECT
      sk.id,
      CASE
        WHEN sk.code LIKE 'sma\_%' ESCAPE '\' THEN 'SMA'
        WHEN sk.code LIKE 'pc\_%'  ESCAPE '\' THEN 'PC'
        WHEN sk.code LIKE 'svt\_%' ESCAPE '\' THEN 'SVT'
        WHEN sub.code IN ('math','physics','svt') THEN 'SMB'
        ELSE                                           'humanities'
      END AS stream
    FROM public.skills    sk
    JOIN public.topics    t   ON t.id   = sk.topic_id
    JOIN public.subjects  sub ON sub.id = t.subject_id
  )
  SELECT
    COUNT(*),
    COUNT(*) FILTER (WHERE dep.stream = 'SMA'),
    COUNT(*) FILTER (WHERE dep.stream = 'SMB'),
    COUNT(*) FILTER (WHERE dep.stream = 'PC'),
    COUNT(*) FILTER (WHERE dep.stream = 'SVT'),
    COUNT(*) FILTER (WHERE dep.stream = 'humanities'),
    COUNT(*) FILTER (WHERE dep.stream <> pre.stream)
  INTO  v_total, v_sma, v_smb, v_pc, v_svt, v_humanities, v_cross
  FROM  public.skill_prerequisites sp
  JOIN  skill_stream dep ON dep.id = sp.skill_id
  JOIN  skill_stream pre ON pre.id = sp.prerequisite_skill_id;

  IF v_sma <> 98 THEN
    RAISE EXCEPTION 'Migration 042 verification: SMA edges expected 98, got %', v_sma;
  END IF;
  IF v_smb <> 31 THEN
    RAISE EXCEPTION 'Migration 042 verification: SMB edges expected 31, got %', v_smb;
  END IF;
  IF v_pc <> 21 THEN
    RAISE EXCEPTION 'Migration 042 verification: PC edges expected 21, got %', v_pc;
  END IF;
  IF v_svt <> 9 THEN
    RAISE EXCEPTION 'Migration 042 verification: SVT edges expected 9, got %', v_svt;
  END IF;
  IF v_humanities <> 42 THEN
    RAISE EXCEPTION 'Migration 042 verification: humanities edges expected 42, got %', v_humanities;
  END IF;
  IF v_total <> 201 THEN
    RAISE EXCEPTION 'Migration 042 verification: total edges expected 201, got %', v_total;
  END IF;
  IF v_cross <> 0 THEN
    RAISE EXCEPTION 'Migration 042 verification: cross-stream edges expected 0, got %', v_cross;
  END IF;

  RAISE NOTICE
    'Migration 042 verification OK: total=% SMA=% SMB=% PC=% SVT=% humanities=% cross=%',
    v_total, v_sma, v_smb, v_pc, v_svt, v_humanities, v_cross;
END
$verify$;

COMMIT;

-- ============================================================================
-- Reversal (manual — repo is forward-only):
--
--   DELETE FROM public.skill_prerequisites
--   WHERE skill_id IN (
--     SELECT id FROM public.skills WHERE code LIKE 'sma\_%' ESCAPE '\'
--   )
--   AND prerequisite_skill_id IN (
--     SELECT id FROM public.skills WHERE code LIKE 'sma\_%' ESCAPE '\'
--   );
--
-- Safe only if no learner-model state references SMA prerequisites.
-- After deletion, re-run the verify CTE; SMA must return to 0 and total to 103.
-- ============================================================================
