-- ============================================================================
-- Migration 045: Misconceptions for skill `sma_limit_calc`.
-- ----------------------------------------------------------------------------
-- Auto-generated by backend/seed/json_encode_misconceptions.dart
-- Source: backend/seed/misconceptions/sma_limit_calc.json
-- Authoring: pedagogy-auditor (lead) + bac-curriculum (validation), per ADR 0008.
-- Shape: schema_version 2 with structured distinguishing_mcq_stem, per ADR 0009.
--
-- Misconceptions emitted (4):
--   - mc.math.sma_limit_calc.forme-indeterminee-valeur-nulle
--   - mc.math.sma_limit_calc.limite-egale-valeur-point
--   - mc.math.sma_limit_calc.infini-moins-infini-nul
--   - mc.math.sma_limit_calc.limite-fondamentale-linearite
--
-- Idempotent: re-running produces the same UPDATE, same end state. The verify
-- block re-runs and either asserts the expected state or rolls back. No INSERT,
-- no row creation, no compounding side effect.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. Load misconceptions onto skill `sma_limit_calc`.
--    Dollar-quoted JSONB literal — no quote-escaping required for the FR text.
-- ----------------------------------------------------------------------------
UPDATE public.skills
SET    common_misconceptions = $mcs$
[
  {
    "id": "mc.math.sma_limit_calc.forme-indeterminee-valeur-nulle",
    "label": "« 0/0 = 0 (ou 1, ou n'existe pas) »",
    "description": "L'élève croit qu'une expression de la forme 0/0 a une valeur fixe et déterminée — généralement 0, ou 1, ou « n'existe pas » — plutôt qu'une forme dont la valeur dépend de la façon dont le numérateur et le dénominateur tendent vers zéro. Face à lim(x→2) (x²−4)/(x−2), l'élève substitue x=2, obtient 0/0, et conclut soit que la limite vaut 0, soit qu'elle n'existe pas, sans chercher à lever la forme indéterminée. Ce modèle traite 0/0 comme une valeur arithmétique ordinaire et non comme un signal qu'une technique de calcul est requise.",
    "contradicts_principle": "Toute forme indéterminée doit être levée avant de conclure : la substitution directe ne suffit pas, et la valeur de la limite dépend du comportement comparatif des termes. La forme indéterminée n'est pas une valeur — c'est un signal que factorisation, conjugué ou équivalents sont nécessaires.",
    "distinguishing_mcq_stem": {
      "stem_text": "lim(x→2) (x²−4)/(x−2) = ?  Choix : A) 4 ; B) 0 ; C) la limite n'existe pas ; D) 1.",
      "distractor_choice_label": "B",
      "distractor_rationale": "L'élève portant ce modèle substitue x=2, obtient 0/0, et traite 0/0 comme la valeur 0 (par analogie avec 0×k=0). Le choix C est une variante secondaire du même modèle (0/0 traité comme indéfini) — diagnostiquement, B est le déclencheur primaire.",
      "correct_choice_label": "A",
      "correct_rationale": "Factorisation : (x²−4)/(x−2) = (x+2)(x−2)/(x−2) = x+2 pour x≠2, donc la limite est 4."
    },
    "label_ar": null
  },
  {
    "id": "mc.math.sma_limit_calc.limite-egale-valeur-point",
    "label": "« La limite en a est la valeur de la fonction en a »",
    "description": "L'élève croit que lim(x→a) f(x) s'obtient toujours par substitution f(a), et confond systématiquement la limite avec la valeur de la fonction au point. Conséquence opératoire : pour une fonction définie par morceaux dont la valeur en a diffère de la limite, l'élève renvoie la valeur de la fonction au lieu de la limite. Ce modèle est distinct de la confusion 0/0 — l'élève peut calculer correctement les formes indéterminées tout en tenant ce modèle pour les cas sans indétermination.",
    "contradicts_principle": "La limite en a décrit le comportement de la fonction au voisinage de a, non sa valeur en a. La substitution directe n'est valide que si f est continue en a — c'est une propriété à vérifier, non un acquis universel. Les deux quantités peuvent différer (fonctions par morceaux, prolongement par continuité), et la limite peut exister même si f n'est pas définie en a.",
    "distinguishing_mcq_stem": {
      "stem_text": "Soit f définie par f(x) = x+3 pour x ≠ 1 et f(1) = 7. Que vaut lim(x→1) f(x) ?  Choix : A) 4 ; B) 7 ; C) 1 ; D) la limite n'existe pas.",
      "distractor_choice_label": "B",
      "distractor_rationale": "L'élève portant ce modèle renvoie f(1)=7 directement, confondant la limite avec la valeur de la fonction au point. La confusion 0/0 ne se déclenche pas ici car il n'y a pas de forme indéterminée — le stem est diagnostiquement distinct de M1.",
      "correct_choice_label": "A",
      "correct_rationale": "Pour x≠1 la fonction vaut x+3 ; la limite en 1 est donc 1+3=4, indépendamment de la valeur f(1)=7."
    },
    "label_ar": null
  },
  {
    "id": "mc.math.sma_limit_calc.infini-moins-infini-nul",
    "label": "« ∞ − ∞ = 0 (les infinis s'annulent) »",
    "description": "L'élève traite ∞ comme un nombre ordinaire et conclut que ∞ − ∞ = 0 (ou parfois ∞/∞ = 1) par analogie avec l'arithmétique des réels : « si on soustrait quelque chose à lui-même, on obtient 0 ». Se manifeste sur des limites comme lim(x→+∞) (√(x²+x) − x) ou lim(x→+∞) (x² − x) : l'élève voit « ∞ − ∞ » et conclut 0 sans réécrire l'expression. Distinct du modèle 0/0 — la forme indéterminée est différente, la technique de levée aussi (factorisation du terme dominant, conjugué).",
    "contradicts_principle": "∞ n'est pas un réel : les formes ∞ − ∞ et ∞ / ∞ sont indéterminées et requièrent une réécriture qui révèle la vitesse relative des deux termes — factorisation du terme dominant pour les polynômes, multiplication par le conjugué pour les radicaux.",
    "distinguishing_mcq_stem": {
      "stem_text": "lim(x→+∞) (x² − x) = ?  Choix : A) +∞ ; B) 0 ; C) −∞ ; D) 1.",
      "distractor_choice_label": "B",
      "distractor_rationale": "L'élève portant ce modèle voit « ∞ − ∞ » et conclut 0 par analogie avec l'arithmétique. Ne déclenche aucun des deux modèles précédents : pas de quotient (M1 ne s'applique pas), pas de valeur en un point fini (M2 ne s'applique pas).",
      "correct_choice_label": "A",
      "correct_rationale": "Factorisation par le terme dominant : x²−x = x(x−1) ; pour x→+∞ le facteur x→+∞ et (x−1)→+∞, donc le produit tend vers +∞."
    },
    "label_ar": null
  },
  {
    "id": "mc.math.sma_limit_calc.limite-fondamentale-linearite",
    "label": "« sin(ax)/x = a par linéarité de la limite »",
    "description": "L'élève a mémorisé lim(x→0) sin(x)/x = 1 et applique une règle de linéarité implicite : « puisque sin(x)/x → 1, alors sin(ax)/x → a, et sin(ax)/(bx) → a/b — la limite se distribue sur les constantes ». Le résultat est souvent numériquement correct dans les cas simples (lim sin(3x)/x = 3 est juste), mais le raisonnement est faux. L'élève ne passe pas par la substitution u = ax et ne comprend pas pourquoi la constante apparaît. Devient visible quand la forme s'écarte du linéaire : lim(x→0) sin(x²)/x ou lim(x→0) x/sin(x).",
    "contradicts_principle": "La limite fondamentale lim sin(u)/u = 1 quand u → 0 requiert que l'argument du sinus et le dénominateur soient le même infiniment petit. La technique correcte consiste à identifier cet infiniment petit (u = ax), à substituer, et à faire apparaître sin(u)/u explicitement. La « linéarité » est une heuristique qui donne la bonne réponse dans les cas simples mais n'est pas un raisonnement valide.",
    "distinguishing_mcq_stem": {
      "stem_text": "lim(x→0) sin(x²)/x = ?  Choix : A) 0 ; B) 1 ; C) 2 ; D) la limite n'existe pas.",
      "distractor_choice_label": "C",
      "distractor_rationale": "L'élève portant le modèle de linéarité confond sin(x²) avec sin(2x) — il traite l'exposant 2 dans x² comme un coefficient qui « passe devant », par analogie incorrecte avec la règle sin(ax)/x → a. Le choix B (=1) est une variante (« sin sur x = 1 toujours »), mais C est le déclencheur primaire et distingue ce modèle des autres dans le set : aucun des trois modèles précédents ne produit C sur ce stem. (Per ADR 0009 : revision de la rationale après pushback de bac-curriculum sur l'ambiguïté du label « le 2 passe devant ».)",
      "correct_choice_label": "A",
      "correct_rationale": "Réécriture par substitution u = x² : sin(x²)/x = x · sin(x²)/x² ; quand x → 0, x² → 0 et sin(x²)/x² → 1 (limite fondamentale appliquée correctement), donc le produit tend vers 0 · 1 = 0."
    },
    "label_ar": null
  }
]
$mcs$::jsonb
WHERE  code = 'sma_limit_calc';

-- ----------------------------------------------------------------------------
-- 2. Verify block — mirrors the pattern from migrations 040-044.
--    Re-asserts the canonical prereq baseline (ADR 0004) so this migration
--    cannot silently drift it, then validates the content invariants:
--      - the target skill row exists and was updated;
--      - common_misconceptions contains exactly 4 entries;
--      - every expected ID is present (set equality, not subset);
--      - every entry carries the canonical six keys
--        (id, label, description, contradicts_principle, distinguishing_mcq_stem, label_ar);
--      - every distinguishing_mcq_stem carries the five structured sub-keys
--        (stem_text, distractor_choice_label, distractor_rationale, correct_choice_label, correct_rationale).
-- ----------------------------------------------------------------------------
DO $verify$
DECLARE
  v_mc_count        INT;
  v_actual_ids      TEXT[];
  v_offender_id     TEXT;
  v_skill_id        UUID;
  -- prereq baseline (must be unchanged by this migration)
  v_total           INT;
  v_sma             INT;
  v_smb             INT;
  v_pc              INT;
  v_svt             INT;
  v_humanities      INT;
  v_cross           INT;
  v_expected_ids    TEXT[] := ARRAY[
    'mc.math.sma_limit_calc.forme-indeterminee-valeur-nulle',
    'mc.math.sma_limit_calc.limite-egale-valeur-point',
    'mc.math.sma_limit_calc.infini-moins-infini-nul',
    'mc.math.sma_limit_calc.limite-fondamentale-linearite'
  ];
BEGIN
  -- 2a. The target skill row exists.
  SELECT id INTO v_skill_id FROM public.skills WHERE code = 'sma_limit_calc';
  IF v_skill_id IS NULL THEN
    RAISE EXCEPTION 'Migration 045 post-condition failed: skill `sma_limit_calc` not found.';
  END IF;

  -- 2b. common_misconceptions has exactly the expected entry count.
  SELECT jsonb_array_length(common_misconceptions)
  INTO   v_mc_count
  FROM   public.skills
  WHERE  code = 'sma_limit_calc';
  IF v_mc_count IS DISTINCT FROM 4 THEN
    RAISE EXCEPTION 'Migration 045 post-condition failed: expected 4 misconceptions on `sma_limit_calc`, got %.', v_mc_count;
  END IF;

  -- 2c. Set equality on misconception IDs (no missing, no extra).
  SELECT array_agg(elem->>'id' ORDER BY elem->>'id')
  INTO   v_actual_ids
  FROM   public.skills,
         LATERAL jsonb_array_elements(common_misconceptions) AS elem
  WHERE  code = 'sma_limit_calc';

  IF NOT (v_actual_ids @> v_expected_ids AND v_expected_ids @> v_actual_ids) THEN
    RAISE EXCEPTION 'Migration 045 post-condition failed: misconception ID set mismatch. expected=%, actual=%', v_expected_ids, v_actual_ids;
  END IF;

  -- 2d. Every entry carries the canonical six keys.
  SELECT elem->>'id'  INTO   v_offender_id
  FROM   public.skills,
         LATERAL jsonb_array_elements(common_misconceptions) AS elem
  WHERE  code = 'sma_limit_calc'    AND  NOT (
           elem ? 'id' AND
           elem ? 'label' AND
           elem ? 'description' AND
           elem ? 'contradicts_principle' AND
           elem ? 'distinguishing_mcq_stem' AND
           elem ? 'label_ar'         )
  LIMIT 1;
  IF v_offender_id IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 045 post-condition failed: misconception "%" is missing one of the six canonical keys.', v_offender_id;
  END IF;

  -- 2e. Every distinguishing_mcq_stem is an object with the five structured sub-keys
  --     (per ADR 0009 §B.2 — step 3 reads distractor_choice_label and correct_choice_label).
  SELECT elem->>'id'  INTO   v_offender_id
  FROM   public.skills,
         LATERAL jsonb_array_elements(common_misconceptions) AS elem
  WHERE  code = 'sma_limit_calc'    AND  NOT (
           jsonb_typeof(elem -> 'distinguishing_mcq_stem') = 'object' AND
           (elem -> 'distinguishing_mcq_stem') ? 'stem_text' AND
           (elem -> 'distinguishing_mcq_stem') ? 'distractor_choice_label' AND
           (elem -> 'distinguishing_mcq_stem') ? 'distractor_rationale' AND
           (elem -> 'distinguishing_mcq_stem') ? 'correct_choice_label' AND
           (elem -> 'distinguishing_mcq_stem') ? 'correct_rationale'         )
  LIMIT 1;
  IF v_offender_id IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 045 post-condition failed: misconception "%" distinguishing_mcq_stem missing structured sub-keys.', v_offender_id;
  END IF;

  -- 2f. Prereq baseline — must be unchanged. Re-asserts ADR 0004's canonical
  --     counts so this content migration cannot silently drift them.
  WITH skill_stream AS (
    SELECT
      sk.id,
      CASE
        WHEN sk.code LIKE 'sma\_%' ESCAPE '\' THEN 'SMA'
        WHEN sk.code LIKE 'pc\_%'  ESCAPE '\' THEN 'PC'
        WHEN sk.code LIKE 'svt\_%' ESCAPE '\' THEN 'SVT'
        WHEN sub.code IN ('math','physics','svt') THEN 'SMB'
        ELSE                                           'humanities'
      END AS stream
    FROM public.skills    sk
    JOIN public.topics    t   ON t.id   = sk.topic_id
    JOIN public.subjects  sub ON sub.id = t.subject_id
  )
  SELECT
    COUNT(*),
    COUNT(*) FILTER (WHERE dep.stream = 'SMA'),
    COUNT(*) FILTER (WHERE dep.stream = 'SMB'),
    COUNT(*) FILTER (WHERE dep.stream = 'PC'),
    COUNT(*) FILTER (WHERE dep.stream = 'SVT'),
    COUNT(*) FILTER (WHERE dep.stream = 'humanities'),
    COUNT(*) FILTER (WHERE dep.stream <> pre.stream)
  INTO  v_total, v_sma, v_smb, v_pc, v_svt, v_humanities, v_cross
  FROM  public.skill_prerequisites sp
  JOIN  skill_stream dep ON dep.id = sp.skill_id
  JOIN  skill_stream pre ON pre.id = sp.prerequisite_skill_id;

  IF v_sma        <> 98  THEN RAISE EXCEPTION 'Migration 045 prereq baseline: SMA expected 98, got %', v_sma; END IF;
  IF v_smb        <> 31  THEN RAISE EXCEPTION 'Migration 045 prereq baseline: SMB expected 31, got %', v_smb; END IF;
  IF v_pc         <> 21  THEN RAISE EXCEPTION 'Migration 045 prereq baseline: PC expected 21, got %', v_pc; END IF;
  IF v_svt        <> 9   THEN RAISE EXCEPTION 'Migration 045 prereq baseline: SVT expected 9, got %', v_svt; END IF;
  IF v_humanities <> 42  THEN RAISE EXCEPTION 'Migration 045 prereq baseline: humanities expected 42, got %', v_humanities; END IF;
  IF v_total      <> 201 THEN RAISE EXCEPTION 'Migration 045 prereq baseline: total expected 201, got %', v_total; END IF;
  IF v_cross      <> 0   THEN RAISE EXCEPTION 'Migration 045 prereq baseline: cross-stream edges expected 0, got %', v_cross; END IF;

  RAISE NOTICE
    'Migration 045 verification OK: skill=`sma_limit_calc` misconceptions=% expected_ids_match=true six_keys_present=true structured_stem_shape=true prereq_baseline=unchanged (total=% SMA=% SMB=% PC=% SVT=% humanities=% cross=%)',
    v_mc_count, v_total, v_sma, v_smb, v_pc, v_svt, v_humanities, v_cross;
END
$verify$;

COMMIT;

-- ============================================================================
-- Reversal (manual; repo is forward-only):
--
--   UPDATE public.skills SET common_misconceptions = '[]'::jsonb
--   WHERE code = 'sma_limit_calc';
--
-- Safe ONLY if no items.distractor_misconceptions or user_misconception_states
-- row references any of these misconception IDs. Misconception IDs are
-- IMMUTABLE once referenced (ADR 0007, ADR 0008). Verify before running:
--   SELECT COUNT(*) FROM public.items
--    WHERE distractor_misconceptions::text ~ 'mc.math.sma_limit_calc.';
--   SELECT COUNT(*) FROM public.user_misconception_states
--    WHERE misconception_id LIKE 'mc.math.sma_limit_calc.%';
-- Both must be 0 to safely reset to [].
-- ============================================================================
