-- ============================================================
-- Islamic Education lesson content: theory, method, example per skill
-- Uses dollar-quoting for JSONB values
-- Covers all 7 skills of the Moroccan Bac Islamic Education syllabus
-- ============================================================

-- 1. Les piliers de la foi (faith_pillars)
UPDATE public.skills SET lesson = $lesson$
{
  "cards": [
    {
      "type": "theory",
      "title_fr": "Les six piliers de la foi (Arkan Al-Iman)",
      "body_fr": "La foi (al-iman) en Islam repose sur six piliers fondamentaux, enumeres dans le celebre hadith de Jibril (rapporte par Muslim) :\n\n1. La croyance en Allah : affirmer l'existence de Dieu, Son unicite (tawhid), et Ses attributs de perfection.\n\n2. La croyance aux anges (al-mala'ika) : creatures de lumiere creees pour obeir a Allah et accomplir des missions precises (Jibril pour la revelation, Mikail pour la subsistance, etc.).\n\n3. La croyance aux livres reveles (al-kutub) : la Torah (Tawrat), les Psaumes (Zabur), l'Evangile (Injil) et le Coran, dernier livre revele et preserve.\n\n4. La croyance aux prophetes et messagers (ar-rusul) : de Adam a Muhammad (paix sur eux), tous ont transmis le message de l'unicite divine.\n\n5. La croyance au Jour dernier (al-yawm al-akhir) : la resurrection, le jugement, la retribution des actes.\n\n6. La croyance au destin (al-qadar) : tout ce qui advient, en bien ou en mal, releve de la science et de la volonte divines, sans que cela n'annule la responsabilite humaine.\n\nCes six piliers forment un ensemble indissociable : nier l'un d'eux invalide la foi tout entiere."
    },
    {
      "type": "method",
      "title_fr": "Arguments rationnels et textuels",
      "body_fr": "L'Islam etablit la foi sur deux types d'arguments complementaires :\n\nArguments textuels (an-naql) :\n- Le Coran : source premiere, parole d'Allah revelee au Prophete.\n- La Sunna : hadiths authentiques du Prophete Muhammad (paix sur lui).\n- Le hadith de Jibril est la reference principale pour les piliers de la foi.\n\nArguments rationnels (al-'aql) :\n- L'argument cosmologique (dalil al-huduth) : tout ce qui commence a exister a une cause ; l'univers ayant un commencement, il a un Createur. Le Coran dit : « Ont-ils ete crees a partir de rien ou sont-ils eux-memes les createurs ? » (At-Tur, 35).\n- L'argument teleologique (dalil al-'inaya) : l'ordre, l'harmonie et la finalite dans la creation temoignent d'un Createur Sage. « Dans la creation des cieux et de la terre, et dans l'alternance de la nuit et du jour, il y a des signes pour les doues d'intelligence » (Al-Imran, 190).\n- L'argument de la fitra : l'etre humain possede une predisposition naturelle a reconnaitre l'existence de Dieu.\n\nMethode d'analyse au Bac :\n1. Identifier le sujet (quel pilier de la foi est concerne)\n2. Citer les preuves textuelles (versets, hadiths)\n3. Developper le raisonnement rationnel\n4. Conclure sur la complementarite entre raison et revelation"
    },
    {
      "type": "example",
      "title_fr": "Question type sur la foi et la raison",
      "body_fr": "Question : « Montrez que l'Islam concilie foi et raison pour etablir la croyance en Dieu. »\n\nReponse structuree :\n\nIntroduction :\nL'Islam, contrairement a certaines idees recues, ne demande pas une foi aveugle. Il invite a la reflexion et au raisonnement pour parvenir a la croyance.\n\nDeveloppement :\n\na) La raison comme chemin vers la foi :\n- Le Coran emploie plus de 750 fois des termes lies a la reflexion ('aqala, tafakkara, tadabbara).\n- « Ne reflechissent-ils pas sur le Coran ? » (Muhammad, 24)\n- L'observation de la creation (cieux, terre, alternance jour/nuit) est presentee comme une preuve rationnelle de l'existence du Createur.\n\nb) Les textes confirment ce que la raison decouvre :\n- La revelation guide la raison et lui fournit des verites qui la depassent (le monde invisible, la vie apres la mort).\n- La foi complete la raison sans la contredire.\n\nc) Les limites de la raison :\n- La raison humaine est limitee et ne peut tout apprehender seule.\n- Les questions metaphysiques (nature exacte de Dieu, modalites du Jour dernier) relevent de la revelation.\n\nConclusion :\nL'Islam etablit un equilibre entre la raison et la revelation : la raison conduit a la foi, et la foi eclaire la raison sur ce qui la depasse."
    }
  ]
}
$lesson$
WHERE id = '33333333-0000-0000-0000-000000000087';

-- 2. Les attributs divins (divine_attributes)
UPDATE public.skills SET lesson = $lesson$
{
  "cards": [
    {
      "type": "theory",
      "title_fr": "Les attributs de Dieu et l'unicite divine (At-Tawhid)",
      "body_fr": "Le tawhid (unicite divine) est le fondement de la croyance islamique. Il se decline en trois dimensions :\n\n1. Tawhid ar-rububiyya (unicite de la seigneurie) : Allah est le seul Createur, Pourvoyeur et Gerant de l'univers.\n\n2. Tawhid al-uluhiyya (unicite de la divinite) : Allah est le seul digne d'adoration.\n\n3. Tawhid al-asma' wa as-sifat (unicite des noms et attributs) : Allah possede des noms et attributs de perfection qui Lui sont propres.\n\nLes noms les plus beaux (Al-Asma' Al-Husna) :\nAllah possede 99 noms mentionnes dans la tradition prophetique, parmi lesquels : Ar-Rahman (le Tout Misericordieux), Al-'Alim (l'Omniscient), Al-Qadir (le Tout Puissant), Al-Hakam (le Juge Supreme), Al-'Adl (le Juste), Al-Latif (le Subtil Bienveillant).\n\nCaracteristiques des attributs divins :\n- Ils sont eternels, sans commencement ni fin.\n- Ils sont parfaits, sans defaut ni imperfection.\n- Ils sont differents des attributs des creatures (« Rien ne Lui ressemble » - Ash-Shura, 11).\n- Ils sont etablis par le Coran et la Sunna authentique."
    },
    {
      "type": "method",
      "title_fr": "Attributs d'essence et attributs d'action",
      "body_fr": "Les savants musulmans distinguent deux categories d'attributs divins :\n\nAttributs d'essence (sifat adh-dhat) :\nCe sont les attributs qui qualifient l'essence meme de Dieu de toute eternite, sans interruption :\n- Al-Wujud : l'existence\n- Al-Qidam : l'anteriorite absolue (sans commencement)\n- Al-Baqa' : la perennite (sans fin)\n- Al-Wahdaniyya : l'unicite\n- Al-Qiyam bi an-nafs : la subsistance par soi\n- Al-Mukhalafa li al-hawadith : la dissemblance avec les creatures\n- Al-'Ilm : la science absolue\n- Al-Hayat : la vie\n- As-Sam' : l'ouie\n- Al-Basar : la vue\n\nAttributs d'action (sifat al-af'al) :\nCe sont les attributs lies aux actes de Dieu, qui se manifestent selon Sa volonte :\n- Al-Khalq : la creation\n- Ar-Rizq : la subsistance\n- Al-Ihya' : donner la vie\n- Al-Imata : donner la mort\n\nDifference fondamentale :\n- Les attributs d'essence sont permanents et inseparables de l'essence divine.\n- Les attributs d'action se rapportent aux actes que Dieu accomplit quand Il le veut.\n\nCette distinction aide a comprendre la relation entre Dieu et Sa creation sans tomber dans l'anthropomorphisme (tachbih) ni dans la negation des attributs (ta'til)."
    },
    {
      "type": "example",
      "title_fr": "Analyser un texte sur le tawhid",
      "body_fr": "Exercice : Analysez le verset suivant et expliquez sa portee dans la conception islamique de Dieu.\n\n« Dis : Il est Allah, Unique. Allah, Le Seul a etre implore pour ce que nous desirons. Il n'a jamais engendre, n'a pas ete engendre non plus. Et nul n'est egal a Lui. » (Al-Ikhlas, 1-4)\n\nAnalyse :\n\n1. « Il est Allah, Unique » (Ahad) :\n- Affirmation du tawhid : Dieu est Un dans Son essence, Ses attributs et Ses actes.\n- Negation de toute forme de polytheisme (chirk).\n\n2. « As-Samad » (Le Seul a etre implore) :\n- Allah est Celui dont toutes les creatures dependent, mais qui ne depend de rien.\n- Attribut d'essence : la subsistance par Soi et la suffisance absolue.\n\n3. « Il n'a jamais engendre, n'a pas ete engendre » :\n- Negation de toute filiation divine : Dieu n'a ni fils, ni pere, ni famille.\n- Distinction fondamentale avec les croyances qui attribuent une filiation a Dieu.\n\n4. « Nul n'est egal a Lui » :\n- Aucune creature ne peut etre comparee a Dieu.\n- Rappel du principe : « Rien ne Lui ressemble » (Ash-Shura, 11).\n\nConclusion :\nCette sourate, bien que courte (4 versets), constitue une synthese complete de la doctrine du tawhid. Le Prophete (paix sur lui) a dit qu'elle equivaut au tiers du Coran en raison de sa portee doctrinale."
    }
  ]
}
$lesson$
WHERE id = '33333333-0000-0000-0000-000000000088';

-- 3. Regles des actes cultuels (worship_rules)
UPDATE public.skills SET lesson = $lesson$
{
  "cards": [
    {
      "type": "theory",
      "title_fr": "Les cinq piliers de l'Islam et les actes cultuels",
      "body_fr": "Les cinq piliers de l'Islam (Arkan Al-Islam) constituent les fondements pratiques de la vie du musulman :\n\n1. La chahada (attestation de foi) : temoigner qu'il n'y a de divinite qu'Allah et que Muhammad est Son messager. C'est la porte d'entree dans l'Islam.\n\n2. La salat (priere) : cinq prieres quotidiennes obligatoires (Fajr, Dhuhr, 'Asr, Maghrib, 'Icha). C'est le lien direct entre le serviteur et son Seigneur.\n\n3. La zakat (aumone legale) : 2,5 % des biens ayant atteint le seuil (nisab) et detenus pendant un an lunaire (hawl). Elle purifie les biens et renforce la solidarite.\n\n4. Le sawm (jeune du Ramadan) : abstinence de nourriture, de boisson et de relations conjugales de l'aube au coucher du soleil, pendant le mois de Ramadan.\n\n5. Le hajj (pelerinage a La Mecque) : obligatoire une fois dans la vie pour celui qui en a les moyens physiques et financiers.\n\nConditions de validite des actes cultuels :\n- L'Islam (etre musulman)\n- La raison ('aql)\n- La puberte (bulugh)\n- L'intention (niyya) : condition indispensable, selon le hadith « Les actes ne valent que par les intentions »\n- La purete rituelle (tahara) pour la priere\n- Le respect du temps prescrit"
    },
    {
      "type": "method",
      "title_fr": "Les cinq categories de jugements en Fiqh (Al-Ahkam Al-Khamsa)",
      "body_fr": "Le Fiqh (jurisprudence islamique) classe tout acte humain en cinq categories :\n\n1. Al-Wajib (obligatoire) :\n- Son accomplissement est recompense, son abandon est sanctionne.\n- Exemples : les cinq prieres, le jeune du Ramadan, la zakat.\n- Un acte peut etre fard 'ayn (obligation individuelle) ou fard kifaya (obligation collective).\n\n2. Al-Mandub / Al-Mustahab (recommande) :\n- Son accomplissement est recompense, son abandon n'est pas sanctionne.\n- Exemples : les prieres surerrogatoires (nawafil), le siwak, le jeune du lundi et du jeudi.\n\n3. Al-Mubah (licite / permis) :\n- Ni recompense ni sanction, que l'on fasse ou non l'acte.\n- Exemples : manger, dormir, voyager (dans les cas ordinaires).\n\n4. Al-Makruh (reprove / deconseille) :\n- Son abandon est recompense, son accomplissement n'est pas sanctionne mais est desapprouve.\n- Exemples : le gaspillage dans l'utilisation de l'eau pour les ablutions, parler pendant l'appel a la priere.\n\n5. Al-Haram (interdit) :\n- Son abandon est recompense, son accomplissement est sanctionne.\n- Exemples : le meurtre, le vol, la consommation d'alcool, l'usure (riba).\n\nSources du droit islamique (par ordre de priorite) :\n1. Le Coran\n2. La Sunna\n3. L'Ijma' (consensus des savants)\n4. Le Qiyas (raisonnement analogique)"
    },
    {
      "type": "example",
      "title_fr": "Question sur les conditions de la priere",
      "body_fr": "Question : « Enumerez les conditions de validite de la priere (salat) et distinguez-les de ses piliers (arkan). »\n\nReponse :\n\nA. Conditions de validite (churut as-salat) :\nCe sont les prealables sans lesquels la priere n'est pas valide :\n1. L'Islam : etre musulman.\n2. La raison ('aql) : le fou n'est pas charge des obligations.\n3. La puberte (bulugh) ou l'age de discernement (tamyiz).\n4. L'entree du temps prescrit : chaque priere a une plage horaire definie.\n5. La purete rituelle (tahara) : ablutions (wudu) ou ablutions seches (tayammum).\n6. La purete du corps, du vetement et du lieu de priere.\n7. Couvrir la 'awra (parties du corps a couvrir).\n8. L'orientation vers la Qibla (La Mecque).\n9. L'intention (niyya) dans le coeur.\n\nB. Piliers de la priere (arkan as-salat) :\nCe sont les actes constitutifs de la priere elle-meme :\n1. Le takbir d'entree (Allahu Akbar).\n2. La station debout (qiyam) pour celui qui le peut.\n3. La recitation de la Fatiha.\n4. L'inclinaison (ruku').\n5. Le redressement apres l'inclinaison.\n6. La prosternation (sujud).\n7. La position assise entre les deux prosternations.\n8. Le dernier tachahud.\n9. Le salut final (taslim).\n\nDistinction cle : les conditions sont prealables et exterieures a la priere ; les piliers sont les composantes internes de la priere elle-meme."
    }
  ]
}
$lesson$
WHERE id = '33333333-0000-0000-0000-000000000089';

-- 4. Droit de la famille en Islam (family_law)
UPDATE public.skills SET lesson = $lesson$
{
  "cards": [
    {
      "type": "theory",
      "title_fr": "Mariage, droits conjugaux, divorce et heritage",
      "body_fr": "Le droit de la famille en Islam organise les relations familiales sur la base de la justice, de la misericorde et du respect mutuel.\n\nLe mariage (az-zawaj) :\n- Contrat civil et sacre fonde sur le consentement mutuel des deux epoux.\n- Piliers du contrat : l'offre et l'acceptation (ijab wa qabul), la dot (mahr) qui est un droit de l'epouse, la presence de temoins et du tuteur (wali).\n- Finalites : la construction d'une famille stable, la preservation de la filiation, l'entraide conjugale.\n\nDroits et devoirs conjugaux :\n- Droits de l'epouse : la dot, l'entretien (nafaqa), le bon traitement, le logement, l'equite en cas de polygamie.\n- Droits de l'epoux : l'obeissance dans le licite, la preservation du foyer.\n- Droits communs : le respect mutuel, la fidelite, la consultation (chura).\n\nLe divorce (at-talaq) :\n- L'Islam autorise le divorce comme dernier recours, apres epuisement des tentatives de reconciliation.\n- Le Coran prescrit des etapes : exhortation, separation dans le lit, mediation familiale (Al-Nisa', 34-35).\n- Types : talaq (initiative du mari), khul' (initiative de l'epouse en restituant la dot), divorce judiciaire.\n\nL'heritage (al-irth) :\n- Reparti selon des regles precises definies dans le Coran (sourate An-Nisa', versets 11-12).\n- Principe : chaque heritier recoit une part definie (fard) selon son lien de parente."
    },
    {
      "type": "method",
      "title_fr": "La Moudawwana marocaine et ses reformes",
      "body_fr": "La Moudawwana (Code de la famille marocain) est le texte juridique qui regit le droit de la famille au Maroc. Elle s'inspire du Fiqh islamique tout en s'adaptant aux realites contemporaines.\n\nHistorique :\n- 1957-1958 : premiere codification du droit de la famille marocain.\n- 2004 : reforme majeure sous le regne de SM le Roi Mohammed VI, visant a renforcer l'egalite et la justice au sein de la famille.\n\nPrincipales reformes de 2004 :\n\n1. La coresponsabilite familiale : la famille est placee sous la responsabilite conjointe des deux epoux (et non du mari seul).\n\n2. Le mariage :\n- Age legal fixe a 18 ans pour les deux sexes.\n- Le consentement de l'epouse est indispensable.\n- La tutelle matrimoniale (wilaya) est un droit de la femme majeure (elle peut l'exercer elle-meme).\n\n3. La polygamie :\n- Soumise a des conditions tres strictes et a l'autorisation du juge.\n- L'epouse peut stipuler dans le contrat de mariage que son mari ne prendra pas de seconde epouse.\n\n4. Le divorce :\n- La procedure de divorce est judiciaire et encadree.\n- Droit de la femme de demander le divorce (tatliq).\n- Protection des droits des enfants (garde, pension).\n\n5. L'heritage :\n- Les petits-enfants du cote de la fille peuvent heriter par le biais du legs obligatoire (wasiyya wajiba).\n\nApproche methodologique au Bac :\n- Toujours situer la question dans le cadre de la Moudawwana marocaine.\n- Montrer comment la loi concilie les principes islamiques et les droits fondamentaux.\n- Citer les articles pertinents quand c'est possible."
    },
    {
      "type": "example",
      "title_fr": "Question sur les droits de la famille",
      "body_fr": "Question : « Expliquez comment la Moudawwana de 2004 concilie les principes islamiques et la modernite en matiere de droits de la femme dans le mariage. »\n\nReponse :\n\nIntroduction :\nLa reforme de la Moudawwana en 2004 represente une avancee majeure dans le droit de la famille au Maroc, conciliant les valeurs islamiques avec les exigences de la justice et de l'egalite.\n\nDeveloppement :\n\n1. Le consentement et la tutelle :\n- L'Islam a toujours exige le consentement de la femme au mariage (hadith : « La femme non mariee ne peut etre mariee sans son consentement »).\n- La Moudawwana renforce ce principe : la femme majeure exerce elle-meme sa tutelle matrimoniale.\n- Cela est conforme a l'avis de certains savants musulmans, dont Abu Hanifa.\n\n2. La coresponsabilite :\n- Le Coran mentionne que les epoux sont « un vetement l'un pour l'autre » (Al-Baqara, 187), ce qui implique la complementarite.\n- La Moudawwana traduit cela par la coresponsabilite dans la gestion du foyer.\n\n3. L'encadrement de la polygamie :\n- Le Coran conditionne la polygamie a la justice entre les epouses : « Si vous craignez de ne pas etre equitables, alors une seule » (An-Nisa', 3).\n- La Moudawwana applique cette condition coranique en soumettant la polygamie a l'autorisation judiciaire.\n\n4. La protection en cas de divorce :\n- Le droit au khul' est d'origine prophetique.\n- La Moudawwana garantit les droits financiers de la femme et des enfants apres le divorce.\n\nConclusion :\nLa Moudawwana montre qu'il est possible de developper un cadre juridique moderne tout en restant fidele aux principes de justice et de misericorde du droit islamique."
    }
  ]
}
$lesson$
WHERE id = '33333333-0000-0000-0000-000000000090';

-- 5. Solidarite et entraide (social_solidarity)
UPDATE public.skills SET lesson = $lesson$
{
  "cards": [
    {
      "type": "theory",
      "title_fr": "Zakat, sadaqa, waqf et entraide communautaire",
      "body_fr": "L'Islam accorde une importance capitale a la solidarite sociale (at-takaful al-ijtima'i), qui s'exprime a travers plusieurs mecanismes :\n\nLa Zakat (aumone legale) :\n- Troisieme pilier de l'Islam, obligatoire (fard) pour tout musulman possedant le seuil minimum (nisab).\n- Taux de 2,5 % sur les biens monetaires detenus pendant un an lunaire (hawl).\n- Huit categories de beneficiaires definies par le Coran (At-Tawba, 60) : les pauvres (fuqara'), les necessiteux (masakin), les agents charges de la collecte, ceux dont les coeurs sont a gagner, les esclaves a affranchir, les endettes, la cause de Dieu (fi sabil Allah), le voyageur demuni.\n\nLa Sadaqa (charite volontaire) :\n- Acte surrerogatoire, sans montant fixe ni conditions prealables.\n- Peut etre materielle (don d'argent, de nourriture) ou immaterielle (un sourire, un bon conseil, retirer un obstacle du chemin).\n- Le Prophete (paix sur lui) a dit : « Un sourire a ton frere est une sadaqa. »\n\nLe Waqf (bien de mainmorte) :\n- Institution par laquelle un bien est immobilise de maniere irrevocable et ses revenus sont affectes a une oeuvre charitable permanente.\n- A finance historiquement les mosquees, les ecoles (madrasas), les hopitaux (bimaristans), les fontaines publiques.\n- Le waqf a ete un moteur essentiel du developpement social dans la civilisation islamique.\n\nL'entraide communautaire :\n- Le Prophete (paix sur lui) a compare la communaute a un seul corps : « Si un membre souffre, tout le corps souffre de fievre et d'insomnie. »\n- L'entraide est un devoir collectif (fard kifaya) : la communaute dans son ensemble est responsable de ses membres vulnerables."
    },
    {
      "type": "method",
      "title_fr": "Valeurs islamiques de solidarite et leur application moderne",
      "body_fr": "L'Islam propose un systeme de solidarite qui allie spiritualite et justice sociale. Voici les valeurs fondatrices et leur traduction contemporaine :\n\nValeurs fondatrices :\n\n1. Al-'Adl (la justice) : la richesse doit circuler et ne pas rester concentree entre les mains d'une minorite (Al-Hashr, 7).\n\n2. Al-Ihsan (la bienfaisance) : aller au-dela du strict devoir pour faire le bien volontairement.\n\n3. At-Ta'awun (l'entraide) : « Entraidez-vous dans la piete et la bienfaisance » (Al-Ma'ida, 2).\n\n4. Ar-Rahma (la misericorde) : « Ma misericorde embrasse toute chose » (Al-A'raf, 156).\n\nApplication moderne :\n\n- Systeme financier : la finance islamique interdit l'interet usuraire (riba) et encourage le partage des risques et des profits (mudaraba, musharaka), promouvant ainsi une economie plus equitable.\n\n- Associations caritatives : de nombreuses organisations s'inspirent du modele de la zakat et du waqf pour mener des actions de developpement social (education, sante, aide aux orphelins).\n\n- Microfinance islamique : des institutions proposent des microcrédits sans interet (qard hassan) pour aider les personnes defavorisees a lancer des activites economiques.\n\n- Role de l'Etat : au Maroc, la gestion des Habous (awqaf) est confiee au Ministere des Habous et des Affaires Islamiques, qui veille a leur bonne utilisation au profit de la communaute.\n\nMethode d'analyse :\n1. Identifier le mecanisme de solidarite evoque (zakat, sadaqa, waqf, etc.).\n2. Citer les sources textuelles (versets, hadiths).\n3. Montrer la pertinence de ce mecanisme dans le contexte contemporain.\n4. Donner des exemples concrets d'application."
    },
    {
      "type": "example",
      "title_fr": "Role de la zakat dans la societe",
      "body_fr": "Question : « Analysez le role de la zakat comme instrument de justice sociale en Islam. »\n\nReponse :\n\nIntroduction :\nLa zakat n'est pas une simple charite : c'est un pilier de l'Islam et un mecanisme de redistribution des richesses concu pour reduire les inegalites et assurer la cohesion sociale.\n\nDeveloppement :\n\n1. Dimension spirituelle :\n- La zakat purifie les biens et l'ame du donneur de l'attachement excessif a la richesse.\n- Le terme « zakat » signifie a la fois « purification » et « croissance ».\n- « Preleve de leurs biens une aumone par laquelle tu les purifies et les fais croitre » (At-Tawba, 103).\n\n2. Dimension economique :\n- Elle empeche la thesaurisation et encourage la circulation des richesses.\n- Elle constitue un transfert direct des riches vers les categories les plus demunies.\n- Dans une economie ou la zakat est correctement appliquee, la pauvrete extreme peut etre significativement reduite.\n\n3. Dimension sociale :\n- Elle renforce les liens de solidarite entre les membres de la communaute.\n- Elle reduit le ressentiment et la fracture sociale entre riches et pauvres.\n- Les huit categories de beneficiaires couvrent un large spectre de besoins sociaux.\n\n4. Application contemporaine :\n- Des pays comme le Maroc integrent la zakat dans leur systeme de solidarite nationale.\n- Les institutions financieres islamiques proposent des fonds de zakat geres de maniere professionnelle.\n- Des plateformes numeriques facilitent la collecte et la distribution de la zakat.\n\nConclusion :\nLa zakat, loin d'etre un vestige du passe, est un outil de justice sociale dont les principes demeurent pertinents face aux defis des inegalites contemporaines. Son caractere obligatoire en fait un systeme structure et previsible de solidarite, distinct de la charite volontaire."
    }
  ]
}
$lesson$
WHERE id = '33333333-0000-0000-0000-000000000091';

-- 6. Tolerance et coexistence (tolerance_coexistence)
UPDATE public.skills SET lesson = $lesson$
{
  "cards": [
    {
      "type": "theory",
      "title_fr": "Tolerance en Islam, diversite et dialogue interreligieux",
      "body_fr": "L'Islam considere la tolerance (at-tasamuh) et le respect de la diversite comme des valeurs fondamentales inscrites dans le Coran et la pratique prophetique.\n\nFondements coraniques de la tolerance :\n- La diversite est voulue par Dieu : « O hommes ! Nous vous avons crees d'un male et d'une femelle, et Nous avons fait de vous des nations et des tribus, pour que vous vous entre-connaissiez » (Al-Hujurat, 13).\n- La liberte de croyance : « Nulle contrainte en religion » (Al-Baqara, 256).\n- Le pluralisme religieux est reconnu : « A chacun de vous Nous avons assigne une legislation et un plan a suivre. Si Allah avait voulu, Il aurait fait de vous une seule communaute » (Al-Ma'ida, 48).\n- Le dialogue respectueux : « Discutez avec les gens du Livre de la meilleure maniere » (Al-'Ankabut, 46).\n\nLa tolerance dans la tradition prophetique :\n- Le Prophete Muhammad (paix sur lui) a cohabite pacifiquement avec les communautes juives et chretiennes a Medine.\n- Il rendait visite aux malades non-musulmans et acceptait leurs invitations.\n- Il a dit : « Celui qui fait du tort a un non-musulman lie par un pacte (dhimmi), c'est comme s'il m'avait fait du tort. »\n\nPrincipes fondamentaux :\n1. La dignite humaine universelle : « Nous avons honore les fils d'Adam » (Al-Isra', 70).\n2. Le refus de la contrainte en matiere de religion.\n3. La justice envers tous, quelle que soit la confession.\n4. Le dialogue constructif base sur les valeurs communes."
    },
    {
      "type": "method",
      "title_fr": "Exemples historiques de coexistence",
      "body_fr": "L'histoire de la civilisation islamique offre de nombreux exemples concrets de tolerance et de coexistence pacifique :\n\n1. La Charte de Medine (As-Sahifa) :\n- Premier document constitutionnel de l'Islam, etabli par le Prophete (paix sur lui) en 622 apres J.-C.\n- Elle organisait la vie commune entre musulmans, juifs et autres groupes de Medine.\n- Principes cles : liberte de culte pour chaque groupe, defense commune de la cite, justice pour tous, resolution pacifique des conflits.\n- Consideree comme un modele precoce de citoyennete fondee sur le vivre-ensemble.\n\n2. Al-Andalus (l'Espagne musulmane, 711-1492) :\n- Modele de convivencia (coexistence) entre musulmans, chretiens et juifs.\n- Les minorites religieuses occupaient des postes importants dans l'administration, la medecine et le commerce.\n- Epanouissement intellectuel et scientifique commun : traduction des oeuvres grecques, avancees en medecine, astronomie, philosophie.\n- Des savants comme Ibn Rushd (Averroes) et Maimonide (juif) ont coexiste et echange dans un climat de respect mutuel.\n\n3. L'Empire Ottoman :\n- Systeme des millets : chaque communaute religieuse gerait ses propres affaires civiles et religieuses.\n- Accueil des juifs expulses d'Espagne en 1492.\n\n4. Le Maroc :\n- Tradition seculaire de coexistence entre musulmans et juifs marocains (les Mellah).\n- SM le Roi Mohammed VI a souligne l'importance de la diversite culturelle et religieuse du Maroc.\n- La Constitution de 2011 affirme l'unite nationale enrichie par ses affluents arabo-islamique, amazigh et saharo-hassani, et ouverte aux influences africaines, andalouse, hebraique et mediterraneenne.\n\nMethode d'analyse :\n1. Citer les fondements textuels (Coran, Sunna).\n2. Illustrer par des exemples historiques precis.\n3. Montrer la pertinence de ces principes aujourd'hui."
    },
    {
      "type": "example",
      "title_fr": "Question sur la tolerance dans l'Islam",
      "body_fr": "Question : « En vous appuyant sur des exemples historiques et des references textuelles, montrez que la tolerance est une valeur centrale de l'Islam. »\n\nReponse :\n\nIntroduction :\nLa tolerance est l'un des fondements de l'Islam, inscrite dans le Coran et illustree par la pratique du Prophete (paix sur lui) et l'histoire de la civilisation islamique.\n\nDeveloppement :\n\n1. Les fondements textuels :\n- Le Coran affirme la liberte de conscience : « Nulle contrainte en religion » (Al-Baqara, 256). Ce verset est un principe absolu qui interdit d'imposer la foi par la force.\n- La diversite est une volonte divine : « Si ton Seigneur l'avait voulu, tous ceux qui sont sur la terre auraient cru. Est-ce a toi de contraindre les gens a devenir croyants ? » (Yunus, 99).\n- Le dialogue est une methode prescrite : « Invite au sentier de ton Seigneur par la sagesse et la bonne exhortation, et discute avec eux de la meilleure facon » (An-Nahl, 125).\n\n2. La pratique prophetique :\n- La Charte de Medine a garanti la liberte de culte aux non-musulmans et les a integres comme citoyens a part entiere de la cite.\n- Le Prophete a accepte des delegations chretiennes a Medine et les a autorisees a prier dans sa mosquee.\n\n3. Les realisations historiques :\n- Al-Andalus a ete un foyer de civilisation ou les trois religions monotheistes ont coexiste et contribue ensemble au progres scientifique et culturel.\n- Au Maroc, la coexistence entre musulmans et juifs est une tradition vivante, temoignant de la capacite de l'Islam a respecter la diversite.\n\nConclusion :\nLa tolerance en Islam n'est pas une simple concession mais une valeur fondamentale, fondee sur la reconnaissance de la dignite humaine universelle et de la diversite voulue par Dieu. L'histoire confirme que les societes musulmanes ont su mettre en pratique ces principes dans des contextes variees."
    }
  ]
}
$lesson$
WHERE id = '33333333-0000-0000-0000-000000000092';

-- 7. Ethique du travail (ethics_work)
UPDATE public.skills SET lesson = $lesson$
{
  "cards": [
    {
      "type": "theory",
      "title_fr": "Valeur du travail en Islam, honnetete et commerce licite",
      "body_fr": "L'Islam accorde une place eminente au travail et le considere comme un acte d'adoration ('ibada) lorsqu'il est accompli avec sincerite et conformement aux regles ethiques.\n\nLa valeur du travail :\n- Le Coran encourage le travail : « C'est Lui qui vous a soumis la terre : parcourez-en les etendues et mangez de ce qu'Il vous fournit » (Al-Mulk, 15).\n- Le Prophete (paix sur lui) a dit : « Nul n'a jamais mange nourriture meilleure que celle gagnee par le travail de ses mains. Le prophete Dawud (David) mangeait du fruit de son travail. »\n- L'Islam condamne l'oisivete et la mendicite pour celui qui est apte a travailler.\n- Tous les prophetes ont exerce des metiers : Dawud etait forgeron, Muhammad etait berger puis commercant.\n\nHonnetete et integrite :\n- La veracite (as-sidq) est une obligation dans toutes les transactions.\n- « Malheur aux fraudeurs qui, lorsqu'ils mesurent pour eux-memes, exigent la pleine mesure, mais qui, lorsqu'ils mesurent ou pesent pour les autres, trichent ! » (Al-Mutaffifin, 1-3).\n- Le Prophete a dit : « Le commercant veridique et digne de confiance sera avec les prophetes, les veridiques et les martyrs au Jour du Jugement. »\n\nCommerce licite (al-halal) :\n- Interdiction de l'usure (riba) : « Allah a rendu licite le commerce et a interdit l'usure » (Al-Baqara, 275).\n- Interdiction de la tromperie (al-ghich), de la fraude et de la vente de produits defectueux sans le signaler.\n- Interdiction du monopole abusif (al-ihtikar) qui nuit aux consommateurs.\n- Obligation de transparence et de consentement mutuel dans les contrats : « O vous qui croyez, ne mangez pas vos biens entre vous de maniere illicite, mais que ce soit un commerce de consentement mutuel » (An-Nisa', 29)."
    },
    {
      "type": "method",
      "title_fr": "Ethique professionnelle islamique",
      "body_fr": "L'Islam definit un cadre ethique complet pour la vie professionnelle, fonde sur des principes spirituels et moraux :\n\nPrincipe 1 : Al-Itqan (la maitrise et l'excellence)\n- « Allah aime que lorsque l'un d'entre vous fait un travail, il le fasse avec excellence (itqan). » (Hadith rapporte par Al-Bayhaqi)\n- L'itqan implique la competence, le soin, la rigueur et la recherche de la perfection dans tout travail.\n\nPrincipe 2 : Al-Amana (la fidelite et la confiance)\n- « Allah vous commande de restituer les depots a leurs ayants droit » (An-Nisa', 58).\n- Le travailleur doit etre digne de la confiance qui lui est accordee : respecter les horaires, proteger les biens de l'employeur, garder les secrets professionnels.\n\nPrincipe 3 : Al-'Adl (la justice)\n- Payer les travailleurs equitablement et sans retard : « Donnez au travailleur son salaire avant que sa sueur ne seche » (Hadith rapporte par Ibn Majah).\n- L'employeur et l'employe ont des droits et des devoirs reciproques.\n\nPrincipe 4 : Al-Ihsan (la bienfaisance)\n- Aller au-dela du strict devoir pour bien faire.\n- Traiter les collegues et les clients avec respect et bienveillance.\n\nPrincipe 5 : La preservation de l'interet general (al-maslaha)\n- Le travail ne doit pas nuire a la societe ni a l'environnement.\n- Les produits et services proposes doivent etre licites et benefiques.\n\nPrincipe 6 : L'equilibre (al-wasatiyya)\n- L'Islam encourage l'equilibre entre le travail et les autres dimensions de la vie (famille, spiritualite, sante).\n- Le Prophete a reproche a ceux qui negligeaient leur famille ou leur sante au profit du travail ou de l'adoration exclusive.\n\nGrille d'analyse au Bac :\n1. Identifier le principe ethique concerne.\n2. Le fonder sur les textes (Coran, Hadith).\n3. Illustrer par un exemple concret.\n4. Montrer sa pertinence dans le monde professionnel actuel."
    },
    {
      "type": "example",
      "title_fr": "Question sur l'ethique du travail",
      "body_fr": "Question : « Quelles sont les regles ethiques que l'Islam impose au commercant ? Illustrez par des exemples. »\n\nReponse :\n\nIntroduction :\nLe commerce est encourage en Islam, mais il est soumis a des regles ethiques strictes visant a proteger les droits de toutes les parties et a assurer la justice dans les transactions.\n\nDeveloppement :\n\n1. La veracite et la transparence :\n- Le commercant doit etre honnete dans la description de sa marchandise.\n- Interdiction de cacher les defauts d'un produit (tadlis).\n- Exemple : le Prophete est passe pres d'un vendeur de cereales et a decouvert que les grains humides etaient caches sous les grains secs. Il a dit : « Celui qui nous trompe n'est pas des notres. »\n\n2. L'interdiction de l'usure (riba) :\n- Toute transaction comportant un interet fixe est interdite.\n- Alternative islamique : le partage des profits et des pertes (mudaraba, musharaka).\n- Exemple : un pret de 1000 DH qui exige le remboursement de 1200 DH est considere comme riba.\n\n3. Le consentement mutuel :\n- Les deux parties doivent etre libres et consentantes.\n- Droit d'option (khiyar) : l'acheteur peut retourner la marchandise en cas de defaut cache.\n- Exemple : la vente sous pression ou par tromperie est nulle en droit islamique.\n\n4. L'interdiction du monopole abusif :\n- Le Prophete a dit : « Celui qui stocke (pour faire monter les prix) est un pecheur. »\n- Objectif : proteger les consommateurs et assurer l'accessibilite des biens de premiere necessite.\n\n5. La generosite et la souplesse :\n- « Qu'Allah fasse misericorde a celui qui est genereux quand il vend, quand il achete et quand il reclame son du. » (Hadith rapporte par Al-Bukhari)\n- Exemple : accorder des delais de paiement aux personnes en difficulte.\n\nConclusion :\nL'ethique commerciale islamique repose sur la justice, la transparence et la bienveillance. Ces principes, loin d'etre un frein a l'activite economique, favorisent la confiance et la stabilite des echanges, tant au niveau local qu'international."
    }
  ]
}
$lesson$
WHERE id = '33333333-0000-0000-0000-000000000093';
