// ============================================================
// Edge Function: POST /record-notion-event
//
// Write-side of the attempt-event pipeline (draft-048/049,
// LEARNER-MODEL-SPEC.md). Records FACTS ONLY — the journal write path
// never classifies (ADR 0013:93-96, restated in LEARNER-MODEL-SPEC §0.4):
// Active/Cleared/Unassessed is a READ-layer contract, not a column this
// function ever sets directly beyond the deterministic clearing fact
// described below.
//
// Two request shapes, discriminated by `action`:
//   { action: "visit",  notion_id, chapter_index, chapters_total }
//     → record_chapter_visit(p_user_id, p_notion_id, p_chapter_index, p_chapters_total)
//   { action: "answer", notion_id, item_id, kind, choice_index, is_correct,
//     misconception_id, chapter_index, item_misconceptions }
//     → record_answer_event(p_user_id, p_notion_id, p_item_id, p_kind,
//         p_choice_index, p_is_correct, p_misconception_id, p_chapter_index)
//     then, best-effort (logged, never fails the response):
//       (c) is_correct === false && misconception_id
//             → record_notion_misconception_exhibited
//       (d) is_correct === true && item_misconceptions.length > 0
//             → clearing check (LEARNER-MODEL-SPEC §3), per misconception m
//               in item_misconceptions:
//                 1. read the active row (cleared_at IS NULL) for
//                    (user, notion_id, m) in user_notion_misconception_states
//                 2. if none → nothing to clear, skip
//                 3. else count DISTINCT item_ids from correct events in
//                    user_answer_events for this (user, notion_id) with
//                    created_at > that row's last_exhibited_at, restricted
//                    to items whose targets (item-misconceptions.json,
//                    generated by web/scripts/build-learner-inputs.mjs)
//                    include m — the journal itself does not store per-event
//                    targets, so this static mapping supplies them
//                 4. if that distinct count >= 2 → record_notion_misconception_cleared
//
// user.id is the JWT-verified subject (anon client's auth.getUser(token)).
// It is NEVER taken from the request body — that would let a caller write
// state for another user (same discipline as submit-answer / delete-self-account).
//
// Auth: userClient (anon key) verifies the bearer token → 401 if invalid.
// All writes go through adminClient (service_role) because every RPC here
// is granted service_role-ONLY (migrations 047/048/049) — authenticated
// callers cannot invoke them directly, by design.
// ============================================================

import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { createClient, type SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2';
// ---- item-misconceptions — static mapping consumed by the clearing check
// (step d). Generated by web/scripts/build-learner-inputs.mjs;
// { "<notion_id>": { "<item_id>": ["mc...", ...] } }.
//
// A STATIC MODULE IMPORT, deliberately — the Sitting-2 staging e2e
// (2026-07-23) proved a standalone .json read via Deno.readTextFile does
// NOT survive bundling (the eszip ships only the module graph), which
// silently disabled the clearing check behind the old lazy-load fallback.
// An imported module is always in the graph; a missing/failed generation
// now fails the DEPLOY (loudly, at bundle time) instead of no-opping the
// clearing check at runtime (silently).
import itemMisconceptionsMap from './item-misconceptions.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const MAX_STRING_LEN = 200;
const ANSWER_KINDS = new Set(['item', 'checkpoint', 'exercise_reveal']);

type ItemMisconceptionsMap = Record<string, Record<string, string[]>>;

// ---- request body shapes ------------------------------------------------

interface VisitBody {
  action: 'visit';
  notion_id: string;
  chapter_index: number;
  chapters_total: number;
}

interface AnswerBody {
  action: 'answer';
  notion_id: string;
  item_id: string;
  kind: 'item' | 'checkpoint' | 'exercise_reveal';
  choice_index: number | null;
  is_correct: boolean | null;
  misconception_id: string | null;
  chapter_index: number | null;
  item_misconceptions: string[];
}

type ValidationResult =
  | { ok: true; body: VisitBody | AnswerBody }
  | { ok: false; error: string };

// ---- validation -----------------------------------------------------------
// Body validation: reject unknown `kind`, oversized strings (>200 chars
// ids), non-numeric indices. Every field is checked structurally before any
// RPC is called — malformed input never reaches Postgres.

function isNonEmptyString(v: unknown, maxLen = MAX_STRING_LEN): v is string {
  return typeof v === 'string' && v.length > 0 && v.length <= maxLen;
}
function isStringOrNull(v: unknown, maxLen = MAX_STRING_LEN): v is string | null {
  return v === null || (typeof v === 'string' && v.length <= maxLen);
}
function isInt(v: unknown): v is number {
  return typeof v === 'number' && Number.isFinite(v) && Number.isInteger(v);
}
function isIntOrNull(v: unknown): v is number | null {
  return v === null || isInt(v);
}
function isBoolOrNull(v: unknown): v is boolean | null {
  return v === null || typeof v === 'boolean';
}
function isStringArray(v: unknown, maxLen = MAX_STRING_LEN): v is string[] {
  return Array.isArray(v) && v.every((s) => typeof s === 'string' && s.length <= maxLen);
}

function validateBody(raw: unknown): ValidationResult {
  if (!raw || typeof raw !== 'object') {
    return { ok: false, error: 'invalid body' };
  }
  const b = raw as Record<string, unknown>;

  if (b.action !== 'answer' && b.action !== 'visit') {
    return { ok: false, error: 'unknown action' };
  }
  if (!isNonEmptyString(b.notion_id)) {
    return { ok: false, error: 'invalid notion_id' };
  }

  if (b.action === 'visit') {
    if (!isInt(b.chapter_index) || b.chapter_index < 0) {
      return { ok: false, error: 'invalid chapter_index' };
    }
    if (!isInt(b.chapters_total) || b.chapters_total < 0) {
      return { ok: false, error: 'invalid chapters_total' };
    }
    return {
      ok: true,
      body: {
        action: 'visit',
        notion_id: b.notion_id,
        chapter_index: b.chapter_index,
        chapters_total: b.chapters_total,
      },
    };
  }

  // action === 'answer'
  if (!isNonEmptyString(b.item_id)) {
    return { ok: false, error: 'invalid item_id' };
  }
  if (typeof b.kind !== 'string' || !ANSWER_KINDS.has(b.kind)) {
    return { ok: false, error: 'unknown kind' };
  }
  if (!isIntOrNull(b.choice_index)) {
    return { ok: false, error: 'invalid choice_index' };
  }
  if (!isBoolOrNull(b.is_correct)) {
    return { ok: false, error: 'invalid is_correct' };
  }
  if (!isStringOrNull(b.misconception_id)) {
    return { ok: false, error: 'invalid misconception_id' };
  }
  if (!isIntOrNull(b.chapter_index)) {
    return { ok: false, error: 'invalid chapter_index' };
  }
  if (!isStringArray(b.item_misconceptions)) {
    return { ok: false, error: 'invalid item_misconceptions' };
  }

  return {
    ok: true,
    body: {
      action: 'answer',
      notion_id: b.notion_id,
      item_id: b.item_id,
      kind: b.kind as AnswerBody['kind'],
      choice_index: b.choice_index as number | null,
      is_correct: b.is_correct as boolean | null,
      misconception_id: b.misconception_id as string | null,
      chapter_index: b.chapter_index as number | null,
      item_misconceptions: b.item_misconceptions as string[],
    },
  };
}

// ---- clearing check (step d) ---------------------------------------------

async function runClearingCheck(
  adminClient: SupabaseClient,
  userId: string,
  notionId: string,
  candidateMisconceptions: string[],
): Promise<void> {
  const mapping: ItemMisconceptionsMap = itemMisconceptionsMap ?? {};
  const notionMap = mapping[notionId] ?? {};

  for (const m of candidateMisconceptions) {
    try {
      // 1. the active row for (user, notion, m) — "active" here means
      //    "exists and not yet cleared" (cleared_at IS NULL), per the
      //    literal clearing-check contract (LEARNER-MODEL-SPEC §3); this
      //    function does not re-derive the read-layer's Active/Cleared/
      //    Unassessed classification (that stays in the read layer).
      const { data: stateRow, error: stateError } = await adminClient
        .from('user_notion_misconception_states')
        .select('last_exhibited_at')
        .eq('user_id', userId)
        .eq('notion_id', notionId)
        .eq('misconception_id', m)
        .is('cleared_at', null)
        .maybeSingle();

      if (stateError) {
        console.error(JSON.stringify({
          event: 'notion_misconception_clearing_state_read_error',
          user_id: userId,
          notion_id: notionId,
          misconception_id: m,
          message: stateError.message,
        }));
        continue;
      }
      if (!stateRow?.last_exhibited_at) continue; // nothing active — nothing to clear

      // 2. correct events since the last exhibition, restricted (via the
      //    static mapping) to items that target m; DISTINCT item_ids.
      const { data: correctEvents, error: eventsError } = await adminClient
        .from('user_answer_events')
        .select('item_id')
        .eq('user_id', userId)
        .eq('notion_id', notionId)
        .eq('is_correct', true)
        .gt('created_at', stateRow.last_exhibited_at as string);

      if (eventsError) {
        console.error(JSON.stringify({
          event: 'notion_misconception_clearing_events_read_error',
          user_id: userId,
          notion_id: notionId,
          misconception_id: m,
          message: eventsError.message,
        }));
        continue;
      }

      const distinctTargetingItems = new Set<string>();
      for (const row of (correctEvents ?? []) as Array<{ item_id: string }>) {
        const targets = notionMap[row.item_id];
        if (targets && targets.includes(m)) {
          distinctTargetingItems.add(row.item_id);
        }
      }

      if (distinctTargetingItems.size >= 2) {
        const { error: clearError } = await adminClient.rpc('record_notion_misconception_cleared', {
          p_user_id: userId,
          p_notion_id: notionId,
          p_misconception_id: m,
        });
        if (clearError) {
          console.error(JSON.stringify({
            event: 'notion_misconception_cleared_rpc_error',
            user_id: userId,
            notion_id: notionId,
            misconception_id: m,
            message: clearError.message,
          }));
        }
      }
    } catch (err) {
      console.error(JSON.stringify({
        event: 'notion_misconception_clearing_unexpected_error',
        user_id: userId,
        notion_id: notionId,
        misconception_id: m,
        message: (err as Error).message,
      }));
    }
  }
}

// ---- handler ----------------------------------------------------------

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  try {
    // ---- auth: verify the caller's JWT via the anon client ----
    const authHeader = req.headers.get('Authorization') ?? '';
    const token = authHeader.replace(/^Bearer\s+/i, '').trim();
    if (!token) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const anonClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
    );

    const { data: { user }, error: authError } = await anonClient.auth.getUser(token);
    if (authError || !user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // ---- body parsing + validation ----
    let rawBody: unknown;
    try {
      rawBody = await req.json();
    } catch {
      return new Response(JSON.stringify({ error: 'invalid JSON body' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const validated = validateBody(rawBody);
    if (!validated.ok) {
      return new Response(JSON.stringify({ error: validated.error }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    const { body } = validated;

    // service_role client — every RPC below is granted service_role ONLY
    // (migrations 047/048/049); user.id is JWT-verified above, never
    // taken from the request body.
    const adminClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
    );

    if (body.action === 'visit') {
      const { error: rpcError } = await adminClient.rpc('record_chapter_visit', {
        p_user_id: user.id,
        p_notion_id: body.notion_id,
        p_chapter_index: body.chapter_index,
        p_chapters_total: body.chapters_total,
      });
      if (rpcError) {
        return new Response(JSON.stringify({ error: rpcError.message }), {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      return new Response(JSON.stringify({ ok: true }), {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // action === 'answer' — (a)/(b): the primary journal + fold write.
    const { error: answerRpcError } = await adminClient.rpc('record_answer_event', {
      p_user_id: user.id,
      p_notion_id: body.notion_id,
      p_item_id: body.item_id,
      p_kind: body.kind,
      p_choice_index: body.choice_index,
      p_is_correct: body.is_correct,
      p_misconception_id: body.misconception_id,
      p_chapter_index: body.chapter_index,
    });
    if (answerRpcError) {
      return new Response(JSON.stringify({ error: answerRpcError.message }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // (c) exhibition — best-effort: log but do not fail the response. The
    // primary event was already recorded; failing the response here would
    // hide a successful write behind a diagnostic-layer hiccup (same
    // discipline as submit-answer's misconception path).
    if (body.is_correct === false && body.misconception_id) {
      const { error: exhibitError } = await adminClient.rpc('record_notion_misconception_exhibited', {
        p_user_id: user.id,
        p_notion_id: body.notion_id,
        p_misconception_id: body.misconception_id,
      });
      if (exhibitError) {
        console.error(JSON.stringify({
          event: 'notion_misconception_exhibited_rpc_error',
          user_id: user.id,
          notion_id: body.notion_id,
          misconception_id: body.misconception_id,
          message: exhibitError.message,
        }));
      }
    }

    // (d) clearing — best-effort, same non-fatal discipline as (c).
    if (body.is_correct === true && body.item_misconceptions.length > 0) {
      await runClearingCheck(adminClient, user.id, body.notion_id, body.item_misconceptions);
    }

    return new Response(JSON.stringify({ ok: true }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: (error as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
