/** @type {import('next').NextConfig} */
const nextConfig = {
  // ESM-only packages in the unified markdown/math pipeline need transpilation
  // so Next.js's webpack/SWC can bundle them without "require of ES module" errors.
  transpilePackages: [
    "react-markdown",
    "remark-math",
    "rehype-katex",
    "remark",
    "rehype",
    "unified",
    "bail",
    "is-plain-obj",
    "trough",
    "vfile",
    "vfile-message",
    "unist-util-stringify-position",
    "unist-util-visit",
    "unist-util-visit-parents",
    "unist-util-is",
    "hast-util-to-jsx-runtime",
    "hast-util-whitespace",
    "property-information",
    "space-separated-tokens",
    "comma-separated-tokens",
    "remark-parse",
    "remark-rehype",
    "mdast-util-to-hast",
    "mdast-util-from-markdown",
    "mdast-util-to-markdown",
    "micromark",
    "micromark-core-commonmark",
    "micromark-factory-destination",
    "micromark-factory-label",
    "micromark-factory-space",
    "micromark-factory-title",
    "micromark-factory-whitespace",
    "micromark-util-character",
    "micromark-util-chunked",
    "micromark-util-classify-character",
    "micromark-util-combine-extensions",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "micromark-util-encode",
    "micromark-util-html-tag-name",
    "micromark-util-normalize-identifier",
    "micromark-util-resolve-all",
    "micromark-util-sanitize-uri",
    "micromark-util-subtokenize",
    "micromark-util-symbol",
    "micromark-util-types",
    "micromark-extension-math",
    "mdast-util-math",
    "rehype-raw",
    "hast-util-raw",
    "hast-util-from-parse5",
    "hast-util-to-parse5",
    "parse5",
    "zwitch",
    "extend",
    "hastscript",
    "ccount",
    "decode-named-character-reference",
    "character-entities",
  ],
};

export default nextConfig;
